- lib/phoenix/endpoint.ex
- lib/phoenix/socket/transport.ex
- test/phoenix/socket/transport_test.exs
The purpose of this PR is to allow loading session config through MFA in `Phoenix.Endpoint.socket`. For a more detail info, please check our this [issue](https://github.com/phoenixframework/phoenix/issues/3659)
> Allow setting mfa for loading socket session config

- lib/phoenix/router.ex
We're attempting to add tracing support for phoenix based on telemetry. Currently, if the router throws we have no way to capture the stack trace/error or finish the trace. I've added telemetry events for failures based on the discussion here: https://github.com/beam-telemetry/telemetry/issues/57.
This PR is incomplete and does not send the correct metadata, provide any testing, or include the necessary documentation improvements. I intend to add those things but I wanted to ensure that this was a desirable feature before I did all of that. In particular, I'm not sure what the correct metadata should be in these scenarios. The error and stack trace is ideal but I'm not sure it's always possible to supply that.
Let me know what you think.
> Emit telemetry when router fails

- lib/phoenix/router.ex
- lib/phoenix/router/helpers.ex
- lib/phoenix/router/route.ex
- lib/phoenix/router/scope.ex
- test/phoenix/router/helpers_test.exs
- test/phoenix/router/route_test.exs
This PR adds a `:trailing_slash` option to Phoenix.Router that can be used to modify the generated helper functions:
1. You can define it globally when using Phoenix.Router:
```elixir
defmodule MyAppWeb.Router do
use Phoenix.Router, trailing_slash: true
end
```
This will cause all generated `*_path` and `*_url` functions to append a trailing slash to the router paths.
2. You can define it per-route, like so:
```elixir
defmodule MyAppWeb.Router do
use Phoenix.Router
scope "/", MyAppWeb do
get("/posts", PostController, :index)
get("/users", UserController, :index, trailing_slash: true)
end
end
```
```elixir
alias MyAppWeb.Router.Helpers, as: Routes
Routes.post_path(MyAppWeb.Endpoint, :index) # => "/posts"
Routes.user_path(MyAppWeb.Endpoint, :index) # => "/users/"
```
**Caveats**
This …
> Add trailing_slash option to Phoenix.Router using and match macro

- installer/lib/phx_new/generator.ex
- installer/templates/phx_assets/package.json
- installer/test/phx_new_umbrella_test.exs
A quick fix against #3680 relating to the installer generating a `--live` app in an umbrella project.
Currently the Webpack template has a [hard coded reference](https://github.com/phoenixframework/phoenix/pull/3680/files#diff-d1254ba0442b3c34b3011c5e46f2ff17R12) to the live_view assets file path that is specific to a standard Phoenix project structure:
```
"phoenix_live_view": "file:../deps/phoenix_live_view" 
```
This copies how `phoenix_html` is set in the generator by checking whether it's in an umbrella project and inserts the correct file path.
> Set correct webpack path for phoenix_live_view in umbrella apps

- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/apps/app_name_web/mix.exs
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
The floki package is missing when generating a new phoenix project with the option --live.
Without this package you will get the following error when running `mix test:
```
...
** (UndefinedFunctionError) function Floki.parse_document/1 is undefined (module Floki is not available)
...
```
> Add missing floki package for phx.new --live

- installer/templates/phx_single/lib/app_name_web.ex
- installer/templates/phx_umbrella/apps/app_name_web/lib/app_name.ex
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
This fixes a compilation error in the generated {app_name}_web.ex file:
```
== Compilation error in file lib/demo_web.ex ==
** (CompileError) lib/demo_web.ex:40: undefined function view_helpers/0
(elixir 1.10.2) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
(stdlib 3.9) erl_eval.erl:680: :erl_eval.do_apply/6
(elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```
~The view_helpers/0 function is not generated in the web context if "--no-html" is used, so we need to check for html before generating the line to invoke view_helpers().~
Some of the imports/aliases in `view_helpers/0` are used even without html. This PR moves the html conditional into the function so that `view_helpers()` can be …
> Generate web view_helpers/0 when html not selected

- README.md
- installer/templates/phx_single/README.md
- installer/templates/phx_umbrella/apps/app_name_web/README.md
- lib/phoenix/endpoint/watcher.ex
Benefits:
- No need to go back one dir, which may confuse beginners
- Keeps the same pattern as used on guides/deployment/releases.md and guides/deployment/deployment.md
> Change docs to use `npm install --prefix assets`

- installer/templates/phx_umbrella/apps/app_name/mix.exs
- installer/test/phx_new_umbrella_test.exs
* Fixes "dependencies have diverged" error (:phoenix requires :phoenix_pubsub 2.0-dev)
* Moves the closing bracket for the deps list to a new line to fix formatting
> Update pubsub to 2.0-dev for new umbrella apps

- guides/deployment/releases.md
<3 <3 Ya'll are awesome thank you for everything <3 <3
When walking through the process of building a release for the first time, we've
seen a few people copy these steps out and expect them to run.
On a new server they fail, as `npm install` is not listed.
This causes a "webpack not found" error, which can be confusing (especially to
those without experience with JavaScript and its build process).
> Include install dependencies step in Release documentation

- guides/realtime/channels.md
https://github.com/jfis/dn-phoenix is a dead link, it should be removed from docs
> Removed dead repo link from docs

- installer/templates/phx_assets/webpack.config.js
Some JS libraries generate chunk files when Webpack is running, and the current config leads to 404 errors when these chunks are referenced in the compiled JS. For example, the [Monaco Editor](https://microsoft.github.io/monaco-editor/) library generates chunks for service workers and languages.
By adding setting `publicPath: '/js/'` to the Webpack config's output, these chunks can be successfully imported. With the updated config, the chunked filenames are generated as `[name].js`. The entry key has been changed to `app`, which produces an `app.js` file in the `priv/static/js` directory.
With the Monaco library imported with the new Webpack config, there are now dozens of files in the js directory:
```
...
52.js
53.js
54.js
55.js
56.js
57.js
58.js
59.js
6.js
60.js
61.js
62.js
63.js
7.js …
```
> Add publicPath to Webpack config

- installer/templates/phx_web/templates/layout/app.html.eex
`defer` is an easy, well supported attribute we can provide in our blueprints to start loading scripts much earlier.  `defer` basically says, go to network but don't execute until `domInteractive` (once HTML is parsed and loaded).  Currently with the `js` file at the end of the body tag, it goes to network and executes only until after the HTML is parsed and loaded.
97% browser support: 
https://caniuse.com/#feat=script-defer
> Add `defer` to default blueprint script

- assets/js/phoenix.js
- assets/test/channel_test.js
Fixes: https://github.com/phoenixframework/phoenix/issues/3572
If we have 2 different listeners and one of them removes the listener
in its body then the second listener is never called:
```javascript
var ref = channel.on("event", () => {
channel.off("event", ref);
});
channel.on("event", () => {
// never called
});
```
This is because the listeners array is used by reference and all the
changes to it are visible before all the listeners are called. Thus, if
one of the listeners is removed then since `i` has not change the next
in line listener is skipped.
To fix this copy the array of listeners before calling them. This
approach is used in many libraries from what I saw ([1], [2]).
[1]: https://github.com/component/emitter/blob/6bd7817e8a444cb16e8abdf7dd2d7f04d5ca3dc8/index.js#L143
[2]: …
> Ensure all event listeners are called

- installer/templates/phx_umbrella/apps/app_name_web/gitignore
Updates a comment in the gitignore of the umbrella template to be up to date with the most recent version of phoenix's directory structure.
> Update gitignore in umbrealla template.

- installer/templates/phx_assets/webpack.config.js
When using `webpack --mode production`, webpack does not set `NODE_ENV` within the build script itself [(see docs)](https://webpack.js.org/guides/production/#specify-the-mode). The result is that `devMode` will always be true in the current `webpack.config.js`, even when running the `deploy` script.
This PR checks the `options.mode` property to set `devMode`. A common alternative is to set `"deploy": "env NODE_ENV=production webpack --mode production"` in `package.json`, but I think this method is cleaner and removes cross-platform concerns about how to set environment variables.
> Fix devMode in webpack.config.js

- installer/templates/phx_live/templates/layout/root.html.leex
- installer/test/phx_new_test.exs
Nothing fancy: <img width="111" alt="Screen Shot 2020-03-27 at 1 18 58 PM" src="https://user-images.githubusercontent.com/168677/77798544-54b34f80-7030-11ea-93ce-6396db6dc64d.png">
// @chrismccord
> Add link to live_dashboard in root layout

- guides/deployment/heroku.md
Adds an example of configuring Node and NPM in `phoenix_static_buildpack.config` so that devs pushing new builds know how to overcome the Node v6.9.2 and NPM v3.10.9 defaults in the Phoenix Static buildpack.
> Heroku Guide Improvement: Add instructions to configure Node and NPM

- lib/mix/tasks/phx.gen.presence.ex
After #2554, an excerpt from `mix help phx.gen.context` reads:
> A new file will be generated in lib/my_app_web/channels/**presence.ex**, where **my_app_web** is the snake cased version of the module name provided.
But see the actual behaviour:
```elixir
$ mix phx.gen.presence MyPresence 
* creating lib/app_name_web/channels/my_presence.ex 
```
Changed this in the doc and did some cleaning up.
> Revise phx.gen.presence module doc

- guides/deployment/heroku.md
per discussion in https://github.com/phoenixframework/phoenix/pull/3706
setting both node and npm - will lead to issues down the line (eg when user wants to use node 12 etc) - it's also complicated figuring out what npm version to actually use etc. etc.
we are still conservative on suggesting node 10 - could be future proofing going 12.16.1.. but that is separate issue..
> heroku: don't suggest setting both node and npm version

- priv/templates/phx.gen.live/index.html.leex
This change fixes a typo error in the template generated by LiveView.
I found the issue while testing the new `phx.gen.live` generator.
> Fix typo in Live index template

- installer/templates/phx_test/live/page_live_test.exs
This fixes a spelling error in the generated page_live_test.exs
> Fixing spelling error

- lib/mix/tasks/phx.gen.context.ex
This allows generators that build on top of `phx.gen.context` to pass in their own help message while using `phx.gen.context`'s argument validation logic. This is the identical pattern that's being used in `phx.gen.schema` to allow `phx.gen.context` to override the help message.
https://github.com/phoenixframework/phoenix/blob/165ff2d131f4494243440d16fe6558d3787b3972/lib/mix/tasks/phx.gen.schema.ex#L122-L135
https://github.com/phoenixframework/phoenix/blob/165ff2d131f4494243440d16fe6558d3787b3972/lib/mix/tasks/phx.gen.schema.ex#L174-L201
This change will allow `phx.gen.auth` to print its own error messages instead of printing out error messages that mention `phx.gen.html` and friends. This could also be useful to allow `phx.gen.live` to have a custom error messages.
> Allow phx.gen.context's help to be extended

- lib/phoenix/controller.ex
Specify that `nil` is returned if there is no message for `key`
> Update doc for `get_flash/2`

- installer/templates/phx_live/templates/layout/root.html.leex
- installer/templates/phx_single/mix.exs
- installer/templates/phx_web/router.ex
- installer/templates/phx_web/templates/layout/app.html.eex
- installer/test/phx_new_test.exs
This corrects a number of issues introduced with the addition of :phoenix_live_dashboard.
- Adds `live_dashboard_path` to the `app.html.eex` dead view
- Conditions `live_dashboard` route on existence so the generated tests pass (#3740 // Thanks @aptinio! )
- Ensures the dashboard works even when `--no-html` is given (#3751 // Thanks @aaronrenner!)
When generated in a project without both html and live, we have to close the gap wrt the session. The router in such cases would look as follows:
```elixir
defmodule MyAppWeb.Router do
use MyAppWeb, :router
pipeline :api do
plug :accepts, ["json"]
end
scope "/api", DevAppWeb do
pipe_through :api
end
#
if Mix.env() in [:dev, :test] do
import Phoenix.LiveDashboard.Router
scope "/" do
pipe_through [:fetch_session, :protect_from_forgery] …
```
> Fix dashboard installer, closes #3740, closes #3751

- priv/templates/phx.gen.live/index.html.leex
- priv/templates/phx.gen.live/live_test.exs
- priv/templates/phx.gen.live/show.html.leex
- test/mix/tasks/phx.gen.live_test.exs
- Ensure scoped routes via `--web` are generated properly.  (e.g. `user_path ==> admin_user_path`)
- Select the form component via the `"form"` tag (so it works with at-myself)
- Fix formatting (albeit there may still be some formatting to fix in the generated app, depending on the length of the path helper)
// @aaronrenner
> Fix helper paths for phx.gen.live with --web

- installer/templates/phx_single/README.md
- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/apps/app_name/mix.exs
- installer/templates/phx_umbrella/apps/app_name_web/README.md
- installer/templates/phx_umbrella/apps/app_name_web/mix.exs
- installer/templates/phx_umbrella/mix.exs
I'd like to propose that newly generated Phoenix apps have a `mix setup`
task (an alias) that sets up developer's environment: fetching mix
dependencies, preparing the database, installing npm deps, etc. This
way, instead of copy-pasting various commands from the README, there's
just one command to remember: `mix setup`. This also serves a good
starting point for developers to put their project-specific setup steps.
This is inspired by: https://github.com/github/scripts-to-rule-them-all.
I've used this pattern over the years on many projects, here are some OSS examples:
- https://github.com/hexpm/hexpm/blob/e52e883ec5360a674f604fed7b54d6c48c431687/mix.exs#L77
- https://github.com/hexpm/diff/blob/d86d1f2f61ffce9f2d69df5125781935487e3f19/mix.exs#L66
- …
> Add `mix setup` to generated apps

- CHANGELOG.md
There are the older thrid-party adapters and the new one built-in to `ecto_sql`. 
Clarify which one is used in phoenix and provide a link for users to explore more.
> Clarify the new tds adapter

- guides/directory_structure.md
- guides/plug.md
In the current 1.5.0-rc.0 [Directory structure guide](https://hexdocs.pm/phoenix/1.5.0-rc.0/directory_structure.html#content) and [Plug guide](https://hexdocs.pm/phoenix/1.5.0-rc.0/plug.html#content) the links to `Gettext` currently take you to `https://hexdocs.com/gettext/` which redirects to `http://ww25.hexdocs.com/gettext` which then resolves to `http://ww25.hexdocs.com/?z`.
This PR corrects the link to point to `https://hexdocs.pm/gettext/Gettext.html`
> Fixes gettext links in guide documentation

- guides/deployment/heroku.md
I noticed the link out to the releases documentation was broken on the Deploying with Heroku guide. I'm presuming it was meant to link to the Phoenix releases docs, which just means changing from an absolute to a relative link.
Hopefully this is ok to merge. If so, do you know how I would go about fixing this guide for old versions of the documentation? I'm presuming they run from a tag, but I obviously can't update the release tag. This link seems to have been introduced in v1.4.12 of the docs, so the following would need updating:
- v1.4.12
- v1.4.13
- v1.4.14
- v1.4.15
- v1.4.16
- v1.5.0-rc.0
I'm happy to do this, I'm just not sure about the process given they are for released versions and the docs live with the code.
Thanks!
> Fix broken link in Deploying with Heroku guide.

- lib/phoenix/logger.ex
Without a deep understanding of how Telemetry events work, it wasn't straight forward on how to use these events to capture specific metrics about a request.
The Phoenix LiveDashboard metrics documentation pulls together everything into a complete example so it seemed like a natural source to cross link.
> Add link to Phoenix LiveDashboard in Logger's docs

- assets/package.json
makes it easy to just `import { Socket } from 'phoenix'` when using rollup.
> include `module` field in package.json

- guides/plug.md
`action_name` typo will result in:
```
CompileError
lib/hello_web/controllers/hello_controller.ex:4: cannot find or invoke local action_name/0 inside guard. Only macros can be invoked in a guard and they must be defined before their invocation. Called as: action_name()
```
Should be `action` as defined in https://hexdocs.pm/phoenix/Phoenix.Controller.html#module-guards
> Fix guides: plug code typo

- CHANGELOG.md
The text pointing to v1.5 release changelog references v1.4
> Fix version number before link to v1.5 changelog

- guides/views.md
The word "structured" has been misspelled as "strucgtured" and this PR fixes it.
> Fix typo error in the word structured

- guides/views.md
A really simple PR fixing a typo in "structure" word in Views guide page.
> Fix type in Views guide page

- guides/contexts.md
- guides/routing.md
- guides/testing/testing_controllers.md
I noticed several places where the mentioned of mix tasks weren't linked so I updated them to be `mix <task.name>` format.
> Update various guides to link to mix tasks

- guides/routing.md
Corrects `rasied` to `raised` in `If no route matches, no pipeline is invoked and a 404 error is raised.` of the pipeline description
> Fix minor typo in phoenix/guides/routing.md

- guides/deployment/releases.md
- add python (needed for nodegyp rebuild, will display error otherwise)
- mkdir isn't needed, WORKDIR will create the directory if it doesn't
exist
- combine commands where possible to reduce the amount of docker layers
- copy package*.json and install packages before doing the deploy so the
install won't happen every time you modify a js/css file or other
asset
- use npm ci instead of npm install
- bash not needed, sh/ash is available
- install ncurses-libs, the app wouldn't start otherwise
- do the chown when /app is still empty and add chown to the copy
command, this saves docker from creating a large layer (about 10Mb)
just for the permission changes
- add a default cmd
- use apk --no-cache so the cache doesn't get added to the image
I'd actually recommend using docker buildkit to …
> improve docker example in release guide

- guides/deployment/heroku.md
node 10.19.0 was bitten by this bug "invalid bin entry" - failing on npm install (sic!) https://github.com/npm/cli/issues/613
see also https://elixirforum.com/t/cant-deploy-phoenix-app-to-heroku/31023
💙
does this need to be "backported" to 1.5 branch to appear on site?
> bump suggested node_version due to npm bug

- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/apps/app_name/mix.exs
- installer/templates/phx_umbrella/apps/app_name_web/mix.exs
...for new generated projects.
Example output before:
```sh
$ mix test
Compiling 21 files (.ex)
Generated example app
08:08:00.701 [info]  Already up
.......
Finished in 0.07 seconds
7 tests, 0 failures
Randomized with seed 806821
```
Output after:
```sh
$ mix test
Compiling 21 files (.ex)
Generated example app
.......
Finished in 0.07 seconds
7 tests, 0 failures
Randomized with seed 662040
```
> Silence an "Already up" message during mix test

- guides/directory_structure.md
The Telemetry supervisor was missing from the directory_structure guide.
I copied the right code from the phoenix-generated application.ex file
> Added Telemetry supervisor to Hello.Application children list in the guides/directory_structure.md

- lib/phoenix/test/channel_test.ex
When using ChannelTest, one of my test cases accidentally passed in `nil` instead of a socket and I got an error from the internals of Phoenix.
```
** (UndefinedFunctionError) function nil.channel_pid/0 is undefined
nil.channel_pid()
(phoenix 1.5.0-rc.0) lib/phoenix/test/channel_test.ex:410: Phoenix.ChannelTest.push/3
```
With these changes it now raises a `FunctionClauseError` at the boundary of the public API and lets the user know they called the function incorrectly.
```
** (FunctionClauseError) no function clause matching in Phoenix.ChannelTest.push/3
(phoenix 1.6.0-dev) lib/phoenix/test/channel_test.ex:407: Phoenix.ChannelTest.push(nil, "event", %{"payload" =>"foo"})
```
> Guard ChannelTest functions

- priv/templates/phx.gen.live/live_test.exs
When running the formatter after `phx.gen.live`, it corrects the following lines in `test/my_app_web/live/post_live_test.exs`
This updates the generator so its code will pass the formatter.
> Fix formatting of generated *_live_test.exs

- assets/js/phoenix.js
on `socket.disconnect()` `waitForBufferDone` always retries 5 times even with empty buffer because when `bufferedAmount === 0` then `if (this.conn.bufferedAmount)` evaluates to false
if I understood correctly, `!bufferedAmount` will be enough - for longpoll there is no buffering, so nothing to wait; for websocket - check for `0`
> fix bufferedAmount check in js

- lib/phoenix/endpoint.ex
This is such a great addition to Phoenix defaults!
One side question: Is there a best practice on draining keep-alive connections now? I have done some hacky things in the past like set an app config and then check it in the controller, but I'm wondering if there's a better solution.
> Fix Cowboy.Drainer link

- guides/testing/testing_controllers.md
Related documentation section: https://hexdocs.pm/phoenix/testing_controllers.html#the-index-action
- Use inline code instead of double quotes to emphasize path to file
- Fix typo in language identifier for the syntax highlighting
> Fix syntax highlighting for a controller test example in documentation

- guides/telemetry.md
👋 @mcrumm asked me to take a look through the new Telemetry docs and PR any suggestions. 
Looks great to me overall, but I added a few suggestions. These suggestions are mostly targeted at clarifying the relationship between `Telemetry.Metrics`, Telemetry reporters and the `:telemetry` library. How these components fit together to achieve instrumentation of your application can be a tough concept to grok in my opinion, but having that understanding will empower users to get the most out of Phoenix's new Telemetry offerings.
Maybe some of the suggestions here represent more detail than ya'll feel is appropriate for these docs, but I'd thought I'd put them forward and see what you think.
> Some suggested updates for clarity/context

- lib/mix/phoenix/context.ex
- lib/mix/tasks/phx.gen.context.ex
- priv/templates/phx.gen.context/fixtures.ex
- priv/templates/phx.gen.context/fixtures_module.ex
- priv/templates/phx.gen.context/test_cases.exs
- priv/templates/phx.gen.html/controller_test.exs
- priv/templates/phx.gen.json/controller_test.exs
- priv/templates/phx.gen.live/live_test.exs
- test/mix/tasks/phx.gen.context_test.exs
This adds a fixtures module to the output of `phx.gen.context` and uses the module throughout `phx.gen.live`, `phx.gen.html` and phx.gen.json`. The module looks like this:
```elixir
defmodule DemoLiveApp.BlogFixtures do
@moduledoc """
This module defines test helpers for creating
entities via the `DemoLiveApp.Blog` context.
"""
def post_fixture(attrs \\ %{}) do
{:ok, post} =
attrs
|> Enum.into(%{
content: "some content",
rating: 42,
title: "some title"
})
|> DemoLiveApp.Blog.create_post()
post
end
end
```
This change originally came about from #3797 and has been discussed further here: https://github.com/aaronrenner/phoenix_generator_proposals_live/pull/1.
Any feedback or suggestions would be appreciated!
Fixes #3797
> Add fixtures module to generators

- lib/phoenix/channel.ex
The documentation of channels does not reveal the underlying implementation (which is good).
Therefore, if you want to monitor the channel, as recommended in the docs of `terminate/2`, the user needs to be explicitly told which PID to monitor, and when it is a good idea to spawn it.
To realize this is not obvious without being documented, compare with the situation in the socket `connect/3` callback. Similar entry point from a user's perspective, but `self()` there is not the one to monitor if you want to keep track of the socket itself.
Since we are here, let me also comment that as a user the perils of `terminate/2` + trapping exits are not clear from the docs. You wonder. "Why is it discouraged? If you cannot trust `terminate/2`, why does the callback exist in the first place?"
From …
> Document self() is the channel server in join/3

- lib/phoenix/endpoint.ex
It points to "Shared configurations" but the subtitle is actually "Common configurations"
> Fix Endpoint.socket/3 docs reference to "Shared configurations"

- guides/deployment/deployment.md
- guides/deployment/releases.md
A few minor typos were introduced in a recent commit that I happen to stumble upon.
> Fix a few minor typos in guides

- lib/phoenix/endpoint/cowboy2_handler.ex
- test/phoenix/integration/endpoint_test.exs
This PR updates the Cowboy2 Handler so that it updates the conn after `call` - this is done so the telemetry event will get the updated values, for example the response `status`.
This mirrors the existing behavior of `plug_adapter` telemetry events in `plug_cowboy`...
https://github.com/elixir-plug/plug_cowboy/blob/master/lib/plug/cowboy/handler.ex#L40-L45
> Update conn in Cowboy2 Handler

- guides/testing/testing_controllers.md
I found a small typo in the docs while brushing up on phoenix this evening :)
> Fix a typo in the docs for testing controllers

- lib/phoenix/endpoint/supervisor.ex
- test/phoenix/endpoint/endpoint_test.exs
I'm pretty sure the validation may be improved, but this PR is to gather feedback related to https://github.com/phoenixframework/phoenix_live_view/issues/911#issuecomment-632905958
Decided to warn instead of raise to follow the same pattern already in use for validating Endpoint config, but I can change to raise if it's better.
> Warn if the host provided for the Endpoint is invalid

- lib/phoenix/channel/server.ex
Someone [was unsure](https://elixir-lang.slack.com/archives/C03EPRA3B/p1590040764311100) about where to add the config, and I agree it's not as clear as it could be.
We could even mention config/config.exs by name, but we don't mention filenames for the supervision tree, so maybe this strikes the right balance.
Also fixed "proccess" and "list it your" typos.
> Typos and clarification in ":pubsub_server not configured" error

- assets/js/phoenix.js
it wasn't immediately obvious reading the documentation that I could receive replies from phoenix push events. I added an example
EDIT: wait, it's not working like that now for me.. I must have done something. I'll update when I figure out why.. :)
> add example for channel.push

- guides/deployment/gigalixir.md
We did an overhaul of all our documentation so this just updates the links to point to their new locations.
> Updated links to Gigalixir Documentation

- installer/templates/phx_assets/app.js
When I first used `liveSocket.enableLatencySim(1000)` it was hard to figure it out that it was still enabled as I did enable it on the app.js file directly. I did try to disable it with `liveSocket.enableLatencySim(0)`. 😄 
In my case I used the phoenix project generator `--live`. Perhaps, we could add the comment to the `app.js.
Related PR:
https://github.com/phoenixframework/phoenix_live_view/pull/933
> Clarify usage of enableLatencySim in app.js

- installer/templates/phx_assets/webpack.config.js
Instead of hard-coding `app`, we should use the entrypoint name, which
allows multiple CSS entrypoints to be generated automatically. This is
especially useful when you want to segregate your frontends, such as
both "public" and "admin" sections which need entirely independent CSS
assets.
> Use entrypoint name for extracted CSS

- lib/phoenix/endpoint.ex
- lib/phoenix/socket.ex
- lib/phoenix/transports/long_poll.ex
- lib/phoenix/transports/long_poll_server.ex
- lib/phoenix/transports/websocket.ex
- test/phoenix/integration/long_poll_channels_test.exs
- test/phoenix/integration/websocket_channels_test.exs
- test/phoenix/test/channel_test.exs
This is a half-done PR to illustrate my point: It'd be great if you could return a custom error from the `connect` function of the WebSocket handler.
Right now when you return `:error` from it, it always returns a 403 status code. I'm not sure why, because it could be possible that you want to return a 400 or 429, for example, in certain situations. And adding a body to explain the error is missing, too, in my opinion.
For example, I want to return a 400 with a detailed error message since my endpoint requires a specific header to be set.
If you're okay with this in general, I can add a proper test and change the docs, too.
> allow custom error response from socket handler

- installer/lib/mix/tasks/phx.new.ex
> Fix typo: Remove extra brace from instructions

- guides/telemetry.md
It's currently very difficult to discover the documentation with the full list of Phoenix telemetry events. Searching `telemetry` in the docs surfaces the guide to the top and `Phoenix.Logger` (where they're defined) as the last search result. Adding a callout and link to the full list in the guide should improve discoverability.
> Add a link to telemetry events in the guide

- lib/phoenix/presence.ex
`c:list/2` does not/no longer exists, so changed the references to `c:list/1`
An example of the the broken link can be viewed at https://hexdocs.pm/phoenix/1.5.3/Phoenix.Presence.html#module-fetching-presence-information
> Fix references to Phoenix.Presence.list/1

- installer/templates/phx_assets/app.scss
The 'invalid-feedback' class is used in standard generated forms.
> Move ‘invalid-feedback’ style selector block to non-LV section

- installer/templates/phx_assets/package.json
- installer/templates/phx_assets/webpack.config.js
On an unmodified default generated project (with --live) using the
Phoenix 1.5.3 installer, the build time is:
$ webpack --mode development
Version: webpack 4.41.5
Time: 1681ms
Changing the source-map mode to `eval-cheap-module-source-map` changes
this time slightly:
Time: 1397ms
The `hard-source-webpack-plugin` caches intermediate build steps, which
produces significantly faster rebuilds:
Time: 474ms
Combining these two results in:
Time: 193ms
This improvement seems to scale well too. On a project including
tailwind, the build time by default is close to 6 seconds, but with the
above config, 212ms.
`eval-cheap-module-source-map` preserves line numbers in the source
maps, but not column information. This seems like a resonable trade off
vs `eval-module-source-map` which is a bit slower. …
> Speed up build times for webpack

- guides/views.md
The code snipper makes use of `render_to_string/3` but the preceeding text instead references `render_to_iodata/3`.
This mismatch is confusing.
> Make code snippet match text; uses render_to_string not render_to_iodata

- assets/package-lock.json
Package.json was updated to 1.5.0 in master branch while package-lock.json was still at 1.4.0. This may cause issues with older versions of npm.
> Update package-lock.json to match package.json

- guides/introduction/community.md
Hi all 👋  - My first PR on Phoenix 🎉 
I removed a broken link from the community page. 
Pragprog migrated its website in June and the screencast seems to be no longer available.
https://pragprog.com/support/index.html#new-site
I'll be glad to close/update the PR if anyone knows that it's a temporary issue 🙂 
Thanks for the great contributing doc 💜
> Remove broken link on community page

- lib/phoenix/presence.ex
The example presence code has a bug where it's building a map of users keyed by id, but then using a key that it gets from the presences map to index into it. The users table is going to have integer primary keys, but presences keys are cast to a string (see https://hexdocs.pm/phoenix/Phoenix.Presence.html#c:track/3) 
This means that the code as written will always return `nil` for the user.
I'm not sure if adding `String.to_integer` here is the cleanest approach, please let me know if there's a better a way to do this!
> Fix bug in presence documentation example

- lib/mix/tasks/phx.gen.json.ex
- test/mix/tasks/phx.gen.json_test.exs
(Note: example given is from the phx.gen.json test)
After `mix phx.gen.json Blog Post posts title:string --web Blog` is run, the generated files rely on `Routes.blog_post_path`.
The outputted shell instructions should include the alias `as: :blog` in the routing scope so that `Routes.blog_post_path` works.
> Fix bug in mix phx.gen.json shell instructions

- guides/testing/testing_contexts.md
The contexts guide link and name are pluralized, but this page was linking to a singular version that doesn't exist.
Not reading them in order means I am jumping around quite a bit :)
> Fix broken link to contexts guide

- lib/phoenix/test/conn_test.ex
While reading through the documentation for `Phoenix.ConnTest`, I came across some type specifications that appear to be incorrect. This is a quick change to resolve the issue. 🙂
> Correct typespecs for delegated ConnTest.get_flash/{1,2}

- lib/mix/tasks/phx.digest.ex
- lib/phoenix/digester.ex
- lib/phoenix/digester/compressor.ex
- lib/phoenix/digester/gzip.ex
- mix.exs
- test/phoenix/digester/gzip_test.exs
- test/phoenix/digester_test.exs
Following on the work in #3836 and #3840, I wanted to have a quick go at a more robust feature described in https://github.com/phoenixframework/phoenix/issues/3836#issuecomment-629623791
I added `compress_file?` to the behaviour to be able to not compress some assets with certain compressors if the content is too small (or similar).
I haven't written any docs/tests yet, and the naming/structure could use some updates, but figured I'd start the discussion with this 🙂
> Configurable static compressors

- guides/controllers.md
The example code uses `#{messenger}` while the clarifying explanation uses `#{id}`.  Perhaps this was on purpose—and if so, please carry on—but it made me do a few double takes trying to figure out where `#{id}` was referenced in the example.
> Keep example and clarification consistent

- lib/phoenix/logger.ex
- lib/phoenix/router.ex
Looking for feedback. This would allow introspection of the connection as it existed when the router_dispatch start event was executed, which will be helpful for debugging, especially in applications with more than one router.
> Add :conn to router_dispatch exception events

- lib/phoenix/presence.ex
Fixes #3941
This pull request fixes the Presence module name In the first code snippet of `lib/phoenix/presence.ex` to include `Web`, for consistency with the `MyAppWeb.Presence` module name used throughout the rest of the docs:
```elixir
defmodule MyAppWeb.Presence do
use Phoenix.Presence,
otp_app: :my_app,
pubsub_server: MyApp.PubSub
end
```
This pull request also updates the `lib/my_app/application.ex` > `children = [`snippet to remove `Web` from `MyApp.PubSub`, as PubSub by default is not generated under `MyAppWeb`:
```elixir
Next, add the new supervisor to your supervision tree in
`lib/my_app/application.ex`. It must be after the PubSub child
and before the endpoint:
children = [
...
{Phoenix.PubSub, name: MyApp.PubSub},
MyAppWeb.Presence,
MyAppWeb.Endpoint
]
```
> Docs: Fix Presence docs code typo

- guides/testing/testing_channels.md
- guides/testing/testing_contexts.md
- guides/testing/testing_controllers.md
* small typos
* use backticks for paths as in the rest of the docs instead of quotes
> fix some small typos in the 'Testing' guides

- lib/phoenix/endpoint.ex
- lib/phoenix/socket/transport.ex
- test/phoenix/integration/long_poll_channels_test.exs
- test/phoenix/integration/websocket_channels_test.exs
In order to correlate distributed traces to actions within websockets we need to have access to trace context headers in order to extract the context without complicated workarounds. 
The [W3C Trace Context Headers](https://www.w3.org/TR/trace-context-1/) are in a firm place naming-wise to add support in Phoenix for usage by projects such as OpenTelemetry. This PR exposes the two official context headers to the `connect_info` map. This is necessary to provide seamless tracing of websockets for users in the `opentelemetry_phoenix` project.
/cc @josevalim @tsloughter @hauleth
> Expose trace context headers in websockets and long polling

- guides/introduction/installation.md
- guides/introduction/up_and_running.md
Added some notes about cowboy 2.8.0 requiring Erlang 22 in the installation and up and running guides. 
Trying to run `mix ecto.create` while running Erlang 21.0.9 gave me the error `Could not compile dependency :cowboy`, even though the installation guide says "Erlang 20 or later". I added some notes based on @josevalim's suggestions in #3903 to let new Phoenix developers know about the issue and how to resolve it. I didn't want to update the installation guide to say "Erlang 22 or later" since it's just a cowboy dependency and not a Phoenix one.
> Add notes on cowboy 2.8.0 and Erlang 22

- guides/controllers.md
A reader might copy this example without realizing a big difference between `#{}` and `<%= %>` - the former allows arbitrary HTML to be inserted.
Should this be called out more specifically in the paragraph following the example?
> Remove XSS vulnerability with proper escaping

- .github/workflows/ci.yml
It appears that the installer tests accidentally were removed during the migration to GitHub Actions. This adds those tests back into CI.
> Run installer tests in ci

- installer/templates/phx_umbrella/config/dev.exs
- installer/templates/phx_umbrella/config/prod.secret.exs
As per https://github.com/phoenixframework/phoenix/commit/cbfc71c7fcd9c5b95ac5ed63719ac88a4927af85, `use Mix.Config` can be replaced with `import Config`.
> replace remaining Mix.Config usage

- guides/plug.md
Use the correct link to Gettext under the Plug section in the guides.
> Fix broken link to Gettext in docs

- lib/phoenix/controller.ex
- lib/phoenix/controller/pipeline.ex
The plug is not used at compile-time, it's safe not to create the compile-time dependency. This should break a lot of compile dependencies in phoenix applications using `action_fallback` - as a "central" component it tends to accumulate a lot of dependencies itself.
> Don't create compile-time dependencies for action_fallback

- lib/phoenix/router/route.ex
`pipe_through` is a list of atoms, as noted in the [module docs](https://github.com/phoenixframework/phoenix/blob/60b87846f3dde0800f93c7db375c356d6dbdc6b9/lib/phoenix/router/route.ex#L22)
> Fix Phoenix.Router.Route.build/13 spec

- guides/introduction/installation.md
It is indeed mentioned in _Up and Running_, but this is the page I re-read first every time I return to Phoenix after several months with other langs, and always have to click around because I forgot what the exact command is (plus it also changed from `mix phoenix.new` at one point). It might also be prudent to give proper context to newcomers as well.
Thanks for considering!
> Explicitly mention `mix phx.new` in Installation guide

- lib/phoenix/endpoint/supervisor.ex
`":"` is a valid character if the host is an IPv6 address.
edit: this assumes the http protocol, we don't need to handle `file://`, do we?
Fixes #3975
> use "/" to detect invalid hosts instead of ":"

- test/phoenix/integration/endpoint_test.exs
- test/support/endpoint_helper.exs
It appears there have been several failures in CI recently due to `:eaddrinuse` errors on the `test/phoenix/integration/endpoint_test.exs`
* https://github.com/phoenixframework/phoenix/runs/1142688759
* https://github.com/phoenixframework/phoenix/runs/1124717272
This attempts to fix the issue by leveraging `:gen_tcp.listen(0,[])` to have the OS provide several unused ports.
/cc @josevalim
> Fix :eaddrinuse errors when running in CI

- lib/mix/tasks/phx.gen.context.ex
- test/mix/tasks/phx.gen.html_test.exs
- test/mix/tasks/phx.gen.json_test.exs
- test/mix/tasks/phx.gen.live_test.exs
When a context exists and a user issues `mix phx.gen.live --no-context`, there is a warning about generating into an existing context, even though the user is not using the context. This change prevents that warning from displaying in the shell.
**Note:** The files being output of the generators are not changing, only the warning/prompt.
The tests in this branch, without the corresponding production code applied, output the following:
```
** (RuntimeError) no shell process input given for yes?/1
stacktrace:
(mix 1.10.4) lib/mix/shell/process.ex:148: Mix.Shell.Process.yes?/1
(phoenix 1.6.0-dev) lib/mix/tasks/phx.gen.context.ex:279: Mix.Tasks.Phx.Gen.Context.prompt_for_code_injection/1
(phoenix 1.6.0-dev) lib/mix/tasks/phx.gen.live.ex:98: Mix.Tasks.Phx.Gen.Live.run/1 …
```
> Silence context generation warnings on `--no-context`

- .github/workflows/ci.yml
This pull request adds Elixir 1.11 to CI and updates Erlang/OTP minor and/or patch versions to their latest.
Its main distinction from https://github.com/phoenixframework/phoenix/pull/4015 is that it mantains conformity to [José Valim advice](https://github.com/dashbitco/broadway/pull/188#issuecomment-649314540):
> I would still advise folks to go with:
> * For each Elixir version, add a run with earliest supported [major] Erlang/OTP
> * For the last Elixir version, also test the latest supported [major] Erlang/OTP
Please refer to the original discussion on https://github.com/dashbitco/broadway/pull/188 for the full rationale.
> Add Elixir 1.11 to CI

- guides/introduction/community.md
The line break made the second line in the paragraph be interpreted as a separate bulleted list item rather than a continuation of the link on the first line.
The live page: https://hexdocs.pm/phoenix/community.html
> Remove extraneous line break in Community docs

- guides/deployment/releases.md
Added `deps.get --only $MIX_ENV` to use the environment variable. This ensures mix only pulls the dependencies necessary for the type of mix environment set within the dockerfile.
> Updated Dockerfile in releases.md

- lib/mix/phoenix.ex
- priv/templates/phx.gen.context/test_cases.exs
- priv/templates/phx.gen.html/controller_test.exs
- priv/templates/phx.gen.json/controller_test.exs
- priv/templates/phx.gen.live/live_test.exs
- test/mix/tasks/phx.gen.context_test.exs
- test/mix/tasks/phx.gen.html_test.exs
- test/mix/tasks/phx.gen.json_test.exs
- test/mix/tasks/phx.gen.live_test.exs
Hello, 
I've stumbled on an issue where generated test cases weren't valid because  `IO.inspect` and `Kernel.inspect` by default inspect only 50 elements in maps. Therefore
generating a schema for example :
`mix phx.gen.live NewPerformers Performer performers attr1 ... attr55`
will result in invalid maps in test cases where `@create_attrs` etc. will be truncated by `inspect`
with `...}` at the end
like this:
```%{attr1: "some value", ..., attr50: "some value, ...}```
It is my first look in the Phoenix code base so my fix is rather naive. I think that I might be fixed in a better way like maybe writing a helper or something. But for now, I have no better idea ;) 
Cheers
Piotr
> fix generators for big argument list >50

- assets/js/phoenix.js
- assets/test/serializer_test.js
- lib/phoenix/channel.ex
- lib/phoenix/channel/server.ex
- lib/phoenix/socket/serializers/v2_json_serializer.ex
- test/phoenix/integration/websocket_channels_test.exs
- test/phoenix/socket/v2_json_serializer_test.exs
- test/support/websocket_client.exs
Initial pass. We need to decide how we want to support the caller push and receive of binary data. For example, we can support `push("foo", <<>>)` or we can require an explicit `push("foo", {:binary, "..."})` since we can't really distinguish between someone pushing a string vs binary and as of now we require maps. Likewise, on the `handle_in` side, either `handle_in("foo", <<>>, socket)` or `handle_in("foo", {:binary, <<>>}, socket)`
> Add binary serialization support to default serializers

- priv/templates/phx.gen.html/controller_test.exs
- priv/templates/phx.gen.schema/migration.exs
When generating code with `phx.gen.html`, the following files have formatting errors
```shell-session
$ mix format --check-formatted
** (Mix) mix format failed due to --check-formatted.
The following files were not formatted:
* test/phx_blog_web/controllers/post_controller_test.exs
* priv/repo/migrations/20201020032211_create_posts.exs
```
Below is the diff the formatter generates
```diff
diff --git a/priv/repo/migrations/20201020032428_create_posts.exs b/priv/repo/migrations/20201020032428_create_posts.exs
index 4270def..18029ab 100644
--- a/priv/repo/migrations/20201020032428_create_posts.exs
+++ b/priv/repo/migrations/20201020032428_create_posts.exs
@@ -8,6 +8,5 @@ defmodule PhxBlog.Repo.Migrations.CreatePosts do
timestamps()
end
-
end
end
diff --git …
```
> Fix formatting with phx.gen.html generated code

- priv/templates/phx.gen.json/view.ex
When running `mix phx.gen.json`, the following formatting error is returned
```shell-session
$ mix format --check-formatted
** (Mix) mix format failed due to --check-formatted.
The following files were not formatted:
* lib/phx_blog_web/views/post_view.ex
```
Below is the diff the formatter generates
```diff
diff --git a/lib/phx_blog_web/views/post_view.ex b/lib/phx_blog_web/views/post_view.ex
index 8462ba6..c009fd3 100644
--- a/lib/phx_blog_web/views/post_view.ex
+++ b/lib/phx_blog_web/views/post_view.ex
@@ -11,8 +11,6 @@ defmodule PhxBlogWeb.PostView do
end
def render("post.json", %{post: post}) do
-    %{id: post.id,
-      title: post.title,
-      body: post.body}
+    %{id: post.id, title: post.title, body: post.body}
end
end
```
This PR copies the same attribute map generator logic …
> Fix formatting with phx.gen.json generated code

- guides/deployment/deployment.md
- guides/deployment/releases.md
This adds the `MIX_ENV=prod` to the docs when running `mix.digest`.
Omitting this will cause errors if there are dev only deps.
> Add MIX_ENV when running digest

- installer/templates/phx_single/config/prod.exs
- installer/templates/phx_single/config/prod.secret.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/prod.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/prod.secret.exs
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
#3551 converted the config from list to keyword by moving the first `inet` / `inet6` option under `transport_options[:socket_opts]`.
All options is down to [ranch_top](https://ninenines.eu/docs/en/ranch/1.7/manual/ranch_tcp/)
This can be simplified by using `:ip` option  actually, since ranch seems to pick up right socket based on the `:ip` option.
Also it could be simpler to use, since if a user want to bind to specific ip address by changing only `:ip` option, not two places to make sure use right `socket opts`.
[ranch_tcp (1.7)](https://ninenines.eu/docs/en/ranch/1.7/manual/ranch_tcp/)
> inet
>     Set up the socket for IPv4.
> inet6
>     Set up the socket for IPv6.
> ip
>     Interface to listen on. Listen on all interfaces by default.
See also [ranch …
> Use ip option instead of transport socket_opts

- installer/templates/phx_assets/package.json
This should work fine since `sass-loader` [supports both libraries](https://github.com/webpack-contrib/sass-loader#implementation) by default:
> By default the loader resolve the implementation based on your dependencies. Just add required implementation to package.json (sass or node-sass package) and install dependencies.
I'm not entirely sure wether the `.sass-cache` in `.gitignore` is still needed though.
Closes #4042.
> Replace deprecated node-sass with sass

- guides/deployment/gigalixir.md
We added support to push to gigalixir via the master branch or the main branch. This means `git push gigalixir` should work in the majority of cases.
> Remove `master` now that github defaults to `main`

- integration_test/test/code_generation/app_with_no_options_test.exs
This ports the recently removed `mix/tasks/phx.new_test.exs` into the integration test suite so we can ensure the development workflow and code compilation works as expected. Here is the previous test for reference:
https://github.com/phoenixframework/phoenix/blob/8e13ccc2f95911655bb9287d49126cb329daa18b/test/mix/tasks/phx.new_test.exs#L44-L92
Since this is running the test in a separate beam instance, we have to send requests using a real http client instead of directly calling the endpoint in elixir. The code to start `mix phx.server` without leaving a zombie process came from @josevalim's comment here: https://github.com/phoenixframework/phoenix/pull/4027#issuecomment-717788510
> Add integration test for development workflow

- guides/contexts.md
Guide in router mounts SessionController under `/sessions` path, not `/session`. Article later on also refers to `/sessions`.
> Now if you visit the sign-in page at http://localhost:4000/sessions/new and enter a bad email address, you should be greeted with your flash message.
> Let's sign in at http://localhost:4000/sessions/new
> Fix typo in contexts guide

- lib/phoenix/endpoint.ex
:wave: hi hi
I see that in the change from 1.4 to 1.5 the `c:Phoenix.Endpoint.subscribe/2` and `c:Phoenix.Endpoint.unsubscribe/1` callbacks and implementations were removed (specifically by [this commit](https://github.com/phoenixframework/phoenix/commit/b7d7751d4fdae3e5e3b26605652e57d73ca4bd32)). It looks like later the callback implementations were undeprecated by [this commit](https://github.com/phoenixframework/phoenix/commit/3d9a6fc73f6cec4e1b0ca3e94fbe1b98a797fe8f) but the callbacks themselves weren't restored.
I understand that these callbacks probably aren't very desirable if y'all intend to deprecate & remove them in the future, but for the time being having them really helps when writing tooling on top of Phoenix that leverages (un)subscribing directly from the Endpoint (and …
> restore Endpoint subscribe/2 and unsubscribe/1 callbacks

- guides/deployment/releases.md
- Use an Elixir 1.11 image, built by the hexpm team
- Break apart build steps for better caching (eg, changing
`config/prod.exs` does not require re-running `mix deps.get`)
- Add notes about configuring a containerized application
> Update example Dockerfile and add some notes

- installer/templates/phx_assets/package.json
I found `assets/package.json` from `phx.new` uses MIT license.
I believe it should be private and unlicensed by default, for following reasons:
- it is unlikely to publish the package to repository, since it's for final assets not for a library
- Elixir part of generated code does not have any license information
From [package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json)
> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
>
> { "license": "UNLICENSED" }
>
> Consider also setting "private": true to prevent accidental publication.
---
Update: since `license` doesn't seem to be required, and npm does not emit error when `private` is true and `license` is omitted, updated this PR to omit license instead of using …
> Private asset package by default

- assets/js/phoenix.js
The documentation provides an example like `channel.push("event")`, but that no longer works with an undefined payload object. An empty object should be the equivalent functionality as the previous undefined case.
#4079 
-----
A second option is to update this code: 
```
encode(msg, callback){
if(msg.payload.constructor === ArrayBuffer){
```
to 
```
encode(msg, callback){
if(msg.payload && msg.payload.constructor === ArrayBuffer){
```
However, I like the idea of not worrying about an undefined msg.payload in the code. But this approach should be completely side effect free, since it would be equivalent to the code that used to work.
> Default pushed payload to an empty object if not provided

- guides/authentication/mix_phx_gen_auth.md
- guides/mix_tasks.md
- lib/mix/tasks/phx.gen.auth.ex
- mix.exs
This adds a new `mix phx.gen.auth` guide under the Authentication guide sub section.
This also adds `mix phx.gen.auth` to the Mix Tasks guide.
> Add mix phx.gen.auth to guides

- guides/directory_structure.md
- guides/mix_tasks.md
- Directory structure:  Was not representing directories correctly
- Mix Tasks: Wrong tree ending tokens
> normalize directory tree markdown examples

- guides/deployment/deployment.md
- guides/deployment/releases.md
- guides/howto/using_ssl.md
- lib/phoenix/channel.ex
- lib/phoenix/code_reloader.ex
- lib/phoenix/endpoint.ex
- lib/phoenix/token.ex
This fixes #4094 
Ran a find-and-replace for `MyApp.Endpoint` -> `MyAppWeb.Endpoint` and `YourApp.Endpoint` -> `YourAppWeb.Endpoint` in the docs
Phoenix generates the endpoint under AppWeb, not under App; I think the docs should reflect this, as I discovered this issue when attempting to use `broadcast!` functions taken from the docs
> Docs: MyApp.Endpoint -> MyAppWeb.Endpoint 

- installer/templates/phx_web/views/error_helpers.ex
This updates the generators in line with https://github.com/phoenixframework/phoenix_live_view/pull/1278
> Use `input_name` in generated LiveView error helpers instead of `input_id`

- integration_test/test/code_generation/app_with_mssql_adapter_test.exs
- lib/mix/tasks/phx.gen.auth.ex
- lib/mix/tasks/phx.gen.context.ex
- test/mix/tasks/phx.gen.context_test.exs
- test/mix/tasks/phx.gen.html_test.exs
- test/mix/tasks/phx.gen.json_test.exs
- test/mix/tasks/phx.gen.live_test.exs
This adds new `--merge-with-existing-context` and `--no-merge-with-existing-context` options to the `phx.gen.context` family of generators. This allows us to have an integration test that merges`phx.gen.auth` generated code with an existing context (a prerequisite for me to clean up some duplicate fixture generation code). This test also found a formatting error where we were missing a blank newline between the existing context's functions/tests and `phx.gen.auth`'s functions/tests. I've also added unit tests and documentation for these new options. 
I was unable to add unit tests for `--no-merge-with-existing-context` because `System.halt/0` is called in the generator and kills the tests.
> Add flag to skip prompt when generator find an existing context

- lib/phoenix/router.ex
This one tripped me up a bit coming from Rails. The path should be singular in Phoenix like it is in the other examples surrounding it, right? If I'm wrong sorry for the bad change, can just close the PR.
> Fix code typo in Router documentation

- lib/phoenix/channel.ex
- lib/phoenix/endpoint.ex
Added {:binary, data} as possible payload type for channel messages.
> Fix Channel and Endpoint typespecs

- guides/plug.md
> Fix a typo

- Earthfile
Problem: 
- when re-running `earthly` locally after changing a test Elixir file, we see a full recompilation of all the dependencies. 
Solution: 
- in the test-setup preparation step we can also compile all the packages with `MIX_ENV=test`. That way they get reused for all the dependent steps.
> CI: include `mix compile` in `test-setup`

- guides/introduction/community.md
- installer/templates/phx_web/templates/page/index.html.eex
The Elixir Discord has grown to a considerable size (and Discord uses Elixir *wink wink*),
so I (think) it's due time to include it as a part of "the community"
> include Elixir Discord as part of "community"

- Earthfile
Instead of running the full `+test_setup` target for javascript tests (that installs elixir and mix.lock dependencies), this uses the latest node 12 alpine container and saves about 10 seconds in build time.
> Run js tests in node container

- guides/controllers.md
when referencing proper name of the framework
> Capitalize "Plug"

- lib/mix/tasks/phx.gen.auth.ex
- lib/mix/tasks/phx.gen.context.ex
- priv/templates/phx.gen.auth/context_fixtures.ex
This PR removes a duplicate `context_fixtures.ex` template from when `phx.gen.auth` was a separate project. It also adds the following internal functions to `Mix.Tasks.Phx.Gen.Context`:
* `ensure_context_file_exists/3`
* `ensure_test_file_exists/3`
* `ensure_test_fixtures_file_exists/3`
These allow other generators like `mix phx.gen.auth` to ensure these files exist before attempting to inject functions into them.
> Remove duplicate test fixture module templates

- guides/testing/testing_controllers.md
Remove extra "we" and improve language at the end of the `create` test section.
> Typo + language improvement

- guides/telemetry.md
Absinthe library added Telemetry events in [version 1.5](https://github.com/absinthe-graphql/absinthe/blob/master/CHANGELOG.md#v150-alpha).
> Add Telemetry link to Absinthe

- lib/mix/tasks/phx.gen.live.ex
Use "a" instead of "an" before "users".
> Grammar fix in doc

- guides/plug.md
The plug.md links to `localhost` are all broken on Hexdocs because it is including the trailing quote.
> Fix Documentation Links

- lib/phoenix/controller.ex
We use `@unsent` to raise an `AlreadySentError` if trying to change the view or the layout after a response is sent. This updates the module variable to include the other unsent states from https://github.com/elixir-plug/plug/blob/40efbe4680f98eb063ea1e17f079c4243b6593cf/lib/plug/conn.ex#L258
It *might* be nicer to expose `unsent?`/`sent?` as functions on Plug.Conn itself. What do you think?
> Update `@unsent` Plug.Conn states to include `:set_chunked` and `:set_file`

- ISSUE_TEMPLATE.md
- guides/deployment/gigalixir.md
- guides/deployment/heroku.md
- guides/introduction/installation.md
- installer/lib/mix/tasks/phx.new.ex
- lib/phoenix/endpoint/watcher.ex
Across the Phoenix docs, Node.js is spelled differently as e.g. "node", "NodeJS", "Node.JS", etc, but the correct spelling is Node.js. This is corrected across the project in this PR.
The term "node" is also easy to confuse with erlang nodes, so it improves the clarity to use Node.js.
References for Node.js being the correct spelling:
- https://nodejs.org/en/
- https://github.com/nodejs/node/pull/33088
> Use consistent naming of Node.js in docs

- guides/deployment/heroku.md
Per https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3, this is already the default, so perhaps not worth mentioning.
Unless I'm missing something and this setting is extra important in the context of Heroku – if so, perhaps the docs could say a bit more about that.
> heroku.md: Remove unnecessary "longpoll: false"

- installer/test/mix_helper.exs
- lib/mix/tasks/phx.gen.auth.ex
- mix.exs
- test/mix/tasks/phx.gen.auth_test.exs
This adds for `phx.gen.auth` to the main test suite. I found that trying to debug using the integration tests is difficult because they are running in a different BEAM instance and tools like `IO.inspect/1` don't output anything to the console (because output is being captured).
1. In order to get these tests to work, I had to add an optional second parameter to `Mix.Tasks.Phx.Gen.Auth.run/1` that allows me to pass in the database adapter and skip the dependency check. With these two options set, I'm able to bypass the need to compile the app that's being tested and test this like the rest of the `phx.gen.*` tasks.
2. Since `phx.gen.auth` injects code into several files in an existing phoenix project, instead of trying to create those needed files in something like …
> Add phx.gen.auth tests to main test suite

- guides/plug.md
We will get an error when loading http://localhost:4000/,
```
ArgumentError at GET /
assign @locale not available in eex template.
```
It is the PageController, not the HelloController where the plug needs to go.
> Fix bug in Plug guide code

- guides/howto/custom_error_pages.md
The custom error pages guide has HTML example for custom error page but it's outdated so different from the generated layout a lot.
This PR is to align the HTML example with the generated layout. Please note that it still does not use Routes helper (like the existing example)
> Update example to match with generated layout

- guides/introduction/installation.md
> Standardize names in Installation (Guides)

- package.json
Many JavaScript bundlers nowadays support native ES modules syntax. In fact, ES modules syntax is preferred it is easier to statically analyze and allows tree-shaking to reduce bundle size.
Modern native ESM dev servers like [vite](https://vitejs.dev/) or [snowpack](https://www.snowpack.dev/) can also consume the native ESM version of the Phoenix client directly without having to convert it from cjs back to ESM again! However, this is only possible if the Phoenix package specifies the entry point to the file using modern syntax.
This PR adds:
- The `module` field: de-facto standard supported by almost all ESM-supporting bundlers.
- The `exports` field: as specified by [Node.js](https://nodejs.org/api/packages.html#packages_package_entry_points). Many modern bundlers are also converging on …
> Add modern entry point for npm package

- installer/templates/phx_assets/app.scss
Vertical % for padding and margins is a percent of the width. When maximizing the browser to full screen especially with a large form, this causes modal to be pushed down the page.
"vh" units seems to be simplest fix here, as the modal is used full screen. If you wanted to generalize it to work within any container, you could do absolute and top/bottom percent (as that refers to the height).
https://css-tricks.com/oh-hey-padding-percentage-is-based-on-the-parent-elements-width/
> Update template app.scss for modal

- lib/phoenix/logger.ex
- test/phoenix/endpoint/endpoint_test.exs
- test/phoenix/router/routing_test.exs
Related to #4194, this change would let us remove a wrapper that needs to know too much about Plug.Telemetry internals and replace it with this:
```ex
plug Plug.Telemetry,
event_prefix: [:phoenix, :endpoint],
log: &__MODULE__.log_level/1
@quiet_paths ["alive", "health", "ready", "favicon.ico"]
def log_level(%{path_info: [head | _]}) when head in @quiet_paths, do: false
def log_level(_), do: :info
```
Incidentally, deploying the wrapper reduced our production log output by a non-insignificant amount (screenshot below) :)
Wdyt?
> Dynamic Phoenix.Logger level

- guides/controllers.md
- guides/ecto.md
- guides/telemetry.md
- lib/phoenix/socket.ex
In the same vein as 12bd337cfdea7e5a7e38d35ae9c891857c6046d7
> Standardize use of key-value pair(s)

- installer/templates/phx_assets/package.json
In case there is another minor release, this fixes Issue #4126
> Allow webpack > 4.41 but < 5

- lib/phoenix/router.ex
- test/phoenix/router/routing_test.exs
@keathley and I were working on standardized metrics around our web requests on a per-route basis. We were able to do that using the `[:phoenix, :router_dispatch, :stop]` Telemetry event for requests that complete successfully, because this event includes things like the `:plug`, `:plug_opts`, and `:route` in the metadata.
Unfortunately, for requests that crash or exit for some reason while in the application code, we got a `[:phoenix, :router_dispatch, :exception]` instead of `:stop`, which we expected, but we were surprised that some of the metadata was missing, which meant that we couldn't attribute this failure to a particular route / controller action like we wanted to.
We didn't like the idea, but we were able to work around this issue by capturing this metadata from the `:start` …
> Include route information in router_dispatch exception telemetry

- integration_test/test/code_generation/app_with_defaults_test.exs
- lib/mix/phoenix.ex
- lib/mix/phoenix/schema.ex
- lib/mix/tasks/phx.gen.context.ex
- priv/templates/phx.gen.context/fixtures.ex
- test/mix/tasks/phx.gen.context_test.exs
This PR extends the fixture generator to create functions for generating unique attributes like is done with the email address in `mix phx.gen.auth`. I'm thinking of this as the first step in fixing #4156.
Below is the file generated by the integration test
```elixir
defmodule DefaultApp.BlogFixtures do
@moduledoc """
This module defines test helpers for creating
entities via the `DefaultApp.Blog` context.
"""
@doc """
Generate a unique post body.
"""
def unique_post_body, do: "some body" <> "#{System.unique_integer([:positive])}"
@doc """
Generate a unique post order.
"""
def unique_post_order, do: System.unique_integer([:positive])
@doc """
Generate a unique post publish_at.
"""
def unique_post_publish_at do
DateTime.add(
~U[2021-02-22 04:29:00Z],
System.unique_integer([:positive])
) …
```
> Generate fixture functions for unique attributes

- lib/phoenix/socket/transport.ex
The previous code would give an error `state` would not be available.
> Fix EchoSocket example code

- test/phoenix/config_test.exs
This test is failing intermittently because the assertion to ensure the ETS table has been removed does not wait for the `Phoenix.Config` process to end this flaky test failure can be recreated pretty reliably with the following command:
```
$ mix test test/phoenix/config_test.exs --trace --seed 422381
Phoenix.ConfigTest [test/phoenix/config_test.exs]
* test can change configuration (2.8ms) [L#25]
1) test can change configuration (Phoenix.ConfigTest)
test/phoenix/config_test.exs:25
Assertion with == failed
code:  assert :ets.info(meta.test, :name) == :undefined
left:  :"test can change configuration"
right: :undefined
stacktrace:
test/phoenix/config_test.exs:42: (test)
* test reads configuration from env (0.01ms) [L#9]
* test starts an ets table as part of the module (0.03ms) [L#17]
* …
```
> Fix flaky Phoenix.Config test

- test/phoenix/router/routing_test.exs
I've seen a few times where one of the telemetry tests fail due to unexpected events like this:
```
+test |   1) test telemetry phoenix.router_dispatch.start and .exception are emitted on crash (Phoenix.Router.RoutingTest)
+test |      test/phoenix/router/routing_test.exs:282
+test |      Unexpectedly received message {:telemetry_event, [:phoenix, :router_dispatch, :stop], {%{duration: 129101}, %{conn: %Plug.Conn{adapter: {Plug.Adapters.Test.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "www.example.com", method: "GET", owner: #PID<0.2406.0>, params: %{"id" => "123"}, path_info: ["users", "123", "edit"], path_params: %{"id" => "123"}, port: 80, private: …
```
> Fix unexpected event errors in telemetry routing tests

- lib/phoenix/router.ex
- test/phoenix/router/routing_test.exs
Ensures the `[:phoenix, :router_dispatch, :stop]` event is emitted when either a plug in the router or a controller halts a conn using `Plug.Conn.halt/2`.
Fixes [#4216][1]
[1]: https://github.com/phoenixframework/phoenix/issues/4216
> emit [:phoenix, :router_dispatch, :stop] on halted Plug.Conn

- priv/templates/phx.gen.html/show.html.eex
- priv/templates/phx.gen.live/show.html.leex
Fixes #4237
Adds `|` between "Edit" and "Back" links in generated show template:
> Add pipe separator between Edit and Back links on show template

- README.md
- RELEASE.md
- guides/introduction/installation.md
- installer/README.md
- installer/mix.exs
I have noticed the instructions were wrong because in some files the Phoenix version was not updated,
so we can rely on `mix archive.install` to retrieve the latest version.
> Correct installation instructions & simplify release process

- guides/deployment/gigalixir.md
When following the Gigalixir deployment guide, I didn't know I could provide an application name because the guide does not mention it. It would have been fine if the name was editable, but it is not. I ended up losing "a lot" of time because I had to destroy my app and create a new one later.
I suggest this small update in the guide since I believe most people would prefer an easy-to-use name, rather than the long random names generated by default.
> Explain how to choose an application name in the Gigalixir guide

- RELEASE.md
- installer/lib/phx_new/generator.ex
- installer/mix.exs
It relies on whether the version number is a -dev or not.
It also fixes the current state, as it hasn't been reverted after latest release.
> Simplify release automatically determining phoenix_dep in generator

- guides/contexts.md
- guides/controllers.md
- guides/howto/custom_error_pages.md
- guides/request_lifecycle.md
- guides/routing.md
- guides/testing/testing_controllers.md
- guides/views.md
- lib/phoenix/controller.ex
- lib/phoenix/router.ex
It replaces the use of "the `PageController`" with "the `PageControler` controller.
Same with views.
Previously we were using "the `PageController` module" to avoid this, but this is incorrect
since the module is `HelloWeb.PageController`.
> Fix grammar. Remove article "the" before controllers and views

- test/phoenix/integration/endpoint_test.exs
- test/support/endpoint_helper.exs
This PR is an attempt to fix intermittent test `:eaddrinuse` test failures like these:
https://github.com/phoenixframework/phoenix/runs/2003562379#step:4:509
I first came across this approach with this PR to bypass: https://github.com/PSPDFKit-labs/bypass/pull/77. It appears that it takes a little bit of time for a socket to shut down after a connection is closed. When open up a connection to find an unused port, then close it so we can reopen it for the phoenix endpoint, if the OS hasn't finished closing down the socket we'll receive this error. By opening a port both times with `so_reuseport`, even if the OS isn't finished shutting down the original socket, we shouldn't receive an error.
Here are a few links I found useful about `so_reuseport`
* An in-depth stackoverflow answer about …
> Use so_reuseport to fix eaddrinuse test failures

- RELEASE.md
It mentions specifically that `mix test` needs to be run for Phoenix and the Phoenix installer.
> Improve RELEASE instructions

- guides/views.md
was introduced in https://github.com/phoenixframework/phoenix/pull/4226
> Remove leftover git conflict mark in Views guide

- mix.exs
- test/phoenix/digester_test.exs
This pull request adds the `.map` extension to the list of _gzippable extensions_.
This is mostly a matter of consistency rather than performance.
```
priv/static
├── css
│  └── app.css
├── js
│  ├── app.js
│  └── app.js.map
```
```
priv/static
├── cache_manifest.json
├── css
│  ├── app-c60f329d5f7165fe3b7016ba48b7252f.css
│  ├── app-c60f329d5f7165fe3b7016ba48b7252f.css.gz
│  ├── app.css
│  └── app.css.gz
├── js
│  ├── app-a3f59890277c10a37e518d3f4e19fb7e.js
│  ├── app-a3f59890277c10a37e518d3f4e19fb7e.js.gz
│  ├── app.js
│  ├── app.js-1d02813ec397c786ae3c97473218f5e0.map # ← Not gzipped
│  ├── app.js.gz
│  └── app.js.map # ← Also not gzipped
```
I think it would be a safe default to assume that if Phoenix generates source maps by default, that they should also be included in the …
> Add .map to gzippable extensions

- installer/lib/mix/tasks/phx.new.ex
- installer/test/phx_new_test.exs
- lib/mix/tasks/phx.ex
It gives the --version option the `phx` task.
It also streamline the format of `mix phx` with headers.
It mentions it is the "Phoenix installer" when you run
`mix phx.new --version`
Output now looks like:
$ mix phx --version
Phoenix v1.6.0-dev
$ mix phx.new --version
Phoenix installer v1.6.0-dev
$ mix phx
Phoenix v1.6.0-dev
Productive. Reliable. Fast.
A productive web framework that does not compromise speed or maintainability.
-v, --version        # Prints Phoenix version
mix phx.digest       # Digests and compresses static files
mix phx.digest.clean # Removes old versions of static assets.
....
> Introduce `mix phx --version` option and streamline help output format

- lib/phoenix/router/helpers.ex
Keyword.has_key?/2 is being passed a non atom key
as described in:
https://github.com/phoenixframework/phoenix/issues/4280
Fixes the issue by checking the type of key
/cc  @conradwt
> Fix router helper

- RELEASE.md
Fix indentation in Markdown list.
Since it was already inside a list, it was looking as one line item.
> Fix indentation in Markdown list.

- guides/deployment/releases.md
Hi 👋 
The package install command `apk add python` no longer seems to work. The solution appears to be to explicitly specify `python2` or `python3` instead. There is some discussion of that here: https://stackoverflow.com/a/62652692/312962
> Update Dockerfile instructions in releases.md

- installer/lib/phx_new/generator.ex
- installer/templates/phx_ecto/repo.ex
This is an intentionally small PR. I'm not sure how best to accomplish this, so I made a tiny guess.
It adds a default `socket_options` to allow IPv6 with Ecto. This is backwards compatible, it does not disable IPv4. It is necessary [so Phoenix can talk to databases over IPv6](https://elixirforum.com/t/use-fly-io-internal-dns-for-resolving-database-url/38889) by default.
Tests pass but I'm not sure this change would actually break an existing test.
> Enable IPv6 for Ecto

- lib/phoenix/presence.ex
Order of invokes was changed, but description wasn't. This synchronizes example with it's description
> Fix presence example description

- guides/contexts.md
Missing div tag in contexts.md did not match with what is generated.
Updated to correctly reflect what is generated.
> Added div for clarity in contexts.md

- guides/routing.md
view/0 was called out for aliasing helpers, when the actual function
aliasing occurs in view_helpers
> Updated Routing guide for clarity

- installer/lib/mix/tasks/phx.new.ex
- lib/mix/phoenix/schema.ex
- lib/mix/tasks/phx.gen.auth.ex
- lib/mix/tasks/phx.gen.context.ex
- lib/mix/tasks/phx.gen.schema.ex
- priv/templates/phx.gen.schema/migration.exs
- priv/templates/phx.gen.schema/schema.ex
- test/mix/tasks/phx.gen.schema_test.exs
I added a new option `--prefix` to the `mix phx.gen.schema` task and to the all related tasks: `phx.new`, `phx.gen.context`, `phx.gen.auth`. So it would be possible to generate files with pre-installed `prefix` option in the `table/2` function in migrations and `@schema_prefix` module attribute in schemas.
> add option `--prefix` to schema and migration generators

- lib/mix/tasks/phx.digest.ex
- lib/phoenix/digester.ex
- lib/phoenix/endpoint.ex
- lib/phoenix/endpoint/supervisor.ex
- test/phoenix/digester_test.exs
- test/phoenix/endpoint/endpoint_test.exs
When generating `static_path` or `static_url` as well as when running `mix phx.digest`it would be nice to have the option of the generated urls to have the `vsn=d`query or not.
This PR adds the possibility and maintains the current behavior as the default, being opt-in.
The `vsn` option as added to the runtime configuration `:url` of `Phoenix.Endpoint` as it looked like an expected place for it.
This PR is also related to #1784
> Change vsn query in assets url to be configurable

- installer/templates/phx_test/live/page_live_test.exs
👋 thanks for all the awesome work with Phoenix and LiveView!
What changed?
=============
This commit tries to clarify the "disconnected/connected" concepts in the sample [`page_live_test.exs`][page live test] that is generated when running `phx new --live`.
Why is a change needed?
----
The `PageLiveTest` that is generated with the `phx new --live` installer seems to be either incorrect or uses confusing language.
The [test][page live test] currently shows the `live/2` helper returning a `disconnected_html` as the third element in the three tuple:
```elixir
{:ok, page_live, disconnected_html} = live(conn, "/")
```
The term "disconnected" is confusing because [`LiveViewTest` docs][test docs] use that same term to describe the disconnected HTML returned from the stateless HTTP request.
Take …
> Clarify disconnected html in PageLiveTest

- lib/phoenix/endpoint.ex
- lib/phoenix/endpoint/cowboy2_adapter.ex
Was out of sync with Phoenix.Endpoint.Cowboy2Adapter
Also added a mention of "top-level" options to make it more clear that
the Phoenix.Endpoint.Cowboy2Adapter configuration lives at the same
level as all the other endpoint configuration and is nested under any
other key.
Also update the link to Plug.Cowboy.Drainer to be more specific/correct
> Update Phoenix Endpoint drainer configuration docs

- guides/mix_tasks.md
The current behavior of `mix phx.new hello` is to create an application at `lib/hello/application.ex`. The Mix Tasks guide referred to the application living in `lib/hello.ex` in a couple of places. Update these paths to reflect the current behavior and the current console output.
I'm very new to Phoenix and Elixir, so please let me know if this is just a misunderstanding on my part. I've been working my way through the guides and this one didn't quite match what I'm seeing.
> Update application filepath in Mix Tasks guide

- guides/realtime/channels.md
It appears as though the code example and the written documentation relating to [Incoming Events]( https://hexdocs.pm/phoenix/channels.html#incoming-events) has diverged slightly. The documentation makes reference to `handle_out/3` and explains the default behaviour, even stipulating the following:
> We included it here because hooking into outgoing events allows for powerful message customization and filtering. 
The code example does not contain a definition for `handle_out/3`.
This change updates the description to ensure it is consistent with the code example.
> Correcting divergence between description and code example in channels guide

- lib/phoenix/param.ex
- test/phoenix/param_test.exs
I tried to place a float in the query string of a URL using the router helpers like this:
```elixir
latitude = 32.149989
longitude = -110.835842
MyAppWeb.Router.Helpers.page_path(:search, %{latitude: latitude, longitude: longitude})
```
But I get the error
```
** (Protocol.UndefinedError) protocol Phoenix.Param not implemented for 32.149989 of type Float. This protocol is implemented for the following type(s): Any, Map, Integer, BitString, Atom
```
I've implemented this in my own application, but I felt like Float is a common enough data structure that it would make sense for me to add this change back upstream for everyone else too. I'm happy to make any changes necessary.
> Implement Phoenix.Param for Float

- assets/js/phoenix.js
- assets/test/socket_test.js
Closes #4307 
According to a Chromium bug report, intensive throttling is not applied to timers that are scheduled from a "network response handler". This was in response to Chrome 88 breaking Microsoft SignalR in a similar way to what's been reported.
I refactored our heartbeat based on their reference:
https://bugs.chromium.org/p/chromium/issues/detail?id=1186569#c3
**EDIT:** I am adding the annotated workflow for this change to reduce any confusion about what is going on.
1. First, `resetHeartbeat()` is called from `onConnOpen`
2. `resetHeartbeat` schedules `sendHeartbeat()` to be invoked after the heartbeat interval (default 30s). Note: the returned timer is not tracked.
3. `sendHeartbeat` then...
1. generates `pendingHeartbeatRef`
2. pushes the heartbeat message to the channel
3. …
> Schedule heartbeat on reply to avoid intensive throttling

- guides/deployment/deployment.md
- guides/deployment/fly.md
- mix.exs
Add an official guide for deploying Elixir applications to Fly.io.
Fly provides a private WireGuard mesh network and it is easy to cluster nodes and deploy to multiple regions regions.
> add fly.io deployment guide

- README.md
Updated the `README` links to point to the new Elixir IRC channel on [libera.chat](https://libera.chat).
> Update README.md with new IRC address

- guides/deployment/releases.md
I initially prepared the Dockerfile for my project according to the Phoenix docs and it worked great without modifications.
After updating to Elixir 1.12 and Erlang/OTP 24, the app crashes at startup complaining about missing `libstdc++` and `libgcc`.
The [OTP 24.0 release announcement](https://www.erlang.org/downloads/24.0) doesn't explicitly mention the new dependencies, but it does say this:
```
The JIT-compiler is enabled by default on most x86 64-bit platforms that have a C++ compiler that can compile C++17.
```
Since [`libstdc++`](https://pkgs.alpinelinux.org/package/edge/main/ppc64le/libstdc++) depends on `libgcc`, it's enough to add the `libstdc++` package to the docker release image.
For anyone who runs into this issue, this is the full error log without `libstdc++` installed: …
> Add libstdc++ package to docker release image in the docs

- CONTRIBUTING.md
- installer/templates/phx_web/templates/page/index.html.eex
Spotted this when creating a new project: the initial template still references the old Freenode channel #elixir-lang.
Update this to #elixir on Libera, which is the [new official IRC channel](https://github.com/elixir-lang/elixir-lang.github.com/commit/1434d99966abe6ce50765e07fa9a6addb1e8355f).
> Update Elixir IRC channel references

- guides/deployment/releases.md
Docker ARGs are scoped per build stage (https://github.com/moby/moby/issues/37345#issuecomment-400245466). The `MIX_ENV` ARG is created in the `build` stage and is referenced in the `app` stage. This results in an incorrect `COPY` directory. The proposed change creates a global `MIX_ENV` ARG that is then usable in both stages.
> Fix multi-stage build args in dockerfile example

- CHANGELOG.md
- guides/introduction/installation.md
- installer/templates/phx_assets/package.json
- lib/phoenix/endpoint.ex
This is a complementation of https://github.com/phoenixframework/phoenix/pull/4337.
Things done:
- Removed the Node.js version requirement from the installation guide
- Added instead the "engines" field with node >=14.x to the `package.json`  
This should at least warn if an older Node.js version is used.
But theoretically we still would support older versions.
(webpack says it support 10.x - but you never really know with all the other dependencies)
- Changed the Node.js download page directly to the nodejs.org landing site (probably quicker for first time node users)
> Improve asset pipline docs

- installer/templates/phx_single/config/config.exs
- installer/templates/phx_single/config/dev.exs
- installer/templates/phx_single/config/runtime.exs
- installer/templates/phx_single/config/test.exs
- installer/templates/phx_umbrella/apps/app_name/config/config.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/runtime.exs
- installer/templates/phx_umbrella/config/dev.exs
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
This fix is needed because we don't want to include a new dependency
required for the "SMTP" adapter (gen_smtp). We choose to use the "Local"
adapter by default and mention Swoosh docs for more adapters.
> Fix default Swoosh adapter for mailer generator

- guides/controllers.md
This PR fixes the url to the `mime.types` documentation.
> Fix the mime.types url

- lib/mix/tasks/phx.gen.channel.ex
- lib/mix/tasks/phx.gen.socket.ex
- priv/templates/phx.gen.socket/socket.ex
- priv/templates/phx.gen.socket/socket.js
- test/mix/tasks/phx.gen.channel_test.exs
- test/mix/tasks/phx.gen.socket_test.exs
The socket generation was removed from the installer, so this task is needed
when the user wants to work with _websockets_ outside LiveView.
This also changes the `mix phx.gen.channel` task to include instructions regarding
this new task when the default socket - `user_socket.ex` does not exist under `/channels`.
Closes https://github.com/phoenixframework/phoenix/issues/4376.
> Add phx.gen.socket to generate a socket file

- installer/lib/phx_new/web.ex
Topbar is not included in the web part of newly created umbrella application. 
Similar issue was already fixed for single application by @josevalim in:
https://github.com/phoenixframework/phoenix/commit/2c5e39117232dc3456f61b03febdd65caca13ea3
Original issue: https://github.com/phoenixframework/phoenix/issues/4380
> fix: Include topbar in newly generated umbrella apps

- lib/phoenix/controller/pipeline.ex
- lib/phoenix/router.ex
Otherwise, in the :compile mode, the router is not recompiled if a *module* plug changes.
cc @josevalim
> Expand the plug only in plug_init_mode :runtime

- installer/templates/phx_single/config/test.exs
- installer/templates/phx_umbrella/config/test.exs
This is to allow unnecessary recompilations when running tests.
> Set plug_init_mode: :runtime in generated config/test.exs

- lib/mix/tasks/phx.digest.clean.ex
- lib/phoenix/digester.ex
- test/phoenix/digester_test.exs
This PR allows `mix phx.digest` to be fully reversed by the `phx.digest.clean` task:
```sh
mix phx.digest.clean --all
```
When run with the `--all` flag, the following files are cleaned:
* All digested versions listed in the `cache_manifest.json` file (including latest).
* All compressed originals (e.g `robots.txt.gz`).
* The `cache_manifest.json` file itself.
> Add --all flag to phx.digest.clean

- guides/howto/custom_error_pages.md
- guides/plug.md
- installer/templates/phx_live/templates/layout/app.html.leex
- installer/templates/phx_live/templates/layout/live.html.leex
- installer/templates/phx_live/templates/layout/root.html.leex
- installer/templates/phx_web/templates/layout/app.html.eex
- lib/mix/tasks/phx.gen.auth/injector.ex
- test/mix/tasks/phx.gen.auth/injector_test.exs
- test/mix/tasks/phx.gen.auth_test.exs
Closes issue #4347
In the html templates the aria roles of `main` and `nav` are explicitly set. According to the spec both `main` and `nav` elements have an implicit aria role and you should not set any role. Explicitly setting the role used to be a workaround for older browsers (released before 2013, most notably IE11).
In the PR I basically make the following change for main and nav elements:
```diff
-   <main role="main" class="container">
+   <main class="container">
<p class="alert alert-info" role="alert"><%%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%%= get_flash(@conn, :error) %></p>
<%%= @inner_content %>
</main>
```
Further reading on explicitly setting role="main" can be found in the MDN article: …
> Remove implicit aria roles for navigation and main elements

- lib/mix/tasks/phx.routes.ex
Added documentation suggesting an alias for those of us who use umbrella apps and didn't think to automate the Router specification. Result of #4411.
> Add documentation suggesting alias for umbrella phx.routes

- lib/mix/tasks/phx.gen.auth.ex
- priv/templates/phx.gen.auth/confirmation_controller.ex
- priv/templates/phx.gen.auth/confirmation_controller_test.exs
- priv/templates/phx.gen.auth/confirmation_edit.html.eex
- priv/templates/phx.gen.auth/context_functions.ex
- priv/templates/phx.gen.auth/registration_controller.ex
- priv/templates/phx.gen.auth/routes.ex
- test/mix/tasks/phx.gen.auth_test.exs
Instead of confirming when the link in the email is clicked,
we explicitly require the user to press a button, that is to
avoid crawlers from automatically visiting emails and confirming
accounts.
> Two step confirmation

- lib/phoenix/code_reloader/server.ex
:wave: hello!
I was playing around with protocol consolidation and I noticed some odd behavior that happens when
- the code reloader is turned on
- protocols have been consolidated (`mix compile.protocols`, or you had `consolidate_protocols: true` in the mix.exs at some point)
- so there are `.beam`s in `_build/<env>/lib/<my_app>/consolidated/`
- protocol consolidation is turned off in the `mix.exs`
- start up `iex -S mix phx.server`
- trigger a code-reload
- derive a protocol at runtime (paste in a new struct with `Jason.Encoder` to IEx for example)
It looks like the `purge` step and the run of the `compile.protocols` respect the `:consolidate_protocols` Mix.Project configuration but this `Code.prepend_path/1` called on the consolidation path does not, so triggering the code reloader …
> guard prepend_path/1 on :consolidate_protocols in code reloader

- lib/phoenix/socket.ex
`%{}` means an empty map
This should silence some dialyzer warnings in phoenix related packages
that use this field legitimately, e.g. this warning that currently appears
in Phoenix.LiveView.Socket.id/1 should disappear:
```
The inferred type for the 1st argument is not a
supertype of the expected type for the id/1 callback
in the Phoenix.Socket behaviour.
Success type:
atom()
| %{
:private => atom() | %{:connect_info => nil | maybe_improper_list() | map(), _ => _},
_ => _
}
Behaviour callback type:
%Phoenix.Socket{
:assigns => map(),
:channel => atom(),
:channel_pid => pid(),
:endpoint => atom(),
:handler => atom(),
:id => nil | binary(),
:join_ref => _,
:joined => boolean(),
:private => %{},
:pubsub_server => atom(),
:ref => _,
:serializer => atom(),
:topic => binary(),
:transport => …
```
> Update Socket.t private field to allow any map

- guides/asset_management.md
- guides/directory_structure.md
- mix.exs
This PR aims to aid developers whose applications have asset management needs
that have grown beyond the possibilities of the Elixir esbuild wrapper.
The PR replaces [one on the esbuild repo](https://github.com/phoenixframework/esbuild/pull/14).
> Document asset management and the creation of custom build configurations

- lib/phoenix/controller.ex
- lib/phoenix/controller/pipeline.ex
Hi!
Apparently became unused after the deprecation of the instrument API: 19b0b01e2fc751901e06fcd74db1fc5b39672d26
---
Was looking at options to disable/change log level per route or controller and reading these lines of code made me think `use Phoenix.Controller, log: false` was still a valid option, when apparently no longer is. So hopefully cleaning this up avoids any future confusion for anyone :-)
Unless this is in fact used and I am missing something.
Thanks!
> Removes unused module attribute @phoenix_log_level

- guides/deployment/releases.md
In docker build instructuion should create homedir depends on $USER not
strict with `/home/elixir`.
> Update docker build in Deploying with Releases documentation

- guides/contexts.md
Missing back-tick causes incorrect formatting.
> Fixes typo in contexts documentation

- CHANGELOG.md
Include changes to `mix phx.new` generator, highlighting that `--live` is now the default and the home page has been reverted to a traditional controller  [#4378]
> Update CHANGELOG to cover phx.new changes

- guides/deployment/heroku.md
The `esbuild` step as proposed in the Heroku guide is broken and produces the error:
```
The input path "&&" does not exist
```
As it seems to not be interpreting the string as a shell command. This in turn causes the boot error:
```
[error] Could not find static manifest at "/app/_build/prod/rel/<app>/lib/<app>-0.1.0/priv/static/cache_manifest.json". Run "mix phx.digest" after building your static files or remove the configuration from "config/prod.exs".
```
Simply dropping the cleanup step from build "solves" the problem, but maybe the cleanup needs to happen inside the generated mix task?
> Update heroku.md to remove broken hook command

- lib/phoenix/endpoint.ex
Hi,
Similar to #2729, in the documentation of `Phoenix.Endpoint`, I have added more details to the example for `:watchers` when the `:env` option is given.
I did not know I needed to give a list of tuples to `:env`.
> Document `env` option on watchers

- CHANGELOG.md
- priv/templates/phx.gen.html/form.html.heex
- test/mix/tasks/phx.gen.html_test.exs
After converting the template from .eex to .heex on https://github.com/phoenixframework/phoenix/commit/12f4116e299b43bec9c74a379d8de55b0a13262c, a comma was left behind.
```diff
-<.form let={f} for={@changeset}, action={@action}>
+<.form let={f} for={@changeset} action={@action}>
```
Thanks for making it so easy to contribute in this project. Just doing `mix deps.get` and `mix test` was enough to start.
> Remove comma on generated form.html.heex

- lib/phoenix/socket.ex
`Phoenix.Endpoint.socket/3` sets `websocket` on by default and `longpoll` is off by default. Previous phrasing implied that both were on by default.
https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3
`:longpoll` - controls the longpoll configuration. Defaults to false
https://github.com/phoenixframework/phoenix/blob/v1.5.12/lib/phoenix/endpoint.ex#L649-L650
> Update `Phoenix.Socket` docs to clarify defaults

- guides/howto/custom_error_pages.md
It seems that the opening sentence in the guide [How-To Custom Error Pages](https://hexdocs.pm/phoenix/1.6.0-rc.0/custom_error_pages.html) got accidentally cut off in PR #4226.
This PR aims to restore the full sentence, while keeping the intended edits from PR #4226.
Have a nice day!
> Restore opening sentence in How-To Custom Error Pages

- installer/templates/phx_single/gitignore
- installer/templates/phx_umbrella/apps/app_name_web/gitignore
I noticed that `priv/static/cache_manifest.json` wasn't ignored by default in the `phx.new` generator while the `priv/static/assets` directory was, and this bugged me as it seems that both work hand in hand and should probably be committed together (or ignored together).
I asked for advice about that in [this forum thread](https://elixirforum.com/t/should-i-commit-priv-static-cache-manifest-json/42194) and apparently, checking the cache manifest runs the risk of Phoenix trying to serve the wrong assets unless the digested assets are also checked in with it (which is not the case by default). Though, in most cases `mix phx.digest` is run prior to deployments which overwrites the checked manifest and that's why this usually doesn't cause real-world problems.
Since it seems there is no …
> Add `cache_manifest.json` to `.gitignore` in `mix phx.new` task

- guides/channels/channels.md
This PR fixes the formatting for the example in [Joining Channels](https://hexdocs.pm/phoenix/channels.html#joining-channels) and [Incoming Events](https://hexdocs.pm/phoenix/channels.html#incoming-events). 
It is missing a space between the two functions to be on par with `mix format` standards.
Fixes #4493
> Fix formatting in Channels Guide example

- lib/phoenix.ex
Considering that the name of the extension is not very indicative of its purpose and even if you do know what it is you may be wondering why it's included by default.
I had to do some light Github spelunking, but figured I'd save some time for the next person.
The list of dependencies generally seems to be out of date, this PR chips away at it :)
> doc: Add dependency documentation for Swoosh

- assets/js/phoenix/ajax.js
- assets/js/phoenix/constants.js
The `Ajax` class is never instantiated, so `this.states` would fail with the following error:
To fix, I simply moved the ready states into a constant and check from there :)
> Fix LongPoll readyState check

- lib/phoenix/test/conn_test.ex
- test/phoenix/test/conn_test.exs
Implements a `ConnTest.path_params/2` function in favor of `LiveViewTest.redirected_params/2` 
Related to: https://github.com/phoenixframework/phoenix_live_view/pull/1575
> Implement ConnTest.path_params/2

- lib/mix/tasks/phx.gen.notifier.ex
Looking at [maybe_print_mailer_installation_instructions/1](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Notifier.html#maybe_print_mailer_installation_instructions/1), there was a small typo found.
> Fix typo in `maybe_print_mailer_installation_instructions/1` docs

- guides/deployment/fly.md
I ran into some issues when trying to deploy phoenix 1.6-rc0 to fly from a Mac M1 (Apple Silicon)
The problem seems to be with building the docker image locally. On Apple Silicon computers, Docker uses qemu as an emulation layer to build Linux platform images which seems to cause issues.
I solved the problem by using fly's remote builder (just using `fly deploy --remote-only`) and thought it would be good to update the docs in case someone else runs into the same issue.
> Mention fly's remote builder on deployment guide

- guides/contexts.md
Appears to have been missed in the revamping of this guide in e4c87a5a290b2e4c9c7ccae35ed4c444397ff992.
> Correct one word ("page" should be "product")

- guides/plug.md
This PR includes:
* updates the default endpoint plugs based on the output of `mix phx.new hello` (v1.6.0), the main addition is the description of `Phoenix.LiveDashboard.RequestLogger`
* I also replaced some links like `[Module](https://hexdocs.pm/project/module.html` and took advantage of the links that ExDoc creates when it founds modules enclosed by backticks :)
* Now the pipeline `:browser` reflects the output from `mix phx.new hello`
* Finally, fixed a missed link to `Plug.Conn.assign/3`, you can find the link at the bottom of the text as references.
> guides: update Plug page

- guides/request_lifecycle.md
This PR updates the `pipeline` structure in `HelloWeb.Router` based on the `mix phx.new hello` output using v1.6.0. 
This PR also removes the (ab)use of the _simply_ word on the same page. I would suggest avoiding saying that things "are easy" or that they're not challenging, everyone learns at its own pace, and that's fine. See https://justsimply.dev/ for more examples.
> guides: update 'request life-cycle' page

- config/config.exs
- mix.exs
- package.json
I honestly don't know if this is the best approach but I am quite stuck with trying to upgrade to Phoenix 1.6 on a fairly large project that uses "Jest" for testing of their JavaScript code (elixirforum thread here: https://elixirforum.com/t/phoenix-1-6-0-npm-package-cannot-be-imported-in-jest/42670/4)
I tried various hacks and third party tools suggested on Jest thread but I wasted a whole day and fixing one thing breaks another, typical Node.js developer story. So, I decided to build CJS package of phoenix.js that Jest can understand like it used to up to 1.5.9.
Now I suspect there was a good reason for not including CJS file, but maybe it's just an omission - for the later case I provide this PR below. Note: in this project "phoenix" is the only package that doesn't provide CJS …
> Build CommonJS module along with ESM and IIFE

- guides/views.md
This PR includes the following changes:
* In the "Rendering templates" section, update the path to the main layout template `lib/hello_web/templates/layout/root.html.heex` instead of `lib/hello_web/templates/layout/app.html.heex`
* Update the example in the "Rendering templates" section to follow the output from Phoenix v1.6.0
> guides: update 'Views and templates'

- guides/contexts.md
Using Changeset.get_field to fetch existing category id's didn't work.
Switcing to Changeset.get_change seems to correct the problem.
See 
https://elixirforum.com/t/problem-retrieving-products-selected-status-in-1-6-0-rc0-contexts-guide/42217
for full explanation : But note that poster was expecting different 
behavior from those two functions.
Could he have found a bug ?
> Fixing doc to make example work with Phoenix 1.6

- guides/controllers.md
This PR includes the following changes:
* Replace `put_layout/2` with `put_root_layout/2` in the _Assigning
Layouts_ section, so, that way the sample works as expected.
* Update the code examples to match Phoenix v1.6.0
* Reduce the verbosity in some links, instead we use the _autolink_
feature from ExDoc (See: https://github.com/elixir-lang/ex_doc/#auto-linking)
* Sort the link references at the end of the document
> guides: update 'Controllers' guide

- guides/deployment/releases.md
The current `Dockerfile` example seems to be not working out of the box. 
This is due to the `COPY` command which copies `my_app/` release directory instead of its content, and when referenced in the `ENTRYPOINT`, it was expecting `bin/` folder.
To fix this I added `/*` to reference the directory content like in this PR
OR
We could reference the directory in `ENTRYPOINT`
```docker
ENTRYPOINT ["my_app/bin/my_app"]
```
But imho, I think the PR solution is cleaner
> Fix Dockerfile in guides/deployment/releases.md

- guides/channels/channels.md
Hi, i noticed the html as shown in the guide would not compile. So I changed the docu to use the {}-notation and also changed the path from js/app.js to assets/app.js
> small fixup in the channel guide

- guides/directory_structure.md
The fact that Phoenix ships with [Milligram](https://milligram.io/) by default is presently not mentioned anywhere in the guides:
https://github.com/phoenixframework/phoenix/search?q=milligram+path%3Aguides
This PR is meant to address this by giving Milligram a quick mention early-on in the official guides.
> Mention milligram in the guides

- README.md
As outlined in [Issue #4573](https://github.com/phoenixframework/phoenix/issues/4573), `After the switch to ESbuild, there is no longer a "watch" task`
This PR commit removes the outdated line from the `README.md`
Before submitting, I reviewed the [CONTRIBUTING.md](https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md) and ran `mix test`
Result:
```
Finished in 0.02 seconds (0.02s async, 0.00s sync)
3 tests, 0 failures
Randomized with seed 268228
```
Thank you all for the amazing work you do!
> Remove Outdated instructions in README for generating phonenix.js

- priv/templates/phx.gen.channel/channel.ex
- priv/templates/phx.gen.channel/channel_test.exs
- test/mix/tasks/phx.gen.channel_test.exs
I added some parentheses, so the generated code passes `mix format --check-formatted`.
> Tweak Channel Generator Output

- guides/real_time/channels.md
phoenix.js is no longer in a single js file, it is now a directory of files. Alternatively we could link to the index.js as the entry point but I think linking to the entire directory is easier to navigate from.
> Fix link to phoenix javascript files

- lib/mix/phoenix/schema.ex
- test/mix/tasks/phx.gen.html_test.exs
While I don't see why someone would want to do this, the DB
engines (e.g., PostgreSQL, MySQL) allow setting an enum type with a single value and don't throw
errors.
Fixes: #4594
> bugfix: allow creating enum with a single value

- guides/controllers.md
The docs are not precise, when using safari - as it will not render without a content_type..
More than open for better wording.
fixes https://github.com/phoenixframework/phoenix/issues/4597
> update controllers.md (safari no content type)

- guides/contexts.md
I noticed a couple of tiny typos in this guide, which was otherwise a very useful resource, so thought I would contribute back to fix them for others.
> Fixes a couple of minor typos in Context guide

- lib/phoenix/endpoint.ex
- lib/phoenix/endpoint/supervisor.ex
- test/phoenix/endpoint/supervisor_test.exs
This PR adds support for running watchers such as `esbuild` on an endpoint even when `:server` configuration is set to `false`. 
This is especially useful when running multiple Phoenix projects under an umbrella application in an environment where you only have access to a single port. In such an environment, you will likely resort to a proxy such as [master_proxy](https://github.com/jesseshieh/master_proxy) and set all the your Endpoint configurations to `server: false`.
See https://github.com/phoenixframework/esbuild/issues/34 for a more detailed explanation of the problem.
> add `:force_watchers` option to `Phoenix.Endpoint`

- guides/ecto.md
These changes bring the Ecto Guide's iex examples in line with the current Phoenix version.
> ecto guide: update iex example output and add missing concept in Data persistence section

- lib/mix/tasks/phx.gen.release.ex
There are some mentions of **live_beats** (https://twitter.com/chris_mccord/status/1462851686352015361) in `phx.gen.release` task docs. Perhaps Chris is trying out new ways to tease us 🤔
Anyway, this PR fixes it to use current app name.
> Fix app name in phx.gen.release docs

- guides/ecto.md
- guides/mix_tasks.md
- installer/lib/phx_new/generator.ex
This follows the orders used in DATABASE_URL, which is
1. username
2. password
3. host
4. database
> Place hostname before database in config

- config/config.exs
- installer/templates/phx_single/config/config.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/config.exs
The `esbuild` installer is by default using version `0.14.0`. However `phx.new` is generating an old version `0.13.5` for the :dev config. When there is a mismatch, esbuild downloads the version that is in the config.
Seemingly esbuild v 0.13.5 segfaults in container, but 0.14.0 does not. Changing the version number in the config fixed my problem.
I made the changes to the `phx.new` installer templates, as well as the `config.ex` in the tree, and am submitting them as this PR.
Thanks for the great work.
> Fixes m1 container segfault (Issue #4629)

- lib/mix/tasks/phx.gen.release.ex
The task generates a hint that is misleading since it uses the wrong namespace:
```
[warn] Conditional IPV6 support missing from runtime configuration.
Add the following to your config/runtime.exs:                                                                                                                                                                                                                                                                                                                           maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []
config :hello, Hello.Repo,
...,
socket_options: maybe_ipv6
[warn] Conditional server startup is missing from runtime configuration.
Add the following to the top of your config/runtime.exs:
if …
```
> Fix content of warning messages in phx.gen.release

- assets/js/phoenix/socket.js
Due to a typo this parameter is not showing up in the online documentation.
Before
After
> Fix socket opts.params documentation

- lib/phoenix/token.ex
The default should be called out so it doesn't lead to confusion or bugs when working with this function. Verbiage taken directly from https://github.com/elixir-plug/plug_crypto/blob/v1.2.2/lib/plug/crypto.ex#L257
> Update the Phoenix.Token.verify/4 docs to mention the default value for max_age

- lib/phoenix/token.ex
Got bitten by this missing piece mentioning the default value earlier today and reading the source led me to the option in Plug.Crypto.
> Add :max_age documentation entry for Phoenix.Token.sign/4

- lib/mix/phoenix/schema.ex
This PR fixes compatibility on schema generator when `Tzdata.TimeZoneDatabase` is the default `time_zone_database`.
```elixir
config :elixir, :time_zone_database, Tzdata.TimeZoneDatabase
```
It solves the error.
```
(with time zone database Tzdata.TimeZoneDatabase), reason: :time_zone_not_found
```
#4633
> tzdata compatibility

- guides/directory_structure.md
- guides/plug.md
- installer/templates/phx_single/config/runtime.exs
This PR fixes a typo and improves the grammar in a few places in the docs.
> Docs: fix typo & grammar mistakes

- lib/phoenix/token.ex
There are three types of errors, this PR adds the missing one. ;)
> docs: add missing error for `Phoenix.Token.verify/4`

- lib/phoenix/socket/transport.ex
- test/phoenix/socket/transport_test.exs
In the internal implementation, the related function is at [here](https://github.com/phoenixframework/phoenix/blob/8d2b33ac9691bd624ede602088d213f89600d233/lib/phoenix/socket/transport.ex#L596):
```elixir
defp origin_allowed?(:conn, uri, _endpoint, %Plug.Conn{} = conn)
```
`uri` is a struct which is generated by `URI.parse/1`, the type of `scheme`
field is a string.
`conn` is a `%Plug.Conn{}`, the type of `scheme` field is an atom.
Because of that, this check will always failed in real case.
* * *
This commit fixes above issue, and fix related tests.
> Fix broken `check_origin: :conn`

- priv/templates/phx.gen.release/Dockerfile.eex
Use _exec form_ instead of _shell form_ [https://docs.docker.com/engine/reference/builder/](https://docs.docker.com/engine/reference/builder/) because the _shell form_ does not forward signals (used by `docker stop`).
> Fix docker stop timeout with phx.gen.release

- guides/deployment/releases.md
- priv/templates/phx.gen.release/Dockerfile.eex
- test/mix/tasks/phx.gen.release_test.exs
The builder image reuses `MIX_ENV` to get deps and copy configs, but the runner image assumes the app was built on the "prod" env, which may not be case if one changes the `MIX_ENV` env value on the build image. This PR just make it a bit easier to spot that the env should be same on both build and runner images.
> Leverage MIX_ENV on the runner image

- installer/templates/phx_assets/app.js
We recently added a Phoenix installation guide to the Tailwind CSS website ([see here](https://tailwindcss.com/docs/guides/phoenix)), and someone pointed out that this comment has a spelling mistake. We've corrected it in our guide, but figured I'd share the fix upstream too 👍
> Fixing spelling mistake in app.js

- guides/contexts.md
Prefix unused "cart" variable with an underscore in contexts guide.
> Prefix unused variable with an underscore

- priv/templates/phx.gen.auth/auth.ex
- priv/templates/phx.gen.auth/context_functions.ex
- priv/templates/phx.gen.auth/settings_controller.ex
- priv/templates/phx.gen.auth/settings_controller_test.exs
- priv/templates/phx.gen.auth/test_cases.exs
Use `schema.singular` on the context function declaration names as most of then already use it.
This is useful when the `phx.gen.auth` is used multiple times, for example:
```
mix phx.gen.auth Accounts User users --web auth
mix phx.gen.auth Accounts Admin admins --web admin
```
In test file, I'm not sure what is the best description for the `inspect/2` function.
> Normalise phx.gen.auth function declaration names

- installer/templates/phx_web/endpoint.ex
- lib/phoenix/controller.ex
- test/phoenix/controller/controller_test.exs
* Include same_site: "lax". Albeit the default,
it is not the default in Safari
* x-xss-protection has been removed in most browsers
in favor of Content Security Policy
* cross-origin-window-policy was not actualy implemented
in browsers and SameSite handles more cases
> Update security practices

- priv/templates/phx.gen.auth/auth.ex
- priv/templates/phx.gen.auth/auth_test.exs
When restoring user sessions from the "remember me"-cookie, the `live_socket_id` value is not set, so the `log_out_*`-function does not disconnect sockets for users that are on a "restored" session.
This PR sets a `live_socket_id` on the session when creating a new session from the "remember me"-cookie and adds an assert in the test suite for this behaviour.
> Set `live_socket_id` when restoring session from cookie

- lib/phoenix/endpoint/cowboy2_adapter.ex
This puts an application's `:http` configuration for their Endpoint
first in the list to be sent into the ranch supervisor. When running on
a newer commit of ranch, this allows an application to specific
`:inet_backend` for the TCP sockets spawned by ranch.
Without this change, the application configuration is always _after_
port and IP. Since `:inet_backend` is only valid when specified as the
first argument to `:gen_tcp.listen/2`, this results in a `:badarg`
error.
> Prioritize user `:http` configuration for ranch

- lib/mix/tasks/phx.gen.release.ex
- priv/templates/phx.gen.release/Dockerfile.eex
- test/mix/tasks/phx.gen.release_test.exs
Checks if the `assets` directory is present and adds asset handling to the Dockerfile if needed.
Not sure if this is the desired direction.
Ref: #4669
> Don't generate asset handling in Docker when directory doesn't exist

- lib/phoenix/endpoint/supervisor.ex
- test/phoenix/endpoint/endpoint_test.exs
- test/phoenix/socket/transport_test.exs
I was reading through the endpoint supervisor code and saw the following TODO so I thought I'd try tackling it.
```
```
This adds the following log message when an endpoint's `:url` or `:static_url` function has a deprecated `{:system, env_var}` tuple.
```
00:14:41.051 [warn] :url configuration containing values of {:system, env_var} tuples for Phoenix.Endpoint.EndpointTest.SystemTupleEndpoint is deprecated.
Configuration:
config :phoenix, Phoenix.Endpoint.EndpointTest.SystemTupleEndpoint,
[host: {:system, "ENDPOINT_TEST_HOST"}, port: {:system, "ENDPOINT_TEST_PORT"}]
Either move these config values into config/runtime.exs:
config :phoenix, Phoenix.Endpoint.EndpointTest.SystemTupleEndpoint,
host: System.get_env("ENDPOINT_TEST_HOST"),
port: System.get_env("ENDPOINT_TEST_PORT")
Or read them …
```
> Deprecate {:system, env_var} tuples for configuring endpoint urls

- lib/phoenix/endpoint.ex
Not sure why it is broken currently, but https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-common-configuration is pretty hard to read right now.
> Fix syntax highlighting in a socket config

- test/mix/tasks/phx.gen.context_test.exs
As commented [here](https://github.com/phoenixframework/phoenix/issues/4683#issuecomment-1059713876). The issue #4683 should be already fixed, but I didn't see any unit test to generate a context that includes enums like:
```
mix phx.gen.context Accounts User users email:text:unique password:text:redact status:enum:verified:unverified:disable
```
So, the idea behind this unit test is to avoid regressions in the future.
> chore(gen.context): add unit test including enums

- priv/templates/phx.gen.release/dockerignore.eex
I wasn't sure why files that weren't copied via the Dockerfile were listed in `,dockerignore`. After learning about the docker build context and why `.dockerignore` is important, I thought it might be helpful to add a comment in this file which provides a little background.
> Add comment explaining .dockerignore

- lib/mix/tasks/phx.gen.notifier.ex
This removes the `maybe_print_mailer_installation_instructions/1` function from the `mix phx.gen.notifier` docs. It seems like this is an internal phoenix function and not an API contract we want to maintain, I'm thinking it should probably be marked with `@doc false`.
If this is intentionally in the API docs so other libraries can depend on it, we can close this PR.
> Hide maybe_print_mailer_installation_instructions/1 from docs

- priv/templates/phx.gen.auth/notifier.ex
- test/mix/tasks/phx.gen.auth_test.exs
After running `mix phx.gen.auth` and registering a user, I was surprised to see the confirmation email come from the literal "MyApp" instead of the actual name of my app. This updates the generators to set from name to the actual name of the app.
I noticed `mix phx.gen.notifier` uses the from name "Phoenix Team" and email "team@example.com". 
https://github.com/phoenixframework/phoenix/blob/90a6494ffc028f2d5aa84a8a3d8f5a022fbd97d3/priv/templates/phx.gen.notifier/notifier.ex#L8
Do we want to update the default from name and email in both of these generators to match?
> Use app name as from name for phx.gen.auth notifier

- priv/templates/phx.gen.auth/schema_token.ex
Currently `mix phx.gen.auth` creates a token module where its references to the current module look like this
```elixir
defmodule MyApp.Accounts.UserToken do
{token, %MyApp.Accounts.UserToken{token: token, context: "session", user_id: user.id}}
#...
end
```
This seems pretty verbose, especially with a longer application name.
This PR switches the references to the current module from using the fully qualified name to use `__MODULE__` instead. This keeps these lines shorter, makes renaming this module easier, and reduces the formatting errors in the generated code if the application name is too long.
```elixir
defmodule MyApp.Accounts.UserToken do
{token, %__MODULE__{token: token, context: "session", user_id: user.id}}
#...
end
```
I didn't find any other generated code that built structs …
> [phx.gen.auth] Improve references to current module SchemaToken module

- lib/phoenix/router/route.ex
While going through the router code to understand its internals, I noticed that `build_params/1`
method is being unused. I thought there might be something I must be missing, so I removed
it and ran the test suite. But that did not seem to break anything. In case this method is needed for a
particular reason, I'd be happy to extend the test cases to account for this.
Thank you 😄
> Removes build_params/1 method since it is unused

- guides/ecto.md
This fixes code examples throughout the Ecto guide for Phoenix v1.6.6. They did not work with the schema generated from `mix phx.gen.schema ...`.
> Match code examples with generated code

- assets/js/phoenix/longpoll.js
Hi,
As a few of my clients access my Phoenix site from restricted networks like government departments, which block or intercept websocket connections, I have to fall back to `LongPoll` from time to time.
When this happens, I'm seeing a lot of errors along the lines of `Cannot read properties of undefined (reading 'code')`, `event is undefined` and so on. After some debugging, I traced the issue back to the `LongPoll` implementation calling the `onclose` and `onerror` callbacks without any arguments, causing those errors when Phoenix's `Socket` tries to access properties on callback events.
In this PR, i updated the `onclose`, `onopen` and `onerror` callbacks to always include an argument, even if it only is an empty object, to closer reflect the behavior of the `WebSocket` transport.
I …
> Fix `LongPoll` callbacks in JS client

- lib/phoenix/presence.ex
- test/phoenix/presence_test.exs
* Raises a custom ArgumentError when init/1 is missing on a presence module when handle_metas/4 is present.
* Adds callback docs to init/1 and handle_metas/4
* Updates references in docs
> Update presence client docs

- guides/authentication/mix_phx_gen_auth.md
Fixes indentation of the list of password hashing mechanisms to properly render the links.
> Fix list indentation in auth guide.

- guides/deployment/releases.md
- priv/templates/phx.gen.release/Dockerfile.eex
This PR refactors the Dockerfile to use build arguments for the base images (with defaults). This allows for easier customisation in CI. For example in Ci we do something like:
```yaml
- name: Docker build
uses: docker/build-push-action@v2
with:
build-args: |
ELIXIR_VERSION=${{ steps.asdf-versions.outputs.elixir }}
ERLANG_VERSION=${{ steps.asdf-versions.outputs.erlang }}
```
> Use build arguments for docker base image versions

- assets/js/phoenix/constants.js
This is a quick drive-by I'm making while I was building the javascript in #4670 
Building our javascript gives the following warning:
```
> js/phoenix/constants.js:3:49: warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
3 │ export const global = globalSelf || phxWindow || this
```
Based on [globalThis - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#search_for_the_global_across_environments) I this the intention here is to use `global` if `window` and `self` both fall through.
> Get rid of top-level `this` in constants.js

- guides/channels/presence.md
Related to issue #4347 and pull request 4407 (https://github.com/phoenixframework/phoenix/pull/4407) where role="main" was removed from the standard templates.
I was just going through the docs/tutorials and ran into this. This PR will make sure the JavaScript works again. It's a tiny change, but as I proposed the earlier removal of role main so I felt obligated to also update this.
(creating it as a draft for now, maybe I find some other things that I can improve on)
> fix: remove role=main in documentation

- priv/templates/phx.gen.release/dockerignore.eex
I noticed builds were hanging when the language server running in VS Code had files open when the docker context was being built. Adding `.elixir_ls` to the `.dockerignore` file fixed it up and reduced the build context by ~18mb.
Some more context: https://community.fly.io/t/elixir-phoenix-docker-builder-timeouts-after-10-minutes-with-an-eof-error/3632
> Add .elixir_ls to .dockerignore

- lib/mix/tasks/phx.gen.release.ex
Sometimes in a project where everything is already compiled, The `mix phx.gen.release` task cannot correctly detect if ecto_sql is already installed or not. This is because the ecto_sql is in fact not loaded yet.
To resolve this we can either try to load ecto_sql using `Application.load(:ecto_sql)` before fetching the loaded apps or simply
use the `Mix.Project.deps_apps` to see if `ecto_sql` is there.
This PR currently implemented the latter.
> Fix flaky phx.gen.release ecto_sql check

- installer/templates/phx_single/formatter.exs
- installer/templates/phx_umbrella/apps/app_name/formatter.exs
- installer/templates/phx_umbrella/apps/app_name_web/formatter.exs
- installer/templates/phx_umbrella/mix.exs
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
That's an attempt to close #4749 
The config is added only if `@html` and Elixir >= 1.13.4 to meet formatter requirements.
> Add HTMLFormatter in formatter.exs templates

- lib/phoenix/router.ex
Closes #4715.
The examples use glob patterns with a prefix which raise a warning with Plug 1.13+.
> Update the routing guide to remove outdated examples

- installer/templates/phx_umbrella/formatter.exs
- installer/test/phx_new_umbrella_test.exs
Fix https://github.com/phoenixframework/phoenix/pull/4793#issuecomment-1102287862
Confirmed the behavior related on https://github.com/phoenixframework/phoenix_live_view/issues/1969 by generating a new umbrella app locally. I get the same exception if there is no `plugins: [Phoenix.LiveView.HTMLFormatter]` on umbrella root.
> Add HTMLFormatter to umbrella root

- installer/templates/phx_web/templates/layout/root.html.heex
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
Second part of https://github.com/phoenixframework/phoenix_html/pull/377
Ref https://github.com/phoenixframework/phoenix_html/issues/372#issuecomment-1107419742 "change the generators to use csrf_token_value".
> Installer - generate CSRF meta with csrf_token_value

- priv/templates/phx.gen.release/dockerignore.eex
Perhaps I am mistaken, but it seems like the `$ cat ...` line is not intended.
> Add # back for .dockerignore comment

- lib/phoenix/test/conn_test.ex
Hi!
I have an API that returns lists of things in the API without any wrapping. After parsing becomes a list:
`[object1, object2, object]`
and it breaks dialyzer because `json_response` specifies that parsed response might be only a map.
I've searched the project for lines that begin with `@spec`, have `json` in the name and `map` in the return value and it looks like it is the only place where `phoenix` assumes the shape of json.
> Fix JSON response @spec

- installer/templates/phx_single/config/config.exs
- installer/templates/phx_single/config/dev.exs
- installer/templates/phx_single/config/test.exs
- installer/templates/phx_umbrella/apps/app_name/config/config.exs
- installer/templates/phx_umbrella/config/dev.exs
- installer/templates/phx_umbrella/config/test.exs
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
Since the `:swoosh, :api_client` is set to false in `config.exs`, this
requires setting both the adapter and api_client in either `prod.exs` or
`runtime.exs` to ensure mails are sent in a production environment.
However, if this is not configured, the following error is raised:
```
** (UndefinedFunctionError) function false.post/4 is undefined
(module false is not available)
```
It is not entirely clear from the error how to track the value back to
this configuration setting.
The `:api_client` is not set in `dev.exs` and `test.exs` separately, as
these are the environments where this value is less likely to be
configured. Now in production, it will default to the swoosh default
(currently hackney). If the user does not have hackney installed in
mix.exs then the error message is more …
> Move swoosh api_client config out of config.exs to ENV.exs

- guides/authentication/mix_phx_gen_auth.md
- Add note about accessing notifier emails when project is configured to use Swoosh.
Since this guide mentions that emails will be logged to the terminal, I was surprised when I didn't see that happen. I vaguely remembered something about going to a URL to view the emails, but it took a while to hunt it down.  It will be easier on newcomers if this info is included in this guide as well.
> Update authentication guide

- guides/contexts.md
Following the guide, eventually I got to this point:
```
$ mix phx.server
Compiling 3 files (.ex)
warning: Category.__schema__/1 is undefined (module Category is not available or is yet to be defined)
lib/hello/catalog.ex:114: Hello.Catalog.list_categories_by_id/1
```
The flow of creating a product with categories then also fails.
The alias fixed it.
> docs: fix diff on ecto contexts walk through

- guides/directory_structure.md
- installer/templates/phx_single/lib/app_name/application.ex
The `Ecto.Repo` trigger some `:init` events that can be lost if the Telemetry start after the Repo.
> Use Telemetry as first child to not miss init telemetry events

- lib/phoenix/endpoint/supervisor.ex
Since Elixir has got the runtime config, it's not necessarily the case that the manifest will be configured in "config/prod.exs", it might be done in the "config/runtime.exs" using env variables for example. For that reason the wording in the error message becomes a bit confusing, I tried to change it as good as I can, sill might need to be more general.
> Adjust error message

- lib/phoenix/token.ex
Each `Phoenix.Token` function takes multiple arguments with ambiguous types. Furthermore, the functions delegate to `Plug.Crypto` which also lacks typespecs. This adds types and specs to make working with `Token` clearer, along with a minor adjustment to option documentation to keep the order consistent between functions.
> Add typespecs to phoenix token functions

- lib/mix/tasks/phx.gen.schema.ex
I added a small paragraph for `--prefix` to the `phx.gen.schema` docs, since it wasn't documented yet.
> Add prefix flag in `phx.gen.schema` docs

- lib/phoenix/socket/serializers/v2_json_serializer.ex
This applies the same conversion for socket.join_ref + reply.ref as one that's done within `encode!` for %Message{}, fixing the error below for when returning `{:noreply, {:ok, {:binary, bin}}, socket}` in `handle_in`.
```
[error] GenServer #PID<0.2890.0> terminating
** (ArgumentError) errors were found at the given arguments:
* 1st argument: not a bitstring
This typically happens when calling Kernel.byte_size/1 with an invalid argument or when performing binary construction or binary concatenation with <> and one of the arguments is not a binary
:erlang.byte_size(2)
(phoenix 1.7.0-dev) lib/phoenix/socket/serializers/v2_json_serializer.ex:145: Phoenix.Socket.V2.JSONSerializer.byte_size!/3
(phoenix 1.7.0-dev) lib/phoenix/socket/serializers/v2_json_serializer.ex:42: …
```
> Fix socket binary reply

- lib/phoenix.ex
I had people today that were discovering Phoenix and just thought that this was the main hub as it was linked as "Docs" from the phoenixframework.org website. I think that for a newcomer that end up there, having the guide link at the top probably would make more sense.
> Put the overview guides link top of moduledoc

- priv/templates/phx.gen.release/Dockerfile.eex
Use newer Debian base image.
Newer Elixir + Erlang releases do not exist on the older 2021 base. At least not as created by the hexpm builder.
Building a new Phoenix app with Elixir 1.14.0 and Erlang 25.0.4 fails to build the docker image because Hexpm has not defined an image for the new Elixir+Erlang versions on the older Bullseye 2021 base.
> Update Dockerfile template

- guides/howto/custom_error_pages.md
- installer/templates/phx_web/templates/layout/root.html.heex
And shorten meta viewport tag to common practice.
I think no new phx project wants to target Internet Explorer anymore.
> Remove obsolete meta http-equiv tag

- installer/templates/phx_web/components.ex
Allowed types for `input` element were missing most of supported types which even generated warnings in templates generated with `phx.gen.html`.
> Add more input types

- priv/templates/phx.gen.auth/confirmation_live.ex
- priv/templates/phx.gen.auth/confirmation_live_test.exs
- priv/templates/phx.gen.auth/login_live.ex
- priv/templates/phx.gen.auth/registration_live.ex
I ran the generator with `mix phx.gen.auth Accounts Player players` and my tests were failing because the templates are hard coded to `:user`.
```
test register player renders errors for duplicated email (TankTurnTacticsWeb.PlayerRegistrationLiveTest)
test/tank_turn_tactics_web/live/player_registration_live_test.exs:58
** (ArgumentError) could not find non-disabled input, select or textarea with name "player[email]" within:
```
The old form was using schema so it seems like the `:user` was an oversight in https://github.com/phoenixframework/phoenix/pull/4955/files#diff-2e85c1d43c43cc817baa18f588d767a32cda37aa39425e44aa6e488237d147e1
I though about adding a test for a mix call with different names but I figure if user still works then the code is correct. I smoke tested it in my app and it …
> Use schema for atom names in auth templates.

- lib/phoenix/verified_routes.ex
- test/phoenix/verified_routes_test.exs
Before this PR `~p"/foo?bar=#{struct}"` would give us `"/foo?bar==123"` because structs would be interpreted as maps of param values.
> Fix bug in sigil_p query encoding

- CONTRIBUTING.md
The formatter wont touch documentation blocks so they must be wrapped manually. I have previously been unsure about this and have noticed some wrap-edits before merges. 100ch seemed to be about what things were wrapped at?
> Add documentation line length suggestion to CONTRIBUTING.md

- installer/templates/phx_web/components.ex
- lib/mix/tasks/phx.gen.html.ex
- priv/templates/phx.gen.live/components.ex
This fixes two issues when generating HTML for a schema with a select tag.
The first is the slot within a `for` comprehension.
The other is the missing attribute `value` for the `:option` slot:
```
warning: undefined attribute "value" in slot "option" for component PhxBlogWeb.Components.input/1
lib/phx_blog_web/templates/post/edit.html.heex:17: (file)
```
> Update select tag generator with new components syntax

- lib/mix/tasks/phx.digest.ex
- test/mix/tasks/phx.digest_test.exs
Currently `mix phx.digest` exits with 0 on error which makes it harder to detect that something went wrong in CI/CD. This PR adds exit with 1 in such case.
> mix phx.digest to return non zero error code on failure

- guides/asset_management.md
I noticed that the link to the Phoenix Tailwind wrapper pointed to the Phoenix Esbuild wrapper. Just a quick fix :)
> Fix Incorrect Link in Asset Guide

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
This fixes a compilation warning related to the value attribute:
```warning: attribute "type" in component MyAppWeb.CoreComponents.input/1 must be one of ["checkbox", "color", "date", "datetime-local", "email", "file", "hidden", "month", "number", "password", "range", "radio", "search", "select", "tel", "text", "time", "url", "week"], got: "textarea"```
> Add missing "textarea" value to the component type list

- lib/phoenix/test/conn_test.ex
- test/phoenix/test/conn_test.exs
Add status code to `Phoenix.ConnTest.redirected_params/2` so that can also be used when status code needs to be different from `302`. Started on (#5021).
#hacktoberfest
> Add status code to ConnTest redirected_params (#5021)

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
The commit https://github.com/phoenixframework/phoenix/commit/9f0b9eca871c9816cd33090177f77b82d152afe6 replaced the web namespace with a fixed name so the generated core component module would have the wrong namespace defined.
> Restore web namespace name when generating core components

- priv/templates/phx.gen.live/core_components.ex
`@row_click` is a function not a `%JS{}` struct
> Fix attr typing

- installer/templates/phx_web/components/core_components.ex
This seems like a bug and was broken when I ran the `mix phx.gen.live ..` and then `mix test`
> Bugfix: Render inner block instead of @message

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
> Fix translate_error/1 for phx.new and phx.gen.live generators with --no-gettext option

- installer/templates/phx_web/telemetry.ex
This pr addresses #4336 .
@chrismccord I took a stab at this issue, and added the remaining [`Phoenix.Logger`](https://hexdocs.pm/phoenix/Phoenix.Logger.html#module-instrumentation) metrics to the telemetry module in the installer template project. If this is not what you were intending let me know and I will close/change this pr!
> Add Further Phoenix Logger Telemetry Data to Generated Projects

- lib/phoenix/controller.ex
They're missing the original `{module(), atom()}` type for the `layout` arg for cases where the `:layouts` option is not supplied to `use Phoenix.Controller`, like in a Phoenix 1.6 app.
This PR fixes the following Dialyzer error:
```
lib/foo_web/controllers/bar_controller.ex:1:call
The function call will not succeed.
Phoenix.Controller.put_new_layout(
_ :: %Plug.Conn{...},
{FooWeb.LayoutView, :app}
)
breaks the contract
(Plug.Conn.t(), [{format :: atom(), layout()}] | false) :: Plug.Conn.t()
```
> Fix specs for put_layout, put_new_layout and put_root_layout

- priv/templates/phx.gen.live/core_components.ex
The id attr is required, so we should include it in the example.
> Improve table component example

- installer/templates/phx_single/config/prod.exs
- installer/templates/phx_umbrella/config/prod.exs
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
The generators should generate `MyApp.Finch`, not `my_app.Finch`
> Properly generate swoosh configuration for finch adapter

- priv/templates/phx.gen.auth/confirmation_html.ex
- priv/templates/phx.gen.auth/registration_html.ex
- priv/templates/phx.gen.auth/reset_password_html.ex
- priv/templates/phx.gen.auth/session_html.ex
- priv/templates/phx.gen.auth/settings_html.ex
When running `mix phx.gen.auth Accounts User users --no-live`, we get multiple errors like this. 
```
+integration-test |        8) test PUT /users/reset_password/:token does not reset password on invalid data (PhxBlogWeb.UserResetPasswordControllerTest)
+integration-test |           test/phx_blog_web/controllers/user_reset_password_controller_test.exs:103
+integration-test |           ** (ArgumentError) no "edit" html template defined for PhxBlogWeb.UserResetPasswordHTML
+integration-test |           code: put(conn, ~p"/users/reset_password/#{token}", %{
+integration-test |           stacktrace:
+integration-test |             (phoenix_template 1.0.0) lib/phoenix/template.ex:177: Phoenix.Template.render_with_fallback/4
+integration-test |             (phoenix_template 1.0.0) …
```
> Fix phx.gen.auth templates for --no-live

- installer/templates/phx_web/controllers/page_html/home.html.heex
The current link redirects to https://fly.io/docs/elixir/getting-started/iex-into-running-app/.
> Fix "Deploy your application" link

- installer/templates/phx_single/config/dev.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
Following directories change in 1.7:
+ `views/` and `templates/` are replaced by `controllers/`.
+ `components/` is added.
This PR makes live_reload work with new file structure.
> Fix broken live_reload in v1.7.0-rc.0

- guides/routing.md
~p"/users/17?#{[admin: true]" -> ~p"/users/17?#{[admin: true]}"
> Typo Fix: Missing curly bracket added.

- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
This fixes the following test failures we've been seeing on master
```
1) test new with umbrella and defaults (Mix.Tasks.Phx.New.UmbrellaTest)
Error:      test/phx_new_umbrella_test.exs:32
Assertion with =~ failed
code:  assert file =~ "lib/#{@app}_web/(live|views)/.*(ex)"
2) test new with defaults (Mix.Tasks.Phx.NewTest)
Error:      test/phx_new_test.exs:34
Assertion with =~ failed
code:  assert file =~ "lib/phx_blog_web/(live|views)/.*(ex)"
```
It appears this was changed in #5082 and we forgot to update the tests.
> Fix live_reload config tests

- priv/templates/phx.gen.auth/auth_test.exs
Reference `current_user` instead of `current_ user` in test name.
Just a small typo I noticed.
> Remove space in test name, referencing `current_user` instead of `current_ user`

- guides/testing/testing.md
The "Introduction to Testing" guide is kind of [broken in `1.7.0-rc.0`](https://hexdocs.pm/phoenix/1.7.0-rc.0/testing.html#view-tests) because of those extra backticks for which I couldn't find a matching pair.
> Remove leftover backticks in testing guide

- priv/templates/phx.gen.json/fallback_controller.ex
Generated fallback controller uses `render("error.json",...`, but my interpretation of v1.7.0+ is that the new convention is to use an atom instead.
i.e:
```
|> render("error.json", changeset: changeset)
|> render(:error, changeset: changeset)
```
1. Generate a new project using this branch.
Instructions on how to use `mix phx.new ...` with a local version [are in the README](https://github.com/phoenixframework/phoenix#generating-a-phoenix-project-from-unreleased-versions)
2. Generate a json resource. Example: `mix phx.gen.json Accounts User users name:string` [generator docs](https://hexdocs.pm/phoenix/1.7.0-rc.0/Mix.Tasks.Phx.Gen.Json.html)
3. In order to trigger an error, add an Echo Changeset constraint to schema. 
```
def changeset(user, attrs) do
user
|> cast(attrs, [:name])
|> …
```
> use :error atom instead of "error.json"

- lib/phoenix/controller.ex
- test/phoenix/controller/render_test.exs
https://github.com/phoenixframework/phoenix_template/pull/4, but moved to the controller, by @josevalim’s request.
> In the current version of [AppSignal’s Phoenix integration](https://github.com/appsignal/appsignal-elixir-phoenix), we use [an extension called `Appsignal.Phoenix.View`](https://github.com/appsignal/appsignal-elixir-phoenix/blob/main/lib/appsignal_phoenix/view.ex) wich is [`use`d in Phoenix applications’ web module files](https://docs.appsignal.com/elixir/integrations/phoenix.html#template-rendering). Since Phoenix 1.7 uses phoenix_template directly, there’s no way for us to hook in anymore.
> 
> With an eye on the future, I’d like to propose adding :telemetry events to ~phoenix_template’s render~ the `Controller.render_with_layouts/4` function. That way, we can restore our …
> Add telemetry events to Controller.render_with_layouts/4

- guides/controllers.md
The Controllers guide was still referencing the Views guide, which no longer exists.
It appears to have been renamed to `components.md` (and significantly updated) in cd049a3325313280530315af9014fcc359d940f4, so this updates the reference accordingly.
> Fix dead reference to old Views guide

- guides/request_lifecycle.md
In the `A new view` section of the `Request life-cycle`, the reader was being taken directly to the `Phoenix.Component` API documentation.
However, there is now a separate guide for components and HEEx templates (which then links to the API docs).
This links the reader to the components guide instead of the API documentation.
> Add reference to Components guide

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Without this the input sends the prompt text which is not desirable.
The current behaviour won't trigger an empty validation.
> Add empty value to select input prompt option

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
This fixes compiler warnings when specifying dimensions with a "textarea" input.
> Add cols and rows to included attributes for input component

- guides/controllers.md
The `Overriding rendering formats` section of the controllers guide talks about accepting `json`, but the example code was using `text.
This updates the example code to also use `json`. It also wraps the output with backticks to make it more clear that it's a literal response.
> Fix inconsistency in controllers guide

- mix.exs
Before this patch, the `browser_open` app env was `false` even though `--open` was used. Not sure why exactly this was broken, but fwiw I found this commit: https://github.com/phoenixframework/phoenix/commit/1422abdbec937a95a934a1a9a82bb9797a9efafb
cc @josevalim
> Fix `mix phx.server --open`

- installer/templates/phx_web/components/core_components.ex
The `aria-describedby={"#{@id}-description"}` is present in the modal tag but the `id={"#{@id}-description"}` attribute is missing in the subtitle tag. This PR fixed this issue.
> Add missing `id` attribute for modal subtitle

- lib/mix/tasks/phx.gen.html.ex
- test/mix/tasks/phx.gen.html_test.exs
- test/mix/tasks/phx.gen.live_test.exs
The template generation for tables in `phx.gen.html/index.html.heex` uses a call to `Phoenix.Naming.humanize` to generate its labels while the generator for input forms only calls `to_string`.
This modifies the `label` function to call humanize as well for consistency.
> Add a call to `humanize` for input form generation for consistency

- installer/lib/phx_new/single.ex
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
In 1.7, The template is using a logo which is an embedded SVG, this file is useless.
Maybe, we can ignore it when generating a project.
> Don't generate `priv/static/images/phoenix.png` in 1.7.0-rc.0

- guides/telemetry.md
Was perusing the docs for phoenix telemetry and noticed this section. Ash emits lots of telemetry events so I figured I'd PR the addition.
> Add Ash Framework to list of telemetry libraries

- guides/routing.md
altering routing docs, as the generated PageController has its only action changed to :home
> doc: renaming :index to :home in routing.md

- test/mix/tasks/phx.gen.json_test.exs
Hi!
Test cases in `phx.gen.json_test.exs` are isolated given gen tasks are run in different `tmp` subdirectories, however it seems this particular recently-added test case having a run time compilation of a `PhoenixWeb.CoreComponents` module is leaking to other test case given the module is not purged/deleted.
In particular it seems to affect the test case titled `"with json --web namespace generates namespaced web modules and directories"` in the same test file.
So the intermittence in the failure depends on the random order of the test case run.
Failure can be reproduced consistently with some seeds. E.g.
```
$ mix test test/mix/tasks/phx.gen.json_test.exs --seed 911231
```
Also, this is the failure that is making `master` last commit and a few pull requests fail: …
> Fixes flaky test case - test/mix/tasks/phx.gen.json_test.exs:166

- test/mix/tasks/phx.gen.cert_test.exs
Hi :wave: 
Just trying to fix a warning showing up in `mix test` runs with OPT24+.
```
(master) $ mix test test/mix/tasks/phx.gen.cert_test.exs
11:08:59.788 [warning] Description: 'Authenticity is not established by certificate path validation'
Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
...
Finished in 0.8 seconds (0.00s async, 0.8s sync)
3 tests, 0 failures
```
```
(fix-test-warning-cert-path-validation) $ mix test test/mix/tasks/phx.gen.cert_test.exs
...
Finished in 0.7 seconds (0.00s async, 0.7s sync)
3 tests, 0 failures
```
> Fixes warning in test case by explicitly asking for no cert path validation

- priv/templates/phx.gen.embedded/embedded_schema.ex
- test/mix/tasks/phx.gen.embedded_test.exs
As mentioned in the [docs](https://hexdocs.pm/phoenix/1.7.0-rc.0/Mix.Tasks.Phx.Gen.Embedded.html#module-attributes) `:references` should be generated when calling it within
`mix phx.gen.embedded Blog.Comment  author_id:references:author` 
but it only creates an empty schema. I've added the population of `:references` as well as a new test. 
I'm not sure if there needs to be anything else since it's an embedded schema and not an actual schema which is why I left out the primary_key and foreign_key assignments. 
Hope this does it!
> Fixes missing :references generation to phx.gen.embedded

- priv/templates/phx.gen.auth/reset_password_controller_test.exs
- priv/templates/phx.gen.auth/reset_password_edit.html.heex
- test/mix/tasks/phx.gen.auth_test.exs
the reset_password edit form did not have password or password_confirmation inputs.
> Add password inputs to password reset edit form

- lib/phoenix/endpoint.ex
* The domain for pow.cx has lapsed and is now a domain seller landing page.
* The repo at https://github.com/basecamp/pow has also been archived.
> Remove reference to pow.cs from Phoenix.Endpoint docs

- priv/templates/phx.gen.live/core_components.ex
`#flash` is the default `id`, so this will work in that case, but it seems as though the hide message should actually go to `@id`?
> bugfix: flash component's phx-click hide should go to @id, not #flash

- installer/templates/phx_single/config/prod.exs
The current swoosh API client config code doesn't work on fly.io, and this fixes it.  After some experimentation, I finally figured out that this works.  Note that the name in for Finch in application.ex is <%= @app_module %>.Finch, and so the finch_name on the adapter needs to be set to this same value in prod.exs.
Another solution is to just call the Finch service "Swoosh.Finch" in application.ex, and then you do not have to give a name for the api client in prod.exs, but the changes I'm suggesting seem more in line with the current code. 
Thanks!
-- Greg
> Correct the swoosh api client configuration

- guides/controllers.md
In the controllers guide discussion of changing the name of an action, the old name and the new name are the reverse of what they should be.
> In the Controllers guide, old name and the new name are the reverse of what they should be.

- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/apps/app_name_web/mix.exs
There are two reasons for this change:
1. This way when we launch the Web app for the first time the assets
would have been built and so we avoid the "flash" from the page
without assets to the one with.
2. I think if there are any assets build errors, they should be a little
bit easier to debug in a terminal window that runs `$ mix setup` than
in the terminal window that runs `$ mix phx.server`, the latter
containing much more log output and such.
> Change `assets.setup` to run esbuild & tailwind

- installer/templates/phx_assets/app.js
The typescript warns of the unused variable `info` on these two lines. It's better to add an underscore to silent this warning.
> Fix unused variable on topbar callback

- priv/templates/phx.gen.live/live_test.exs
There is a small error in the template of the Liveview generator.
```elixir
test "deletes post in listing", %{conn: conn, post: post} do
{:ok, index_live, _html} = live(conn, ~p"/posts")
assert has_element?(index_live, "#post-#{post.id}")
assert index_live |> element("#posts-#{post.id} a", "Delete") |> render_click()
refute has_element?(index_live, "#post-#{post.id}")
end
```
this fails because "#post-#{post.id}" was never there in the first place, yet in `master` template this is passing. Making the selectors match fixes the false positive.
> fix pluralization in live generator delete template

- lib/phoenix/digester.ex
If a project has a lot of assets or uses slow compressors (e.g. brotli), compressing in parallel can save a noticable amount of time. On my ~2019 4+4 core laptop CPU, with Phoenix' built in gzipper, ~150Mi assets in ~9000 files:
```
// sequential
24,33s user   3,67s system   142% cpu   19,585 total
// parallel
31,49s user   4,54s system   408% cpu    8,815 total
```
On freshly created phx.new v1.6.15, the difference is negligible, as the Elixir start up time dominates the total time. Below are two example runs, which are not statistically significant. I'm including these mostly to serve as comparison point to the numbers above.
```
// sequential
1,08s user    0,10s system   147% cpu    0,803 total
// parallel
0,95s user    0,13s system   146% cpu    0,736 total
```
If you're wondering …
> run asset compression in parallel

- guides/plug.md
- guides/routing.md
With the switch to Tailwind this no longer exists `<main class="container">...</main>`
This is a PR that updates the Plug guide to match what the generators are now creating.
> Update plug.md guide to match new generator output

- lib/phoenix/digester.ex
Phoenix compresses all assets twice, even when their contents are the same. While this is unlikely for non trivial CSS/JS assets, it's always the case for all other kinds of assets. The issue is only noticable when using slow compressors and/or a lot of assets.
Technically the compressor might return a different result for the digest and regular version, since it also receives the filename as metadata. However, the behaviour doesn't promise anything in this regard, nor do any of the public implementations on Github use the filename in the actual compression. The specific search used was
https://github.com/search?l=Elixir&q=%22behaviour+Phoenix.Digester.Compressor%22&type=Code -- most of the results are from vendoring Phoenix, there are only a couple of independent implementations.
Below …
> only compress once if asset content and digest are equal

- installer/templates/phx_assets/app.js
- installer/templates/phx_assets/topbar.js
The topbar delay functionality was added upstream in https://github.com/buunguyen/topbar/pull/15.
With this change phoenix once again packages the same code as upstream which means it's easier to move from the generated code to using a dedicated js package manager like `npm` or `yarn`.
There should be no functional difference.
> Use topbar 2.0.0 in project generator

- installer/lib/phx_new/generator.ex
- installer/test/phx_new_test.exs
- lib/mix/tasks/phx.gen.release.ex
This PR implements the backward compatible approach suggested by @ijdickinson in [this comment](https://github.com/phoenixframework/phoenix/issues/5164#issuecomment-1399218037).
We enable ipv6 when `ECTO_IPV6` is not empty, or `0`, or `false`.
Fixes #5164.
Built with ❤️ in Milan during [![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)
> fix: check ECTO_IPV6 for falsey values to enable ipv6

- lib/phoenix/controller.ex
Relates to: https://github.com/phoenixframework/phoenix/issues/5278#issuecomment-1432896755
```elixir
@spec put_new_layout(Plug.Conn.t(), [{format :: atom, layout}] | layout) :: Plug.Conn.t()
def put_new_layout(%Plug.Conn{state: state} = conn, layout)
when (is_tuple(layout) and tuple_size(layout) == 2) or is_list(layout) or layout == false do
```
The typespec is now in sync with the guards and allows to pass a `layout()` without a `format`.
The problem starts when [default layouts](https://github.com/phoenixframework/phoenix/blob/v1.7.0-rc.3/lib/phoenix/controller.ex#L230) are set in the Phoenix.Controller and the error case of [__view__](https://github.com/phoenixframework/phoenix/blob/v1.7.0-rc.3/lib/phoenix/controller.ex#L1823)
and [__layout__ …
> Fix typespec for Phoenix.put_new_layout

- lib/phoenix/socket/serializers/v1_json_serializer.ex
- test/phoenix/socket/v1_json_serializer_test.exs
Currently, if when establishing a websocket connect, no `vsn` parameter is given, the socket connection defaults to the V1 serializer for encoding and decoding message. If passed a message that doesn't match what the serializer is expecting, a very cryptic message is raised:
```
Ranch listener TenantWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.30056.42> exit with reason: {:function_clause, [{Phoenix.Socket.Message, :from_map!, [[nil, "1", "phoenix", "heartbeat", %{}]], []}, {Phoenix.Socket, :__in__, 2, [file: 'lib/phoenix/socket.ex', line: 471]}, {Phoenix.Endpoint.Cowboy2Handler, :websocket_handle, 2, [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 145]}, {:cowboy_websocket, :handler_call, 6, [file: …
```
> Provide a better error message when getting malformed V1 Socket Payloads

- lib/mix/tasks/phx.gen.auth/injector.ex
- priv/templates/phx.gen.auth/forgot_password_live_test.exs
- priv/templates/phx.gen.auth/registration_controller_test.exs
- priv/templates/phx.gen.auth/session_controller_test.exs
- test/mix/tasks/phx.gen.auth/injector_test.exs
- test/mix/tasks/phx.gen.auth_test.exs
Hi all,
Pulled the 1.7rc, and noticed that the `gen.auth` templates aren't stylistically aligned with the awesome work that the tailwind devs applied to the rest of the `phx.new` templates. There are a handful of additional updates I would make, but I wanted to keep the PRs small, so this one just updates the auth-related link styles so that they're identical to the link styles from `phx.new`.
I _think_ it would make sense to replace the `@phoenixframework`, `GitHub` and `Getting Started` links if a user has already taken the step to generate authentication, as that implies that the developer already has a level of fluency in the elixir/phoenix ecosystem. Then these registration links would sit in their place, inline with the phoenix logo, but that change feels like a bigger discussion …
> Unify `gen.auth` and `phx.new` menu styles

- lib/phoenix/token.ex
Hello, I've found a wrong typespec for socket-like struct which was added in that [commit](https://github.com/phoenixframework/phoenix/commit/2aa5c9b0d6d8a6edfb2df2375868928d02780a0a) and dialyzer raise warnings when socket object passes here. Maybe I was wrong, but I wrote some examples with similar typespec, and it's not passed.
Examples:
wrong typespec, dialyzer has not passed:
```
defmodule BackendWeb.Test do
@type context :: %{endpoint: atom} | atom | binary
@spec test(context) :: {:ok, context}
def test(context) do
{:ok, context}
end
def test_spec() do
test(:atom)
test("binary")
test(%Phoenix.Socket{
endpoint: :atom,
channel: :atom,
channel_pid: self(),
handler: :atom,
pubsub_server: :atom,
serializer: :atom,
topic: "topic",
transport: :atom,
transport_pid: self()
})
end
end
``` …
> Fix token typespec for socket like struct

- priv/templates/phx.gen.auth/login_live_test.exs
The [login_live_test.exs](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.auth/login_live_test.exs) template differed from the templates [registration_live_test.exs](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.auth/registration_live_test.exs#L80) and [reset_password_live_test.exs](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.auth/reset_password_live_test.exs#L96) by [not using `main` as part of the selector](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.auth/login_live_test.exs#L66) and [not using a sigil with vertical bars](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.auth/login_live_test.exs#L80).
I'm pedantic and this …
> Improved the code consistency of the login_live_test.exs template

- lib/phoenix/socket/transport.ex
[`Phoenix.Socket.connect/2`](https://hexdocs.pm/phoenix/Phoenix.Socket.html#c:connect/2) can return `{:error, term()}` tuple, while [`c:Phoenix.Socket.Trasnport.connect/1`](https://hexdocs.pm/phoenix/Phoenix.Socket.Transport.html#c:connect/1) allows only for `:error`.
> Include `{:error, reason}` in `c:Phoenix.Socket.Transport.connect/1`

- priv/templates/phx.gen.auth/login_live.ex
warning: a map with atom keys was given to a form. Maps are always considered parameters and therefore must have string keys, got: %{email: nil}
(phoenix_html 3.3.1) lib/phoenix_html/form_data.ex:83: Phoenix.HTML.FormData.Map.name_params_and_opts/2
(phoenix_html 3.3.1) lib/phoenix_html/form_data.ex:53: Phoenix.HTML.FormData.Map.to_form/2
> Fix warning for string keys on form for phx.gen.auth on login_live.ex

- installer/templates/phx_assets/hero_icons/UPGRADE.md
Due to some differences between BSD and GNU `tar`, it may be better to use the `tar.gz` artifact so that the instructions remain consistent across different environments when updating heroicons. This should address the error below when following the instructions with GNU tar installed.
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: heroicons-2.0.16/optimized: Not found in archive
tar: Exiting with failure status due to previous errors
```
Should the generator be updated to use `optimized.tar.gz` and `:erl_tar.extract/2`?
> update heroicons upgrade instructions

- lib/phoenix/router/console_formatter.ex
If you run `mix phx.routes` when all your non-socket routes have Verb/Method lengths less than `Post` you will get an issue with the formatting of socket longpoll routes.
This is because when calculating column widths, verb length of socket routes is not taken into account. This PR fixes that.
**Note:** *this is my first PR and I'm just getting back into Elixir after a long hiatus. any feedback of course is welcome*
> includes check of socket, longpoll verbs when calculating column widths for routes

- guides/plug.md
Potential Fix for [Issue #5315](https://github.com/phoenixframework/phoenix/issues/5315)
This PR points to `http://localhost:4000/hello` and adds a note showing why this won't be seen on the home page.
> Plug guide fix

- guides/introduction/packages_glossary.md
Minor spelling fix. I think you want "peek" here, as in to look and not "peak" as in summit.
> Fix typo: peeking, not peaking

- priv/templates/phx.gen.auth/settings_live.ex
**Replaces https://github.com/phoenixframework/phoenix/pull/5323**
The template for user settings renders two DOM nodes with the same id. One is the visible email input on the change email form and the other is a hidden input on the change password form.
This PR gives the hidden email input a specific id of hidden_user_email to ensure valid HTML and prevent the error "Multiple IDs detected: user_email. Ensure unique element ids." from being displayed in the developer console.
_I am not sure how I messed up the first branch but this is now a clean branch that should be green. On the bright side my fork now has the actions running so I should avoid red PRs in the future_.
> Rename id to ensure all ids are unique.

- guides/deployment/fly.md
- guides/deployment/heroku.md
- guides/howto/using_ssl.md
- guides/introduction/community.md
Reading the doc I found some old links and I do this pr to correct them.
- In [`guides/howto/using_ssl.md`](https://hexdocs.pm/phoenix/using_ssl.html) the [link](https://erlang.org/doc/man/ssl.html) does not work without the "www" (all other links to the erlang doc use the "www").
- In [`guides/introduction/community.md`](https://hexdocs.pm/phoenix/community.html#books) the links to the pragprog books changed (none work except the last one).
- In [`guides/deployment/heroku.md`](https://hexdocs.pm/phoenix/heroku.html#initializing-git-repository) the [`#tracking-your-app-in-git`](https://web.archive.org/web/20210319082555/https://devcenter.heroku.com/articles/git#tracking-your-app-in-git) part was removed and now it should be `#prerequisites-install-git-and-the-heroku-cli`. Similarly, in …
> fix old link in doc

- lib/mix/tasks/phx.gen.ex
When you run `mix help phx.gen` it renders a table. For some reason the checkmarks were taking up two "spaces" which messed up the table alignment. This PR replaces the `✓` with `x` and the table now renders properly.
> Updating phx.gen moduledocs to fix improperly rendered table

- priv/templates/phx.gen.auth/forgot_password_live.ex
- priv/templates/phx.gen.auth/reset_password_edit.html.heex
- priv/templates/phx.gen.auth/reset_password_live.ex
- priv/templates/phx.gen.auth/reset_password_new.html.heex
Both the login and register links on the bottom of the forgot / reset password screens is larger then any of the other text. I have changed them to the same size as the other text on the page.
> Adjust text size of login and register links.

- priv/templates/phx.gen.auth/forgot_password_live_test.exs
- priv/templates/phx.gen.auth/registration_controller_test.exs
- priv/templates/phx.gen.auth/session_controller_test.exs
In some tests generated by `phx.gen.auth` the paths are hard coded to `~p"/users/..."`, so the tests fail when a different schema module or web namespace is used.
To fix this problem, interpolate `<%= schema.route_prefix %>` into `~p` instead of hard coding `/users`.
I tested this PR manually with two examples from the official documentation:
```
$ mix phx.gen.auth Accounts User users --web Warehouse
$ mix phx.gen.auth Backoffice Admin admins
```
Please let me know if you would like additional assertions in `test/mix/tasks/phx.gen.auth_test.exs` for this PR. By reading through the existing tests I came to the conclusion that this bug is too specific to warrant its own regression test. Maybe adding a test for a schema module other than `User` might be a good idea, though?
> Fix hard coded paths in tests generated by `phx.gen.auth`

- installer/templates/phx_web/components/core_components.ex
- installer/templates/phx_web/components/layouts/app.html.heex
- installer/templates/phx_web/controllers/page_html/home.html.heex
- priv/templates/phx.gen.live/core_components.ex
Hi:
This commit changes no functionality; it simply re-orders the Tailwind CSS classes so that they match the order that comes out from the Tailwind formatter:
https://github.com/100phlecs/tailwind_formatter
Thanks!
-- Greg
> Re-order the Tailwind CSS classes in the generators

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Adds the "list" attribute to the allowed attributes you can pass into the input component. The list attribute is used in conjunction with the `datalist` element to generate auto-complete suggestions on text inputs.
```html
<input name="fruit"  list="fruit-suggestions" />
<datalist id="fruit-suggestions">
<option value="Apple" />
<option value="Orange" />
<option value="Banana" />
</datalist>
```
> Update core input component to support list attribute

- guides/controllers.md
not sure how it was setup before Phoenix 1.7, but the default action for "/" is now `PageController.home` and not `PageController.index`. I've gone through and updated the controller guide docs changing appropriate references to the `home` action and adding `layout: false` in the code snippets as well. 
In the flash section I removed the `info` flash message as it cannot be seen along with the `error` flash message and might cause confusion and updated the reference to the `flash` code in the app template to point at the `flash_group` component added to the top of the `home.html.heex` file.
resolves issue #5365
> update PageController index action to home in Controllers Guide

- lib/phoenix/endpoint/supervisor.ex
- test/phoenix/endpoint/supervisor_test.exs
When a user misconfigures their app to not set `server: true` on the endpoint with releases the app just hangs and has no reason to log anything by default. 
See https://github.com/dwyl/phoenix-liveview-chat-example/pull/111#discussion_r1137410990 this should warn them if they have HTTP/HTTPS set but not server: true.
> Adding info log if they have http/https set but not server: true set

- lib/phoenix/verified_routes.ex
`sigil_p/1` should be [`sigil_p/2`](https://github.com/phoenixframework/phoenix/blob/84a32e3605824c5190187afd61ffb9596fde9ff1/lib/phoenix/verified_routes.ex#LL202C12-L202C19)
> Fix `sigil_p` arity in docs for `url/1`

- priv/templates/phx.gen.auth/auth_test.exs
Just a quick PR to fix some minor typos in test descriptions.
> Fix typos in auth test names

- lib/phoenix/controller.ex
When a root layout is defined as a plug for example, and we want to disable it in a particular controller action, `put_root_layout(conn, html: false)` doesn't work.
The same way that we use to disable layouts `put_layout(conn, false)` can be used to disable root layouts, however the type spec was not supporting that, so apps using dialyzer get errors.
This adds spec support for passing `false` as second argument.
> Support passing false as the second argument in put_root_layout

- guides/asset_management.md
`esbuild` 0.17.0 [changed the API](https://github.com/evanw/esbuild/releases/tag/v0.17.0) and the existing script from the docs no longer works in watch mode.
It fails with the following error:
```
➜ node build.js --watch
✘ [ERROR] Invalid option in build() call: "watch"
/Users/dino/dev/phoenix-with-npm/assets/node_modules/esbuild/lib/main.js:255:12:
255 │       throw new Error(`Invalid option ${where}: ${quote(key)}`);
╵             ^
at checkForInvalidFlags (/Users/dino/dev/phoenix-with-npm/assets/node_modules/esbuild/lib/main.js:255:13)
at flagsForBuildOptions (/Users/dino/dev/phoenix-with-npm/assets/node_modules/esbuild/lib/main.js:457:3)
at buildOrContextContinue (/Users/dino/dev/phoenix-with-npm/assets/node_modules/esbuild/lib/main.js:1009:9)
at buildOrContextImpl …
```
> Update example esbuild script for esbuild 0.17+

- guides/mix_tasks.md
updated folder structure of `priv/static` and `assets/` as part of `mix.digest` guide to match output from phoenix 1.7
> updated folder structures to match 1.7

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Use the spelling that is used by the Tailwind/Heroicons team: https://tailwindcss.com/docs/stroke-width#setting-the-stroke-width
> Change Hero Icons to Heroicons

- guides/ecto.md
Guides - ecto - remove alias from example of generated user schema. Closes #5371
> Guides - ecto - remove alias from example of generated user schema

- guides/components.md
update guide - favor given example over generic syntax for example function component call with attribute, closes #5369
> update guide - components - favor given example over generic syntax

- guides/real_time/channels.md
Since the heroku demo app isn't live anymore, consider removing a reference from the docs (the github repo is still referenced).
If the demo app is supposed to be live, please ignore.
> Channel guide: remove live demo reference

- lib/phoenix/controller.ex
Maintain consistency in the documentation examples between passing the status code to `put_status/2` as either an integer or an atom. 
Give preference here to the atom format since the HTTP code is visible when passing the template name to `Phoenix.Controller.render/2`.
> [docs] Update `Phoenix.Controller.action_fallback/1` documentation

- guides/controllers.md
There is a small typo in the [Controllers](https://hexdocs.pm/phoenix/controllers.html#flash-messages) guide, one right parenthesis too many at the end:
```elixir
def home(conn, _params) do
conn
|> put_flash(:error, "Let's pretend we have an error.")
|> redirect(to: ~p"/redirect_test"))
end
```
> Fix typo in Controllers guide

- guides/routing.md
This is kind of trivial, but it made me do a double-take when reading the documentation.
> Correct verified route paths in routing guide

- guides/contexts.md
- guides/controllers.md
- guides/plug.md
- guides/request_lifecycle.md
- guides/routing.md
- installer/templates/phx_web/router.ex
- installer/test/phx_new_umbrella_test.exs
- test/phoenix/controller/controller_test.exs
- test/phoenix/controller/render_test.exs
issue: https://github.com/phoenixframework/phoenix/issues/5449
This is `Phoenix.Controller.put_root_layout/2` spec
```elixir
@spec put_root_layout(Plug.Conn.t(), [{format :: atom, layout}] | false) :: Plug.Conn.t()
```
and docs
```elixir
iex> root_layout(conn)
false
iex> conn = put_root_layout(conn, html: {AppView, :root})
iex> root_layout(conn)
{AppView, :root}
iex> conn = put_root_layout(conn, html: :bare)
iex> root_layout(conn)
{AppView, :bare}
```
However, the `installer/templates/phx_web/router.ex` file does not include the format. Therefore, I have made modifications to that file, as well as the docs and test code.
Here are the main changes I have in mind:
https://github.com/phoenixframework/phoenix/pull/5439/files#diff-f1841e0d79d5be386a09b926ccbd396bdbdd9b78b720cebcb5b4642d5f3a556b …
> Add `format` support to `put_root_layout/2`

- lib/phoenix/router.ex
- test/phoenix/verified_routes_test.exs
Retain route definition order during creation of routers __verify_route__/1 functions
Closes #5451
> Retain route order for warn on verify

- lib/phoenix/endpoint/render_errors.ex
- test/phoenix/endpoint/render_errors_test.exs
Based on the commentary at https://github.com/phoenixframework/phoenix/blob/main/lib/phoenix/endpoint/render_errors.ex#L4-L6, the observed behaviour of Phoenix is incorrect; presently we re-raise all errors when rendering them. This has never really been visible with Cowboy since it generally does not log errors. However, Bandit's general policy is to log any errors which are raised out of a plug, which made this much more visible.
This PR corrects the behaviour of RenderErrors to match its documentation, resulting it in the following changes to Phoenix's outward behaviour:
* `NoRouteError` errors are no longer re-raised
* All other raised errors continue to be re-raised
* All client-facing logging is unchanged
In terms of broader outward behaviours:
* Cowboy's end-to-end behaviour is …
> Do not re-raise on NoRouteError

- guides/testing/testing_channels.md
* update listings
* replace MyAppWeb with HelloWeb
* remove listing for handle_out/3 since it is not defined in generated HelloWeb.RoomChannel
> Update testing channels guide - to match a phoenix 1.7.2 project

- lib/phoenix/router.ex
This PR suppresses a dialyzer error that shows up in projects depending on phoenix `v1.7.2` (possibly brought in with `v1.7.0`)
Environment
- Elixir version: Elixir 1.14.4 (compiled with Erlang/OTP 23)
- Phoenix version (mix deps): 1.7.2
- OS: Fedora 36
```
deps/phoenix/lib/phoenix/router.ex:514:pattern_match
The pattern can never match the type.
Pattern:
:error
Type:
{%{
:conn => nil,
:log => :debug,
:path_params => map(),
:pipe_through => [any(), ...],
:plug => ArgonApi.AuthController | ArgonApi.NotFound,
:plug_opts => :index | [],
:route => <<_::8, _::size(16)>>
}, (map(), map() -> map()), (map() -> map()),
{ArgonApi.AuthController, :index} | {Phoenix.Router.Route, {_, _, _}}}
```
> Suppress dialyzer pattern_match error

- lib/phoenix/token.ex
https://github.com/phoenixframework/phoenix/commit/0587b9d0dc03267b6acf6d96ad14fa0095247407 added typespecs to Phoenix.Token, but did not include the `max_age` option for `Phoenix.Token.sign/4` and `Phoenix.Token.encrypt/4`. It also removed the documentation for `max_age` from these functions - I don't know why.
https://github.com/elixir-plug/plug_crypto/blob/5884b466766676f7db7f79d62cadead47f161d36/lib/plug/crypto.ex#L171 includes max_age for sign and encrypt.
This PR re-adds the documentation and also adds the max_age option to the typespec.
> Add default max_age to Phoenix.Token sign and encrypt typespec

- installer/templates/phx_web/components/layouts/root.html.heex
A recent change was made to the root.html.heex layout - "Use tailwind JIT to accommodate CSP"
However, in that change, the syntax used was slightly incorrect (an extra space character), so TailwindCSS was not able to interpret the "arbitrary property" 
Correcting this change by omitting the space character.
(see the [TailwindCSS docs](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties) for more information on the expected syntax for "arbitrary properties")
---
Screenshots from Chrome devtools:
**With a space:**
**Without a space:**
> Correct the use of TailwindCSS JIT class

- installer/templates/phx_assets/tailwind.config.js
Hero icons begin to repeat vertically or horizontally when calculated space shrinks by the layout rules. `mask-repeat` rule set to `no-repeat` fixes these artifacts.
I found this useful but if you think it's too restrictive and rather should be done by tweaking the layout itself, please discard.
> Fix hero icons mask repeat

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
In the core components, [textarea inputs](https://github.com/phoenixframework/phoenix/blob/a310102eb0e20b918624bb2323a6afb124fcaddd/priv/templates/phx.gen.live/core_components.ex#L337) and [nearly all others](https://github.com/phoenixframework/phoenix/blob/a310102eb0e20b918624bb2323a6afb124fcaddd/priv/templates/phx.gen.live/core_components.ex#L360) have a "mt-2" class, only the [select input](https://github.com/phoenixframework/phoenix/blob/a310102eb0e20b918624bb2323a6afb124fcaddd/priv/templates/phx.gen.live/core_components.ex#L317) has a "mt-1" class. This makes things look inconsistent when, for example a text input is horizontally positioned next to a select input. This commit fixes that.
Before (Please don't mind the German :smile:):
After:
> Improved the visual consistency of the select input core component.

- priv/templates/phx.gen.auth/auth.ex
Hello!
When using the generated auth files from `mix phx.gen.auth` attempting to turn `socket = mount_current_user(session, socket)` into a pipeline requires the user reorder the arguments.
If we change `mount_current_user` to follow the general Elixir convention of the struct being transformed as the first argument it becomes easy to turn `socket = mount_current_user(socket, session)` into:
```elixir
socket =
socket
|> mount_current_user(session)
|> mount_session_id(session)
|> mount_another_thing(session)
```
> Swap session, socket arguments in phx.gen.auth mount_current_user

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
https://github.com/phoenixframework/phoenix/commit/21cf47df1a1beba97ae4828dfc8528f4e63660d2 fixed the input border for `input` fields only. This applies the same change to `textarea`.
> Fix input border feedback for textarea

- guides/howto/file_uploads.md
- mix.exs
If you search for `elixir phoenix upload` your first result will be a page that is about six years old
If you are very unlucky, you might find a link on the forums to a guide on `phoenixframework.org` and it will 404
This PR reintroduces the File Uploads guide, updated to work with the current Contexts guide.
> Reintroduce the File Uploads guide

- installer/templates/phx_web/components/core_components.ex
Just fixing the tiniest typo I ran into.
> Fix typo in core_components.icon's @doc

- guides/json_and_apis.md
I propose the following three changes to the JSON and APIs guide.
> Address three minor typos in the JSON and APIs guide.

- lib/phoenix/test/channel_test.ex
- test/phoenix/test/channel_test.exs
As proposed by @josevalim in #5326, I added an optional 4th argument to `socket/3` and `connect/3` that 
allows to give the `pid` of the test process.  This is needed when wanting to use the socket from a `Task` or 
other process that is not  your test.
> Allow using socket/connect in another process.

- installer/templates/phx_single/config/prod.exs
- installer/templates/phx_umbrella/config/prod.exs
Swoosh starts an in memory storage for mails by [default](https://hexdocs.pm/swoosh/Swoosh.html#module-production)
I do not think anybody uses this in production, so I think adding this to the generated `prod.exs` file makes sense.
> Do not run swoosh memory storage process in production

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Very small typo, added a missing `as` to the core_components moduledoc
> Minor typo: such -> such as

- installer/templates/phx_web/telemetry.ex
I think this is a typo, that the actual event is `[:phoenix, :channel_joined]`.
https://github.com/phoenixframework/phoenix/blob/3f0dfced31a66edb0932c479e2da51125d1c8e30/lib/phoenix/logger.ex#L137
https://github.com/phoenixframework/phoenix/blob/3f0dfced31a66edb0932c479e2da51125d1c8e30/lib/phoenix/logger.ex#L333
> Update `Telemetry` installation template

- installer/lib/phx_new/web.ex
- installer/test/phx_new_umbrella_test.exs
When generating projects without html in umbrella (`mix phx.new my-app --umbrella --no-html`), the file `error_html_test.exs` still get created.
If you run `mix test` on a newly created project, it fails because it expects html.
I fixed that by moving the generation of that file from the "new" template to the "html" template. I updated the tests to match the expected behaviour. All other tests are passing fine.
I also took advantage of the same commit to fix a typo of `pager_controller_test.exs`, which should be `page_controller_test.exs`.
Cheers from Brazil, @chrismccord @josevalim!   🧡
> Remove error_html_test on new without html

- priv/templates/phx.gen.auth/reset_password_live_test.exs
Currently, the form submits "confirmation_password", which (I believe) could lead to false positives. Instead, this template should use the expected key, "password_confirmation".
> Use correct form field name in reset_password_live_test template

- lib/phoenix/digester.ex
- test/phoenix/digester_test.exs
[Sourcemaps][0] are usually generated alongside the asset they describe, and due to this many tools assume that for an asset like app-{hash}.js the sourcemap will be found at app-{hash}.js.map. This change ensures that digested sourcemaps will have paths matching their corresponding assets.
[0]: https://web.dev/source-maps/
Closes #5523
> Ensure sourcemaps are digested with expected hash/extension

- priv/templates/phx.gen.release/Dockerfile.eex
I've recently run into a problem:
2023-07-28T09:56:42Z app[e784e1e0b52d48] iad [info]** (exit) an exception was raised:
2023-07-28T09:56:42Z app[e784e1e0b52d48] iad [info]    ** (MatchError) no match of right hand side value: {:error, :enoent}
2023-07-28T09:56:42Z app[e784e1e0b52d48] iad [info]        (public_key 1.14) pubkey_os_cacerts.erl:38: :pubkey_os_cacerts.get/0
2023-07-28T09:56:42Z app[e784e1e0b52d48] iad [info]        (inets 9.0.1) httpc.erl:476: :httpc.ssl_verify_host_options/1
2023-07-28T09:56:42Z app[e784e1e0b52d48] iad [info]        (inets 9.0.1) httpc.erl:1015: anonymous fn/0 in :httpc.http_options_default/0
2023-07-28T09:56:42Z app[e784e1e0b52d48] iad [info]        (inets 9.0.1) httpc.erl:961: :httpc.http_options/3
2023-07-28T09:56:42Z app[e784e1e0b52d48] iad [info] …
> Add ca-certificates package to phx.gen.release/Dockerfile.eex

- guides/contexts.md
I've just been working through the Contexts guide (https://hexdocs.pm/phoenix/contexts.html), and I feel like the code for `get_cart_by_user_uuid` should have `+` diff markers, like the other functions that are added in the same diff.
See screenshot:
The line below the diff even says `We started by implementing get_cart_by_user_uuid/1`, so I feel like this was probably the original intention.
Thanks!
> Context Guide: add `+` markers for `get_cart_by_user_uuid` in diff

- lib/phoenix/socket.ex
Often times, random bots or scanners hit URLs with garbage params. When this happens with a Phoenix socket URL, serializer negotiaiton can fail and Phoenix will log this event.
Currently this happens at the `:error` level. In most cases, this is not an error conditions, but an expected failure due to garbage in, garbage out. As such, it's probably more appropriate for this to be at the `:warning` level.
> Change socket serializer/version logs to warning.

- guides/components.md
Since the component guide expects that readers have gone through the request life-cycle guide, we can favor HelloController over PageController when it comes to demonstrate some layout adjustments.
Since the PageController does not use app layout after project generation, it is more straightforward to show layout adjustments on the HelloController.
closes #5532
> Favor HelloController for showcasing layout changes, closes #5532

- lib/phoenix/code_reloader/proxy.ex
The Code Reloader crashes, when there is a `%Mix.Task.Compiler.Diagnostic` with `:file` equal to `nil`.
```elixir
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
(elixir 1.15.2) lib/io.ex:671: IO.chardata_to_string(nil)
(elixir 1.15.2) lib/path.ex:327: Path.relative_to/2
(phoenix 1.7.7) lib/phoenix/code_reloader/proxy.ex:66: Phoenix.CodeReloader.Proxy.diagnostic_to_chars/1
(elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
(phoenix 1.7.7) lib/phoenix/code_reloader/proxy.ex:26: Phoenix.CodeReloader.Proxy.handle_cast/2
```
This compiler warning crashes the Code Reloader.
```elixir
[
%Mix.Task.Compiler.Diagnostic{
file: nil,
severity: :warning,
message: "Locale :de has no associated gettext locale. Cannot translate {:<<>>, [line: 50], …
```
> Fix crash of Code Reloader when %Mix.Task.Compiler.Diagnostic{file: nil}

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
When reading through `CoreComponents` `@moduledoc`, I thought that perhaps some of the sentences could use small adjustments – though my English is not very good so I’m not sure if I actually improved anything.
I found the same string in two different files so I made the same changes to both, but am not sure if that’s required. Please let me know your thoughts 🙏
> Clarify CoreComponents moduledoc

- lib/phoenix/channel.ex
- lib/phoenix/channel/server.ex
I was confused by some code which set a struct as a payload until I recalled that payloads get serialized this way and saw that the struct implemented the required protocol. I think this makes the expectation clearer.
> Notes about payload serialization

- lib/mix/tasks/phx.routes.ex
This Pull Request updates the list of valid options in `Mix.Tasks.Phx.Routes`, adding a new `--method` option, which, when combined with the `--info` option, allows users to specify what HTTP method should be used in conjunction with the specified URL.
This should help in cases where the same URL matches multiple controller actions, depending on the HTTP method. For example, an application with a URL such as `/api/v1/users` might use it to list users, with the `GET` method, or to create a new user, with the `POST` method.
I noticed that, currently, there aren't any tests for the `--info` option and ended up trying to add some. However, I ran into an issue where `Code.fetch_docs/1` was not able to find the controller module. I am assuming that's also the reason why there are no tests for …
> Add `--method` option to phx.routes mix task

- lib/phoenix/endpoint.ex
- test/phoenix/endpoint/endpoint_test.exs
With this PR, you can use the ~p sigil to resolve static assets with fragment identifiers (e.g. useful to address only a specific section of an SVG image).
For instance, if you have a "digest" version of an asset:
Before:
```
~p"/images/icons.svg" == "/images/icons-6051db34009ab48e6232cf685fca2bd4.svg?vsn=d"
~p"/images/icons.svg#warning" == "/images/icons.svg#warning"
```
Now:
```
~p"/images/icons.svg" == "/images/icons-6051db34009ab48e6232cf685fca2bd4.svg?vsn=d"
~p"/images/icons.svg#warning" == "/images/icons-6051db34009ab48e6232cf685fca2bd4.svg?vsn=d#warning"
```
Closes #5507
> Add support for static resources with fragments. Closes #5507

- lib/phoenix/test/conn_test.ex
Replace 'not found' with 'internal server error' in assert_error_sent/2 code examples. 
This could reduce confusion since "not found" errors are no re-raised.
Closes #5480
> Replace 'not found' with 'internal server error' in assert_error_sent/2 examples

- guides/introduction/up_and_running.md
Hi, this is not a bug, just a doc update. In 1.7.7 we see the following:
> chore(docs): update docs to reflect 1.7.7 steps

- installer/templates/phx_static/home.css
Resolves https://github.com/phoenixframework/phoenix/issues/5546
I checked, the valueless custom CSS properties aren't used anywhere in the `home.css`, and they are technically syntax errors, so let's remove them.
> Remove invalid CSS from generated home.css

- guides/routing.md
Hi, there!
Thank you for the fantastic guides. I was learning Elixir / Phoenix today, and noticed a reference to an incorrect pipeline name in the routing guide.
The guide mentions the `review_checks` pipeline which is not in the guide. I believe it is actually referring to the `auth` pipeline:
Do let me know if this is intentional. Thank you!
> [GUIDE] Fix incorrect pipeline name in routing guide

- lib/phoenix/logger.ex
Hi,
This should close https://github.com/phoenixframework/phoenix/issues/5555.
> Fix logger crash on atom status

- lib/phoenix/router.ex
This fixes https://github.com/phoenixframework/phoenix/issues/5559
I reversed the order of the scopes in the documentation example to match the authenticated route first and added a small blurb to recommend this approach in other apps. Feel free to remove the blurb if you don't think it's helpful.
> Update documentation around authenticated routes

- lib/phoenix/endpoint.ex
- lib/phoenix/socket.ex
- test/phoenix/socket/socket_test.exs
To configure the socket `drainer`, one must currently set it up during the compile time. I suggest adding an option to pass `{M, F, A}` to return the drainer configuration keyword list, just like the `check_origin` option. This would allow for runtime configuration of the drainer.
However, I could not find any tests related to this feature.
> [Socket Draining] Dynamic socket drainer configuration

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
It fixes a bug introduced in 10891447eddc023bd79e1b9f8b46f8a3344542bb, which does not allow to close flash when id is not given.
> Assign generated id to reuse in flash template

- installer/templates/phx_assets/tailwind.config.js
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
- installer/test/phx_new_web_test.exs
Previously, the tailwind config assumed that an app name ended in `_web` and used that for the config to import.
This commit changes it so that the app name is used instead.
This closes https://github.com/phoenixframework/phoenix/issues/5403
> Fix tailwind config for umbrella apps

- lib/phoenix/test/channel_test.ex
- test/phoenix/test/channel_test.exs
When testing with channels, map keys are stringified to replicate what would happen in the browser. This allows a test such as:
push(socket, "topic", %{foo: "bar"})
The ChannelTest module will modify this to reflect a real client, resulting in the channel receiving:
%{"foo" => "bar"}
This commit also includes arrays, making the behaviour consistent when pushing data containing an array.
This closes #5423
> Stringify lists in the ChannelTest module

- lib/phoenix/controller.ex
Currently Phoenix support (although it's soon-to-be-deprecated) format of putting layout:
```
plug :put_layout, {AppWeb.LayoutView, :layout}
```
however:
a) the spec doesn't reflect that, which means that code wouldn't pass dialyzer checks
b) warning doesn't mention anything about deprecations, it only suggests using code which wouldn't pass dialyzer:
```
warning: conflicting layouts found. A layout has been set with format, such as:
put_layout(conn, html: {AppWeb.LayoutView, :layout})
But also without format:
plug :put_layout, {AppWeb.LayoutView, :layout}
In this case, the layout without format will always win.
If you use layouts with formats, make sure that they are
used everywhere. Also remember to configure your controller
to use layouts with formats:
use Phoenix.Controller, layouts: …
```
> Fix inconsistency in code vs spec

- lib/phoenix/router.ex
While looking into [this issue](https://github.com/phoenixframework/phoenix/issues/5463), it was noted that maybe the documentation for `Phoenix.Router.scope/2` did not make it clear that the `:log` option only controls the log level for the router dispatching message logged by Phoenix.
[It was suggested](https://github.com/phoenixframework/phoenix/issues/5463#issuecomment-1720947223) that updating the documentation for this option can help clarify this, while also pointing users to documentation on how they can also control plug level logging.
As such, this Pull Request does exactly that, by updating the documentation for both `Phoenix.Router.scope/2` and `Phoenix.Router.match/5` in regards to the `:log` option.
> Update documentation for :log option on both scope/2 and match/5

- installer/templates/phx_assets/tailwind.config.js
This is an embarrassingly tiny niggle, but something my linter picked up in a recent project: since the callback passed to `map` does not return anything, `map` returns just an array of `undefined`... and in any case the result of the `map` is thrown away. Therefore it would be semantically nicer to do a `forEach` loop instead (or just a for loop, but the outer loop is already a `forEach` so this fits better stylistically).
> Change non-returning map into forEach

- lib/phoenix/controller.ex
- test/phoenix/controller/controller_test.exs
according to https://www.rfc-editor.org/rfc/rfc6266#appendix-D when it is not possible to express a filename with regular encoding, a `filename*` parameter can be added to the header.
This commit adds the `filename*` when the encoded filename does not match the filename.
This has been tested on chrome, safari and firefox.
This closes #5478
> Fix filename when sending downloads with non-ascii names

- priv/templates/phx.gen.auth/confirmation_live_test.exs
I noticed a flaky test from my generated liveview auth. The confirmation liveview has a test to make sure that there's not a flash with an error when confirming as a logged in user. The problem is the connection already had an error flash from a test case that was a little higher in the same test. I was only getting the bug after adding a redirect from my home url ("/") in my pages controller, but then it would have two flashes: 
```
1) test Confirm user confirms the given token once (MyAppWeb.UserConfirmationLiveTest)
test/my_app_web/live/user_confirmation_live_test.exs:20
Expected false or nil, got "User confirmation link is invalid or it has expired."
code: refute Phoenix.Flash.get(conn.assigns.flash, :error)
arguments:
%{"error" => "User confirmation link is invalid or it has …
```
> Fix small bug in test - reused conn from previous test case

- lib/mix/phoenix/schema.ex
- lib/mix/tasks/phx.gen.html.ex
- lib/mix/tasks/phx.gen.live.ex
- priv/templates/phx.gen.schema/schema.ex
- test/mix/tasks/phx.gen.html_test.exs
- test/mix/tasks/phx.gen.live_test.exs
- test/mix/tasks/phx.gen.schema_test.exs
Previously when using the html and live generators, generating a map field would result in a text input field. There is no trivial way to input map data in a text field. The map input is now skipped when generating the html and live forms.
This introduces a new issue where the field is missing, but marked as required on the schema. To fix this, a new `optionals` value is available on the generator schema, maps are automatically included into this schema. Any optionals are now skipped when generating `validate_required` in the schema file.
This closes #5235
> Skip map inputs in generated forms

- installer/templates/phx_single/lib/app_name/application.ex
- installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
When using the sqlite3 ecto adapter, the new and umbrella generators will add the `Ecto.Migrator` to run the migrations.
By default these run only when inside of a release, but the intent is to allow the end user to customize this in a way that suits their production environment.
This closes #5262
> Automatically migrate when release starts using sqlite 3

- installer/lib/phx_new/project.ex
- installer/test/phx_new_test.exs
- lib/mix/phoenix/schema.ex
- lib/mix/tasks/phx.gen.context.ex
- lib/mix/tasks/phx.gen.schema.ex
- priv/templates/phx.gen.auth/migration.ex
- priv/templates/phx.gen.auth/schema.ex
- priv/templates/phx.gen.schema/migration.exs
- priv/templates/phx.gen.schema/schema.ex
- test/mix/tasks/phx.gen.auth_test.exs
- test/mix/tasks/phx.gen.schema_test.exs
The generators now consider the :timestamp_type value in the generator config for an application.
For backwards compatability, if this value is not set, it will default to `:naive_datetime` which will generate the timestamps without an explicit type, otherwise the type will be set explicitly, such as:
`timestamps(:type, :utc_datetime)`
This closes #5564
> Allow UTC datetimes in the generators

- priv/templates/phx.gen.auth/confirmation_live_test.exs
Hi 👋
Ran into a small bug with the auto-generated (`mix phx.gen.auth`) test file for user confirmations. If you change the confirmations LiveView to redirect to a route that requires authentication, it fails since the redirect is followed with a `conn` that isn't logged in via (e.g. for a user schema) `log_in_user`
> Use logged-in `conn` when following redirect

- guides/real_time/presence.md
The presence guide has been split into two sections, the existing one is now usage with Channels and JavaScript.
The new section if the guide is focused on LiveView and outlines creating an Elixir based presence client, and using a LiveView stream for rendering the list of online users.
This closes #4858
> Add documentation on using presence with LiveView

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Hi!
Currently, the `<.input type="checkbox">` in the core components is "unsafe" to use from a DX point of view:
Using `<.input type="checkbox" checked={true} />` without an attribute `value="…"` raises a runtime exception because the `value` key is not in assigns.
The `@value` is not a required attr in the `def input`, yet, the `def input` for checkbox was pattern matching for it in the function argument, so the `value` attr is de facto required even if announced optional.
I can’t see why the `value` is mandatory, the body of the function is barely using it as a fallback if `@checked` is not set. So I propose to just dropping it from the function pattern matching, and later check if present in the assigns map.
See also [this discussion](https://elixirforum.com/t/semantics-of-the-input-typ …
> Allow `<.input type="checkbox">` without `value` attr in core components

- lib/mix/tasks/phx.gen.schema.ex
- test/mix/tasks/phx.gen.schema_test.exs
This allows us to provide a `--repo` flag to `mix phx.gen.schema`
It seems support is already built in for this with `Mix.Phoenix.Schema` so I simply added it to the `opts` in the format it seems is expected and made it utilise that `repo` for the migration path as well
Through options i've also added a `--migration_dir` which is passed in and used instead of the generated repo path
If this is wanted lemme know and I'll add tests to get it merged
> Allow --repo option & --migration-dir for phx.gen.schema 

- guides/contexts.md
> Docs: Remove separate index for leftmost column in multi-index

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
If no `id` was specified (like in `flash_group`) it defaulted to `nil`. The call to `assign_new` (#5542) did nothing because a default of `nil` had been assigned already.
> Fix flash without ID not being closeable

- guides/deployment/heroku.md
I found that there was some duplicate text and code block in the Heroku guide. 
ref: https://github.com/phoenixframework/phoenix/pull/5558
Thanks!
> remove duplicate text in heroku guide

- lib/mix/tasks/phx.routes.ex
I'm not entirely sure how to reproduce this, not even how it actually happens, but I'm currently working on a codebase where running `mix phx.routes --info [ROUTE]` raises an exception with the following message:
```elixir
Function: :index
** (ArgumentError) cannot convert the given list to a string.
To be converted to a string, a list must either be empty or only
contain the following elements:
* strings
* integers representing Unicode code points
* a list containing one of these three elements
Please check the given list or call inspect/1 to get the list representation, got:
[generated: true, location: 32]
(elixir 1.15.5) lib/list.ex:1084: List.to_string/1
(phoenix 1.7.8) lib/mix/tasks/phx.routes.ex:109: Mix.Tasks.Phx.Routes.get_url_info/2
(mix 1.15.5) lib/mix/task.ex:447: anonymous …
```
> Fix phx.routes mix task when docs return multiple annotations 

- guides/cheatsheets/router.cheatmd
- guides/cheatsheets/routing.cheatmd
- mix.exs
Adding cheatsheets for routing syntax. The Phoenix guidelines are super detailed and awesome, but there are moments when I just need to grab the syntax and go without the deep dive.
I plan to do the same for plugs, however, I'd appreciate community feedback on this one before proceeding.
> docs: add routing cheatsheet

- lib/phoenix/endpoint.ex
- lib/phoenix/endpoint/cowboy2_adapter.ex
- lib/phoenix/endpoint/supervisor.ex
- test/phoenix/endpoint/endpoint_test.exs
Solves https://github.com/phoenixframework/phoenix/pull/5553
Paired with https://github.com/mtrudel/bandit/pull/258 over in Bandit-land
@mtrudel will follow with a change to refactor https://github.com/livebook-dev/livebook/pull/2316 once this is merged/released (@josevalim relevant to your recent interests)
> Add `c:Phoenix.Endpoint.server_info/1`

- lib/phoenix/token.ex
Adjusts comments for sign and encrypt to mention their counterparts, verify and decrypt. Clarify that the default "max age" value for verify and decrypt comes from the token creation call.
> Phoenix.Token doc tweaks

- guides/components.md
While following the Phoenix guides, I tried to get the compile time warning the guide was talking about, but all I could get was a runtime error when loading the page.
After reading the [`attr/3`](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#attr/3) documentation, it seems the warning is only emitted when setting the `required` option to `true`.
*Since I'm a complete beginner with Phoenix, don't hesitate to point out any potential mistake or misunderstanding I could have made in my edit!*
> Add required option to attr/3 in Components guide

- guides/authentication/api_authentication.md
Fixed a missing parameter in a code sample in the API Authentication guide.
> docs: fix code sample in API Authentication guide

- lib/mix/tasks/phx.gen.release.ex
If the combination of the current Elixir version and OTP is not found in the
Docker registry we should default to a known combination, in this case the
latest Elixir version for that OTP version.
In case that no combination of Elixir/OTP is found the message shown to the
user is also more informational.
> Default to latest Elixir version Docker image

- lib/phoenix/endpoint.ex
Found while reviewing the changes that went into 1.7.10.
> Fix documentation typo in endpoint.ex

- guides/mix_tasks.md
Fixes grammar error in [Mix tasks Guide](https://hexdocs.pm/phoenix/mix_tasks.html): "By pressing confirming" -> "By confirming"
> Fix grammar error in 'Mix Tasks Guide'

- guides/contexts.md
Fixes typo in [Contexts Guide](https://hexdocs.pm/phoenix/contexts.html): `ShoppingChart` -> `ShoppingCart`
> Fix typo in 'Contexts Guide': `ShoppingChart` -> `ShoppingCart`

- guides/ecto.md
Remove extra parentheses in code example in [Ecto Guide](https://hexdocs.pm/phoenix/ecto.html):  `iex)>` -> `iex>`
> Remove extra parentheses in code example in 'Ecto Guide'

- lib/phoenix/verified_routes.ex
This PR updates `<.link>` components to use `href=` instead of `to=` as the latter doesn't seem to be supported anymore.
> docs: update verified_routes.ex <.link/> examples

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
The path changed recently as we moved from a vendored copy to a Mix
dependency.
> Update path to heroicons in documentation

- lib/mix/tasks/phx.gen.release.ex
The warning to update `config/runtime.exs` only applies to other supported databases.
> phx.gen.release: Do not show IPv6 warning for SQLite3

- guides/asset_management.md
This can be valuable to people who want to avoid Node.js in their
projects, while having a simpler way to track and update dependencies
straight from Git or path, etc.
> Document using Mix to track JS dependencies from source

- priv/templates/phx.gen.release/rel/migrate.sh.eex
- priv/templates/phx.gen.release/rel/server.sh.eex
Shell script defaults are not great.
By default a script will keep executing even if a command fails or if it tries to expand a variable which isn't set.
It's unlikely the commands generated here would fail, but people might be making changes to these scripts and expanding them later.
It's better to generate a safer starting point.
`-e` will make the shell exit with an error if a command fails.
`-u` will make the shell exit if it tries to expand an unset variable.
I also wanted to set `-o pipefail` which would cause a pipeline to fail if any of the commands in the pipeline fail (rather than just the last one, as is the default).
However, that option is not part of the POSIX standard so it won't be there in all shells.
See [manual](https://man7.org/linux/man-pages/man1/set.1p.html) for …
> Make generated release scripts safer

- installer/templates/phx_gettext/errors.pot
After creating a new project, running `mix gettext.extract --merge` would remove that line anyway, causing an unnecessary change.
Related to #5649.
> Remove extra newline in errors.pot from installer template

- test/phoenix/controller/controller_test.exs
With Elixir 1.15.7 and OTP26.2, this test randomly fails:
```
1) test path and url generation current_path/2 allows custom nested query params (Phoenix.Controller.ControllerTest)
test/phoenix/controller/controller_test.exs:789
Assertion with == failed
code:  assert current_path(conn, %{foo: %{bar: [:baz], baz: :qux}}) == "/?foo[bar][]=baz&foo[baz]=qux"
left:  "/?foo[baz]=qux&foo[bar][]=baz"
right: "/?foo[bar][]=baz&foo[baz]=qux"
stacktrace:
test/phoenix/controller/controller_test.exs:791: (test)
```
It relied on ordering of a map. Switching to a keyword list, we avoid this pitfall.
> Fix flaky test for `Phoenix.Controller.current_path/2`

- installer/templates/phx_assets/tailwind.config.js
- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/apps/app_name_web/mix.exs
- integration_test/mix.exs
The `-micro` variant was released yesterday ([announced in the blog post](https://tailwindcss.com/blog/heroicons-micro)). The `-micro` variant is a new set of `16x16px` icons.
I have updated the `mix.exs` generators to Heroicons tag `v2.1.1`. To support the smaller size correctly, I have made a minor change to use `theme("spacing.4")` for the `width` and `height` only for `-micro` icons, by default.
> Upgrade Heroicons to v2.1.1 with support for the new `-micro` variant.

- guides/deployment/heroku.md
- guides/introduction/overview.md
- guides/mix_tasks.md
- guides/request_lifecycle.md
- installer/lib/mix/tasks/phx.new.ex
For the 1.16 release, content from
https://elixir-lang.org/getting-started/ has [moved to HexDocs](https://github.com/elixir-lang/elixir/issues/12747).
In particular, the link to umbrella projects docs in the phx.new task
help was returning 404 and has been manually corrected to the new
location (https://github.com/elixir-lang/elixir-lang.github.com/issues/1740).
> Update links to Elixir docs

- installer/templates/phx_assets/tailwind.config.js
We recently added support for the new 'micro' variant with proper sizing (16x16 pixels).
This change updates the default size of the original icons (no suffix) and their 'solid' variant to be their native size (24x24 pixels).
The 'mini' variant remains at their native size (20x20 pixels).
> Set Heroicon default size to native icon size

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- lib/phoenix/endpoint/cowboy2_adapter.ex
Not sure about the testing CI/strategy but I tried to extend it to cover all supported versions :)
* Test against newest elixir & otp
* Test against oldest supported elixir (Changelog and mix say 1.11) and I think we should test against it to avoid accidental brekage
* updated patch versions for elixir versions
Thanks as always for your excellent work! :green_heart:
> Extend test matrix to cover supported versions

- installer/templates/phx_single/config/config.exs
- installer/templates/phx_single/config/dev.exs
- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/config.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
- installer/templates/phx_umbrella/apps/app_name_web/mix.exs
When adding more than one app to your umbrella project you can't use default for tailwind and esbuild configurations or they will clash between them. By using their names instead of "default" the issue is fixed.
Closes #5631
Steps to test it (assuming you are [using phoenix mix from source code](https://github.com/phoenixframework/phoenix#generating-a-phoenix-project-from-unreleased-versions)):
1. `mix phx.new --umbrella /tmp/a`
2. `mix phx.new.web /tmp/a_umbrella/apps/b`
3. Change `config/runtime.exs` &  `config/dev.exs` to change one of the apps to listen in something that isn't `4000`.
4. `cd /tmp/a_umbrella && mix ecto.migrate`
> Use umbrella apps names instead of "default"

- guides/deployment/heroku.md
The smallest Heroku Postgres plan is now "mini". I've updated the deployment guide accordingly!
https://elements.heroku.com/addons/heroku-postgresql
>  In the Heroku deployment guide, changes postgres plan from hobby-dev to mini

- priv/templates/phx.gen.auth/confirmation_instructions_live_test.exs
- priv/templates/phx.gen.auth/confirmation_live_test.exs
- priv/templates/phx.gen.auth/forgot_password_live_test.exs
- priv/templates/phx.gen.auth/login_live_test.exs
- priv/templates/phx.gen.auth/registration_live_test.exs
- priv/templates/phx.gen.auth/reset_password_live_test.exs
- priv/templates/phx.gen.auth/settings_live_test.exs
Test suites generated by `mix phx.gen.auth` conditionally set `async: true` if the database adapter is Postgres. Some of those test suites are missing that condition despite no apparent issues running tests concurrently.
I used these steps to test this out:
- Created a simple demo app using `mix phx.new`
- Add authentication code using `mix phx.gen.auth Accounts User users` and run migrations
- Run `for X in 1 2 3 4 5 6 7 8 9 10; do mix test; done`
I've ran these tests many times and I did not see any failures.
Originally posed as a question [here](https://elixirforum.com/t/why-arent-all-test-suites-generated-by-mix-phx-gen-auth-tagged-with-async-true/60812), pinging @josevalim as requested :)
> Make test suites generated by phx.gen.auth use async: true

- guides/mix_tasks.md
To use an application's infrastructure, the docs say `@requirements ["app.config"]` should work, but it doesn’t:
```
→ mix task.name
Compiling 1 file (.ex)
** (RuntimeError) could not lookup Ecto repo App.Repo because it was not started or it does not exist
(ecto 3.11.1) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
(ecto 3.11.1) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2
(app 0.1.0) lib/app/repo.ex:2: App.Repo.all/2
(app 0.1.0) lib/mix/tasks/task.name.ex:13: Mix.Tasks.App.Ingest.run/1
(mix 1.16.0) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
(mix 1.16.0) lib/mix/cli.ex:96: Mix.CLI.run_task/2
/Users/jyc/.asdf/installs/elixir/1.16.0-otp-26/bin/mix:2: (file)
```
I asked on the forums and it turns out that `app.start` is the correct name: …
> Fix broken reference to app.config in "Creating our own Mix task" docs

- guides/contexts.md
There is a typo on the contexts guide where the field `cart_id` is mentioned as `cart-id`.
> Fix typo in the contexts guide

- guides/plug.md
The [Head Plug](https://github.com/elixir-plug/plug/blob/85f03493afd78441b1ee2692b198641ccbee6bdc/lib/plug/head.ex#L18) doesn't strip the body from the response, it just converts `HEAD` requests to `GET` requests.
> Correctly describe Head Plug

- guides/howto/custom_error_pages.md
This docs page on custom errors uses an example that has paths that don't exist in new projects (js/css directory instead of assets directory).
> Paths in custom error example should match latest assets paths for new projects

- installer/lib/phx_new/generator.ex
Use the frequently seen shortcut for new apps.
> Replace Path.dirname(__ENV__.file) with __DIR__ in SQLite config

- installer/lib/phx_new/generator.ex
- installer/templates/phx_single/config/runtime.exs
Fixes the endpoint config comment when generating a new project with `mix phx.new --adapter=cowboy`. Currently it always links to Bandit.
[diff](https://elixirstream.dev/gendiff/phx_new/4D359BC0A7DA7B6C0E8C41FCA9D6F904#68944278--61) for `VERSION=1.7.10 phx.new my_app` x `VERSION=1.7.11 phx.new my_app --adapter=cowboy`
> Fix docs when generating with --adapter=cowboy

- guides/asset_management.md
When `esbuild` is called by elixir in the default template (`dev.exs`), it has the the following environment set:
```
env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
```
This patch suggest a similar option using a `build.js` file. This helps the developer discover the option.
> Add nodePaths to the example code

- lib/mix/tasks/phx.gen.cert.ex
We could not generate a certificate with phx.gen.cert today because of an invalid end date.
With a starting date of 2024-02-29 the task would generate an invalid end date of 2025-02-29.
This PR fixes this bug by calculating an end 365 days in the future.
> Generate certificate with a valid end date on a February 29

- CHANGELOG.md
> Fix wrong header level in changelog

- priv/templates/phx.gen.socket/socket.ex
Very small docs correction. Saw it as I was reading the docs myself. Incorrect use of possessive as plural. I picked upcase for acronym "ID". Downcase would be fine too.
> Update comment in socket.ex

- guides/deployment/heroku.md
According to the Using SSL guide, `force_ssl` is compile time to should be set in a file other than `runtime.exs`.
I also took the opportunity to clarify Heroku's "best practices" as being the 12-Factor App methodology and to improve some of the working.
This config works for me, but if I missed something, please let me know!
> Clarify force_ssl in Heroku deployment guide

- lib/mix/tasks/phx.gen.cert.ex
Use Date.iso8601 function instead of custom implementation to calculate start and end date for the generated certificate
> Use Date.iso8601 function to calculate start and end date for the generated certificate

- installer/templates/phx_single/lib/app_name_web.ex
As "view" mentions have been removed from the `moduledoc` and were replaced by "component" I thought it might make sense to remove it from `__using__` doc as well.
> remove `view` from doc

- guides/real_time/channels.md
Reading about Phoenix channels and wondering about client libraries, I was reading the [Client Libraries](https://hexdocs.pm/phoenix/channels.html#client-libraries) section and saw the mention of the [Writing a Channels Client](https://hexdocs.pm/phoenix/writing_a_channels_client.html#content) how-to guide, so I thought it would be useful to directly link to that guide.
> Add link to the "Writing a Channels Client" how-to guide

- priv/templates/phx.gen.auth/auth.ex
Plug.CSRFProtection [docs](https://hexdocs.pm/plug/Plug.CSRFProtection.html):
> we recommend developers to invoke delete_csrf_token/0 every time after they log a user in, to avoid CSRF fixation attacks.
I'm curious as to why that advice is not implemented in the `phx.gen.auth` templates.
There probably is a good reason I'm missing. If so, add that reason to the documentation?
Further reading:
https://hexdocs.pm/plug/Plug.CSRFProtection.html
https://security.stackexchange.com/a/22936
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html
> Prevent session fixation attack (phx.gen.auth + CSRF)

- lib/phoenix/controller.ex
Adjusting documentation according to [the source code](https://github.com/phoenixframework/phoenix/blob/b07c13019cf9cc8e1cc6098b85a4c0aff4c4cea1/lib/phoenix/controller.ex#L1277).
> Fix Phoenix.Controller.send_download/3 :encode option doc

- lib/mix/tasks/phx.digest.ex
Reenable phx.digest task to allow running the task with different arguments for different assets  paths.
Fixes #5752
> Allow running phx.digest task multiple times

- priv/templates/phx.gen.auth/login_live.ex
The [Phoenix docs say](https://hexdocs.pm/phoenix_live_view/0.20.12/Phoenix.Component.html#live_flash/2):
> `live_flash(other, key)`
> This function is deprecated. Use Phoenix.Flash.get/2 in Phoenix v1.7+. 
But the live_flash is still being used on generated auth, this PR fixes it.
I didn't find any other place that uses the `live_flash/2`.
Thanks!
> replace deprecated live_flash for Phoenix.Flash.get in phx.gen.auth

- lib/phoenix/token.ex
Whoops - I missed a "be" :sweat_smile:
> Fix typo in Token docs

- guides/howto/writing_a_channels_client.md
Just a small doc change to reduce confusion. It now matches the order of the list on line 34, which is the expected behavior.  👍
> Re-order doc to better match example

- lib/phoenix/test/conn_test.ex
- test/phoenix/test/conn_test.exs
This PR adds follow_redirect/2 to Phoenix.ConnTest.
When testing complex redirect flows e.g a callback from an external source, then I found it as usefull as Phoenix.LiveViewTest.follow_redirect.
> Add follow_redirect/2 to Phoenix.ConnTest

- lib/phoenix/test/conn_test.ex
- test/phoenix/test/conn_test.exs
Currently, if you set `remote_ip` during a test when building a conn, calling a `dispatch` call e.g `get` will run the conn through `recycle` which will lose this information. This PR changes that so it is maintained similar to `host`.
> Persist `remote_ip` during recycling of a conn

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
In the documentation, `data structure` is written as `datastructure`.
> fix typo for core components documentation

- guides/routing.md
> Fix typo in verified routes guide

- CHANGELOG.md
While searching the docs for information on the deprecation warning, I didn't at first find this deprecation as I was grepping for `Deprecations`, and so only saw the 1.7.0-rc deprecation.
> Changelog: pluralize "Deprecations" for consistency

- installer/lib/phx_new/web.ex
This PR includes `logo.svg` into umbrella project generator. 
This file is currently properly included in "single" projects, thanks to https://github.com/phoenixframework/phoenix/commit/5a01f103371199d60f85c86860e897a7e4dab36b, but is missing in umbrella projects.
> Use logo asset in umbrella generator

- guides/mix_tasks.md
- lib/mix/tasks/phx.gen.json.ex
- test/mix/tasks/phx.gen.json_test.exs
The statement "Add the resource to your :api scope" is confusing for new-comers.
Users will open the router.ex file, and quickly find a section:
```
pipeline :api do
plug :accepts, ["json"]
end
```
and paste the line into this block.
Experienced phoenix devs will understand that this is a pipeline and not a scope, but these semantics will not be obvious the newby. 
The pull request changes the line to read:
"Add the resource to "/api" scope" or ( "Add the resource to "/api/v1" scope"  if you have configured the api_endpoint like this)
I was struggling with this, and this user on the forums as well:
https://elixirforum.com/t/can-someone-please-help-me-with-this-basic-api-creation-rubber-ducky-edition/53684/7
> Clarify user message in phx.gen.json

- lib/phoenix/verified_routes.ex
I believe it should be `sigil_p/2` like in the docs for `url/1` instead of `sigil_p/1`, which does not exist.
> fix typo in verified routes docs

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
This PR aligns the transition time and duration values in a couple of show & hides in the generators. The default transition time for `JS.show` and `JS.hide` is [200ms](https://github.com/phoenixframework/phoenix_live_view/blob/adacdfd985b7282903012057167ac563fb89d983/assets/js/phoenix_live_view/js.js#L5) but the Tailwind durations are set to 300ms.
After making the changes, I noticed there is already an [open PR](https://github.com/phoenixframework/phoenix/pull/5733) with the same change. However, that one changes the time of the animations to the shorter 200ms, whereas this one keeps the longer 300ms version - which I personally prefer. Choose the version you prefer, the shorter or longer animation.
> Align time and duration values in a couple of show / hides

- installer/templates/phx_static/home.css
- installer/templates/phx_web/components/layouts/root.html.heex
One day, perhaps over a decade ago, it used to bring visual improvement and consistency to font rendering across browsers and operating systems.
But, over the years, the default subpixel-antialising in browsers/OSes produces better results than 'antialiased'.
There are many discussions about this on the web, I mention a few:
- https://github.com/google/fonts/issues/1170
- https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
- https://web.dev/articles/antialiasing-101
- https://en.wikipedia.org/wiki/Subpixel_rendering
> Remove 'antialiased' CSS class from root template

- installer/templates/phx_umbrella/apps/app_name/mix.exs
This PR allows running `mix ecto.setup` from the root of an umbrella project.
> Allow `mix ecto.setup` from the umbrella root.

- lib/phoenix/verified_routes.ex
Documentation in the form of examples was missing for functions without specs:
- path/3
- static_url/2
- static_path/2
- static_integrity/2
static_url/2 also incorrectly claimed to accept a URI argument in its error clause but does not accept one.
> Add documentation to Phoenix.VerifiedRoutes functions

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
This is a tiny bugfix for the `checkbox` input component in the core components.
The problem here is that if I have a FormField with a boolean value of `true` and I render a checkbox input using the core components for it, the value of the field will not be sent properly if I disable the checkbox because the `disable` attribute is only set on the "true" checkbox input, not on the fallback "false" one. Because disabled inputs are not sent when the form is submitted, this means that the fallback "false" value will be sent even though the real value of the FormField is "true".
This bugfix sets the `disabled` attribute also on the "false" fallback checkbox input. This completely removes the field value from being submitted, which is the expected behaviour because disabled inputs are not …
> Disable fallback checkbox in Core Components if FormField is disabled as well

- lib/phoenix/router.ex
I was trying to skip helpers generation for some of my routes.
Contrary to what is stated in the documentation, you need to pass `as: nil` option instead of `as: false` to achieve this behaviour.
> Correct documentation about route helpers generation

- installer/test/mix_helper.exs
- test/mix/tasks/phx.digest.clean_test.exs
- test/mix/tasks/phx.digest_test.exs
- test/mix/tasks/phx.routes_test.exs
- test/phoenix/controller/render_test.exs
- test/phoenix/digester_test.exs
- test/phoenix/endpoint/endpoint_test.exs
- test/phoenix/param_test.exs
- test/phoenix/router/routing_test.exs
- test/phoenix/verified_routes_test.exs
This allows to use the new `mix test --repeat-until-failure` feature to run the unit tests.
I also found some more issues where mix compile was called in tests leading to missing modules if you had bad luck. This is now fixed by always passing `--no-compile`.
Furthermore, all directories in the `tmp` folder are now properly cleaned up. https://github.com/phoenixframework/phoenix/pull/5623 already tried to do this, but this still left directories if the generated test name or random string contained a `/` character.
> make tests repeatable (--repeat-until-failure)

- lib/phoenix/test/conn_test.ex
- test/phoenix/test/conn_test.exs
This conflicts with follow_redirect in LiveView.
Reverts phoenixframework/phoenix#5797
> Revert "Add follow_redirect/2 to Phoenix.ConnTest"

- lib/mix/tasks/phx.gen.auth.ex
Replace the local private function with the public one in Mix.Phoenix used by all the other generators.
> Use Mix.Phoenix.generator_paths in phx.gen.auth.ex

- lib/mix/tasks/phx.digest.clean.ex
- lib/mix/tasks/phx.digest.ex
- test/mix/tasks/phx.digest_test.exs
Args like "--no-deps-check" do not get passed through causing `compile` to fail in instances where it's important to not check deps. For example this broke our nix build which handles deps in its own way.
It breaks these instructions: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/beam.section.md?plain=1#L215
Also adds command line docs and removes `--no-deps-check` flag on tests that use `--no-compile`
> Pass all_args to compile task in digest tasks

- priv/templates/phx.gen.release/Dockerfile.eex
- test/mix/tasks/phx.gen.release_test.exs
This step will install Tailwind and esbuild earlier and the container layer shall be cached depending only on dependencies and config (where Tailwind and esbuild tool versions are actually defined).
Code changes in priv, lib and assets shall not cause those tools to be re-downloaded and installed.
Closes #5833.
> phx.gen.release: Add explicit mix assets.setup step

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Fixes #5852: action block rendering under hover when there is more than one line.
> #5852 Fix action block rendering for tables

- lib/mix/tasks/phx.server.ex
When `mix phx.server -- arg1` command has been run, it starts server, then halts it immediately.
This PR fixes that bug, so once you run command it does not halt server.
More details on [issue tracker](https://github.com/phoenixframework/phoenix/issues/5867#issue-2406001001)
> Fix mix phx.server command bug - it halts if command line args separator -- has been used

- guides/deployment/heroku.md
The current Heroku deployment instructions are incompatible with newer versions of Node.js, causing deployment failures and confusion for developers using up-to-date environments. See https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/112
We have replaced the current buildpack with https://github.com/gigalixir/gigalixir-buildpack-phoenix-static, which supports installation of current Node.js versions. This change allows us to use more recent Node.js versions in our Heroku deployments, resolving the compatibility issues we were facing.
> Update Heroku deployment documentation

- CONTRIBUTING.md
- guides/directory_structure.md
- guides/introduction/packages_glossary.md
- guides/request_lifecycle.md
As I read through the docs, there are some minor improvements that can be made to help improve readability. These are not documentation bugs.
Most of these changes fall into categories like plurality correction, correct tense usage within a paragraph, grammar adjustments, etc.
I've deliberately tried not to rewrite or reword things except where I feel they read better, and in most cases you'll find these changes to be very minor. I'm cautious to avoid changing any meaning.
This is my first contribution, and while it's low hanging fruit, I appreciate the focus the community has on good documentation, so helping to make this even better is a great place to start.
I have only read a few guides so there is not a lot to this commit but I wanted to submit early in part as a check to ensure that …
> docs: minor grammar etc improvements.

- guides/deployment/releases.md
- priv/templates/phx.gen.release/Dockerfile.eex
When running docker I got these warnings:
```
4 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 21)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 79)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 80)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 81)
```
> Fix some Docker warnings

- lib/phoenix/endpoint.ex
- lib/phoenix/endpoint/supervisor.ex
- test/phoenix/endpoint/supervisor_test.exs
This is useful to override `watchers` when we want to override the config.
keywords are not overridable. ref. https://hexdocs.pm/elixir/main/Config.html#config/3
> Add `false` value to disable `watchers`

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
This disables some animation if a user prefers reduced motion using one of those tailwind modifiers described [here](https://tailwindcss.com/docs/animation#prefers-reduced-motion).
> Only spin loading spinners if user does not prefer reduced motion

- guides/plug.md
The first example (adding locale) of router.ex doesn't align with generated code or subsequent examples. There are two issues:
1.  `plug :fetch_flash` should be `plug :fetch_live_flash` 
2. Missing line: `plug :put_root_layout ...`
> Correct example router.ex code in Plug guide

- guides/deployment/fly.md
I am trying to fix a broken link [Working with Fly.io applications](https://fly.io/docs/getting-started/working-with-fly-apps/). 
According to what I see from [IA](https://web.archive.org/web/20200812153205/https://fly.io/docs/getting-started/working-with-fly-apps/#viewing-applications), the page doesn't exist anymore and they separated it into different parts.
> fix broken link

- lib/phoenix/param.ex
Updates the documentation to show usage in `VerifiedRoutes` instead of Route helpers and shows an example to directly implement the protocol for an internal Elixir `Date` struct instead of deriving an implementation, when you don't define the struct yourself
> Update docs for `Phoenix.Param`

- lib/phoenix/router.ex
This is my first PR, as I was reading through docs as someone new to Phoenix framework and noticed this section of the `Phoenix.Router` docs didn't make sense to me.
This fixes a typo where a host option passed to `scope/2` is described as if it were a part of the `path` param instead. I updated the description instead of fixing the example, because I personally found the example to be useful in better understanding the options available when defining router scopes, but changing the example instead would also work if preferred.
I removed the sentence about named routes because:
1. They aren't explained previously in this documentation.
2. They seem to be related to helpers (deprecated), as the `phx.routes` mix task doesn't output them when helpers are disabled, so it's not clear to me if …
> docs: router, fix scope example explanation typo

- guides/asset_management.md
In Phoenix `1.7.14`, using `npm install some-package --save` from inside the `assets/` directory doesn't actually appear to do anything while `npm install some-package --prefix assets` creates `package.json` and `package-lock.json` files and is what was suggested in the auto-generated `app.js` that you get with a new Phoenix app. So I attempted to tweak the guide to clarify this + make it match the comments in `app.js`.
Feel free to tweak / ignore as desired.
> Clarify instructions for using npm install method for third-party JS packages

- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/apps/app_name_web/mix.exs
- lib/phoenix/code_reloader.ex
- lib/phoenix/code_reloader/mix_listener.ex
- lib/phoenix/code_reloader/server.ex
This improves the code reloader to better handle concurrent compilations using Mix listeners API coming in Elixir v1.18.
The code reloader already handles concurrent compilation by checking the Elixir compiler manifest. If the manifest appears stale, we prune all modules from the given application. However, always pruning all modules can be expensive if the number of loaded modules is large.
This PR introduces a Mix listener that listens to concurrent compilations and keeps track of the changed modules. Then, before compiling, we prune only the modules that actually changed.
On Elixir < 1.18 we fall back to the current approach. On Elixir >= 1.18 we warn if the listener is not configured (and also use the fallback).
cc @josevalim
> Implement mix listener to respect concurrent compilations

- guides/controllers.md
Only action name should be changed to match route renaming.
Change of passing template's name leads to bug, as the template is not renamed.
And description above clearly talks only about action.
> Fix action rename example in controllers guides

- guides/components.md
I didn't see many (any?) code examples in docs of how to render a functional component directly in controller. This PR adds that.
> [docs] add code example on how to render functional component in controller

- installer/lib/mix/tasks/phx.new.ex
When generating a new application using Elixir 1.18.0-dev, this warning is raised:
> Compiling 1 file (.ex)
>      warning: Mix.Rebar.rebar_cmd/1 is deprecated. Use rebar_args/2 or available?/1 instead
>      │
>  275 │       Mix.Rebar.rebar_cmd(:rebar3)
>      │                 ~
>      │
>      └─ lib/mix/tasks/phx.new.ex:275:17: Mix.Tasks.Phx.New.rebar_available?/0
Not sure if this is a good practice, but that's I come up with.
> phx.new - Fix deprecation warning when using Elixir ~> 1.18

- lib/phoenix/socket.ex
- lib/phoenix/transports/long_poll.ex
- lib/phoenix/transports/long_poll_server.ex
The `link: true` option was supported with versions of `phoenix_pubsub` earlier than 2.0.0, and was removed in this commit https://github.com/phoenixframework/phoenix_pubsub/commit/c05d47f6411d81f3cd94d53607848b5195239c4f
As Phoenix requires `phoenix_pubsub` `~> 2.1`, I believe removing these options is safe.
> Remove an old and unused PubSub subscribe option

- lib/phoenix/controller.ex
- test/phoenix/controller/controller_test.exs
> Send download encodes reserved chars

- installer/templates/phx_web/controllers/page_html/home.html.heex
The Elixir Slack has a large community and an active #phoenix channel, people should be directed there along with IRC and Discord.
> Add Slack community link to home template

- guides/json_and_apis.md
This is a trivial fix to some grammar in `json_and_apis.md` - No worries if this gets rejected/closed as too trivial but just wanted to point it out while reading the guide!
> Fix some grammar in the JSON and APIs guide

- lib/phoenix/endpoint.ex
- lib/phoenix/endpoint/supervisor.ex
- lib/phoenix/socket/transport.ex
- lib/phoenix/transports/long_poll.ex
- lib/phoenix/transports/websocket.ex
- test/phoenix/endpoint/supervisor_test.exs
- test/phoenix/socket/transport_test.exs
This PR proposes adding a `check_csrf` option to Phoenix's socket transport, so as to enable caching Liveview's static rendering.
After releasing [`plug_http_cache`](https://github.com/tanguilp/plug_http_cache), I was asked if we could use it to cache Liveviews.
After a few experiment, I came with the following PR last year: https://github.com/phoenixframework/phoenix/pull/5667. Note that in this PR, I **didn't** follow the proposed approach in the discussion there (prefer being honest here :see_no_evil:).
I took more time to study the different approaches how to implement it this year. I described it in 2 blog posts:
- [Caching Liveviews - Part 1: The road to HTTP-caching Liveviews](https://svground.fr/blog/posts/caching-liveviews-part-1/)
- [Caching Liveviews - Part 2: Publicly caching …
> Add `check_csrf` option to socket transport options

- lib/mix/phoenix/schema.ex
- After change from [this PR](https://github.com/phoenixframework/phoenix/pull/4601/files#diff-4307581434ae66da4750cde438c2b192c4a11c8b71ba32dbf78aea36daa0ee3eR368), `:enum` valid case becomes redundant. Next line has general check that includes valid enum case.
- Also removed redundant passing throw for `:datetime` case. Instead, return already prepared result right away.
> Remove redundant validate_attr case.

- priv/templates/phx.gen.auth/confirmation_edit.html.heex
- priv/templates/phx.gen.auth/confirmation_instructions_live.ex
- priv/templates/phx.gen.auth/confirmation_live.ex
- priv/templates/phx.gen.auth/confirmation_new.html.heex
Email confirmation pages can be open by logged in user. In such case we have following inconsistency.
- Below confirmation form we have "Register" and "Log in" links.
- While at the top menu we have "Settings" and "Log out".
This change fixing inconsistency by presenting links below confirmation form only if user is not logged in.
Note: I used `if !condition` because `unless` is going to be deprecated.
> Auth links consistency on email confirmation pages.

- priv/templates/phx.gen.auth/schema_token.ex
Simple typo in doc.
Query build in method `verify_change_email_token_query` differs from `verify_email_token_query`. It returns `user_token` instead of `user`.
For quick presentation of proof, here is reference to invocation code:
```elixir
with {:ok, query} <- UserToken.verify_change_email_token_query(token, context),
%UserToken{sent_to: email} <- Repo.one(query),
```
> Correct query result in doc to verify_change_email_token_query.

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Remove the default `nil` value for the `as` attribute in the generated `simple_form` core component.
This default interferes with the form name present in the form struct provided through the component's `for` attribute when used with `:let=`.
For example, consider the following code:
```
<.simple_form :let={f} for={@form}>
<%= inspect(f.name) %>
<.input field={f[:bar]} label="Bar" />
</.simple_form>
```
When rendered, `f.name` is `nil`, and the `name` attribute of the form field only contains `bar`, missing the proper field name prefix from the form struct:
```
<div class="mt-10 space-y-8 bg-white">
nil
<div data-phx-id="m9-phx-GAgAfRg6YU4XV6tC">
<label for="bar" class="block text-sm font-semibold leading-6 text-zinc-800" data-phx-id="m10-phx-GAgAfRg6YU4XV6tC">
Bar
</label>
<input …
```
> Preserve original name when `as` is not provided to `simple_form`

- installer/templates/phx_assets/app.js
- installer/templates/phx_single/config/dev.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
This article describes a new and useful feature in Live reload 1.5 and later.
I think it could make sense to enable it by default for new projects...
https://fly.io/phoenix-files/phoenix-dev-blog-server-logs-in-the-browser-console/
> Enable web console logger for new projects

- installer/templates/phx_single/README.md
- installer/templates/phx_umbrella/apps/app_name_web/README.md
Markdown linters hate indented bullet points.
This PR fixes the README that Phoenix generates when running `mix phx.new`
> Fix linting on README templates

- installer/templates/phx_assets/app.js
Relates to: #5799
Relates to: #5910
cc @josevalim
> enable live reload features by default for new LV apps

- lib/phoenix/endpoint/supervisor.ex
There was a slight time window in between starting the socket listener and actually setting the config in persistent_term that could rely in a crash on incoming requests. This commit fixes this by calling the warmup function as a child in the endpoint supervisor, after the config is started, but before the socket listener is started.
Fixes https://github.com/phoenixframework/phoenix/issues/5981.
> run endpoint config warmup before starting socket

- lib/phoenix/test/channel_test.ex
This at least makes this more discoverable. I still don't really understand why the API wouldn't handle this for the user though.
> Link module documentation of `leave` and `close` crashing the test process

- priv/templates/phx.gen.auth/schema.ex
I know the conventional wisdom is there's no reason to over complicate email validation because it is implicitly validated by  sending a confirmation email.
The current regex accepts multiple emails separated by commas or semicolons. For example: 
- `email1@example.com,email2@example.com`
- `email1@example.com;email2@example.com`
Some email servers accept a comma or semicolon seperated list of emails as valid and would send the content to each recipient. For example, [Mailgun](https://mailgun-docs.redoc.ly/docs/mailgun/api-reference/openapi-final/tag/Messages/). Documentation mentions you can use comma to separate multiple recipients. (I haven't tested it)
That means the implicit validation of the email is not enough. It could allows user with one email to sign up multiple times by using …
> Prevent multiple emails separated by commas in email field

- lib/phoenix/endpoint.ex
I couldn't find reference to `MIX_BUILD` in the Mix docs, but I think `MIX_TARGET` is what's meant to be referred to here.
See https://hexdocs.pm/mix/Mix.html#module-environment-variables and https://hexdocs.pm/mix/Mix.html#module-targets for more info.
> Refer to `MIX_TARGET` not `MIX_BUILD` in docs around separate build directories

- guides/testing/testing_controllers.md
correct path for generated `index.html.heex`
> fixed index.html.heex path (fixes #6036)

- installer/templates/phx_assets/tailwind.config.js
Ensure SVG icon data is properly encoded as data URI, fixes #6038.
> Encode SVG icons data

- .github/workflows/ci.yml
- lib/phoenix/code_reloader/server.ex
- lib/phoenix/router.ex
- lib/phoenix/socket/pool_supervisor.ex
- mix.exs
v1.13 and earlier are no longer supported and, given we will probably stay on v1.8 for a while, it makes sense for us to push to at least v1.15.
> Require Elixir v1.15 for Phoenix

- guides/deployment/deployment.md
Currently, Phoenix will automatically enable a long-poll Socket implementation and LiveView will fallback to long-polling automatically, in order to avoid issues with network conditions not allowing WebSockets. This comes with a major undocumented footgun - Long-Polling requires that either all requests go to the same machine (stickiness), or that nodes in a cluster can communicate.
This documents the footgun and warns the user, along with explaining why this happens.
> Document the Long-Poll Transport Limitations

- lib/phoenix/router/route.ex
Found by 1.19 typesystem. The `build_params()` call returns a non empty list so `merge_all = merge_params ++ merge_private ++ merge_assigns` is non empty as well.
```
warning: comparison between distinct types found:
merge_all != []
given types:
dynamic(non_empty_list(term(), term())) != empty_list()
where "merge_all" was given the type:
merge_all = merge_params ++ merge_private ++ merge_assigns
While Elixir can compare across all types, you are comparing across types which are always disjoint, and the result is either always true or always false
typing violation found at:
│
180 │     if merge_all != [] do
│                  ~
│
└─ lib/phoenix/router/route.ex:180:18: Phoenix.Router.Route.build_prepare/1
```
> Remove not used code

- installer/templates/phx_assets/app.css
I suspect this PR might be a slightly hard sell, but I will do my best to motivate my reasons for proposing its inclusion.
LiveView generates non-optional wrapper divs. This presents challenges for using LiveViews in certain layouts. For example, if you want your LiveView to be a flex child, then your best course of action is to add `container: {:div, style: "display: contents"}` when rendering the LiveView. `display: contents` makes the element invisible for layout purposes, so the child of the wrapper div effectively replaces the wrapper div in the layout.
Another option is to make this the global default for your wrapper divs. This can be done in CSS with the following line:
```css
[data-phx-root-id] { display: contents }
```
Adding this to an existing project might be tricky, because …
> Make Liveview's root divs transparent for layout purposes.

- priv/templates/phx.gen.auth/auth.ex
- priv/templates/phx.gen.auth/auth_test.exs
> phx.gen.auth: don't generate on_mount functions when not needed

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
Other core component input has class `sm:leading-6` and error handling cause select input has different height and error feedback:
Before:
After:
> Update inconsistent core_component select input class

- .formatter.exs
So one can simply add `:phoenix` to their `:plugins` option in `.formatter.exs` and it will not automatically include parens to those functions when `mix format`ing
Original PR https://github.com/phoenixframework/phoenix_live_view/pull/3535
> Add LiveViewTest.assert_* macros to locals_without_parens config

- installer/lib/phx_new/generator.ex
To keep the same pattern used in the `gen.secret` task. See https://github.com/phoenixframework/phoenix/commit/2c9fc8512065ae36a83b3479fba9ef9ca4c479b1
> Add `padding: false` to `Base.encode64/2` in New generator

- lib/mix/tasks/phx.gen.live.ex
- test/mix/tasks/phx.gen.live_test.exs
Fixes https://github.com/phoenixframework/phoenix/issues/5871
> raise when using form as schema name in phx.gen.live

- lib/phoenix/code_reloader/server.ex
This reverts commit 0f9628a and improves the error message.
@josevalim should we backport?
> revert code reloader changed file detection

- installer/templates/phx_single/config/dev.exs
- installer/templates/phx_umbrella/config/dev.exs
Closes https://github.com/phoenixframework/phoenix_live_view/issues/3565.
> Add note about changing debug_heex_annotations to config

- guides/asset_management.md
- installer/templates/phx_single/config/config.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/config.exs
> change es2017 to es2022 in asset management guide

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.html/index.html.heex
- priv/templates/phx.gen.html/show.html.heex
- priv/templates/phx.gen.live/core_components.ex
- priv/templates/phx.gen.live/index.ex
- priv/templates/phx.gen.live/show.ex
Buttons and Links must not be nested inside each other, otherwise there are accessibility issues. A previous PR did not fix the problem, but just inverted the problem.
Adds a helper function to return button_classes for styling other components, like links.
Fixes #5770.
Relates to: #5820
> add button_classes to CoreComponents

- lib/mix/tasks/phx.gen.context.ex
- test/mix/tasks/phx.gen.context_test.exs
fixes #6080 
first time contributing to Phoenix, so I hope I got it right ^^
> Allow skipping migration when generating context with `--no-migration`

- assets/js/phoenix/ajax.js
- assets/js/phoenix/constants.js
- assets/js/phoenix/longpoll.js
- assets/js/phoenix/socket.js
- assets/test/channel_test.js
- guides/real_time/channels.md
- lib/phoenix/endpoint.ex
- lib/phoenix/socket/transport.ex
- lib/phoenix/transports/long_poll.ex
- lib/phoenix/transports/websocket.ex
For WebSocket, the `Sec-WebSocket-Protocol` header is used. For LongPoll, an `Authorization` header is passed instead.
Fixes https://github.com/phoenixframework/phoenix/issues/5778.
> Support transport agnostic token passing in channels

- installer/templates/phx_single/lib/app_name/application.ex
- installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex
- installer/test/phx_new_test.exs
- installer/test/phx_new_umbrella_test.exs
fixes #5945 
The wording of the code comment implies the opposite of what the function actually does.
I aligned the code with the comment. Can also do it the other way around if needed.
> align sqlite migration code with comment

- lib/phoenix/verified_routes.ex
https://hex.pm/packages/cldr_routes is a 404. Should be https://hex.pm/packages/ex_cldr_routes
> Fix ex_cldr_routes URL

- installer/templates/phx_assets/app.css
- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.live/core_components.ex
also fixes table border not showing on hover
Relates to: https://github.com/phoenixframework/phoenix/pull/5013
Relates to: https://github.com/phoenixframework/phoenix/pull/5250
Relates to: https://github.com/phoenixframework/phoenix/issues/5852
This is technically the same as https://github.com/phoenixframework/phoenix/pull/5250, but I think it is much more readable when we extract the styling of the pseudo elements into the app.css instead.
cc @LostKobrakai
> fix rounded corners when no actions are provided

- lib/phoenix/socket/transport.ex
- test/phoenix/integration/websocket_channels_test.exs
Supersedes https://github.com/phoenixframework/phoenix/pull/5904.
> WebSockets: support passing through sec-websocket headers

- guides/authn_authz/api_authentication.md
Improve API, if only by a tiny amount, by removing case sensitivity of the token's "Bearer" prefix. HTTP/1.1 Authentication specifies that [a case-insensitive token be used](https://datatracker.ietf.org/doc/html/rfc7235#section-2.1).
Somewhat related, I think that [OAuth 2.0 RFC using (uppercase) "Bearer" in its example](https://datatracker.ietf.org/doc/html/rfc6750#section-2.1) doesn't necessarily mean that the _implementation_  must also be case sensitive since the example is written in ABNF notation, which [is case insensitive](https://www.rfc-editor.org/rfc/rfc5234#page-5).
Performance of the current vs the proposed version seems to be equivalent:
```
Operating System: macOS
CPU Information: Apple M3 Pro
Number of Available Cores: 11
Available memory: 18 GB
Elixir 1.18.2
Erlang 27.2.3 …
```
> Allow case-insensitive token type

- lib/phoenix/code_reloader/server.ex
When starting, the code reloader checks if _build/dev/myapp/priv is a symlink or hard copy. It may be a hard copy on Windows, if Mix cannot create a symlink. To allow symlinks, it may be necessary to run the terminal as Administrator at least once. So, if it is a hard copy, reloader removes _build/dev/myapp/priv and lets Mix recreate it, possibly creating a symlink. The main reason is that making hard copy on each recompilation is slow on Windows.
The above assumes that there exists priv/ at the top level and is either symlinked or copied. However, it is possible that _build/dev/myapp/priv is created directly. If that's the case, if the reloader removes it (as it does currently), it is just missing altogether. This PR fixes it by checking if the top level priv/ exists before deleting the …
> Change reloader to not remove priv if it is not a copy

- installer/templates/phx_single/config/dev.exs
- installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
When not in the docker container, the current code produces
```elixir
config :foo, FooWeb.Endpoint,# Binding to loopback ipv4 address prevents access from other machines.
```
which turns to the following.
```elixir
config :foo, FooWeb.Endpoint,
```
To keep the comment on the next line, add new line after else.
> Fix endpoint binding comment location in installer templates

- lib/phoenix/router.ex
- lib/phoenix/router/console_formatter.ex
- lib/phoenix/verified_routes.ex
This comes with two parts:
- These routes are expanded when printing routes using `mix phx.routes`. I've added an additional `label` metadata which is extremely useful for things like `AshJsonApi` to display the resource & action being routed to
- verified routes logic has been modified to match these expanded routes as well. 
I've tested manually and it works well, but I will of course add tests for this logic if this kind of thing seems like a good idea to the team.
Original ElixirForum discussion: https://elixirforum.com/t/allow-forwarded-to-plugs-to-have-a-callback-that-returns-additional-routes/65365/2
I had to use `Code.ensure_compiled/1` on the nested plug, which I couldn't find a good way around but I'm open to ideas on (open to ideas on the whole implementation).
One note is that …
> Add `Phoenix.VerifiedRoutes` behaviour for custom routers

- lib/phoenix/router.ex
- test/mix/tasks/phx.routes_test.exs
- test/phoenix/verified_routes_test.exs
@zachdaniel I needed to make a little adjustment. While the type for formatted_route defines verb, path and label
```elixir
@type formatted_route :: %{
required(:verb) => String.t(),
required(:path) => String.t(),
required(:label) => String.t()
}
```
The code expected plug_opts instead and didn't handle the label. I believe this was just an oversight, but please double check.
> add test for new verified routes behavior for mix phx.routes

- lib/phoenix/controller.ex
- test/phoenix/controller/controller_test.exs
We have an app that is getting a lot of AlreadySentErrors. Likely somewhere we have missed an `halt()`, but tracking that down is tricky. I wonder if we could supply some more information in the various places the error gets raised to help someone debug the issue? I have supplied a small example, but the exact wording and contents can be discussed.
I'm happy to roll this out to more places if we agree it's a good idea.
> Include more information on AlreadySentError errors

- CHANGELOG.md
Specifying layouts without module is now deprecated (See #6132). However the changelog incorrectly states that layouts with modules are deprecated.
> Correct wording of layouts without modules deprecation

- guides/plug.md
The rest of the guide here uses _you_, so this felt out-of-place.
Before:
> Go to http://localhost:4000/ and you should see the locale exhibited. Visit http://localhost:4000/?locale=fr and you should see the assign changed to "fr". Someone can use this information alongside [Gettext](https://hexdocs.pm/gettext/Gettext.html) to provide a fully internationalized web application.
After:
> Go to http://localhost:4000/ and you should see the locale exhibited. Visit http://localhost:4000/?locale=fr and you should see the assign changed to "fr". You can use this information alongside [Gettext](https://hexdocs.pm/gettext/Gettext.html) to provide a fully internationalized web application.
> tiny documentation update: (Someone -> You)

- .gitignore
- installer/.gitignore
- installer/mix.exs
- installer/templates/phx_web/components/core_components.ex
- installer/test/phx_new_test.exs
- mix.exs
- test/mix/tasks/phx.gen.live_test.exs
Fixes #6154
It also includes the core_components file in the Phoenix archive, therefore the copy should always succeed. We can also use `cp` instead of `cp!` and not include it in the archive, as it should have already been copied prior to building the archive.
> invert copy_core_component

- installer/recreate_default_css.exs
* There is no more "themes: all;" in the target CSS file, so `String.replace/3` is a no-op. The default theme config was changed in 6da42953c4e7d94e7666fa0584b29fc4e35fc465 (#6147)
* installer/templates/phx_static/default.css is up-to-date, last updated in cc5c7af03507710952c6c73a27f02e7fb6a70d3f
> Remove no-op lines from recreate_default_css script

- guides/authn_authz/scopes.md
Document a not-so-obvious step of adding the :assign_org_to_scope hook to the router.
> Improve scopes documentation for on_mount hooks

- priv/templates/phx.gen.auth/scope.ex
Truth be told, I'm not entirely sure if it's really a mistake in the docs, or it's a mistake in the module name. Or a mistake in my understanding of scopes. Please do check my understanding - I wrote a rather verbose commit message just to be clear.
> Fix wrong module name in Scope moduledoc

- guides/data_modelling/cross_context_boundaries.md
While going through the docs, I noticed that the command to generate the auth code is slightly different than the previous version - the name of the user's table is not in the plural. This PR fixes this detail.
> Adjust the User table name to be plural in Cross Context Boundaries

- priv/templates/phx.gen.auth/auth.ex
- priv/templates/phx.gen.auth/auth_test.exs
When re-authenticating to access a sudo-mode protected page, the existing session would be cleared, invalidating the existing CSRF token. This meant that any open tab with in-progress forms would be invalidated. Now, we just put the new token into the session, keeping the same session id + CSRF token.
> do not create a new session on sudo mode re-auth

- installer/templates/phx_web/components/core_components.ex
Removes compiler warning when a generated `CoreComponents.button` is wrapping a `Phoenix.Component.link` with a `method` attribute.
Resolves #6172
> Add method to global attributes for generated button core component

- guides/controllers.md
- installer/templates/phx_web/controllers/page_controller.ex
Since the generators are no longer defining dynamic layouts with put_layout or in use Phoenix.Controller (since https://github.com/phoenixframework/phoenix/pull/6136/files ), I think there's no need for explicitly disabling the layout in the PageController in the installer or guides
> Do not specify layout: false in PageController examples

- lib/mix/tasks/phx.gen.auth.ex
- priv/templates/phx.gen.auth/auth.ex
- priv/templates/phx.gen.auth/auth_test.exs
- priv/templates/phx.gen.auth/conn_case.exs
- priv/templates/phx.gen.auth/context_fixtures_functions.ex
- priv/templates/phx.gen.auth/context_functions.ex
- priv/templates/phx.gen.auth/migration.ex
- priv/templates/phx.gen.auth/schema_token.ex
- priv/templates/phx.gen.auth/settings_controller_test.exs
- priv/templates/phx.gen.auth/settings_live_test.exs
- priv/templates/phx.gen.auth/test_cases.exs
The auth code currently generated by mix phx.gen.auth generates tokens with a fixed expiration of 60 days. Unless a user logs in again, they will never get a new token. Once that token expires, they are forced to log in again. This could happen in the middle of a session, such as while they are filling out a form, causing them to lose their submission when the POST redirects them to log in again.
This PR fixes this by issuing a new token automatically to valid sessions that are using a token more than 7 days old.
With this new refresh mechanism, tokens now expired after 14 days instead of the old default of 60. Shorter lived tokens decrease the window of possible abuse if the token is exfiltrated somehow, such as from a backup of a browser cookie store.
Both the token life and reissue age …
> Reissue new tokens periodically in phx.gen.auth code.

- installer/templates/phx_web/components/layouts.ex
Before:
After:
Also adds `cursor: pointer` to those buttons.
> small adjustments for theme switcher

- lib/phoenix/code_reloader.ex
- test/phoenix/code_reloader_test.exs
The code reloader capture the output of mix compile tasks and shows it directly on the exception page. When the output includes ANSI escapes for coloring they are left as is:
This adds a simple regex pass to remove them.
> Do not show ANSI escape codes on exception pages

- installer/templates/phx_assets/app.css
Based on documentation from:
* https://tailwindcss.com/docs/adding-custom-styles#adding-custom-variants
* https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually
And a comment at:
* https://github.com/phoenixframework/phoenix/pull/6109#discussion_r1984001238
> fix: Fix Tailwind custom variants for loading classes

- installer/templates/phx_assets/app.css
- installer/templates/phx_static/default.css
Closes https://github.com/phoenixframework/phoenix/issues/6188.
`[data-phx-session]` is more appropriate, since the session attribute is already included in the disconnected render.
> use data-phx-session as selector for LV containers

- priv/templates/phx.gen.auth/schema.ex
- test/mix/tasks/phx.gen.auth_test.exs
We can do that because new apps require Elixir 1.15+.
> phx.gen.auth: Replace `utc_now/0 + truncate/1` with `utc_now/1`

- installer/templates/phx_assets/app.css
- installer/templates/phx_static/default.css
> Use better styling for errors on light theme

- installer/templates/phx_web/components/layouts.ex
The `#server-error` was targeting `.phx-client-error #client-error`
> Fix server-error css selector

- installer/templates/phx_static/default.css
- installer/templates/phx_web/components/core_components.ex
- installer/templates/phx_web/components/layouts.ex
- priv/templates/phx.gen.auth/login_live.ex
- priv/templates/phx.gen.auth/session_new.html.heex
Before, only some of them were outline, sometimes
the same icon was used in different styles.
We also use size-x more consistently.
Closes #6192.
> Apply icons and sizes more consistently.

- installer/templates/phx_web/components/layouts.ex
Add w-fit to logo to limit is clickable area
Currently, the logo’s anchor tag in the header spans the full width, resulting in an invisible but clickable area. This could lead to unexpected behavior and poor UX. By restricting the anchor tag’s size using w-fit, it now only spans its actual content.
Before:
Entire header area is clickable (even outside the logo)
with red background for demonstation
After:
Only the logo itself is clickable (no excess clickable area, no pointer cursor outside the logo)
(with red background for demonstation)
> Add w-fit to logo to limit is clickable area

- priv/templates/phx.gen.live/index.ex
- priv/templates/phx.gen.live/show.ex
Originally reported: https://elixirforum.com/t/phoenix-1-8-0-rc-0-released/70256/96
This was an oversight. We don't want to subscribe on the disconnected render, because a webserver like Bandit can reuse processes.
> only subscribe if connected

- guides/data_modelling/cross_context_boundaries.md
Updates the cross-context boundaries guide to improve the handling of attributes in the `cart_item` changeset and clarifies the rationale behind these changes in the documentation.
Closes #6217.
> discard price user input in cross-context boundaries guide

- assets/js/phoenix/ajax.js
- assets/test/longpoll_test.js
Hi, we noticed that when opening a socket in a ServiceWorker and using `LongPoll`, the socket fails because neither `XMLHTTPRequest` or `XDomainRequest` are available in the ServiceWorker scope.
I realise this is a bit of an edge case, as if you have ServiceWorker support, you probably already have native `WebSocket` support. In our instance, we sometimes fall back to LongPoll when network conditions block connections.
To work around this, I've added support for using `fetch`, which is in the global scope of a ServiceWorker. To ensure we don't break any existing setups, `LongPoll` requests still prefer `XDomainRequest` and `XMLHTTPRequest` in the same ordering as before; this only acts as a fallback when neither are available.
> Add fetch() support to LongPoll when XMLHTTPRequest is not available

- lib/phoenix/endpoint.ex
Disable logging as described here https://github.com/phoenixframework/phoenix_live_view/issues/617 no longer works on 1.8 rc.
```
== Compilation error in file lib/myapp_web/endpoint.ex ==
** (ArgumentError) unknown keys [:log] in [connect_info: [session: [store: :cookie, key: "_myapp_key", signing_salt: "zuUbpEkB", same_site: "Lax"]], log: false], the allowed keys are: [:path, :serializer, :transport_log, :check_origin, :check_csrf, :code_reloader, :connect_info, :auth_token, :timeout, :max_frame_size, :fullsweep_after, :compress, :subprotocols, :error_handler]
(elixir 1.18.3) lib/keyword.ex:362: Keyword.validate!/2
(phoenix 1.8.0-rc.3) lib/phoenix/endpoint.ex:718: Phoenix.Endpoint.socket_paths/4
(phoenix 1.8.0-rc.3) lib/phoenix/endpoint.ex:648: anonymous fn/3 in …
```
> add `:log` to `common_config`

- guides/real_time/channels.md
- guides/real_time/presence.md
- priv/templates/phx.gen.socket/socket.js
- test/mix/tasks/phx.gen.socket_test.exs
Removes outdated token authentication documentation from the generated `socket.js` file from `phx.gen.socket`. Instead, it reduces the maintenance of the generator by providing a link to the token authentication section in the guides.
Also, redacts the rest of the docs to reference the new method for authenticating.
Closes #6241.
> use single source of truth for socket token authn docs

- guides/request_lifecycle.md
This PR improves documentation clarity and grammar:
- Corrects article usage ("a HTTP" → "**an** HTTP")
- Replaces period with colon for correct punctuation (“like this.” → “**like this:**”)
- Fixes the formatting of “Cross-Site-Scripting” to “Cross-Site Scripting” for proper terminology
- Adds a missing comma for readability
> Minor grammar/typo fixes in request_lifecycle.md

- guides/data_modelling/cross_context_boundaries.md
Ran into some errors while going through the context guides in `1.8.0-rc.3` along with an update to a diff section that looked old.
> Fixes to Cross-context Boundaries guide

- guides/authn_authz/mix_phx_gen_auth.md
In this case, I believe we want the verb `log in` and not the adjective `login`.
> Update guide file: mix_phx_gen_auth.md (`login` vs `log in` change)

- priv/templates/phx.gen.auth/auth.ex
> Update `phx.gen.auth` template for `auth.ex` (fixes typo code comment)

- lib/phoenix/logger.ex
- lib/phoenix/socket/message.ex
- test/phoenix/socket/message_test.exs
Its very possible we don't want to do this way, but I think sharing the implementation of a possible fix is valuable.
The `Last Message` on a GenServer crash can display the values from a form submit, which will not have Phoenix's parameter filtering logic applied to the `"value"` string. This was reported by a user of mine when submitting a form that takes a password.
What I've done here is just a very naive match on this specific pattern of socket message to scrub values in the inspect protocol. The issue with this is that we're lifting a LV concern to a Phoenix concern potentially. Since all we are doing is scrubbing values that are configured for scrubbing, this seems safe enough to me to make a PR.
I'm happy if this is just a discussion starter and maybe we figure some other way out …
> Scrub `payload["value"]` for LiveView form submit events

- guides/routing.md
The [verified routes](https://hexdocs.pm/phoenix/Phoenix.VerifiedRoutes.html) documentation contains "Or as a keyword list or map of values:" whereas the [routing](https://hexdocs.pm/phoenix/routing.html#more-on-verified-routes) documentation only specifies either a query string or "dictionary of key-value pairs".
The intent of this PR is to clarify what is acceptable as a query parameter and reflect what is documented in the verified routes guide.
> Include maps in the verified routes section of the routing guide

- guides/data_modelling/contexts.md
- guides/introduction/up_and_running.md
This allows the commands to be copied correctly. The leading `>` has been removed so that it isn't included in the copied output.
This fixes #6281
> Use `bash` for syntax highlighting of windows commands

- lib/mix/tasks/phx.gen.auth.ex
Closes https://github.com/phoenixframework/phoenix/issues/6249.
> warn when using phx.gen.auth without esbuild

- guides/introduction/community.md
- guides/security.md
- mix.exs
This PR adds a security documentation page. I checked with @chrismccord and got approval to write all this up and submit here. My goal with the documentation is to:
- Explain the scenarios that are most likely to lead to a security incident for a Phoenix developer
- Provide examples of unsafe vs safe code 
- Enable readers to quickly check their own projects, for example with SSRF a developer's reaction could be - "We are making HTTP requests but we never use user input to craft the URLs so we are good there"
There are of course more areas that can be documented (Cross site websocket hijacking, atom DoS, etc), which I'd like to add in the future. 
Please let me know if I made an errors when opening this PR that need to be fixed, it's my first contribution to Phoenix and I did my best to …
> Security docs

- assets/js/phoenix/index.js
> Fix missing examples

- priv/templates/phx.gen.auth/schema.ex
- priv/templates/phx.gen.auth/settings_live.ex
The code also validates if the email changed but I think adding uniqueness to the option is good enough?
> Provide better name for validate_email option

- priv/templates/phx.gen.auth/schema.ex
When the `--binary-id` option is used with `phx.gen.auth`, the generated schema file was missing a blank line between the `import Ecto.Changeset` and the `@primary_key` declaration.
The new placing of the `<%= if ... do %>...<% end %>` construct matches how it is done in the `schema_token.ex` template file.
> Fix missing newline in phx.gen.auth template

- lib/mix/tasks/phx.gen.auth.ex
- lib/mix/tasks/phx.gen.html.ex
- lib/mix/tasks/phx.gen.json.ex
- lib/mix/tasks/phx.gen.live.ex
- test/mix/tasks/phx.gen.auth_test.exs
- test/mix/tasks/phx.gen.html_test.exs
- test/mix/tasks/phx.gen.json_test.exs
- test/mix/tasks/phx.gen.live_test.exs
After running `mix phx.gen.auth` and reviewing the generated code, I noticed that it added the `as: :some_name` option to the `scope` macro in the router.
This option is not there on new projects, and `:as` is documented to have no effect when using Verified Routes (which phx.new uses).
Considering the Router Helpers deprecation status, this commit removes the `as: :some_name` option from the generated code.
It does mean someone using the modern generators within a project using Helpers would have to manually add the `as: :some_name` option if they want to have a `some_name_path` function.
> Remove deprecated route names from phx.gen.* templates

- installer/templates/phx_assets/app.css
The Theme Switcher [root.html.heex](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/layouts/root.html.heex) uses the `data-theme` attribute to toggle between light/dark themes. 
Tailwind's `dark:` variant expects per default a `class="dark"` though.
This custom variant makes Tailwind's `dark:` work with `data-theme="dark"`.
`@custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));`
Without this, the `dark:` utility will not work, even DaisyUI themes switch correctly.
👉 Reference: https://tailwindcss.com/docs/dark-mode#using-a-data-attribute
> Enable Tailwind `dark:` with data-theme attribute

- installer/templates/phx_web/components/core_components.ex
- priv/templates/phx.gen.auth/context_functions.ex
When reviewing generated code, I noticed that some docstrings used `~S` unnecessarily.
The case for `@doc ~S"""` is when examples or prose contain backslashes or `#{...}` interpolation, which is not the case here.
> Remove sigil_S from docstrings in templates

- guides/security.md
Fixes the text rendering errors on https://hexdocs.pm/phoenix/1.8.0-rc.4/security.html
Attached is a screenshot showing the current error.
> Fix security docs text rendering

- guides/data_modelling/cross_context_boundaries.md
- guides/data_modelling/in_context_relationships.md
- guides/data_modelling/your_first_context.md
I went through the context guides again in `rc4` to check on my changes in `rc3`. A minor cause of confusion I missed last time was the current context generators not having a default `attrs` for the create function.
This change removes the default `attrs` from snippets that show the default create function of a context.
> Guides: Removes default arg for context create functions

- guides/request_lifecycle.md
Hello,
I found 2 minor typos while following the guide on Request life cycle.
I’ve followed contributing guidelines recommended process for this pull request.
> Fix minor typos in guide request_lifecycle

- mix.exs
Changes JS documentation link in the sidebar from `/js/` to `js/index.html` which works both for online and offline (the file:// protocol) use cases.
**Context**
The link that was added via https://github.com/phoenixframework/phoenix/pull/6247 results in the following href `<a href="/js/">JS Documentation</a>` which when clicked leads to `https://hexdocs.pm/js/` at [hexdocs](https://hexdocs.pm/phoenix/1.8.0-rc.4) and `file:///js/` locally.
**How to test the change**
- Locally, run `mix docs -f html`. Open the docs. Click the "JS documentation" external link and see if it opens the JS documentation page.
- For [Hexdocs](https://hexdocs.pm/phoenix/1.8.0-rc.4/overview.html), open DevTools and manually edit the `href` attribute to be `js/index.html` and then click on it. It should lead to the …
> Use relative path for JS doc link

- lib/mix/tasks/phx.gen.ex
I’ve been maintaining a Phoenix app since version 1.6. When we upgraded to Phoenix 1.7 to adopt LiveView, I often used the phx.gen.live generator. However, I always had to manually edit the generated files to match our internal style and UI structure, which became tedious over time. 
Recently, while exploring Phoenix 1.8 RC-1, I noticed changes in the generators, including the deprecation of the form_component, which I really liked for its more SPA-like behavior in earlier versions. 
While reading through some documentation, I stumbled upon a blog post explaining how to customize Phoenix generators. That was a eureka moment. I realized I could avoid all those repeated edits by overriding the templates once and letting the generator produce code that matches our conventions out of the box. …
> Add guide for live_view generator customization

- installer/templates/phx_assets/tsconfig.json
Closes https://github.com/phoenixframework/phoenix/issues/6391.
> don't include node_modules in tsconfig path mapping

- guides/data_modelling/cross_context_boundaries.md
- guides/data_modelling/in_context_relationships.md
- guides/data_modelling/more_examples.md
- guides/data_modelling/your_first_context.md
- guides/ecto.md
- guides/security.md
This PR updates the data modeling guide to align with the current Phoenix generator default and replaces deprecated usage of `Repo.transaction/2`.
- replace `Repo.transaction/2` with `Repo.transact/2`
- update `timestamps()` to `timestamps(type: :utc_datetime)`
> Update data modelling guide and ecto guide

- installer/templates/phx_single/config/config.exs
- installer/templates/phx_single/config/prod.exs
- installer/templates/phx_umbrella/apps/app_name/config/config.exs
- installer/templates/phx_umbrella/config/extra_config.exs
- installer/templates/phx_umbrella/config/prod.exs
The installer creates config files that mostly use the imperative mood but are oddly inconsistent:
`installer/templates/phx_single/config/config.exs`:
> \# **Configures** the mailer
> \# Configure esbuild (the version is required)
> \# Configure tailwind (the version is required)
> \# **Configures** Elixir's Logger
`installer/templates/phx_single/config/prod.exs`:
> \# **Configures** Swoosh API Client
> \# Disable Swoosh Local Memory Storage
> \# Do not print debug messages in production
`installer/templates/phx_single/config/dev.exs`:
> \# Watch static and templates
> \# Enable dev routes
> \# Do not include metadata
> \# Set a higher stacktrace
> \# Initialize plugs at runtime
> \# Disable swoosh api client
I suggest sticking to imperative mood for consistency
> Fix comments in installer config

- guides/asset_management.md
- installer/templates/phx_web/components/core_components.ex
This pull request broadens the accepted type for the class attribute to better reflect its actual usage and improve component flexibility.
Currently, the type is too restrictive, which leads to unnecessary warnings for perfectly valid cases like:
```elixir
<.icon name="hero-x-mark" class={[@condition && "foo", "bar"]} />
```
The tag engine supports class values as:
- strings
- lists of strings, false, or nil
- nested lists of these values
By widening the type, we align the type spec with real behavior, eliminate false warnings, and allow more flexible component usage.
> Class attribute type

- guides/authn_authz/scopes.md
Changes
- Updated route prefix from /orgs/:org → /organizations/:org
- Added route_access_path example using slug, ensuring generators create LiveView routes correctly with slugs instead of IDs
- Fixed unused user variable in test helper
Rationale
The route prefix was updated to /organizations for consistency with Phoenix generators. This ensures alignment with generated code and prevents discrepancies that could confuse new developers.
Additionally, the route_access_path example was adjusted to use slugs, which is required for generators to build correct LiveView routes without falling back to IDs.
> update scope documentation and config examples

- lib/phoenix/channel.ex
A minor typo: `send(self, :after_join)` -> `send(self(), :after_join)`
> Fix missing () in error message's suggestion

- lib/mix/phoenix/schema.ex
- test/mix/tasks/phx.gen.context_test.exs
- test/mix/tasks/phx.gen.schema_test.exs
This PR resolves #6377 
When you have a scope and you try to generate a schema (or context), the field will be duplicated.
```
mix phx.gen.context Blog Post posts title:string user_id:references:users
```
The generated schema will look like:
```
defmodule MyApp.Blog.Post do
use Ecto.Schema
import Ecto.Changeset
@primary_key {:id, :binary_id, autogenerate: true}
@foreign_key_type :binary_id
schema "posts" do
field :title, :string
field :user_id, :binary_id
field :user_id, :binary_id
...
end
...
end
```
As @josevalim suggested on the issue #6377, the generation will raise when there's conflict between the scope and the reference.
I'm not sure if the error message I'm displaying is meaningful enough. Please let me know if you have suggestions. :)
> Raise when a reference conflicts with the scope on schema generation

- lib/mix/phoenix/scope.ex
Very minor improvement
The examples for `route_prefix/2` is still using what I assume the old function name.
> Fix examples for route_prefix/2

- installer/templates/phx_web/components/core_components.ex
Removed in https://github.com/phoenixframework/phoenix/commit/712ad7ede061b4716d6b17fc3b6bb7e4858d5ebe, but it is useful not having to write `@field[:name].value` etc. and AI also makes mistakes there.
Closes https://github.com/phoenixframework/phoenix/pull/6389.
> Re-add support for hidden inputs

- installer/templates/phx_web/endpoint.ex
Configure Plug.Static with raise_on_missing_only: code_reloading?() to help developers catch missing entries in static_paths() during development. This prevents the common trap where files like favicon.svg return 404 because they aren't properly declared in the :only list (often because they digested paths).
Part of the fix for: https://github.com/phoenixframework/phoenix/issues/6203
Requires: https://github.com/elixir-plug/plug/pull/1286
> Enable raise_on_missing_only in development

- installer/templates/phx_web/components/core_components.ex
The use case is to support checkboxes outside the <.form /> element. One needs the `form` attribute on the shadow input. Otherwise, you end up with inconsistent behavior.
```elixir
<.input type="checkbox" form={@form.id} field={@form[:active]} />
<.form for={@form} id={@form.id}></.form>
```
We've been using this in production for a few months without issue. I'm happy to make adjustments if there are concerns about passing all of `rest` to that input.
> Update checkbox input

- installer/templates/phx_single/mix.exs
- installer/templates/phx_umbrella/mix.exs
Corrects `mix compile` flag in precommit task from `--warning-as-errors` to `--warnings-as-errors`
> Fix precommit task to use correct --warnings-as-errors flag
