phoenixframework/phoenix

lib/phoenix/code_reloader.ex
lib/phoenix/code_reloader/server.ex
priv/template/config/dev.exs
test/phoenix/code_reloader_test.exs

This PR addresses https://github.com/phoenixframework/phoenix/issues/581
Adds `:reloadable_paths` Endpoint config that is set to `["--elixirc-paths", "web"]` by default in dev.exs.

Reloadable paths config for Code Reloader

---

README.md

Roadmap section in README is already removed by @chrismccord's commit:
https://github.com/phoenixframework/phoenix/commit/8ae36a9ff791008ff5448554d73211807fd576f9

remove obsolete roadmap link

---

lib/phoenix/endpoint/adapter.ex
lib/phoenix/endpoint/cowboy_websocket.ex
lib/phoenix/transports/websocket.ex

Cowboy websockets can be initialized with a maximum timeout time. Until now, this has been left to be the default setting, meaning no timeout at all, since cowboy websockets assume `:infinity` as default.
This PR adds an optional endpoint transport configuration setting `websocket_timeout` that specifies the timeout to be used in milliseconds.
Doesn't break backwards-compatibility.
~cheers, Johanna.

Make websocket timeout configurable

---

lib/phoenix/router.ex
lib/phoenix/router/resource.ex
test/phoenix/router/helpers_test.exs
test/phoenix/router/resource_test.exs

Adds the ability to define a set of routes that wont require an index action or an ID parameter in the path.
Example:
```elixir
resource "/session", SessionsController
```
Will generate the following routes:
* `GET /session` => `:show`
* `GET /session/new` => `:new`
* `POST /session` => `:create`
* `GET /session/edit` => `:edit`
* `PATCH /session` => `:update`
* `PUT /session` => `:update`
* `DELETE /session` => `:delete`

Added `Router.resource` for defining a singular resource

---

priv/template/config/prod.exs

It might be a rookie mistake, but I honestly spent 10 minutes trying to find where the `https` setting was going. In retrospect, it was caused by the order of the example code.

Making more obvious the https setting

---

lib/phoenix/endpoint/server.ex

This PR attempts to make tracking down port number related bugs a little bit easier when deploying the application by raising a descriptive error. By default the prod environment uses only an environment variable to get the port, but if that variable doesn't exist the config's port is set to nil. This causes a no function clause matching error when starting the app.

Raise an error when the port number in the config is nil.

---

lib/mix/tasks/phoenix.new.ex
test/mix/tasks/phoenix/new_test.exs

Hello,
I believe I successfully implemented this feature, but I have some problems writing a successful test; after some refactorings it should pass, but it fails with this error:
```
> mix test test/mix/tasks/phoenix/new_test.exs
Compiled lib/mix/tasks/phoenix.new.ex
Generated phoenix.app
.
1) test two arguments (both name and path arguments) (Mix.Tasks.Phoenix.NewTest)
test/mix/tasks/phoenix/new_test.exs:48
Expected .gitignore to exist, but does not
stacktrace:
test/mix/tasks/phoenix/new_test.exs:63: anonymous fn/0 in Mix.Tasks.Phoenix.NewTest.creates_files_and_directories/1
(elixir) lib/file.ex:1061: File.cd!/2
test/mix/tasks/phoenix/new_test.exs:57
.
Finished in 1.0 seconds (0.2s on load, 0.8s on tests)
3 tests, 1 failures
Randomized with seed 787097
```

Allow project creation omitting project directory

---

lib/phoenix/router.ex

There is an example of route globbing within the channel section, but the pattern is different for controllers. Routes with a glob need to be followed by a word value, like `*other`. This took a few tries for me to figure out and I didn't see it documented anywhere.

Add documentation about route globbing

---

lib/phoenix/controller/logger.ex
test/phoenix/controller/logger_test.exs

Changing the log level to info exposes helpful information like request params in production. Talk about a simple change! As discussed in phoenixframework/phoenix/issues/651

Set controller logger mode to info

---

lib/phoenix/code_reloader.ex

if the response has no content type, get_resp_header returns an empty list which hd does not like. This PR handles this situation.

handle the case when the response has no content type

---

lib/phoenix/channel.ex

Socket was misspelled in the channel documentation.

Fix typo in channel documentation

---

lib/phoenix/html/form.ex

This trivial change should make it slightly easier to make a proper form struct at a glance.

More precise type spec for Form struct

---

lib/phoenix/html/link.ex
test/phoenix/html/link_test.exs

Add support for `button` link helper to create navigation buttons to
destructive actions. This provides an alternative to link/2 which
can have accessibility issues as it requires JavaScript. Also prevents
web spidering software from following links to potentially destructive
actions.

Add `button/2` to HTML link helpers

---

lib/phoenix/controller.ex
test/phoenix/controller_test.exs

As discussed in IRC:
`Phoenix.Controller.render/3`, `Phoenix.Controller.json/2`, `Phoenix.Controller.text/2` and `Phoenix.Controller.html/2` overwrite the `content-type` header if set.
We should only add the default headers if it's not set already.

Only add content type if not set

---

lib/mix/tasks/phoenix.new.ex

Today the wording is confusing as it says brunch was set up, when in fact it was not.

Fix wording when `--no-brunch` is passed to phoenix.new

---

lib/phoenix/html/form.ex
lib/phoenix/html/tag.ex
test/phoenix/html/form_test.exs

Hi guys, thanks for the awesome work in phoenix framework.
While updating to phoenix 0.10.0, and updating the html to use the new form helpers, I noticed that there is no `textarea` tag. Is there any reason for not include this one?
Thanks in advance!

textarea tag?

---

CHANGELOG.md
lib/phoenix/endpoint.ex
lib/phoenix/endpoint/adapter.ex
lib/phoenix/router/live_reloader.ex
priv/templates/new/config/dev.exs
test/phoenix/code_reloader_test.exs

Live reload doesn't work when using [pow](http://pow.cx) in development. Pow
doesn't work with websockets, so it just throws errors in the console.
I propose adding a `live_reload_host` option that can be set to
`ws://localhost:4000` in order to work around this issue.
This is just a quick hack, so I'm open to suggestions.
If we are cool with this, I'll add documentation.

Allow host to be configured for live_reload

---

lib/phoenix/controller.ex
test/phoenix/controller_test.exs

It's easy to think that the layout and view is set when calling `plug :action` in a controller so people (myself included) put their plugs below `plug :action` and then wonder why `put_layout` and friends don't work as expected. In reality the view and layout are set when you call `use Phoenix.Controller` so user's plugs should go above `plug :action` if you're working with the view or layout (and in most other cases too).
This PR makes it so that when you call `put_layout`, `put_new_layout`, `put_view`, `put_new_view` and `put_layout_formats` on a conn that was already sent, you get a friendly error instead of wondering why the wrong view/layout was rendered.

Friendly plugs - raise AlreadySentError when calling layout functions on sent conn

---

installer/templates/new/mix.exs

I found a problem to build [in this way](http://www.phoenixframework.org/v0.10.0/docs/advanced-deployment).
I think it's up to lack of some dependencies to build by exrm.
So, I added some dependencies. Please check out my code.

Add some dependencies to build by exrm

---

lib/phoenix/html/tag.ex
test/phoenix/html/form_test.exs
test/phoenix/html/tag_test.exs

The reasoning is that `false` is excluded so `nil` should be also.

Exclude nil value attributes from tags

---

installer/templates/new/mix.exs
lib/phoenix/channel.ex
lib/phoenix/channel/server.ex
lib/phoenix/channel/transport.ex
lib/phoenix/socket.ex
lib/phoenix/socket/message.ex
lib/phoenix/transports/long_poller/server.ex
lib/phoenix/transports/websocket.ex
priv/static/phoenix.js
test/phoenix/channel_test.exs
test/phoenix/integration/channel_test.exs
test/phoenix/integration/websocket_client.exs
test/phoenix/socket/message_test.exs
test/phoenix/transports/json_serializer_test.exs
test/phoenix/transports/long_poller_test.exs
web/static/js/phoenix.js

We've overhauled the channel API to allow "synchronous" messaging, and I really love the results. By synchronous, I mean being able to reply to an incoming event directly, while ensuring messaging ordering for the same incoming events. This not only lets you do proper request/response messaging where necessary, but it also fixes issues we have in our <= 0.10 apis where joins were not synchronous and messages could be dropped if you fired them before you were fully joined. With these changes, we have a few high-level concepts which make up channels:
1. The client and server push messages down the socket to communicate
2. The server can reply directly to a pushed message
3. The server can broadcast events to be pushed to all subscribers
The flows looks like this:
- client `push("ev1")` -> …

Sync channel messaging with new push API

---

priv/static/phoenix.js
web/static/js/phoenix.js

As always, thanks for providing such an awesome tool. I just upgraded to Phoenix 0.11, and when leaving a channel I get the following error:
```
/Users/seejee/code/elixir-talk/node-client/vendor/phoenix.js:317
chan.reset();
^
ReferenceError: chan is not defined
at /Users/seejee/code/elixir-talk/node-client/vendor/phoenix.js:317:7
at Push.matchReceive (/Users/seejee/code/elixir-talk/node-client/vendor/phoenix.js:195:7)
at Object.callback (/Users/seejee/code/elixir-talk/node-client/vendor/phoenix.js:148:13)
at /Users/seejee/code/elixir-talk/node-client/vendor/phoenix.js:297:19
at Array.map (native)
at Channel.trigger (/Users/seejee/code/elixir-talk/node-client/vendor/phoenix.js:296:8)
at Object.callback (/Users/seejee/code/elixir-talk/node-client/vendor/phoenix.js:275:13)
at …
```

Fixing reset call in Channel.leave

---

lib/mix/tasks/phoenix.digest.ex
lib/phoenix/digester.ex
test/mix/tasks/phoenix.digest_test.exs
test/phoenix/digester_test.exs

This task is responsible for digesting and compressing the assets files as described at #735.
I used the [discourse's](https://github.com/discourse/discourse) assets to make a benchmark since it has ~ 991 assets files. The results were pretty nice.
```
phoenix (introduce-digest-task) $ time mix phoenix.digest /Users/laurocaetano/Desktop/discourse/app/assets -o /tmp/assets
Check your digested files at '/tmp/assets'
real	0m2.446s
user	0m1.926s
sys	0m1.290s
```
This task will read the input/output path and proceed as following:
* Filter for files (excluding directories)
* Get the file digest
* Compress the file
* Save the files to disk
* Generate the manifest
It also takes account the relative path when saving the files to the output path, see:
```
|-fonts
|-images
|---favicons
|-javascripts …
```

Introduce the digest task

---

lib/phoenix/channel.ex

This is to avoid having to provide default implementations of `handle_info` in the channels.
I also found that `handle_out` defcallback still had the `{:ok, Socket.t}` result listed as a valid result, which afaik it is not anymore...
Should not break backwards compatibility.
~ cheers, Johanna

Adds defcallback and default impl for channel handle_info/2

---

lib/phoenix/conn_test.ex

I think `handful` was meant to be `helpful`.

Fix typo in documentation

---

lib/phoenix/controller.ex

The phrasing made it sound like a controller is a
form of router.

Clarify plug pipeline docs in `Phoenix.Controller`

---

installer/templates/new/mix.exs

postgrex and phoenix_ecto should be also listed in
the application configuration in order to make these
libs' modules available in within an OTP release.
Reference: https://github.com/bitwalker/exrm#common-issues
I need small help with testing the changed generator. The approach described in docs (with `--dev` param) seems to use my global phoenix installation. (I tried from the git checkout directory and from installer/ directory)

Declare missing applications in mix.exs

---

installer/lib/phoenix_new.ex
installer/templates/new/mix.exs
installer/test/phoenix_new_test.exs
test/mix/tasks/phoenix.new_test.exs

We should have an option to specify which adapter should be used with `phoenix_ecto`. Right now we assume everyone is using Postgres.
```
mix phoenix.new my_app --adapter mysql
```
Should it default to `pg` ?

Add --adapter option to phoenix.new

---

.travis.yml

:information_desk_person: This change updates Phoenix to run tests against version 1.0.4 of Elixir. 
Might also be worth running the test suite against a matrix of Erlang and Elixir versions, but I'll work on that in a follow up changeset.

Test against Elixir v1.0.4

---

lib/mix/tasks/phoenix.gen.html.ex
lib/mix/tasks/phoenix.gen.json.ex

I started a new project and I was sure (in my mind) that there was a generator for controllers or resources.
Running `mix -h` showed:
```text
...
mix new                # Create a new Elixir project
mix phoenix.gen.html   # Generates HTML files for a resource
mix phoenix.gen.model  # Generates an Ecto model
...
```
The description of the `phoenix.gen.html` made me believe that it generated only HTML files, which in my mind sounded like views/templates.
I spent sometime searching for a missing resource generator. I know that this info is in the upgrade guide, but I wasn't upgrading, so I didnt read it. Same thing could happen to a new user.
I think the description could be a little better. This PR is just one suggestion.
(I know the answer lies in checking `mix help phoenix.gen.html` but …

Make it more clear that the generators dont only generate views

---

priv/static/phoenix.js
web/static/js/phoenix.js

`this.states` implies that these values would be subject to change. Possibly confusing to someone consuming the library.

Prefer SOCKET_STATES over this.states in phoenix.js

---

lib/phoenix/view.ex

Just a couple of small typos in the documentation of `render_one` in `Phoenix.View`.

Fix typo in documentation of `render_one`

---

installer/templates/new/test/support/conn_case.ex

Functionality is already plural.

Fix word usage in `ConnCase` docs.

---

test/phoenix/controller/flash_test.exs

Small changes to remove ambiguity in their meaning.

Use some clearer test names in `flash_test`

---

installer/lib/phoenix_new.ex
installer/test/mix_helper.exs
installer/test/phoenix_new_test.exs

patch for #826 
besides default mysql username/password, MSSQL credentials updated as well to be different. Also updated MixHelper.assert_file/2 function to allow list of regular expressions to be matched.

different credentials in generated app for different databases

---

lib/mix/phoenix.ex
lib/mix/tasks/phoenix.gen.html.ex
lib/mix/tasks/phoenix.gen.model.ex
priv/templates/model/migration.exs
priv/templates/model/model.ex
test/mix/tasks/phoenix.gen.html_test.exs
test/mix/tasks/phoenix.gen.model_test.exs

I'm not sure what the syntax would look like, but It'd be cool to be able to do something like
```
mix phoenix.gen.model Foo foos ...
mix phoenix.gen.model Bar bars foo_id:references(:foos)
```

Any plans to add support for foreign keys to phoenix.gen.model?

---

.travis.yml

Hi Chris,
this PR fixes the invocation of the `after_script` on Travis.
Since we switch to the `installer/`dir after `mix test` in order to invoke it again, we have to return to `TRAVIS_BUILD_DIR` for the subsequent invocation of InchEx.

Fix travis after_script invocation

---

installer/lib/phoenix_new.ex
installer/templates/new/priv/static/robots.txt

Because all web apps need a robots.txt file

Add default robots.txt file to phoenix.new

---

lib/phoenix/router/route.ex
test/phoenix/router/pipeline_test.exs
test/phoenix/router/routing_test.exs

This is an issue noticed by someone (not me) at the Elixir Conf EU Phoenix Tutorial (22 April 2015).
Query params are URI decoded in Plug, but params that are embedded in a route such as
```
get "/hello/:name", HelloController, :hello
```
```http://myserver.com/hello/Bob%20Smith``` will result in params being ```%{name: "Bob%20Smith}``` rather than ```%{name: "Bob Smith}```.

Url decode route params

---

web/static/js/phoenix.js

Hi there, found this while reading the ES6 source out of interest, so I am not 100% certain it is an error :sake: 
Caught it because of the downcased "L" in `CHANNEl_EVENTS` ...

Fix typo in phoenix.js

---

brunch-config.js
installer/templates/static/brunch/brunch-config.js

Backward-compatibility is maintained but we might as well be using the new name. It's also less confusing.
Here is the commit that introduced that change: https://github.com/babel/babel-brunch/commit/fa8dd643431e99d8a4fd05ad6637204264e9f497

babel-brunch option key has changed from ES6to5 to babel.

---

installer/templates/static/brunch/brunch-config.js

We decided to leave the default as is but to give an example of separating the two bundles (app and vendor).

Commented example of having a separate vendor.js bundle

---

installer/lib/phoenix_new.ex
installer/templates/new/mix.exs
priv/templates/model/model.ex

This pull request uses latest phoenix_ecto that depends on phoenix_html + poison instead of phoenix. Unfortunately, we cannot merge this yet, because we haven't released the latest phoenix_ecto as doing so would break existing applications (due to its dependency on phoenix_html).
We will need to release phoenix_ecto and merge this right before the next phoenix release.

Update to latest phoenix_ecto

---

lib/mix/tasks/phoenix.server.ex

It may be desired to pass arguments from `mix phoenix.server` to "app.start".  An example of this would be `--no-deps-check` which comes up when .git directories are wiped on a PaaS (in my case, `flynn` re: [elixir issue #1430](https://github.com/elixir-lang/elixir/issues/1430)).  This pull request passes through those arguments for the Mix task.
I'd be happy to discuss the merits of this patch.

Pass arguments from task phoenix.server to app.start

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/adapter.ex
lib/phoenix/router/helpers.ex
test/phoenix/endpoint/adapter_test.exs
test/phoenix/endpoint/endpoint_test.exs
test/phoenix/router/helpers_test.exs

This option is the first step to achieve multiple assets hosts (#617).
When accessing the `static_url` function it will return the URL based on this configuration. If no configuration for `static_url` is provided, it will fallback to `url`.

Add `static_url` configuration.

---

installer/templates/new/web/templates/layout/application.html.eex

Encourage others to write HTML which is accessible. Roles aid assistive technologies in deciding what the correct way to announce content to a user is. For this reason, I think it is important to encourage developers to write accessible HTML using roles, as recommended by Bootstrap which is used here, rather than bare HTML.

Encourage accessible HTML

---

installer/lib/phoenix_new.ex
installer/templates/new/test/support/channel_case.ex
lib/mix/tasks/phoenix.gen.channel.ex
priv/templates/channel/channel.ex
priv/templates/channel/channel_test.exs
test/mix/tasks/phoenix.gen.channel_test.exs

refs: https://github.com/phoenixframework/phoenix/issues/741
This channel generator generates the a channel and channel_test file. The channel generated is very basic. It defines two `join/3` functions that pattern-match on either "topic:lobby" or "topic:" <> subtopic_id and a `handle_in/3` for every event arg. The `handle_in/3` just broadcasts the event with the attrs.
The channel_test here makes use of the helper in the PR here https://github.com/phoenixframework/phoenix/pull/652. Will make changes to it when necessary.
Let me know if there are any changes that need done. Thanks in advance! :)

Channel generator

---

installer/templates/new/web/templates/page/index.html.eex

Updated the ```freenode IRC``` link to use ```http://webchat.freenode.net/?channels=elixir-lang``` instead of ```irc://irc.freenode.net/elixir-lang``` on the newly generated app welcome page.
Nothing major but to make it consistent with the on-line docs.

Updated freenode IRC link to use http on the welcome page

---

lib/phoenix/endpoint/cowboy_handler.ex

This lets me run multiple listeners for the same endpoint under a single supervisor, for instance an IPv4 and an IPv6 listener. (There are a few other places where Phoenix assumes that there will only ever be one HTTP and one HTTPS listener, for instance in configuration and, by extension, the URL building functions.)

Allow custom refs in child_specs

---

installer/lib/phoenix_new.ex
installer/templates/static/brunch/.gitignore
installer/templates/static/robots.txt
installer/test/phoenix_new_test.exs

Closes https://github.com/phoenixframework/phoenix/issues/875
When generating a new Phoenix app with brunch, it generates all static files in `web/static` and gitignores all files in `priv/static`.

Ignore priv static

---

lib/phoenix/router/helpers.ex
test/phoenix/router/helpers_test.exs

Configured `static_url` was not used to generate the url via the `static_url` helper and the `url` helper was also broken.

Fix static_url helper to use static_url endpoint config

---

lib/phoenix/controller.ex

Without the backticks, this markdown gets rendered as `"<em>/</em>"` in HTML (see: [Phoenix.Controller.accepts/2](http://hexdocs.pm/phoenix/Phoenix.Controller.html#accepts/2)).
This change keeps the asterisks visible when rendered into HTML.
An alternate fix would be to escape the asterisks themselves (`\\*/\\*`) but using backticks looks a little bit nicer when viewing the markdown directly.

Wrap asterisks in backticks to avoid emphasis

---

lib/phoenix/controller.ex
test/phoenix/controller/controller_test.exs

Adds jsonp support to controllers. While CORS is usually preferable for cross domain requests I think there is also some value in having jsonp support: works well with older browsers (IE < 10), good jQuery integration, etc.
The syntax for the jsonp feature is the same as for json:
```elixir
jsonp conn, %{foo: :bar}
```
This will produce the following output on request (GET /?callback=cb):
```javascript
/**/ typeof cb === 'function' && cb({"foo":"bar"});
```
It's possible to override the callback parameter:
```elixir
jsonp conn, %{foo: :bar}, callback: "cb"
```
that allows you to use the overridden callback name in the query string (GET /?cb=cb)

implemented jsonp support for controllers and added tests

---

installer/templates/static/brunch/brunch-config.js

I encountered a problem when installing bootstrap-sass through bower where I noticed its JS files weren't being compiled. Turns out bootstrap-sass has an `/assets` directory and brunch, by default, copies all files in any `/assets` dir, even ones in bower deps, straight to `priv/static`.
This PR fixes this problem and shows where to copy non-css and non-js assets to, which is `web/static/assets` by default.

Set different assets directory

---

lib/phoenix/pubsub/local.ex
test/shared/pubsub_test.exs

Return the HashSet directly instead of converting it to a list. The
conversion is not really needed and will be expensive if the number of
subscribers is large.
Updated the function doc so we say we return a `Enumerable.t` instead of the concrete HashSet type.
This replaces PR #937

Fix local subscribers return value

---

installer/templates/new/web/templates/layout/app.html.eex
installer/test/phoenix_new_test.exs

If the `--no-brunch` flag is set when creating a new project using
installer, e.g.
mix phoenix.new /tmp/testapp --no-brunch
The line that is responsible for running the JavaScript for assets using
brunch is not included.
This prevents the JavaScript error:
> ReferenceError: require is not defined
This closes issue #942

fix(installer): do not attempt to use require without brunch

---

lib/phoenix/test/conn_test.ex

The `accept` header should be singular.

Fix `accept` request header typo in docs

---

priv/templates/html/controller.ex
priv/templates/html/controller_test.exs
priv/templates/json/controller.ex
priv/templates/json/controller_test.exs
test/mix/tasks/phoenix.gen.html_test.exs
test/mix/tasks/phoenix.gen.json_test.exs

In reference to this issue: https://github.com/phoenixframework/phoenix/issues/957
I switched from using `get` to `get!` then I added some tests in the mix task section and everything worked, which was great. 
Next, I got a little ambitious and tried to use the modified mix tasks to generate controllers so I could make sure they would work. This step wasn't so great because I couldn't get it to work without resorting to using a weird `ln -S` trick in my `~/.mix/phoenix-0.14.0-dev` dir (lol it's very likely I just didn't install the .ez archive correctly, but please forgive, I'm new to elixir).
Next, I used the 0.14-dev phoenix to start a new `hello_phoenix` project to test. I ran `mix phoenix.gen.json User users name:string email:string` and then ran `mix test`
I was greeted by: …

Switch to use Repo.get! to properly 404

---

lib/phoenix/view.ex

`conn` should be `@conn`. I fixed this.

Fix typo in example of render_existing.

---

lib/phoenix/view.ex

Hi there! Very new to the Elixir / Phoenix community. I noticed the last few CI builds were failing and "spotted" a `\u1` that shouldn't be there.
After hearing such wonderful things about this community, I had to pounce on this small opportunity to contribute!
Thanks again for your hard work!

Remove `\u1` character that crashed CI

---

lib/phoenix/endpoint/cowboy_handler.ex

Starting a Phoenix server in dev:
```
[debug] Running StockholmElixir.Endpoint with Cowboy on port 4000 (http)
```
Starting a Ruby on Rails server in dev:
```
=> Rails 4.1.4 application starting in development on http://0.0.0.0:3000
```
I like about the Rails message how you can click the link (in certain terminals) or copy-paste it.
Starting a Phoenix server in dev, after this pull request:
```
[debug] Running StockholmElixir.Endpoint with Cowboy on http://localhost:4000
```
Note how this pull request just hardcodes "localhost". I suspect that perhaps this isn't suitable in every situation, but I thought I'd make a first attempt. I'm happy to make it smarter as needed. Let me know of any issues.

Show full local URL when starting server

---

priv/templates/model/model.ex

The docstring says that you have to pass nil as params to return an empty changeset, yet this functionality is (will be) deprecated.

Fixed the docstring to comply with the latest version of ecto

---

installer/templates/static/brunch/brunch-config.js

The docs for the Brunch concatenation feature have moved:
https://github.com/brunch/brunch/tree/stable/docs#concatenation
This updates `brunch-config.js` accordingly.

Update link to concatenation docs in braunch-config.js

---

lib/phoenix/controller.ex

Just clarifying that `false` can be passed to `put_layout/2` and no layout would be rendered. I wanted to add a doctest but they are currently disabled for this file.

Add documentation about passing `false` to put_layout/2

---

lib/phoenix/router.ex

Just clarifying singleton option usage on resources, because I'm getting this question too often :sweat_smile:  (specially since `resource` deprecation warnings on 0.14)

Add usage example about resources singleton option

---

installer/templates/static/brunch/brunch-config.js
installer/templates/static/brunch/package.json

With this flag, dependencies in npm can be loaded in brunch for example:
npm install --save react
Then in app.js
import React from "react"
This will use the React dependency from npm instead of requiring it to
be included locally in the "vendor" directory.
The issue can be found at https://github.com/brunch/brunch/issues/991

feat(brunch-config.js): enable npm by default

---

lib/phoenix/pubsub.ex
lib/phoenix/pubsub/local.ex
lib/phoenix/pubsub/pg2.ex
lib/phoenix/pubsub/pg2_server.ex
lib/phoenix/transports/long_poll/server.ex
test/phoenix/pubsub/local_test.exs
test/phoenix/pubsub/pubsub_test.exs
test/shared/pubsub_test.exs

The clients are the ones sending the messages now, except for distributed messages, which are spread by the PG2 Server.

Remove bottlenecks from Phoenix PubSub Local

---

installer/lib/phoenix_new.ex
installer/templates/new/test/views/layout_view_test.exs
installer/test/phoenix_new_test.exs

A newly generated Phoenix application has an "empty" test file for the page view, but not for the layout view. This PR generates one for the layout view as well.

Add layout_view_test.exs to Match page_view_test.exs

---

lib/phoenix/channel.ex
lib/phoenix/channel/transport.ex
lib/phoenix/pubsub/local.ex
priv/static/phoenix.js
test/phoenix/integration/http_client.exs
web/static/js/phoenix.js

Previously, the comments read "ie", which is short for "id est", meaning, "that is". This implies that what follows is what you're really trying to say. For example, on line 211, ie meant that the event was always going to be `"phx_join"`.
Now, the comments read "e.g.", which is short for "exempli gratia", meaning "for example". That same example now means that event is going to be a string from the list of events, like `"phx_join"`

Fix latin abbreviations in Phoenix.js comments

---

lib/mix/phoenix.ex

I thought that `mix phoenix.gen.model user:references` generates `nil` for `:user` of @valid_attrs param.

Fix missing :references key

---

lib/phoenix/digester.ex
test/phoenix/digester_test.exs

It doesn't help to gzip bitmap files like PNG or JPEG, and can sometimes be bigger than the uncompressed file.
I'm using a "gzip whitelist" by file extension here, but if there's a better way to do it, I'm all ears.

Only gzip files that are known to be plain text.

---

priv/static/phoenix.js
web/static/js/phoenix.js

So `this.log` isn't defined here. It looks like it should be `this.socket.log` as it is in the onClose and onError callbacks.

Fix this.log in Channel.leave where it isn't defined.

---

installer/lib/phoenix_new.ex
installer/test/phoenix_new_test.exs

This commit fixes a bug in the installer `phoenix.new` task
that was causing the `favicon.ico` file to not be found
when requested by browsers at `/favicon.ico`.
The `favicon.ico` file was generated in `web/static/assets/images`
so a `phoenix.digest` will create `priv/static/images/favicon.ico`.
The mount set up by `Plug.Static` can never find this file, since
the mount is relative to `priv/static`.
This commit changes the path of the generated `favicon.ico` to be
`web/static/assets/favicon.ico` so that it will be correctly
digested at `priv/static/favicon.ico`, where it can be found by
the mount.

Fix path to generated favicon file.

---

lib/phoenix/supervisor.ex

The module specification for `Phoenix.Transports.LongPoll.Supervisor` should be `supervise/2`.

Fix module definition call

---

installer/templates/new/config/dev.exs

svg files are common for image assets and changes to them should cause a page reload.

include svg in files that cause a reload

---

installer/templates/static/brunch/brunch-config.js

Fix typo in brunch-config.js

---

lib/mix/tasks/phoenix.gen.json.ex
priv/templates/phoenix.gen.json/view.ex
test/mix/tasks/phoenix.gen.json_test.exs

Addresses #1125.
This will include generated fields in the default JSON output. So if you run `mix phoenix.gen.json User users name:string email:string` you'll get the following in the `web/views/user_view.ex` file:
```elixir
def render("user.json", %{user: user}) do
%{
id: user.id,
name: user.name,
email: user.email
}
end
```
I added tests similar to how the HTML generator did it (it didn't explicitly check for all fields, just one of them). 
I opted to build the list of fields in the generator itself instead of iterating inside the template as I found it easier to get clean output without extra whitespace, without an errant comma after the last field, etc. This also gracefully handles the case where the user doesn't provide any fields (e.g. `mix phoenix.gen.json User users`).
Let me …

Include generated model fields in JSON output

---

lib/phoenix/test/channel_test.ex
test/phoenix/test/channel_test.exs

I chatted with José in IRC awhile back about adding a subscribe_and_join! function. Here's the PR! I also added some other functions that I have needed when testing channels lately.
* Add subscribe_and_join!/3 for easier for more concise tests
* Add ability to assert that pushes/broadcasts were for a specific
topic. This makes it possible to test that a push/broadcast was sent for other topics. I

Improve channel testing helpers

---

lib/mix/tasks/phoenix.gen.json.ex
test/mix/tasks/phoenix.gen.json_test.exs

Previous to this change, the `phoenix.gen.json` generator was
creating invalid elixir code when the model included more than
one field. The generator was not placing commas between fields
for the singular method.
I got into this while creating a brand new phoenix project with
version 0.17 and after doing:
```shell
mix phoenix.gen.json Human humans name age:integer
```
I got the following error while trying to run the migrations:
```
== Compilation error on file web/views/human_view.ex ==
** (SyntaxError) web/views/human_view.ex:14: syntax error before: name
(elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```
The problem was in the generated `web/views/human_view.ex`
missing some commas in the following function:
```elixir
def …
```

Make sure json view generator joins fields with commas.

---

lib/mix/tasks/phoenix.gen.html.ex
lib/mix/tasks/phoenix.gen.json.ex

* Changes `an` -> `a`
* Removes unnecessary `-`

Fix typos in phoenix.gen.html/json

---

priv/templates/phoenix.gen.json/controller_test.exs
test/mix/tasks/phoenix.gen.json_test.exs

This PR will fix a failing test after using the json generator.
```
mix phoenix.gen.json User users name:string
```
I got the following failing test after running the migrations and `mix test `
```
test/controllers/user_controller_test.exs:18
Assertion with == failed
code: json_response(conn, 200)["data"] == %{"id" => user.id()}
lhs:  %{"id" => 20, "name" => nil}
rhs:  %{"id" => 20}
stacktrace:
test/controllers/user_controller_test.exs:21
```
The controller test that fails contains the following lines:
```
assert json_response(conn, 200)["data"] == %{
"id" => <%= singular %>.id
}
```
but it's missing the name.
I'm new to Phoenix and Elixir and was checking out the generators (great stuff btw) when I stumbled upon this. Thought I might submit a PR.

Make sure controller test from generator uses all model fields

---

lib/mix/tasks/phoenix.gen.channel.ex

I believe the full module name should be in the example so it works out of the box without aliasing your channel in user_socket.ex

Full Module Name in Example

---

installer/templates/static/brunch/brunch-config.js

Changed `brunch-config` to using all double-quotes now to be consistent with the other `.js` templates
Swapped over from https://github.com/phoenixframework/phoenix/pull/1177

Update brunch-config.js to use all double-quotes

---

lib/mix/tasks/phoenix.gen.json.ex
test/mix/tasks/phoenix.gen.json_test.exs

Possibly it is only a problem with json resources.   I added  "new" method to my drive_state_controller.ex for this route to work: 
URL:   http://localhost:4000/drive_states/new?state=2&name="drive2"
Code I added to drive_state_controller.ex for the above URL to work
def new(conn, %{"name" => name, "state" => state} = drive_state_params) do
create conn, %{"drive_state" => drive_state_params}
end
This is how I created my model:
>mix phoenix.gen.json DriveState  drive_states name:string state:integer
"new" shows up in the routes below but doesn't work out of the box
>mix phoenix.routes
Generated drive_state app
page_path  GET     /                       DriveState.PageController :index
drive_state_path  GET     /drive_states           DriveState.DriveStateController :index
drive_state_path …

"new"route listed but not supported

---

installer/templates/ecto/model_case.ex

I have git hooks which warn me about trailing whitespace when I commit, and it complained about these in a freshly generated Phoenix app.
Also consistent with e.g. line 46.

Strip trailing whitespace in template

---

lib/mix/tasks/phoenix.gen.json.ex
priv/templates/phoenix.gen.json/controller_test.exs
test/mix/tasks/phoenix.gen.json_test.exs

The generated controller test for `mix phoenix.gen.json` used atom keys
in the "shows chosen resource" test, when comparing against the
controller response data. The actual response has string keys, so the
test failed.
eg
```
1) test shows chosen resource (ConmanData.BobControllerTest)
test/controllers/bob_controller_test.exs:18
Assertion with == failed
code: json_response(conn, 200)["data"] == %{id: bob.id(), name: bob.name(), eyes: bob.eyes()}
lhs:  %{"eyes" => nil, "id" => 13, "name" => nil}
rhs:  %{eyes: nil, id: 13, name: nil}
```
This now expects string keys, so the generated test should succeed.

String keys gen.json controller test show resource

---

installer/lib/phoenix_new.ex
installer/templates/ecto/model_case.ex
installer/templates/new/test/support/channel_case.ex
installer/templates/new/test/support/conn_case.ex
installer/templates/new/web/web.ex
installer/test/phoenix_new_test.exs
lib/mix/tasks/phoenix.gen.html.ex
lib/mix/tasks/phoenix.gen.json.ex
lib/mix/tasks/phoenix.gen.model.ex
priv/templates/phoenix.gen.model/migration.exs
test/mix/tasks/phoenix.gen.model_test.exs

Adds support for:
* `binary_id` as default in ecto models in installer
* `binary_id` in the model generator
* default generator options
* MongoDB adapter in installer

Support for Mongodb in installer

---

lib/phoenix/token.ex

Prior to this commit, we had a disconnect between the documented units
(seconds) and the actual units (milliseconds) that were used for
validating the maximum age of a token. This meant that the suggestion of
a 2 week maximum age as 1209600 seconds was, in reality, checked as
milliseconds resulting in a default maximum age of a little over 20
minutes. This commit updates the documentation to reflect that `max_age`
is measured in milliseconds, updates the defaults to their millisecond
equivalents, and tests that the `max_age` does, in fact, validate using
milliseconds.

token `max_age` is checked in ms, make docs consistent

---

installer/test/mix_helper.exs
lib/mix/phoenix.ex
test/mix/tasks/phoenix.gen.json_test.exs

This prevents code from being generated if one of the types is invalid.
Fixes #1215

fix(Mix.Phoenix): validate attrs on generators

---

installer/lib/phoenix_new.ex
installer/templates/new/config/config.exs
installer/templates/new/config/dev.exs
installer/templates/new/lib/application_name/endpoint.ex
installer/templates/new/mix.exs
installer/templates/new/test/views/error_view_test.exs
installer/templates/new/web/router.ex
installer/templates/new/web/views/error_view.ex
installer/templates/new/web/web.ex
installer/test/phoenix_new_test.exs

This allows to skip generating HTML views and including related
dependencies (phoenix_html, phoenix_live_reload).
Fixes https://github.com/phoenixframework/phoenix/issues/1192

Add --no-html flag to Phoenix installer

---

README.md

In the context of this project it makes more sense to mention Phoenix itself instead of Elixir.

'Contributions to Phoenix' makes more sense

---

lib/phoenix/channel.ex

`{:ok, socket}` is not a correct result according to Phoenix.Channel

Fixes wrong reply tuple in Phoenix.Channel moduledocs

---

README.md

- clarify that --dev must be used in the installer directory and with a relative path to the project to be generated
- note that Mix will use an installed archive before the local source code
- link to related issue and PR for more info
- prefer 'project' to 'app' to avoid confusion with OTP Applications

Improve docs on using the --dev switch

---

lib/phoenix/channel/server.ex

The pattern expected on error seems to only require `{:error, reply :: map}` whereas the outputted error also mentioned a socket was required. Hope this is correct and not something I'm missing.

Fix incorrect error message on channel join pattern mismatch.

---

lib/phoenix/socket/transport.ex

Noticed this when reading through the source for the longpoll and websocket transports.
The documentation also mentions that transports dispatch to channels: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/transport.ex#L179

change `sockets` to `channels` in Transport.dispatch

---

lib/phoenix/controller/pipeline.ex

Hi,
Really small edit for clarity. I believe `or` is the better wording than `and` for this line explaining the plug guards as the action can only be one value at a time.
Cheers,
Darian

Phoenix.Controller.Pipeline docstring update

---

LICENSE.md
README.md
mix.exs

Explicitly mention MIT License in the README.md and convert License to markdown.

License updates

---

lib/phoenix/channel.ex

The current guard doesn’t allow the ~w sigil for example.

Allow any code in channel intercept argument

---

lib/phoenix/template.ex
test/phoenix/template_test.exs

I was not sure if it was worth creating another module specifically for javascript (like `Phoenix.Template.Javascript`) since it would do exactly the same so I added `Phoenix.Template.HTML` as the default encoder for js.

Adds Phoenix.Template.HTML as a default js encoder

---

lib/phoenix/transports/long_poll.ex

Picked up on this here: https://github.com/jerel/phoenix_js/issues/1
I think we need to include the access origin control headers on each simple request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests) for the server to allow a cross site request to happen.
Allowing all requests through should be okay because we can use the check_origin method to verify access. (this really only effects long polling). I could even have a crack at using the check_origin list to add the correct hosts to the header if preferred.

add origin control headers to simple requests

---

lib/phoenix/endpoint/server.ex
lib/phoenix/transports/long_poll.ex

This just removes some redundancies:
- Endpoint.Server doesn't have to `import Supervisor.Spec`, as it calls `use Supervisor` at the top of the module
- `@behaviour Phoenix.Socket.Transport` was stated twice in Transports.LongPoll

Remove redundancies

---

installer/lib/phoenix_new.ex
installer/templates/static/brunch/package.json
package.json

This updates the installer to utilize an [npm run script](https://docs.npmjs.com/cli/run-script) for running `brunch build`.
npm run scripts are run with any locally installed bins in the `PATH`, so that you can call the executables directly without having to call into `node_modules/...` or ask that someone install a dependency globally. This is preferable because the current method of reaching into `node_modules/...` is prone to breaking if the `brunch` package ever changes where it stores the bin, whereas this will always work as long as it defines an executable in its `package.json`.

Use npm script for building brunch

---

installer/templates/new/config/dev.exs
installer/templates/static/brunch/package.json
lib/phoenix/endpoint.ex
package.json

This is a follow-up to conversation that happened in #1270 . Moves the `brunch watch --stdin` call into an npm script.

Use npm script for brunch watch tasks

---

installer/templates/new/test/views/error_view_test.exs

Tests were not updated to reflect change to error_view
https://github.com/phoenixframework/phoenix/commit/46f83f1280851d08223bcd42c8fc72ba9081a5f6

Fix error_view_test to use atoms

---

lib/phoenix/endpoint/cowboy_handler.ex

I think this should be `long_poll` rather than `long_pool`.

fix docs typo

---

lib/phoenix/socket/transport.ex

Corrected a tiny spelling mistake.

Fix typo in Phoenix.Socket.Transport.parse_origin

---

installer/templates/new/web/templates/layout/app.html.eex

This commit improves accessibility in the default layout by incorporating HTML5 sectioning elements instead of `div` elements. It adds additional elements but does not change the appearance.
* Replace `div` for header with `header` element
* Add `nav` element with `role="navigation"`
* Wrap import with `main` element
* Move `role="main"` from outer `div` to new `main` element as `main` role is for the main content of the document.
I have left the `class` attributes intact so as not to break the CSS.

Update HTML layout to use sectioning elements

---

installer/templates/new/config/prod.exs

See this issue for further information: https://github.com/bitwalker/exrm/issues/206.

Add comment about necessary root path changes for OTP depoyments

---

lib/phoenix/view.ex

Thanks to @chrismccord for the suggestion.

Using the ~E sigil rather than raw/1

---

lib/phoenix/socket.ex

`MyApp.Endpoint.broadcast/2` is not generated by default by the endpoint, needs to have a 3rd parameter as well.

Fix socket.ex docu

---

lib/phoenix/test/channel_test.ex

Adds an example for testing async closes/errors of channels.

Enhance ChannelTest docs

---

installer/templates/new/web/templates/layout/app.html.eex
installer/test/phoenix_new_test.exs

I think this is better than defaulting to "Hello Phoenix!". Rails also does the same. What do you think?

Set application's module name as the default <title> in app layout.

---

lib/phoenix/pubsub/local.ex

ETS :bag insertion for elements with the same key grows linearly (on the number of elements with same key). On the other hand :duplicate_bag insertion is constant.
This change does not increase the size of the ETS and there is no performance degradation for lookups and deletions.
I was able to replicate insertion timeouts when there are lots of elements with same key using :bag but it does not happen using :duplicate_bag.

Optimization for PG2 ETS insertion

---

lib/phoenix/controller.ex

Hello!
I'm not 100% sure I'm correct here, but I think that this typespec stated that this function takes a list of params, but the implementation takes a binary.
Cheers,
Louis

Fix scrub_params/2 typespec

---

web/static/js/phoenix.js

This fixes an issue where the Phoenix JavaScript lib won't compile with Babel 6 and the ES2015 presets.
As of Babel 6.0, ES2015 transpiling has been moved to a preset plugin. Here's the the 6.0 [blog post](https://babeljs.io/blog/2015/10/29/6.0.0/) with some more details.
To reproduce,
```bash
npm i -g babel # to install Babel 6.0 and the `babel` binary
npm i babel-preset-es2015 # installs ES2015 preset (it isn't found when installed globally, must be local)
cd web/static/js
babel --presets "es2015" phoenix.js
TypeError: phoenix.js: Duplicate declaration "channel"
482 |
483 |   channel(topic, chanParams = {}){
> 484 |     let channel = new Channel(topic, chanParams, this)
|         ^
485 |     this.channels.push(channel)
486 |     return channel
487 |   }
at File.buildCodeFrameError …
```

Babel 6 ES2015 compilation issue

---

CHANGELOG.md
lib/phoenix/channel.ex
lib/phoenix/channel/server.ex
test/phoenix/channel_test.exs
test/phoenix/test/channel_test.exs

@josevalim I'd like to get your sign-off on this one. I think it's time we can bring back `reply` in the channel API. If you remember, we had `reply`, which we renamed to `push` when we added true replies with the 3-tuple `{:reply, ..., socket}`. We've had the first use-case of needing to async reply to a push so it's time to add this feature. I think it has been plenty long since the name change that this won't cause problems. This is analogous to `GenServer.reply`.

Allow async replies. Closes #1324

---

installer/test/phoenix_new_test.exs

Recently https://github.com/phoenixframework/phoenix/commit/968777244510fa96defd61be7d1e0f7a5ef53462 and https://github.com/phoenixframework/phoenix/commit/6b203d99ccf141abf58b8b19ea8bd15be9851590 were reverted but there was a separate commit for the test https://github.com/phoenixframework/phoenix/commit/8b3a143ec00b451f18e3ff2d35c98af373c0c579.
All the builds have been failing on master since then, this should fix that.

Fix installer spec

---

lib/phoenix/channel.ex
lib/phoenix/channel/server.ex

Proxy the Channel.Server code_change function to the overridable Channel
code_change callback.

Expose code_change for channels. Fixes #1336

---

lib/phoenix/template.ex

I recently used Phoenix.View in a library which required the Phoenix
compiler. It raised this helpful error, but I wasn't sure how to add it
to compilers. When I did find `Mix.compilers` I did this:
Mix.compilers ++ [:phoenix]
Which didn't work. It turns out that `phoenix` needs to be first. This
commit adds an example to make things a bit easier.

Clarify how to use the Phoenix compiler

---

lib/phoenix/token.ex

I didn't realize this until I checked the code and then checked the Plug
docs. I think including this is a good idea so people don't accidentally
send sensitive data.
A small but (I think) important change :)

Explain that tokens are readable by clients

---

mix.exs

> The :contributors field is deprecated, change to :maintainers
https://github.com/hexpm/hex/blob/9944bb14512235f16a14449dea7c3124b7c580c4/lib/mix/hex/build.ex#L96

Change a option of :package from :contributors to :maintainers

---

test/phoenix/integration/long_poll_test.exs

Calling assert_receive will wait until the message is received or the
timeout is reached. This should prevent the intermittent failures on
Travis CI.

tests(Phoenix.Integration.LongPollTest): fix intermittent failure

---

lib/phoenix/router.ex

Remove query string output from url when no query string is passed to the helper function.

Fix router.ex docs

---

installer/templates/static/brunch/package.json
package.json

I'm thinking I must have missed something obvious because everything just worked.

Bump brunch to 2.0.0

---

installer/templates/new/web/templates/layout/app.html.eex
lib/phoenix/controller.ex
lib/phoenix/view.ex
test/fixtures/templates/layout/app.html.eex
test/fixtures/views.exs
test/phoenix/controller/render_test.exs

@josevalim I still need to bump the docs, but I'm PR'ing now because I think I'll have to convince you this is the way to go :) There is some necessary coupling b/w the inner view and layout that the `conn` approach made murky. This PR introduces two new "magic" assigns, but it does it the clearest way, with the clearest coupling. It also avoids coupling the rendering to the `%Conn{}`, which may not always be present.

Drop inner in favor of explicit render

---

installer/templates/new/web/channels/user_socket.ex

By default user_id will be an integer and integers are not valid
arguments to Kernel.<>

Fix installer's user_socket code sample

---

lib/phoenix/router.ex

Applied back ticks and double quotes to paths in `router.ex` docs.

Update Router docs to make paths consistent

---

mix.exs
mix.lock

Current version of **poison** in phoenix raises warning for depending on elixir `1.0.x`.
Since `1.3.1`, [poison already relaxed this dependency](https://github.com/devinus/poison/commit/b057121ac1bcadc2f938df66ca586d31fc682e20).

Update poison (1.3.0 -> 1.5.0)

---

lib/phoenix/controller.ex
lib/phoenix/controller/pipeline.ex
lib/phoenix/endpoint.ex
lib/phoenix/endpoint/instrument.ex
test/phoenix/endpoint/instrument_test.exs

This PR adds a bunch of stuff:
- `instrument/3-4` macros to `Phoenix.Endpoint`: we need this because we often don't have the endpoint at compile time, so we can't call `endpoint.instrument`
- instrumentation for controller dispatching
- instrumentation for controller rendering
(this is what @josevalim suggested for now)
This works but I don't think it's very pretty. I can't think of a better way to do it now, but I feel we need generic instrumentation very strongly :( I would love to do
```elixir
config :phoenix, instrumenters: [...]
config :my_app, MyApp.Endpoint, instrumenters: [...]
config :postgrex, instrumenters: [...]
```
Just to write this down somewhere where it won't get buried (instead of IRC), the problem with this is that if I change the `:instrumenter` config for the …

Various instrumentations

---

lib/phoenix/controller/pipeline.ex

It's annoying to see these generated functions show up in ExDoc documentation for Phoenix controllers. It would be better to only see the functions I defined on my `Phoenix.Controller` in ExDoc, because those are the only ones I can write documentation for.

Mark pipeline generated functions as `@doc false`

---

installer/templates/ecto/seeds.exs

Hey all!
I just wrote my first `priv/repo/seeds.exs` file for a phoenix project and noticed the helper text above doesn't include the application module name before the model name:
MyApp.Repo.insert!(%SomeModel{})
This PR changes that helper text to:
MyApp.Repo.insert!(%MyApp.SomeModel{})
Since we're already spotting the user `MyApp.Repo`, figured it was appropriate to also spot them `MyApp.SomeModel` to make the syntax crystal clear.
Thoughts?

Improve helper text in seeds.ex

---

installer/templates/static/brunch/package.json

Otherwise when you add a new dependency with `npm install --save`, brunch is alphabetically reordered in the list. This can cause confusion in a git commit.

Alphabetical order in phoenix.new package.json

---

lib/phoenix/router.ex

It wasn't obvious to me how to use path helpers for routes with glob-like patterns. This adds a short paragraph with an example about that to the router documentation.
see  #1396

example for a path helper for glob-like patterns

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

@josevalim I'd like to rename this to something like `assert_renders_error`, but I'm not liking any alternatives. Thoughts on impl and alternate name?
TODO

Add assert_sent to ConnTest

---

lib/phoenix/endpoint/cowboy_handler.ex
lib/phoenix/endpoint/handler.ex
lib/phoenix/endpoint/server.ex

- allow configuring Endpoint Handler via application config,
to pass a custom childspec to Phoenix.Endpoint.Server supervisor
- defaults to Phoenix.Endpoint.CowboyHandler

(configurable) Endpoint Handler Behaviour

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/instrument.ex

This PR adds documentation to the `Phoenix.Endpoint.Instrument` module which gives a detailed overview of the instrumentation API we added to Phoenix. Let me know how it looks!

Enhance instrumentation docs in Phoenix.Instrument

---

test/mix/tasks/phoenix.gen.model_test.exs

The change in the `test/mix/tasks/phoenix.gen.model_test.exs` avoid problems in creating folders in OS like alpine.
```shell
/azk/phoenix # mix test test/mix/tasks/phoenix.gen.model_test.exs:163
Including tags: [line: "163"]
Excluding tags: [:test]
1) test uses defaults from :generators configuration (Mix.Tasks.Phoenix.Gen.ModelTest)
test/mix/tasks/phoenix.gen.model_test.exs:163
** (File.Error) could not make directory (with -p) /azk/phoenix/tmp/uses defaults from :generators configuration (migration): protocol error
stacktrace:
(elixir) lib/file.ex:208: File.mkdir_p!/1
installer/test/mix_helper.exs:15: MixHelper.in_tmp/2
test/mix/tasks/phoenix.gen.model_test.exs:164
Finished in 0.6 seconds (0.5s on load, 0.04s on tests)
10 tests, 1 failure, 9 skipped
```

Fixing `File.Error` could not make directory (with `:`) in alpine

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/instrument.ex

The original code triggers an error in dialyzer that causes it to crash. You can verify this by adding: `{:dialyze, "~> 0.2"},` to the phoenix deps and running `mix deps.get && mix compile && mix dialyze` before and after applying this patch.
This also removes the duplication in the case clauses.

Refactor to fix dialyzer crash

---

lib/phoenix/controller.ex

The @spec said the tuple should be {atom, binary} but in `__using__` the second part of the tuple is the symbol `:app`. Seems like a symbol should be allowed so this commit adjusts the spec.

Fix dialyzer warning in put_new_layout

---

lib/phoenix/endpoint.ex

The example at https://github.com/phoenixframework/phoenix/blob/4d4f1b77/lib/phoenix/endpoint.ex#L332 uses the binary "index.html" as argument to Endpoint.Instrument, but this fails as the generated instrument function(s) have a is_map guard on the runtime argument. This changes the example to use a map instead.

Fix Phoenix.Endpoint instrument example

---

lib/phoenix/router/helpers.ex
test/phoenix/router/helpers_test.exs

Instead of simply returning an error when passing an atom to a route
helper that hasn't been defined, the error now prompts the user to input
a defined route instead.
Previously an `UndefinedFunctionError` was raised.
Now an `ArgumentError` is raised with the following message:
No route helper clause for MyApp.Router.Helpers.foo_path/2 defined
for action :skip.
The following foo_path/2 actions are defined under your router:
* :file
* :show
The only thing that is missing that I can think of is returning the error for functions which have an `arity` higher than 3.
For example:
user_channel_post_path(conn, :show, user, channel, post, foo: "bar")
**TODO**

feat(Phoenix.Router.Helpers): better errors on path helpers

---

README.md

I've updated the Important Links section to add working links to the elixir-lang IRC page and the main Freenode page.

Add IRC links for #elixir-lang and Freenode to README.md

---

README.md

Replaces wrong link 2 (freenode) with the correct link 4 (github issue tracker).

Update issue tracker link to reference correct link

---

installer/templates/static/brunch/brunch-config.js
installer/templates/static/brunch/package.json

Skip phoenix_html npm dependency when using --no-html flag

---

lib/mix/tasks/phoenix.gen.html.ex
lib/mix/tasks/phoenix.gen.json.ex
priv/templates/phoenix.gen.html/controller_test.exs
priv/templates/phoenix.gen.json/controller_test.exs

Currently if you generate a project with `--binary-id` option, this project is properly using binary IDs almost everywhere by default.
This is, however, not true about the generated tests for the controllers - for both HTML and JSON.
This pull requests fixes the tests so the generated tests are respecting global `binary_id` generators setting. Tests scaffolded using phoenix.gen.json or phoenix.gen.html after this patch do pass correctly when `--binary-id` is used.

Support --binary-id when generating scaffold

---

installer/templates/new/priv/gettext/en/LC_MESSAGES/errors.po
installer/templates/new/priv/gettext/errors.pot

If the project is generated with --no-ecto we don't want to include the
changeset error translations in .po* files.
* If the project is generated with `--no-html` and `--no-ecto` should we completely remove the `ErrorHelpers` module?
* The `phoenix.gen.json` task relies on the `ErrorHelpers.translate_error` to exist. It won't if the project is generated with `--no-ecto`, is that ok?

Don't include Ecto gettext translations if --no-ecto

---

lib/phoenix/pubsub.ex
lib/phoenix/pubsub/pg2.ex
lib/phoenix/pubsub/pg2_server.ex
test/phoenix/pubsub/pubsub_test.exs
test/shared/pubsub_test.exs

Support for scoping a broadcast is needed for Phoenix.Presence features. This PR adds scoped broadcasts via tuple to mirror the `send` api. @josevalim I could use your opinion on the API choices and configuration options. We could also make these changes backwards compatible by only invoking the adapters broadcast/5 if we have a target node, but this PR as written will break existing pubsub adapters. 
My test is also pretty weak, but without standing up a 2nd VM, I think it's the best we've got.

Support broadcasts to individual destination nodes

---

lib/mix/phoenix.ex
test/mix/tasks/phoenix.gen.model_test.exs

Mix.Tasks.Phoenix.Gen.Model does not allow :binary
typed attributes despite being a valid primitive
type. This commit adds :binary to the list of
valid types in the Phoenix module.
Fixes #1511.

Fixes Mix.Tasks.Phoenix.Gen.Model w/:binary types

---

RELEASE.md

Spotted a spelling mistake while reading -
`compatibilitiy` > `compatibility`

Fixes typo

---

lib/phoenix/channel.ex

@chrismccord Just wanted to check that you were happy with the use of `MyApp` and the line break before pushing into master.

docs(Phoenix.Channel): use ChangesetView to render changeset errors

---

installer/templates/new/test/views/error_view_test.exs
installer/templates/new/web/views/error_view.ex

I'm not sure if it was made intentionally, but when I encountered it in new app it felt weird as everywhere, even in rfc (https://tools.ietf.org/html/rfc2616#section-10.5.1) it is "Internal server error" not "Server internal error".

Change word order in 500 error messages in templates

---

lib/phoenix/controller.ex
lib/phoenix/endpoint/render_errors.ex
lib/phoenix/exceptions.ex
test/phoenix/controller/controller_test.exs
test/phoenix/endpoint/render_errors_test.exs

As discussed in #1521:
1. Raise Phoenix.NotAcceptableError in Phoenix.Controller.accepts instead of halting the connection with a 406 status
2. Rescue Phoenix.NotAcceptableError in RenderErrors.fetch_format/2 and render original error with first acceptable format.
I am not sure if this is the best place to rescue the error. And: is the halted:true-line at https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/render_errors.ex#L69 still needed?

Raise not acceptable error & fall back to first acceptable format on error

---

lib/phoenix/controller.ex
lib/phoenix/exceptions.ex
test/phoenix/controller/controller_test.exs

This is useful to render a helpful error entity for the client which includes
the acceptable mime types.
RFC 2616: "Unless it was a HEAD request, the response SHOULD include an entity containing a list of available entity characteristics and location(s) from which the user or user agent can choose the one most appropriate."
Follow up from #1521

Phoenix.NotAcceptableError contains accepts field

---

lib/phoenix/endpoint/render_errors.ex

#1521 
* removed check for halted connection in render/5
* removed double use of fetch_query_params in fetch_format/2

Endpoint.RenderErrors: cleanup render/5 and fetch_format/2

---

lib/phoenix/endpoint.ex

Ran across this minor typo when reading the docs last night.

Fix small typo in endpoint.ex documentation

---

installer/templates/static/brunch/package.json

Brunch related dependencies are meant for app development only, and we can leave
the `dependencies` group for runtime deps like `phoenix_html` and other packages
added by developers during development.

Move brunch packages to `devDependencies`.

---

installer/templates/static/app.css

Several people have been confused by the inclusion of Bootstrap and
a few CSS rule-set in static/app.css when creating new project. This
commit addresses that by expliciting stating that the content of this
file is only here for convenience and can be safely deleted.

Add a disclaimer to static/app.css for new project

---

config/config.exs
lib/phoenix/controller/logger.ex
lib/phoenix/endpoint/instrument.ex
lib/phoenix/socket/transport.ex
test/phoenix/controller/logger_test.exs
test/phoenix/endpoint/instrument_test.exs
test/phoenix/integration/long_poll_test.exs
test/phoenix/integration/websocket_test.exs

I'm not entirely happy with this PR but I thought I'd gather feedback before going any further:
* Although I think we should be DRY and not duplicate the `filter_value/2` in two different places `Phoenix.Logger.Filter` doesn't feel like the right module name for that. Any suggestions?
* I kept the tests for filtering in `test/phoenix/controller/logger_test.exs`, although they are a bit redundant with the tests I have in `test/phoenix/logger/filter_test.exs` I still feels better having them here.
* That being said I should probably have equivalent tests for `lib/phoenix/socket/transport.ex`
Let me know your thoughts and I'll fix the PR.

Filter payload on channel join

---

installer/templates/new/priv/gettext/errors.pot

I noticed this when I ported the new informative comments into Gettext (https://github.com/elixir-lang/gettext/commit/c132d0ad1530aaae882993105b7011f99428a634).

Fix a typo in a comment in the installer

---

lib/phoenix/template.ex

Without this typespec, running Dialyzer on fresh Phoenix project gives
following warnings:
`layout_view.ex:2: Function template_not_found/2 only terminates with explicit exception`
`page_view.ex:2: Function template_not_found/2 only terminates with explicit exception`
This pull request has two problems:
- added typespec uses built-in `binary` type instead of `Phoenix.Template.name` one.
- typespec is added inside the quoted code of the `__using__` macro. I'm not sure, if it's correct place for it.

Add typespec for Phoenix.Template.template_not_found/2

---

lib/mix/tasks/phoenix.gen.secret.ex
test/mix/tasks/phoenix.gen.secret_test.exs

Regarding #1587 set a minimum length to mix phoenix.gen.secret.
I've set the minimum length to 32 characters, and it will raise on anything shorter.

Set minimum length to mix phoenix.gen.secret

---

installer/templates/new/lib/application_name.ex

There's a very tiny race condition here on startup, where if you make an
HTTP request right as the Endpoint process has started, but before the
Repo process has started, you'll receive an error saying that the Repo
process hasn't started yet. To avoid these errors let's start the Repo
process first since most Endpoints will most likely depend on access to
the database.

Start Repo process before accepting HTTP requests

---

lib/phoenix/router/scope.ex
test/phoenix/router/resources_test.exs

This shows a warning anytime you declare a path that doesn't start with a `/` in a `Router`. This is only for consistency in router files. Not including the `/` still works. Closes #1438.
All of the router macros (http verbs, trace, options, connect, match, and resources) go through the `Scope.route/7` function, so I thought that'd be a good place to put the validation. Otherwise, all slashes are removed and reconstructed in the `Scope.join_path/2` function which is called inside `Scope.route/7`.
The `scope` macro doesn't go through `Scope.route/7`, so it gets its own validation. I wasn't sure how to do it via pattern matching with the `opts` in `push(module, opts)`, so I just used an `if` statement. Any feedback here?
I was torn on splitting up the `router_test` and `scope_test` that I …

Warn on router paths without leading slash

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

(or text_response errors)
What should it do if the body isn't a string or is really long?
~~also, it currently shows the JSON unparsed. maybe not the best~~
ref: https://groups.google.com/forum/#!topic/phoenix-talk/Y5g6cqkPk0o

conntest: include body in json_response errors

---

lib/phoenix/presence.ex
priv/templates/phoenix.gen.presence/presence.ex

The Phoenix.Presence examples in both the source and the generated file use `state` instead of `socket`, and also return a tuple instead of simply `:ok` as stated. This corrects all four instances.

Fix typos in Phoenix.Presence example docs

---

lib/phoenix/digester.ex
test/fixtures/digest/priv/static/css/app.css

This PR fixes the regex to match urls in compressed stylesheets generated by brunch or webpack, otherwise stylesheets will reference non-digested versions of assets

Fix regex to match urls in compressed stylesheets

---

installer/templates/static/brunch/brunch-config.js

It was pointing to `stable` and 404'ing on GitHub. Switching it to
master fixes it.

Fix the brunch configuration documentation link

---

lib/phoenix/endpoint/adapter.ex

This may seem a bit pedantic, but it's potentially confusing because the current warning message looks like the period is part of the file name.

Fix placement of period within quotes in static cache manifest warning.

---

lib/phoenix/channel/server.ex
lib/phoenix/socket/transport.ex
lib/phoenix/transports/long_poll_server.ex
lib/phoenix/transports/websocket.ex
priv/static/phoenix.js
test/phoenix/integration/long_poll_test.exs
test/phoenix/integration/websocket_test.exs
test/phoenix/transports/transport_test.exs
web/static/js/phoenix.js

- Transport store join ref with channel pid and relay when channel closes/errors.
- Transport closes existing channel if client races a duplicate join.
- Last join wins and client properly filters channels specific phx_close/phx_error events.
@josevalim if you have time I could use a review here since it will effect @sasa1977's recent work.

Resolve join/leave race conditions from the client. Closes #1485

---

CHANGELOG.md

Noticed a small typo in the changelog.

Typo: unsubscibe -> unsubscribe (2x)

---

lib/phoenix/test/conn_test.ex

Took me a little bit to debug what was going wrong with my tests where I was being lazy and passing a model as a param. Ended up finding that the Plug test adapter does not normalize structs, and thought that documenting that in Phoenix might be useful for others who run into the situation.

Document dispatch behaviour for struct params

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/adapter.ex
test/phoenix/endpoint/adapter_test.exs

I'm deploying the same code for multiple clients with different URLs. I can solve this with multiple builds, but being able to specify it from the environment (like the port) would be excellent.

Support reading the host from the environment at runtime

---

lib/phoenix/endpoint/cowboy_handler.ex

This PR changes the message displayed by running `mix phoenix.server` to include a clickable link. For example, it'd be:
`Running Hello.Endpoint with Cowboy on http://localhost:4000`
Thought this would be a nice feature—let me know what you think. I might've missed some stuff like other domains. Thanks!

Add clickable link to server info

---

lib/phoenix/template.ex
test/fixtures/templates/user/render_template.html.eex
test/fixtures/views.exs
test/phoenix/view_test.exs

Useful for overriding render/2 clauses for precompiled
templates to compose assigns before rendering template

Add private render_template clauses. Closes #1655

---

installer/lib/phoenix_new.ex

While I was reading the book I found these extra spaces when I ran the installer.

Fix a few typos in phoenix.new installer

---

lib/mix/phoenix.ex
test/mix/phoenix_test.exs

Previously the dates and times would be passed as "2010-04-17" or
"14:00:00" in the tests. These would not be recognized by phoenix_html
resulting in an "unrecognized date" error.
Fixes #1660

Use datetime types recognized by phoenix_html in generators

---

installer/templates/new/config/config.exs
installer/test/phoenix_new_test.exs

I generated an app today (from `master`) w/ the `--no-ecto` option and I noticed that the `config.exs` file still contained the `ecto_repos: [MyApp.Repo]` config.
Thanks for the project!

Omit `ecto_repos` config when generating with `--no-ecto`

---

installer/templates/new/config/config.exs
installer/test/phoenix_new_test.exs
lib/mix/phoenix.ex
lib/mix/tasks/phoenix.routes.ex

When using generators, `Mix.Phoenix.base/0` looks for the `:namespace` config option not `:app_namespace`.
https://github.com/phoenixframework/phoenix/blob/master/lib/mix/phoenix.ex#L145
This not only fixes a bug but also makes this option consistent with the `:namespace` option for views.

Fix namespace option for generators

---

installer/templates/static/brunch/package.json

When installing other packages, `npm` reformats `package.json` to remove the extra line break. This creates more action than necessary in the commit.
This PR cleans up default formatting of `package.json`, making it match more closely to `npm` standards.

reformat JSON entry for repository.

---

installer/templates/static/brunch/package.json

This PR serves the same purpose as #1683, but without conflicts.

resolve npm warn regarding SPDX license expression.

---

README.md

This commit refactors the instructions on how to create a project
using github source to make it more explicit and easier to follow for
new comers.

Improve instructions on how to build from source

---

test/fixtures/manifest_upgrade.json
test/phoenix/endpoint/endpoint_test.exs

I thought there was an issue with `Endpoint.static_path(some_path)` not getting updated when there was a config change. This test proves that this isn't the case.
What was actually happening in my case was that `Endpoint.config_change` never got called, and thus the cache was never purged, causing `Endpoint.static_path` to return the stale cached paths. In order to force `config_change` to be called, [I added my app :version to the `Endpoint` config](https://github.com/bitwalker/exrm/issues/206#issuecomment-212538439).

Add a test for re-reading manifest.json on config change.

---

lib/phoenix/naming.ex
test/phoenix/naming_test.exs

Closes #1692
This PR makes it possible to pass a `:lower` option to `Phoenix.Naming.camelize`:
```ex
Phoenix.Naming.camelize("my_app") # "MyApp"
Phoenix.Naming.camelize("my_app", :lower) # "myApp"
```
Thanks to @chrismccord for the help!

Add `:lower` option to Phoenix.Naming.camelize

---

installer/templates/new/web/channels/user_socket.ex
lib/mix/tasks/phoenix.gen.channel.ex
lib/phoenix/channel.ex
lib/phoenix/socket.ex
lib/phoenix/test/channel_test.ex
test/phoenix/integration/long_poll_test.exs
test/phoenix/integration/websocket_test.exs
web/static/js/phoenix.js

Makes use of singular topic names for docs and tests per convention for naming channels as mentioned here: [#1696](https://github.com/phoenixframework/phoenix/issues/1696)

Updates docs per singular topic convention for channels

---

priv/templates/phoenix.gen.channel/channel.ex
test/mix/tasks/phoenix.gen.channel_test.exs

The generated test of handle_out/3 was passing for the wrong reason. The generated version of handle_out/3 was never invoked, because the "broadcast" event was not being intercepted.
~~Add `intercept` call to generated channel module, so that the test continues to pass, now for the right reason. That reason being, the generated version of handle_out/3 is invoked which pushes the payload back to the socket.~~
The handle_out/3 function is not needed in many cases and is generally considered an advanced feature. No need to generate it with all channels.
h/t @nathanl for pairing

Remove handle_out/3 from generated channel

---

lib/phoenix/test/channel_test.ex
test/phoenix/test/channel_test.exs

This uses code lifted from `Plug.Adapters.Test.Conn` to stringify map keys pushed to a channel under test. See: https://groups.google.com/forum/#!topic/phoenix-core/keDSxYg_jSQ

Stringify parameter keys pushed to a channel in test

---

lib/phoenix/controller.ex

When we have an invalid `redirect to:` path, we were getting an error like this:
```
** (exit) an exception was raised:
** (ArgumentError) the :to option in redirect expects a path
```
Which was not very helpful. Which didn't give much information about the issue.
I have made a small change that makes it more clear. With this pull request we get a message like this:
```
** (exit) an exception was raised:
** (ArgumentError) the :to option in redirect expects a path but was "http://localhost:4000/login"
```
Which gives a better idea where the error came from.

Improving error message when invalid redirect to: path

---

package.json

* Fix description to more closely match the published package contents.
* Add SPDX-compatible license expression (to match Phoenix's license).
---
This will clean up the published metadata on npmjs.com.

Add additional data for npm

---

CHANGELOG.md
installer/templates/new/config/config.exs
installer/templates/new/config/dev.exs
lib/phoenix/endpoint/adapter.ex
lib/phoenix/endpoint/watcher.ex
test/phoenix/endpoint/watcher_test.exs

Support System.cmd options for watchers instead of root config

---

installer/templates/ecto/model_case.ex

In Ecto 2.0.0 (currently in RC), errors take on a different format and look like this:
```elixir
[username: {"can't be blank", []}]
```
[see docs for 2.0.0-rc.5](https://hexdocs.pm/ecto/2.0.0-rc.5/Ecto.Changeset.html)
whereas before, they looked like this:
```elixir
[username: "can't be blank"]
```
[see docs for 1.1.7](https://hexdocs.pm/ecto/Ecto.Changeset.html)
The current function for `errors_on` will not work with this new error format, so I've updated it to parse the errors first so it can be used the same way as before, like this:
```elixir
assert {:username, "can't be blank"} in errors_on(%User{}, %{username: nil})
```

Update errors_on in model_case to refelct Ecto 2.0.0 errors changes

---

lib/phoenix/test/conn_test.ex

New to contributing, so I don't know if this is too minor for a pull request, but here goes.
Stumbled upon it while testing a Plug and had to do a double take because of the "@spec build_conn()" above the conn function. Even though it is minor, I think it's worth fixing.
If I made a mistake with the typespecs, let me know!

Fix a typo in the conn() deprecation notice; improve the build_conn() typespec

---

lib/phoenix/controller.ex
mix.exs
mix.lock

Current plug has ugly deprecated warnings when using Plug.MIME.
Using mime here as a seperate dependency omits those warnings and is backwards compatible with old plug versions.

add mime as standalone dependency

---

lib/phoenix/endpoint.ex

Secrets are used for encryption rather than encoding data. 🔑

Update documentation for endpoint.ex

---

lib/phoenix/controller.ex
lib/phoenix/test/conn_test.ex

The Plug.MIME library was still called in some places, which generates ugly warning messages with current Plug.

call the standalone MIME library in all places

---

lib/phoenix/router/helpers.ex
test/phoenix/router/helpers_test.exs
test/phoenix/router/routing_test.exs

Route helpers encode named param segments with
URI.encode_www_form, but when named params are
received from new requests, the values were not
decoded, leading to a mismatch between how the
helpers encode params and how the route decodes
them. For example, previous behavior:
profile_path(conn, :show, "my name")
=> "/users/my+name"
params
=> %{"id" => "my+name"}
Fixed behavior:
profile_path(conn, :show, "my name")
=> "/users/my+name"
params
=> %{"id" => "my name"}
@josevalim I'd appreciate a sign-off on this one

Properly encode named params.

---

lib/mix/tasks/phoenix.gen.model.ex
test/mix/tasks/phoenix.gen.model_test.exs

`mix phoenix.gen.model Score scores score:integer user_id:references:users:unique` currently creates two indices (with the same name)
When running the created migration this gives an error
```
00:32:35.055 [info]  == Running EcPredictions.Repo.Migrations.CreateScore.change/0 forward
00:32:35.056 [info]  create table scores
00:32:35.077 [info]  create index scores_user_id_index
00:32:35.078 [info]  create index scores_user_id_index
** (Postgrex.Error) ERROR (duplicate_table): relation "scores_user_id_index" already exists
```
This pull requests filters out the normal index you get with an association.
Also adds a test for the fact that an index is added when adding a belongs_to field

Add only one index

---

installer/lib/phoenix_new.ex
installer/templates/new/config/config.exs

Previously the config for the phoenix generators was appended to the
file. This is technically not a problem, however the comment for the
`import_config "#{Mix.env}.exs" explicitly states that it should be at
the bottom of the file.
Before:
import_config "#{Mix.env}.exs"
config :phoenix, :generators,
binary_id: true
After:
config :phoenix, :generators,
binary_id: true
import_config "#{Mix.env}.exs"
The spacing in the template is deliberate to ensure there is only a
single space between the blocks.

Fix binary-id generator location in config/config.exs

---

lib/phoenix/test/conn_test.ex

The first arg for `put_req_header` should be the `conn` itself.

Use put_req_header correctly in recycle documentation

---

installer/lib/phoenix_new.ex

Warn the user that the directory already exists and give them the
option to cancel.

Give user the option to install over existing dir.

---

installer/templates/static/brunch/brunch-config.js

The current link [https://github.com/brunch/brunch/blob/stable/docs/config.md#files](url) to the Brunch documentation in brunch-config.js does not work anymore due to
> The docs were moved to the Brunch website: http://brunch.io/docs/config
this pull request updates the link to the "Files" section. Also it removes the link [https://github.com/brunch/brunch/tree/master/docs#concatenation](url) as there is no direct reference to this topic in the current Brunch documentation.

Update brunch-config.js documentaion links

---

mix.exs

This change allows `.svg` files to be gzipped along with the rest of the text based assets (like js and css). Please let me know what you think and if I need to update anything else.

Add .svg to default gzippable_exts

---

installer/lib/phoenix_new.ex

In this pull request I've changed the phoenix.new script to now use Mix.shell.cmd/2 instead of :os.cmd/1, because according to the comments it caused some problems on Windows systems. This is possible now because the Mix.shell.cmd/2 function supports the 'quiet: true' option.
I've also added error handling where the return code of the shell command is checked. 
Because I reside in China at the moment, on numerous occasions my 'mix deps.get' command failed because of the Chinese firewall randomly dropping connections without the phoenix.new script informing me that the command failed.
Up for debate is still how to properly handle the error. Instead of printing an error message we could of course also stop the script, but this might be a little bit too intrusive since just running the …

Improve phoenix.new with Mix.shell.cmd/2 and error handling

---

lib/phoenix/token.ex

It was interpreted as code block, not bullet list.
**Before:**
**After:**

Doc: fix indentation of bullet list in token.ex

---

lib/phoenix/test/channel_test.ex

Add `@spec` and fix document in `Phoenix.ChannelTest`
I think `push` returns `reference()`, not `:ok`.

add spec and fix doc in channel test

---

lib/phoenix/channel.ex

`Enum.reduce` has to return the accumulator otherwise in this example `MyApp.Endpoint` just subscribe 1 `topic` in list `topics`.
Example:
topics = ["user:1", "user:2"]
without return `acc`:
`iex> "user:1"`
and return `acc`:
`iex>"user:1"`
`iex>"user:2"`

fix phoenix channel doc Subscribing to external topics

---

lib/phoenix/test/conn_test.ex

Fixes a very small typo in `Phoenix.ConnTest` docs for `recycle/1`

Fix a tiny, tiny typo

---

lib/phoenix/router.ex

This is a proposal to add a check for the `scheme` field of the Plug.Conn when generating URLs with the Router Helpers.
My use case was the following:
I have a phoenix server running behind an SSL proxy (ELB in this case) and I wanted to return URLs with a scheme based on the protocol the client uses. (Which is set through "x-forwarded-proto")
Thoughts? :smile:

Add docs for URI argument in Router url helpers

---

installer/templates/new/test/support/channel_case.ex
installer/templates/new/test/support/conn_case.ex

When generating with the `--no-ecto` option, both `ConnCase` and `ChannelCase` were issuing an unused variable warning.

Silence unused warnings in support test cases

---

lib/phoenix/endpoint/cowboy_handler.ex

write actual addr in log
bug describe:
server's log always show `localhost`, even it's setuped by user, like that:
```
[info] Running Demo.Endpoint with Cowboy using http://localhost:4000
```
It will make user confused.

write actual addr in server's log

---

priv/static/phoenix.js
web/static/js/phoenix.js

While trying out the new and exciting Presence feature I've just discovered phoenix.js documentation is wrong. In the example it says you should listen to `presences` room channel event to get the current presence of the room channel after you join it. It seems listening to that event doesn't trigger anything. However changing it to `presence_state` does the job.
Edit: Just realized you can use the event name you prefer in the `handle_info(:after_join)` call. In this case `presence.ex` [doc](https://github.com/phoenixframework/phoenix/blob/f7ea46ea581d96ef40245264085369261d195473/lib/phoenix/presence.ex#L46) says `presence_state` so rather than a documentation fix I'd say this PR is a consistency improvement.

Make phoenix.js doc consistent with presence.ex

---

lib/phoenix/test/channel_test.ex

These assertion macros are potential sharp points, since they are
patterns.  This provides documentation to call this out a bit more
explicitly.

Add documentation to assert_push

---

installer/templates/ecto/model_case.ex

With the new error format in Ecto 2, this is no longer true.

Remove out of date docs for errors_on

---

lib/phoenix/naming.ex
test/phoenix/naming_test.exs

I noticed an issue when I created a new phoenix application with:
`mix phoenix.new channel_test_2`, which produced modules named `ChannelTest2...`
but when I created a new channel like:
`mix phoenix.gen.channel Room`, the channel and test module were named `ChannelTest_2.RoomChannel` and `ChannelTest_2.RoomChannelTest`.
I dug into this and noticed that `phoenix.new` uses `Macro.camelize`, while `phoenix.gen.channel` uses  `Phoenix.Naming.camelize`, which didn't handle the `_2` case the same as `Macro.camelize`. This PR makes `Phoenix.Naming.camelize` behave similarly, at least for the _[some digit] case.
`Phoenix.Naming.underscore` already behaves in a manner similar to `Macro.underscore`, so no changes were needed there.
**Note**
Camelizing _[digit] is a little weird, as formatting will …

Phoenix.Naming.camelize behavior similar to Macro.camelize for strings like 'module_name_N' where N is a digit

---

lib/phoenix/transports/websocket.ex

Allow to force WebSocket transport process garbage collection with `send socket.transport_pid, :garbage_collect`. Could be useful after processing large messages.

New feature: Force WebSocket transport garbage collection

---

installer/templates/ecto/seeds.exs

A very minor tweak, but I feel like the proposed change is much clearer. The current text in `seeds.exs` is rather redundant.. "as they will fail if something goes wrong" can be said about literally any failure, anywhere. Specifying that execution will be halted if something goes wrong more clearly conveys the intended use of bang functions

Use clearer language when recommending bang functions in seeds

---

lib/phoenix/controller.ex

This is how it is described in the Plug documentation because the old way is
no longer supported.
https://github.com/elixir-lang/plug/blob/master/lib/plug/mime.ex#L6

Update docs to new method of adding a MIME

---

priv/templates/phoenix.gen.presence/presence.ex

Hi,
I just started to play with `Phoenix.Presence`.
I guess the `push` to the socket has to be done after `Phoenix.Presence.track` in the doc, which I guess it would track the data in his own process and *then* send the presence list to the clients
Thanks!

push socket should be before Presence.track in doc

---

lib/phoenix/template.ex

Following the discussion on the mailing list: https://groups.google.com/d/msg/phoenix-core/mElIxJkO8RU/5zYSjqUBDQAJ

List assigns keys on template mismatch errors

---

lib/phoenix/controller.ex
lib/phoenix/endpoint.ex

Hi,
Currently there no way to distinguish views and this patch fixes this.
When applied metadata looks like this:
```elixir
%{format: "json-api", template: "index.json-api", view: Api.UserView}
```
Can this be applied to 1.2 branch as well? 
Thank you.

Add :view key to phoenix_controller_render event metadata

---

package.json

Packages published to NPM better include its original source files, as the they are not meant to be served directly. (although can be, through npmcdn or other services)
Including the original es6 code enables all sorts of nice functions in build tools.

Expose source es6 file too in npm package

---

priv/templates/phoenix.gen.model/migration.exs

It's just a small thing that has been bugging me for while.
When generating a migration, an empty line is added after the last `create index`. This removes the empty line added after the indexes creation and adds one just before.
Old behaviour:
```elixir
defmodule MyApp.Repo.Migrations.CreateMyTable do
use Ecto.Migration
def change do
create table(:my_table) do
end
create index(:my_table, [:col_a])
create index(:my_table, [:col_b])
end
end
```
New behaviour:
```elixir
end
create index(:my_table, [:col_a])
create index(:my_table, [:col_b])
end
end
```

Remove empty line after indexes in migrations

---

lib/phoenix/endpoint.ex

If `config[:url][:host]` is a tuple in the format {:system, env_var}, get the specified env var and pass _that_ as the host for force_ssl, as is done for `Endpoint.Adapters.url/1`
Resolve #1883

Get host from system env for force_ssl if specified

---

lib/phoenix/endpoint.ex

Specify that `Plug.SSL` is forwarded `:host` from `:url`'s config
Describe how to use `Plug.SSL`'s default host value by setting to `nil`
See #1571

Update Endpoint docs to better explain force_ssl config

---

lib/phoenix/socket/transport.ex

Fix typo in Transport comments

---

lib/phoenix/endpoint/watcher.ex

fixes issue #1870 
If System.cmd returns a non-zero exit code in watcher this will sleep a few seconds (to avoid hitting the max restarts / max seconds of the supervisor) and then exits and is restarted.
I'd spoken with Chris last week about logging something when we do this but after having played with it I think the output from brunch is probably sufficient for the user to understand what's happening.
Example:
```
/Users/adamkittelson/Code/apathy-drive-ex/brunch-config.js:11
'web/static/js/app/jquery-1.10.2.min.js':
^
Error: couldn't load config /Users/adamkittelson/Code/apathy-drive-ex/brunch-config.js. SyntaxError: Unexpected token :
at Object.exports.loadConfig (/Users/adamkittelson/Code/apathy-drive-ex/node_modules/brunch/lib/helpers.js:592:13)
at initialize …
```

restart Watcher when it crashes

---

lib/phoenix/channel.ex

Just a little something I stumbled upon reading the channels docs.

Fix a module definition typo in the channels docs

---

lib/phoenix/channel/server.ex

I noticed the other day that if I returned `{:noreply, socket, :hibernate}` in a handle_info callback in one of my Channels that I received an error. I spoke briefly with @chrismccord about it this afternoon to check if it was a design decision and he invited me to make a PR.
Thanks!
Adam

handle 3-element :noreply tuple results the Channel server handle_info callback

---

lib/phoenix/controller.ex
lib/phoenix/endpoint.ex

Hi, I was just digging into the instrumentation and thought this would be a nice addition to the event data for `:phoenix_controller_render`. In particular I think it would enable correlation of render/call events and make it much simpler to get any custom data to the render instrumentation in the future.
If this is acceptable I will also update the Endpoint documentation.

Add conn to runtime data in render instrumentation

---

lib/phoenix/transports/long_poll_server.ex

I am aware that this is not the most useful change in the world, but I've literally just started to read and understand this source code and this is the most I can contribute at this time :)

Fix typo in Phoenix.Transports.LongPoll.Server documentation

---

lib/phoenix/endpoint/server.ex
test/phoenix/integration/endpoint_test.exs

For example:
config :my_app, MyApp.Endpoint,
http: [{:port, 4000}, :inet6]
Redo of #1932 plus a test

Allow non-keyword list in Endpoint http config

---

lib/phoenix/endpoint/render_errors.ex
test/phoenix/endpoint/render_errors_test.exs
test/phoenix/integration/endpoint_test.exs
test/test_helper.exs

Potential fix for #1920 
On screenshot displayed traffic for 2 get requests which render 404 page.
First request was made before fix and contains one extra 204 response,
second request was made after fix and contains only one response.

Fix extra 204 response when 404 error and debug_errors enabled

---

lib/phoenix/controller/pipeline.ex
lib/phoenix/exceptions.ex

I was passing params to a create action and got this error.
I eventually figured it out but found the error message to be unclear. I put what I thought was more human readable. Open to other message ideas or if I'm missing some common terminology concepts that I'm not considering.

made missing parameter error message more human readable

---

installer/lib/phoenix_new.ex
installer/lib/phx_new.ex

Looks like this change fixes the random build failures.
I'm still not exactly sure what's causing this, but it looks like calling the task directly (rather than going through Mix.TasksServer) fixes it - some race conditions, silent failure maybe? At the very least I was able to get a consistent repro test, see this commit message & content: https://github.com/wojtekmach/phoenix/commit/552b00a55c1924ae82f1fb0957d8ed1c4014dfde - perhaps someone more experienced might have better luck tracking it down :-)

Fix flaky installer tests

---

installer/templates/assets/brunch/package.json
installer/templates/static/brunch/package.json

The are 2 ways to ensure deploy reliability with npm versions:
a. The perfect way: Use [npm-shrinkwrap.json](https://docs.npmjs.com/cli/shrinkwrap); or
b. The "this will do" way: Lock versions of direct dependencies using `--save-exact`.
This does (b), since (a) is a pretty cumbersome thing to maintain, especially to those new to the npm ecosystem. While it's not as perfect as (a), it does the job most of the time.
This protects users from strange behaviors that may be introduced by new versions of Brunch plugins. I don't have an example of that at the moment, but Brunch itself has had many of those from 2.0 to 2.6 (phoenix has had Brunch's version locked already).

Brunch: lock npm dependency versions

---

lib/phoenix/endpoint.ex

While recently studying the innards of Phoenix, I noticed that there appears to be partial-implementations of Plug.Builder in a few places. Namely the endpoint and controller code. I thought router may be at fault too, but realized it's a little different with pipelining.
The endpoint work was straightforward with a couple small caveats. However, the controller proved me be trickier due to the instrumentation that's happening. Rather than trying to figure that all out, I've opted to offer the endpoint changes which may spark inspiration to dig in other places.
Two of them:
1. As of 1.2, Plug.Builder raises an error when nothing is plugged. By default Phoenix.Endpoint has no plugs. In order to keep it happy, a "dummy" function must be plugged. However, this [has been removed from …

Replace endpoint manual builder impl with Plug.Builder

---

priv/templates/phoenix.gen.html/edit.html.eex
priv/templates/phoenix.gen.html/index.html.eex
priv/templates/phoenix.gen.html/new.html.eex
priv/templates/phoenix.gen.html/show.html.eex

Just some simple span tags around it fixes it on the 3.x and 4.x CDN versions of Bootstrap I've tested.

Fix spacing between generated Edit and Back links.

---

lib/phoenix/controller.ex
test/phoenix/controller/controller_test.exs

HTTP Accept headers with media range without subtype should be accepted if the Plug accepts a media-type matching the base type specified in the header.
eg. Accept text/* should be accepted for text/html, text/plain etc.
RFC: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
This change doesn't affect the order in which types are currently processed in the content negotiation, just adds the ability to match media types with an empty subtype.

Accept media-range with empty subtype

---

lib/phoenix/param.ex

The documentation for `Phoenix.Param` appears to be out of sync with the implementation. It says:
> By default, [Phx] implements this protocol for [...] maps. For maps
> and structs, a key :id is looked up.
However the Map [implementation](https://github.com/phoenixframework/phoenix/blob/655f45bf9cf6cc0b1d85af3d1c9c43afbcacaf1a/lib/phoenix/param.ex#L75-L80) of the protocol raises an error.
The most obvious and easiest solution would be to update the documentation to match the implementation (it [was added](https://github.com/iamvery/phoenix/commit/9f668b05b57e9bc160b30397177a7e96e87b4fb3#diff-bfdd7e816187d8bfe18e7eb889727fcb) before [map support was removed](https://github.com/iamvery/phoenix/commit/870e779d593f19871d32f48e4f2440f25ced939d#diff-bfdd7e816187d8bfe18e7eb889727fcb)) , but …

Phoenix.Param for maps

---

installer/templates/assets/brunch/app.js
installer/templates/static/brunch/app.js

Currently when generating a phoenix app with `--no-html`, it will still try to import the phoenix_html javascript dependency.
```
Resolving deps of web/static/js/app.js failed. Could not load module 'phoenix_html' from '.../web/static/js'. Possible solution: add 'phoenix_html' to package.json and `npm install`.
```

Do not import phonix_html when generating with --no-html

---

lib/phoenix/token.ex

Fix warning when generating docs, backquotes were not closed correctly.

Fix unclosed backquotes in Token docs

---

installer/templates/assets/brunch/gitignore

Hey!
I found it very annoying to have to add `npm-debug.log` to my gitignore whenever I created a new project. All I did was add it to `installer/templates/assets/brunch/gitignore`, hopefully thats all I need to do?
Thanks.

Add npm-debug.log to gitignore

---

lib/phoenix/token.ex
lib/phoenix/transports/long_poll.ex
lib/phoenix/transports/long_poll_server.ex

Elixir spec for `System.time_unit` doesn't include underscore versions (though they still work at runtime). Therefore, in a Phoenix dependent project dialyzer will generate errors (e.g. when invoking `Phoenix.Token.sign`).
Looking at Elixir docs, it seems that the decision to not support underscore style of units is deliberate. Therefore, it seems reasonable to use Elixir style of time units in Phoenix.

replace `milli_seconds` with `milliseconds`

---

lib/phoenix/channel.ex
lib/phoenix/logger.ex
lib/phoenix/socket.ex
lib/phoenix/socket/transport.ex
test/phoenix/integration/long_poll_test.exs
test/phoenix/integration/websocket_test.exs
test/phoenix/logger_test.exs

/cc @josevalim 
We can also ditch the clauses in the Phoenix.Logger that match on the "phoenix" topic since they are there to silence the live reloader channel, which can now simply do `log: false` internally.

Add configurable logging to channels

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

I was trying to send an empty response according to [this](http://www.phoenixframework.org/docs/controllers#section-sending-responses-directly). But in my tests, I was getting `** (CaseClauseError) no case clause matching: {:error, :invalid}`
According to poison `{:error, :invalid}` is a possible response in decode (https://github.com/devinus/poison/blob/master/lib/poison.ex#L66). However, it's just not being handled in `json_response`. I added a clause to handle this scenario.
I ended up using [response/2](https://hexdocs.pm/phoenix/Phoenix.ConnTest.html#response/2) to make the assertion in my test. Should the error message suggest to use this other function?

Handle empty json in json_response

---

lib/phoenix/token.ex

* I found it very confusing to have "user" as the salt argument.
* Changed the salt from "user" to "tokensalt123".
* Added documentation briefly describing the salt with a link
to wikipedia entry.
* Added documentation briefly describing the fact that the third
argument can be any Elixir term which was very useful for me
but not obvious since the functions do not have specs.

Tweaked `Phoenix.Token` documentation.

---

installer/templates/assets/brunch/brunch-config.js
installer/test/phx_new_test.exs
installer/test/phx_new_umbrella_test.exs

In brunch 2.8.2 the following is valid in autoRequire:
"js/app.js": ["app"]
In brunch 2.9.1 this has to be:
"js/app.js": ["js/app"]
Otherwise the following error will be logged and the JavaScript will not
execute:
> Uncaught Error: Cannot find module 'js/app' from '/'
The difference in the compiled JavaScript prior to this change was:
$ diff /tmp/app-broken.js /tmp/app-working.js
151c151
< require.register("js/app.js", function(exports, require, module) {
---
> require.register("app.js", function(exports, require, module) {
I'd appreciate if someone else could validate the solution just to make sure it isn't only happening to me.

fix brunch-config.js in installer to be compatible with 2.9.1

---

CHANGELOG.md
lib/phoenix/controller.ex
test/phoenix/controller/controller_test.exs

@josevalim I wasn't sure the best place for these to live. My first goto was the Router.Helpers, but there is no need for us to inject the functions, and the module itself is private (moduledoc false). They are also more discoverable on Phoenix.Controller, but we'll have to import them in web.ex/view, or have folks import as needed. Wdyt?

Introduce current_path and current_url

---

package.json
web/static/js/phoenix.js
web/test/socket_test.js

This PR adds a few mocha tests for the `Socket` object in `phoenix.js`.
I'm opening this PR as a potential starting point for building out a suite of unit tests for the javascript functionality provided by `phoenix.js`. Though only just a few tests, there are already a few key decision points where I'm looking for feedback before I get too far.
Though `phoenix.js` touches a few browser APIs, I decided to stick with the Node.js context for the tests for simplicity. This means introducing a few libraries, e.g., `jsdom`, `jsdom-global`, `mock-socket`, to mock out those dependencies. We could certainly run the tests in a browser-based runner, e.g., karma, testem, etc., instead (or do both!), though the approach I went with was consistent with the existing presence tests. Looking for comments. …

Add socket.js tests

---

web/static/js/phoenix.js

If you set xhr.timeout in IE11 before calling open it raises an InvalidStateError.
Relevant documentation: https://msdn.microsoft.com/en-us/library/cc304105(v=vs.85).aspx
This is the reason LongPoll does not work in IE11.

Fix IE Bug

---

web/static/js/phoenix.js

Extract serialization out so anyone can swap the serialization method. I'm currently using this for MessagePack serialization. It will fallback to JSON if LongPoll is detected.
This would allow someone to write a different serializer such as:
``` javascript
import msgpack from "msgpack-js-v5"
export default class MsgPackSerializer {
contentType() { return "application/msgpack" }
isBinary() { return true }
binaryType() { return "arraybuffer" }  
encode(payload, callback) {
callback(msgpack.encode(payload))
}
decode(payload, callback) {
var fileReader = new FileReader()
fileReader.onload = function(e) {
let bytes = new Uint8Array(e.target.result.slice(0, e.target.result.byteLength))
//console.log("about to decode message, that starts with", bytes);
let msg = msgpack.decode(bytes) …
```

Extract serialization into a separate class

---

priv/templates/phoenix.gen.model/migration.exs
priv/templates/phoenix.gen.model/model.ex
test/mix/tasks/phoenix.gen.model_test.exs

FIX #1605
Adding a foreign_key to the belongs to so that the key can be changed without having to update the migrations
With help from @trevoke

Adding foreign key to the generated belongs to

---

lib/phoenix/socket/transport.ex
lib/phoenix/test/channel_test.ex

This fixes following messages while testing channels:
```
12:33:32.295 application=app [error] Instrumenter Phoenix.Logger.phoenix_channel_join/3 failed.
** (CaseClauseError) no case clause matching: :error
(phoenix) lib/phoenix/logger.ex:94: Phoenix.Logger.channel_log/3
(vok_web) lib/vok_web/endpoint.ex:1: VOKWeb.Endpoint.instrument/4
(phoenix) lib/phoenix/test/channel_test.ex:330: Phoenix.ChannelTest.join/4
test/channels/transport_channel_test.exs:11: VOKWeb.TransportChannelTest.__ex_unit_setup_1/1
test/channels/transport_channel_test.exs:1: VOKWeb.TransportChannelTest.__ex_unit__/2
(ex_unit) lib/ex_unit/runner.ex:289: ExUnit.Runner.exec_test_setup/2
(ex_unit) lib/ex_unit/runner.ex:247: anonymous fn/2 in ExUnit.Runner.spawn_test/3
(stdlib) timer.erl:166: :timer.tc/1
(ex_unit) …
```

Make channel `log_join` and `log_handle_in` configs work with ChannelTest

---

.travis.yml

It looks like we'll get 1.4 soon, and I thought adding the release
candidate to the travis matrix as an allowed failure might help in
finding and squashing any bugs in the release candidate, as well as
give folks time to make any updates or address any deprecations that
might be coming in 1.4.

Add Elixir 1.4 to travis allowed failures

---

lib/phoenix/router.ex
test/phoenix/router/route_test.exs
test/phoenix/router/routing_test.exs

This adds some tests and a note in the Router documentation about using `:*` as an HTTP method catch-all in the `match` macro. The behavior already existed but was not documented. Thanks @chrismccord for pointing this out!
Addresses issue #977.

Test and document Router catch-all verb matches

---

test/phoenix/router/routing_test.exs

@chrismccord After reviewing my last merged PR (thanks!) I couldn't resist going back and giving it the more elegant name: "any" verb instead of "catch_all". This matches the example of `:*` you added to the router docs.
Superficial change, I know, but I hope you agree it reads better this way. :)

Rename catch-all verb test to any verb

---

lib/phoenix/code_reloader/server.ex

This would cause an error in applications which did not configure their `reloadable_compilers` option,
and did not have a default compiler (gettext) present.

Avoid running compilers not present in the application's compiler list.

---

installer/templates/assets/bare/gitignore
installer/templates/assets/brunch/gitignore
installer/templates/phx_umbrella/apps/app_name_web/gitignore
installer/templates/static/bare/gitignore

Hey Guys,
**TL;DR:** In this PR I propose to ignore all secret files in the config folder.
I read through the “Programming Phoenix” book the other day. In this book I came across a chapter where I had to create `dev.secret.exs` in the config folder.
In order to protect it I had to put it into `.gitignore`. So I thought we should ignore all secret files matching the pattern by default.

Ignore all files matching /config/*.secret.exs pattern by default.

---

lib/mix/tasks/phoenix.ex
test/mix/tasks/phoenix_test.exs

Hey :wave: 
I noticed that there was no `mix phoenix` task to list the phoenix specific mix tasks. Ecto has the `mix ecto` that I've found super useful to remind myself what the tasks are called again.
This PR adds a "base" mix task called phoenix which prints out the version of phoenix, short description and lists all the available tasks:
```
$ mix phoenix
Phoenix v1.3.0-dev
A productive web framework that does not compromise speed and maintainability.
Available tasks:
mix phoenix.digest       # Digests and compresses static files
mix phoenix.digest.clean # Removes old versions of static assets.
mix phoenix.gen.channel  # Generates a Phoenix channel
mix phoenix.gen.html     # Generates controller, model and views for an HTML based resource
mix phoenix.gen.json     # Generates a …
```

Adds mix.phoenix task to provide list of phoenix tasks

---

lib/phoenix/param.ex

It was in use before in Phoenix.Param.Map, but is not anymore
after the dropping of Elixir v1.1 support.

Remove unnecessary Phoenix.Param.Any.deriving/3 public function

---

lib/mix/tasks/phoenix.digest.clean.ex
lib/phoenix/digester.ex
test/fixtures/digest/cleaner/latest_not_most_recent_manifest.json
test/phoenix/digester_test.exs

This addresses #2074 and fixes several other bugs with the new digest/digest.clean.
Previously:
1. `mtime` was updated to the current time for all assets, including those that were not digested this time around.
2. If a file was deleted manually, it would not be removed from the manifest the next time digest was run.
3. In manifests affected by some of the other bugs this pull fixes, it was possible that clean would delete the latest version of an asset.
4. Cleaned assets were not removed from the manifest.
5. Cleaned assets were not also removed from the `_build` directory when `build_embedded` was true (#2074)
6. The documentation for `digest.clean` was incorrect.
I added test cases to cover these and some other edge cases that were exposed while I was refactoring. Please let me know if …

Fix digest clean

---

lib/phoenix/controller.ex

Fix the documentation that wrongly states the function `Phoenix.Controller.get_flash/1` would return `nil` if no flash messages are set, even though `conn.private.phoenix_flash` is an empty map by default.

Update faulty @doc for Phoenix.Controller.get_flash/1

---

installer/templates/assets/brunch/package.json

Bump brunch to 2.10, as this is the minimum required to work without javascript-brunch

Remove javascript-brunch because it is deprecated

---

lib/mix/phoenix/context.ex

When I tested gen.json|html it would generate module names like `defmodule App.Web.Web.PostController do`. Now it correctly generates `defmodule App.Web.PostController do`. 
I also went ahead and made sure we weren't matching on Module.split\1 anywhere else.

Fix module name issue with new phx.gen.json and phx.gen.html.

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

Fixes `redirected_to` when passed an atom instead of an integer for the status. The docs for `redirected_to/2` give the following example, which doesn't currently work. This PR fixes it.
```elixir
assert redirected_to(conn, :moved_permanently) =~ "/foo/bar"
```

Allows atom statuses in `redirected_to`

---

installer/templates/assets/brunch/package.json
installer/templates/static/brunch/package.json

In https://github.com/phoenixframework/phoenix/pull/2082 we forgot to remove deprecated `javascript-brunch` package and align the versions in both installer templates. 
Shall we add a comment to both files that there are two of them to mitigate the reduce the likelihood of doing the same mistake again?

Align and bump npm package versions.

---

installer/lib/phx_new/umbrella.ex
installer/templates/phx_umbrella/gitignore
installer/test/phx_new_umbrella_test.exs

`mix phx.new app_name --umbrella` creates a new umbrella app without `.gitignore` file in the root directory. This PR adds a test and fixes the same.

Add missing .gitignore in umbrella app

---

installer/templates/static/phoenix.css

This was made in response to #2103. Please excuse any mistakes as this is my first PR to Phoenix.
This tweaks the default CSS as little as possible so that the framework logo is scaled on mobile devices. The page looks as it already does on larger devices.
I'm more than happy to pop in standard Bootstrap navigation which would collapse by default if it's something you'd be interested in. Thanks!

Make the default page responsive

---

installer/lib/phx_new/generator.ex
lib/mix/phx.ex
lib/mix/tasks/phx.gen.html.ex
lib/mix/tasks/phx.gen.json.ex
lib/mix/tasks/phx.gen.schema.ex

This fixes compilation issues (https://github.com/phoenixframework/phoenix/pull/1927/files#diff-7a2d67c8d1b6c38fd3498e4e09e8d9e2R1)
The code has been copied from `Phx.New.Generator`.

phx.gen.*: Remove dependency on installer code

---

lib/phoenix/channel/server.ex
lib/phoenix/socket.ex
lib/phoenix/socket/transport.ex
lib/phoenix/test/channel_test.ex
lib/phoenix/transports/long_poll_server.ex
lib/phoenix/transports/websocket.ex
test/phoenix/integration/long_poll_test.exs
test/phoenix/test/channel_test.exs
test/phoenix/transports/transport_test.exs

ref: https://github.com/phoenixframework/phoenix_pubsub/issues/68
Previously a channel could gracefully terminate
using the stop semantics of a regular genserver;
however when restarting an application for deploys
the shutdown of the transport and channel processes
would be indistinguisable from an intentional channel
shutdown and would cause clients to incorrectly not
reconnect after server restart. This commit adds a
{:graceful_exit, channel_pid, %Phoenix.Socket.Message{}}
contract to distinguish an intentional channel exit from
what should be regarded as an error condition on the client.
cc @josevalim . Longer term, Saša's design will be a better solution so we can avoid more duplication across transports, but in the interest of shipping 1.3, the `{:graceful_exit, ...` can be handled …

Add graceful exit contract to transports

---

lib/phoenix/channel.ex

Reply with created record as specified on line 74
instead of replying with changeset.

Update docs of channel.ex

---

web/test/channel_test.js

This PR builds on #1999 by adding JavaScript tests for the `Channel` class in `phoenix.js`. Tests should cover most the key behavior around joining/leaving channels, timeouts, and pushing data to channel topics.

Add channel js tests

---

installer/lib/mix/tasks/phx.new.ecto.ex
installer/lib/mix/tasks/phx.new.ex

I believe (newbie alert!), that these two mentions of "ecto models" in the new `phx` mix tasks documentation were overlooked in #1927.
This PR fixes that.

Remove mentions of "ecto models" from mix tasks documentation

---

installer/lib/mix/tasks/phoenix.new.ex

`installer/lib/mix/tasks/phoenix.new.ex` got moved down two directory levels without updating the `@phoenix` path calculation, which uses `__DIR__`, causing `mix phoenix.new foo --dev` to fail.

Update relative path to installer directory (#2124)

---

installer/templates/phx_single/README.md
installer/templates/phx_umbrella/apps/app_name_web/README.md

When creating a new Phoenix application, it generates README files that include the old deprecated `mix phoenix.server` command.

Use new generator commands in the README template files

---

lib/mix/tasks/phoenix.gen.json.ex
lib/mix/tasks/phx.gen.html.ex

Does it make sense to add a “-no-schema” option to phx.gen.html/json? May be useful in umbrella apps where schema goes in another app/folder.

Remove model switch from phx.gen.html.ex

---

installer/lib/mix/tasks/phx.new.ex
installer/test/phoenix_new_test.exs
installer/test/phx_new_umbrella_test.exs

When running the new phoenix 1.3 umbrella generator, the path to the database config
file is incorrect.  Eg.
$ mix phx.new /tmp/hello --umbrella
before:
```
Before moving on, configure your database in config/dev.exs and run:
$ mix ecto.create
```
after:
```
Before moving on, configure your database in apps/hello/config/dev.exs and run:
$ mix ecto.create
```
A side-effect of this fix is that when you run the phx.new.web generator
the configuration message is no longer displayed (because there is no app_path)
which is correct since the web-only app doesn't have any database config.

Fix ecto generator config path for umbrella apps

---

CHANGELOG.md

I have seen at least [one question](https://elixirforum.com/t/access-conn-path-params-in-phoenix-app/3902) asking why `conn.path_params` doesn't work in Phoenix 1.2 even with Plug 1.3.
Now that support was added in dad413f, we might as well document it, at least in the CHANGELOG. :)
This PR also fixes capitalization of the previous line to match the rest of them.

Mention conn.path_params in CHANGELOG

---

installer/lib/phx_new/generator.ex
installer/test/phx_new_test.exs

web_app's type is string
fix #2155

fix phx.new generated generators config with --binary-id

---

lib/phoenix/endpoint/instrument.ex

Fixed spec to match name of compile_stop_callbacks/2.

---

priv/templates/phx.gen.context/schema_access.ex

Create function has one param while the produced examples have two.
Current produced examples:
```elixir
iex> create_letter(letter, %{field: value})
{:ok, %Letter{}}
iex> create_letter(letter, %{field: bad_value})
{:error, %Ecto.Changeset{}}
```

Fix create function example in context generator template

---

priv/templates/phx.gen.context/context_test.exs

The template for context tests currently generates trailing spaces, and if the generator was called with no resource attributes, also an empty line. This fixes that behaviour.

Don't generate trailing whitespace in context tests

---

ISSUE_TEMPLATE.md

Html comments allow the precheck part of the issue template to remain visible for the issue creator, but it's not going to be visible as part of the issue when rendered by github.

Hide precheck in issue template from appearing in issues

---

lib/mix/tasks/phx.gen.context.ex

Fixes #2173.
The context module generator was creating the file with `File.write!/3` instead of the `Mix.Generator` convenience function `create_file/3`.

Show context module file creation when using phx.gen

---

installer/lib/phx_new/ecto.ex
installer/templates/phx_umbrella/apps/app_name/gitignore
installer/test/phx_new_umbrella_test.exs

`mix phx.new --umbrella` creates two application in an umbrella project, say `my_app` and `my_app_web`. I found that `prod.secret.exs` in `apps/my_app/config` is not listed in `gitignore`. So the file possibly accidentally be under version controlled. I guess this is not intended.
In this pull request, I add a line simply ignoring `config/*.secret.exs`. Would you let me know If there is any other good solution or some reasons that it is not ignored.
Thanks.

not-web app secret config generated with phx.new --umbrella is not ignored

---

lib/mix/tasks/phoenix.gen.model.ex

Fixes a small typo in the `phoenix.gen.model` task. It named `phoenix.gen.json` instead of phoenix.gen.model` as the current mix task.

Fix model mix task deprecation warning

---

lib/phoenix/endpoint/watcher.ex

These would normally show up when starting the server in the root
directory, and `npm install` will fail unless it's run in `/assets`.

Update commands in the watcher's logger

---

lib/phoenix/token.ex
test/phoenix/token_test.exs

This parameter can be useful for integration testing or to deal with edge cases such as day light savings when using short-lived tokens.
I can imagine some might prefer ```System.monotonic_time``` over ```System.system_time```. With this change it would be possible to make that choice. Might make sense to implement a complementary parameter to verify. At the moment we can use max_age to adjust time on ```verify```.
I also added some tests for key options, It might be redundant but better err on the side of too many tests when dealing with security related matters. These test make sure we are at least sending the parameters with correct spelling and provide reasonably secure defaults.

Support signed_at option for Token.sign

---

lib/mix/tasks/phx.gen.html.ex
lib/mix/tasks/phx.gen.json.ex

When running the `phx.gen.html` or `phx.gen.json` generators, the path to the router.ex file is displayed as:
```
lib/dev_app_web/web/router.ex
```
where it is now located in
```
lib/dev_app_web/router.ex
```
This makes use of the `Mix.Phoenix.web_prefix()` function to point to the correct directory for the `router.ex` file whether in an umbrella project or not.

fix path to router.ex in generators for an umbrella application

---

lib/phoenix/endpoint/render_errors.ex
test/phoenix/endpoint/render_errors_test.exs

[WIP] Persist resp_headers and other conn data on NoRouteError

---

lib/phoenix/controller.ex

I'm not sure if there is a more preferred syntax here, but these example didn't work for me unless I wrapped the parameters in brackets. I'm told that `when` is not a function.

Fix syntax errors in controller plug examples

---

lib/phoenix/controller.ex

Phoenix.Controller aliases Plug.Conn.AlreadySentError, but only took advantage of the alias in one place.

Don't raise misleading AlreadySentErrors and use Plug.Conn.AlreadySentError alias

---

installer/lib/mix/tasks/phoenix.new.ex
installer/lib/mix/tasks/phx.new.ex
installer/templates/new/config/dev.exs
installer/templates/phx_single/config/dev.exs
installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
lib/phoenix/endpoint.ex

npm links all executables from a package (as specified by the `"bin"` field in package.json) to `node_modules/.bin`.
This PR updates Phoenix to call brunch from this location so that it isn't coupled to the internal structure of the brunch package.

Use brunch from node_modules/.bin

---

lib/phoenix/presence.ex

Edit documentation to remain consistent with the new convention for calling zero arity functions with parentheses in the latest versions of Elixir.

Update documentation for Phoenix.Presence

---

lib/phoenix/socket/transport.ex
lib/phoenix/transports/websocket.ex

Since I spent 20 minutes tracking down why check_origin wasn't working
as expected I'm submitting this as a PR to improve the documentation
(since I never encountered the (very nice!) error defined in
transport.ex)
I'm not sure if the formatting would come out 100% but wanted to at least get the conversation about the content started.

Improve websocket check_origin documentation to be more explicit

---

priv/templates/phx.gen.context/test_cases.exs

The generated context test is named "list_xxx/1 returns all xxxs", but list_xxx takes no arguments.
/0, right?

Arity typo on list_<schema> context test name?

---

installer/templates/phx_ecto/data_case.ex

This is code of the generated `Accounts.create_user`:
```
@doc """
Creates a user.
iex> create_user(%{field: value})
{:ok, %User{}}
iex> create_user(%{field: bad_value})
{:error, %Ecto.Changeset{}}
"""
def create_user(attrs \\ %{}) do
%User{}
|> user_changeset(attrs)
|> Repo.insert()
end
```
It will return `{:error, changeset}` when errors happen, not `changeset`.

fix doc of errors_on function

---

lib/phoenix/controller.ex
test/phoenix/controller/controller_test.exs

This fixes errors like this:
```
Request: GET /listings?filter[status]=draft
** (exit) an exception was raised:
** (Protocol.UndefinedError) protocol String.Chars not implemented for %{"status" => "draft"}
(elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
(elixir) lib/string/chars.ex:17: String.Chars.to_string/1
(elixir) lib/uri.ex:105: URI.encode_kv_pair/1
(elixir) lib/enum.ex:1293: anonymous fn/4 in Enum.map_join/3
(stdlib) lists.erl:1263: :lists.foldl/3
(elixir) lib/enum.ex:1772: Enum.map_join/3
(phoenix) lib/phoenix/controller.ex:1288: Phoenix.Controller.current_path/2
(web) lib/web/views/view_helpers.ex:36: Web.ViewHelpers.link/3
(web) lib/web/templates/component/menu.html.slim:9: Web.ComponentView."menu.html"/1
(web) lib/web/templates/layout/app.html.slim:28: …
```

Fix current_path error when using nested query params

---

lib/mix/tasks/phoenix.routes.ex

This fixes the warning message that says:
"mix phoenix.router is deprecated. Use phx.router instead."
The mix task is called `phx.routes`.

Fix the typo in phx.router (should be phx.routes)

---

installer/templates/new/web/views/error_helpers.ex
installer/templates/phx_web/views/error_helpers.ex

Previously, if a field had multiple errors, only the first would be
displayed.
With this change, each error on the field is displayed in its own tag.
Fixes https://github.com/phoenixframework/phoenix/issues/2274

`error_tag` shows all errors on field, not just first

---

lib/phoenix/code_reloader/server.ex

This fixes the issues mentioned in [1] where the code reloaded would be
in the wrong directory. `cached/0` works but is Elixir 1.4 exclusive, so
the deps are retrieved conditionally depending on if the function exist.
[1] https://github.com/elixir-lang/elixir/issues/6104

use Mix.Dep.Umbrella.cached/0 instead of loaded/0

---

.travis.yml

Hi, 
A small update to always test the latest Elixir 1.4 & 1.3 rather specify the patch level and also bump the OTP level. 
Thanks
Sam

Bump versions used by Travis

---

priv/templates/phx.gen.presence/presence.ex

Since we want to discourage the use of Repo outside of contexts in 1.3,
we should probably use a context (Accounts) when fetching the user map.
A comment has been left on the format of the `users` so that the code
example is still obvious.

Remove the use of Repo in the generated presence docs

---

lib/mix/tasks/phx.gen.channel.ex
lib/mix/tasks/phx.gen.presence.ex
test/mix/tasks/phx.gen.channel_test.exs
test/mix/tasks/phx.gen.presence_test.exs

When in an umbrella and the `context_app` config is set, the files
should go in directories without the web prefix.
In the channels test, the test_prefix is specified directly so that the
files ends up in:
`/test/channels/foo_test.exs` instead of
`test/phoenix_web/channels/foo_test.exs`

Fix location for files in presence and channel generators

---

lib/phoenix/router.ex

Looks like the docs didn't match the macro definitions.
I also added examples to demonstrate the usage of various scope functions to try and make this clearer.

Fix function argument inconsistencies in docs for scope

---

lib/mix/tasks/phoenix.digest.ex
lib/mix/tasks/phoenix.gen.channel.ex
lib/mix/tasks/phoenix.gen.html.ex
lib/mix/tasks/phoenix.gen.json.ex
lib/mix/tasks/phoenix.gen.model.ex
lib/mix/tasks/phoenix.gen.presence.ex
lib/mix/tasks/phoenix.gen.secret.ex
lib/mix/tasks/phoenix.routes.ex
lib/mix/tasks/phoenix.server.ex
lib/mix/tasks/phx.digest.clean.ex
lib/mix/tasks/phx.digest.ex
lib/mix/tasks/phx.gen.channel.ex
lib/mix/tasks/phx.gen.context.ex
lib/mix/tasks/phx.gen.embedded.ex
lib/mix/tasks/phx.gen.html.ex
lib/mix/tasks/phx.gen.json.ex
lib/mix/tasks/phx.gen.presence.ex
lib/mix/tasks/phx.gen.schema.ex
lib/mix/tasks/phx.gen.secret.ex
lib/mix/tasks/phx.routes.ex
lib/mix/tasks/phx.server.ex

The functions should not be called manually (only through `Mix.Task.run`).
This also makes the task docs much more concise and less cluttered.

Remove all functions from mix tasks from docs

---

lib/mix/tasks/phx.gen.embedded.ex
lib/mix/tasks/phx.gen.schema.ex
test/mix/tasks/phx.gen.embedded_test.exs

I was surprised reading the docs for `mix phx.gen.embedded` saying that it required a plural name which is used for the 'table name'.
Embedded schemas aren't linked to a table, and may be used to validate data coming from other sources (request params, message queues, etc.)
This PR removes the required plural name argument from `phx.gen.embedded` and de-couples `phx.gen.embedded` from `phx.gen.schema`.
So the interface is just:
```
mix phx.gen.embedded Blog.Post title:string views:integer
```

Remove plural name arg from phx.gen.embedded

---

lib/mix/tasks/phx.gen.html.ex
priv/templates/phx.gen.html/edit.html.eex
priv/templates/phx.gen.html/index.html.eex
priv/templates/phx.gen.html/new.html.eex
priv/templates/phx.gen.html/show.html.eex
test/mix/tasks/phx.gen.html_test.exs

Currently, when the `--web` option is used, the templates generated are inconsistent with the controller code regarding namespaced path helpers. While the controller correctly follows the convention of `<namespace>_<resource>_path(conn, ...)`, the templates are always generated with `<resource>_path(conn, ...)`, regardless of `--web`.
As an example, when we run the generator as follows:
```
mix phx.gen.html Blog Post posts title:string --web Admin
```
We expect all path helpers to be generated as `admin_post_path(@conn)`. The same goes for the router scope, to be compatible it should include an `as` directive – like `scope "/admin", App.Web.Admin, as: :admin` – otherwise both controller and templates will not compile.
Now the templates follow the same convention, as well as the shell …

Fix phx.gen.html templates and shell instructions with --web

---

priv/templates/phx.gen.embedded/embedded_schema.ex

The current template generates inlined fields, which is invalid Elixir. Now we have one line per field.
```
$ mix phx.gen.embedded Blog.Postr title:string body:text views:integer
```
Before:
```elixir
embedded_schema do
field :body, :string    field :title, :string    field :views, :integer
end
```
After:
```elixir
embedded_schema do
field :body, :string
field :title, :string
field :views, :integer
end
```

Fix spacing in generated embedded schemas

---

installer/templates/new/lib/app_name.ex
installer/templates/phx_single/lib/app_name/application.ex
installer/templates/phx_umbrella/apps/app_name_web/lib/app_name/application.ex
lib/phoenix/router.ex

There are a number of links pointing to elixir-lang.org that
are redirected to hexdocs.pm currently. Simply replace the old ones
to the new targets.
e.g.
http://elixir-lang.org/docs/stable/elixir/Application.html
=>
https://hexdocs.pm/elixir/Application.html

Fix outdated links: from elixir-lang.org to hexdocs.pm

---

lib/phoenix/router.ex

This PR adds an example of nested resources in the router and what routes are generated from such nesting.

Adds documentation to Phoenix.Router about nested resources in the router

---

installer/templates/static/brunch/socket.js

The instructions currently refer to the old way to passing passing
parameters on `socket.connect`. If followed, this results in a
warning message in the JS console that "passing params to connect is
deprecated. Instead pass :params to the Socket constructor", see
[`phoenix.js L533`](https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L533).
This confused me as I was reading through this, so I've created an
update that points to the correct location for passing the token.

Update instructions for token authentication in comments

---

lib/phoenix/controller.ex

Correct the doc example for `action_fallback`, by fetching the post with the correct param, id.

Update docs for action_fallback

---

README.md
assets/js/phoenix.js
lib/phoenix.ex
mix.exs
package.json
priv/static/phoenix.js

connects to #2331  
This PR does the following:
* Updates the comments in `assets/js/phoenix.js` to JSDoc format
* Adds `documentation` as a dev dependency in package.json
* Adds  an npm script `docs` to generate docs into the `doc/phoenix.js` folder
When generated, the docs look like below
I did also try outputting the docs as markdown and including them as an extra for Phoenix's docs and while it did work, it was a bit jumbled I think. Here is a screen shot of that

Generate Phoenix.js documentation

---

README.md
package.json

A global installation of brunch is not required as it can be executed using *npm scripts*. 
It also prevents any potential problems when there is a mismatch between the local version of brunch and the globally installed one.
I added two scripts for the most common tasks `watch` and `build`.
Let me know if I'm missing something.

No need to install brunch globally

---

test/phoenix/integration/websocket_test.exs

Use distinct room names in websocket integration tests to avoid race condition.  Closes #2242
Unit tests in test/phoenix/integration/websocket_test.exs are relying on process death to unregister names, resulting in occasional failures.

Unique room names in WebSocket int tests.  Closes #2242

---

priv/templates/phx.gen.html/controller_test.exs
priv/templates/phx.gen.json/controller_test.exs

Opening for discussion as suggested by @chrismccord 
Here is an example gist containing the new and old generated controller tests:
new: https://gist.github.com/Gazler/aa4b6dfcd92cbe86e58e4ad22918b4fe#file-new_controller_test-exs
old: https://gist.github.com/Gazler/aa4b6dfcd92cbe86e58e4ad22918b4fe#file-old_controller_test-exs
If we want to continue with this, I'll update the rest of the generators.

Use describe for generated controller tests

---

lib/phoenix/template.ex

`:format_encoders` example shows `Phoenix.HTML.Engine` set as the encoder for HTML.
However, `Phoenix.Template.HTML` is the module that implements `encode_to_iodata!/1`, not `Phoenix.HTML.Engine`.

Fix documentation on format encoders

---

lib/phoenix/socket/transport.ex

As mentioned in #2365 `Phoenix.Socket.Transport` doesn't use the flag for configuring logging. This is pretty spammy since it logs every time a channel is joined :-)
This PR changes this so the flag is checked whenever `Phoenix.Socket.Transport` would previously log as info.

Use log_join flag in Phoenix.Socket.Transport

---

priv/templates/phoenix.gen.html/controller_test.exs

Right now, test redirects to :index, but controller redirects to :show, resulting in a red test from the start.

controller_test to start from green

---

priv/templates/phoenix.gen.model/migration.exs

Fixed code style in migration template: extra newline before `end` removed, and only one newline at the end of file left.
Was before:
```elixir
defmodule YahtzeePhoenix.Repo.Migrations.CreateThing do
use Ecto.Migration
def change do
create table(:things) do
add :name, :string
timestamps()
end
end
end
```
Is now:
```elixir
defmodule YahtzeePhoenix.Repo.Migrations.CreateThing do
use Ecto.Migration
def change do
create table(:things) do
add :name, :string
timestamps()
end
end
end # Single newline at then end of file
```

Fixed newline in migration template

---

lib/mix/tasks/phx.gen.html.ex
lib/mix/tasks/phx.gen.json.ex

Phoenix used to generate tables like `<context_name>_<table_name>` but not anymore.
The docs for `phx.gen.context` state that the generator will generate normal table names without prepending the context name, which is the actual behavior.
This PR is just to fix the docs for `phx.gen.html` and `phx.gen.json`.

fix docs: phx does not prepend context name to table names anymore.

---

lib/mix/tasks/phx.routes.ex
test/mix/tasks/phx.routes_test.exs

Update `mix phx.routes` hint to match generated router module with the move to isolated web directory in #2393.

Fix mix phx.routes router module hint

---

lib/mix/tasks/phx.gen.html.ex
lib/mix/tasks/phx.gen.json.ex

I noticed a very small typo getting re-acquainted with mix tasks under the `Web namespace` section (https://hexdocs.pm/phoenix/1.3.0/Mix.Tasks.Phx.Gen.Json.html#module-web-namespace) that appears to affect both `phx.gen.html` and `phx.gen.json`. I looked for similar PR's to see if this was addressed recently and noticed #2406 also didn't cover both files, so I included that as well.

Fixed generate typo in phx.gen.html and phx.gen.json docs

---

assets/js/phoenix.js

After VSN 2.0 the comment about timeout is not valid.

Fixed info about timeout duration in phoenix.js

---

lib/phoenix/controller.ex

`mix phx.gen.json ...` generates FallbackController with line
`|> render(MyAppWeb.ErrorView, :"404")`
This causes dialyzer to fail with:
`The call 'Elixir.Phoenix.Controller':render(#{'__struct__':='Elixir.Plug.Conn'...},'Elixir.MyAppWeb.ErrorView','404') breaks the contract ('Elixir.Plug.Conn':t(),binary() | atom(),'Elixir.Keyword':t() | map()) -> 'Elixir.Plug.Conn':t()`
This PR relaxes type spec on Phoenix.Controller.render/3 to allow calling
`def render(conn, view, template)
when is_atom(view) and (is_binary(template) or is_atom(template))` override

Fix dialyzer error when on Phoenix.Controller.render/3

---

installer/templates/phx_web/templates/layout/app.html.eex

**Reason for change:**
I did this because http://www.phoenixframework.org/docs url seems to have moved and returns a 404 currently. 
How change solved the issue:
I changed it to http://hexdocs.pm/phoenix/adding_pages.html which was the most appropriate link I found in the docs. I'd be happy to change it to something more useful if the community has a better suggestion.

change getting started url in the default layout

---

assets/js/phoenix.js
assets/test/channel_test.js

Following this discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/phoenix-core/vHq964tYMqI/Sw_5t4tQAAAJ
This PR introduces ref counter in the channel. Now `channel.on(...)` returns a unique integer, which can be used to remove one exact even handler and not all handlers matching the event as it was before.
```javascript
ref1 = channel.on("event", do_stuff)
ref2 = channel.on("event", do_other_stuff)
channel.off("event", ref1)
// Since unsubscription, do_stuff won't fire,
// while do_other_stuff will keep firing on the "event" 
```

Ref generation for channel even handlers

---

lib/phoenix/token.ex

This brings sockets in line with how connections and raw endpoints are treated by `Phoenix.Token.{sign,verify}`

Make sure sockets with unconfigured endpoints raise warning

---

installer/test/phx_new_test.exs
installer/test/phx_new_umbrella_test.exs

Just went through and added something like:
assert_file "phx_blog/.gitignore", ~r/\n$/
every time I found .gitignore in the installer tests.
passes if and only if the new phx installer is installed locally.  Not
sure how to trigger tests to use the repo's version of the installer.

simple tests to check that generated .gitignore end with newline

---

lib/phoenix/endpoint.ex

HTTP and HTTPS are acronyms and should be capitalized.

Fix typo and capitalize HTTP and HTTPS in docs

---

lib/phoenix/endpoint.ex

Right now if you don't have pubsub configured at at all and attempt to use `Endpoint.subscribe` or similar, you get an error that looks like:
```
** (ArgumentError) argument error
(stdlib) :ets.lookup(nil, :subscribe)
(phoenix_pubsub) lib/phoenix/pubsub.ex:288: Phoenix.PubSub.call/3
(absinthe) lib/absinthe/subscription/proxy.ex:19: Absinthe.Subscription.Proxy.init/1
(stdlib) gen_server.erl:365: :gen_server.init_it/2
(stdlib) gen_server.erl:333: :gen_server.init_it/6
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
Separately I plan on adding a PR to Phoenix.PubSub to make that a little better, but the advantage of handling this error in Phoenix itself is that we can provide very detailed suggestions for how to recover from the error.
Note: I'm a bit unclear on the best way to …

Improved Endpoint.subscribe/1 Error Message

---

assets/js/phoenix.js

When the examples go too long it makes the table render off the side and it looks bad.
Also in our examples we used 3 different ways of showing js functions, this reduces that a bit.
Before:
After:

Shortening phoenix.js example so it renders correctly.

---

guides/docs/phoenix_mix_tasks.md

There could have been a reason for why this was left with the old style, if so, apologies...

Updating mix task documentation to prefer mix phx.new

---

installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex
installer/test/phx_new_umbrella_test.exs

Before:
```elixir
Supervisor.start_link([
], strategy: :one_for_one, name: MyApp.Supervisor)
```
After:
```elixir
Supervisor.start_link([], strategy: :one_for_one, name: MyApp.Supervisor)
```

Remove whitespace If Ecto is not included on phx.new --umbrella

---

assets/js/phoenix.js

#2444
This allows this configuration to work for tvOS tvml where socket.js is the file that comes by default with phoenix.
```
import {Socket,LongPoll} from "./3rd/socket.js"
let socket = new Socket("http://localhost:4000/socket", { transport: LongPoll, params: {token: "asdf"}})
socket.connect()
socket.onClose( e => console.log("Closed connection") )
var channel = socket.channel("atv:lobby", {})
channel.join()
.receive("ok", resp => { console.log("Joined successfully", resp) })
.receive( "error", () => console.log("Connection error") )
channel.on( "atv:YSdjLkyEcWmkj64wW", msg => console.log(msg.body) );
```

adding in tvOS tvml support for issue #2444

---

guides/docs/channels.md

In the channels [Tying it all together section](https://hexdocs.pm/phoenix/channels.html#tying-it-all-together).
User is referred to
```
lib/hello/endpoint.ex
```
but in phoenix 1.3 , path project generator makes is:
```
lib/hello_web/endpoint.ex
```

Update channels.md typo for endpoint.ex

---

guides/docs/testing/testing_schemas.md

An Elixir's String.duplicate/2 function can be used at no risk instead of creating our own function.

Use String.duplicate/2 instead.

---

guides/docs/channels.md

Updated a small number of module names to include the "Web" suffix - e.g. HelloWeb instead of Hello, so documentation matches what phx.new generates in 1.3.

Updated module names

---

assets/js/phoenix.js

use `self` instead of `window` for access to globals in either web worker or window contexts

Add Seamless Web Worker Support

---

lib/phoenix/logger.ex
test/phoenix/logger_test.exs

Initial conversation here: https://groups.google.com/forum/#!topic/phoenix-core/drYwLVlnvI4
I started with `discard` and `keep` as names to get things started. I'm fine with any name you want.
There are a couple choices I made when implementing the keep strategy that are worth discussing. First, I didn't want filtering to discard the structure of the data. For example, if there is a deeply nested structure, I didn't want to specify every key in the path to the leaf data. This will make it easier to look at a log and see which key you want to add.
``` elixir
filter_values(%{"foo" => %{"bar" => 1}}, ["bar"])
#=> %{"foo" => %{"bar" => 1}}
filter_values(%{"foo" => %{"bar" => 1}}, [])
#=> %{"foo" => %{"bar" => "[FILTERED]"}
filter_values(%{"foo" => %{"bar" => 1}}, ["bar"])
#=> %{"foo" => …
```

Add parameter keep strategy

---

guides/docs/ecto.md

Per @chrismccord [here](https://github.com/phoenixframework/phoenix/commit/88eddbf55a8a489883e02e4265bafaa441643bc6#commitcomment-24471061): The namespacing/context ideas come later in the context guide; using them here without explanation is confusing, and adding an explanation would be premature since we tackle this later.
This reverts commit 88eddbf55a8a489883e02e4265bafaa441643bc6.

Revert "add the context module name in phx.gen.schema run"

---

guides/docs/contexts.md
guides/docs/introduction/overview.md

* changed the link for the guides repo from the old `https://github.com/phoenixframework/phoenix_guides/` to the current location of the guides at `https://github.com/phoenixframework/phoenix/tree/master/guides`
* fixed a small typo in the contexts guides
While going through the guides I discovered two other dead links, but I did not touch them as I didn't know what the desired change would be.
* The first was [in the overview](https://github.com/phoenixframework/phoenix/blob/master/guides/docs/introduction/overview.md#overview) the link to the `Learning Elixir and Erlang Guide` does not appear to work.
* The second was [in the channels section that links to the presence guide](https://github.com/phoenixframework/phoenix/blob/master/guides/docs/channels.md#presence). This one I was …

Updated a bad link and fixed a typo in the guides

---

guides/docs/controllers.md

(resolves https://github.com/phoenixframework/phoenix_guides/issues/803)
Add section on halt()
Add section on action_fallback

Add Phoenix 1.3 controller features to guides

---

guides/docs/contexts.md

This is not correcting any mistakes, but does a couple of things to make a particular diff clearer to the reader:
- shows the previous state for some changed lines, so that it's easy to compare what's changed
- removes some parameters that are no longer necessary after the change

More accurate diff for controller actions

---

guides/docs/ecto.md

I noticed there was a link that was broken in the Phoenix Guides under the [Ecto](https://hexdocs.pm/phoenix/ecto.html) section.  I've updated that link so that it no longer leads to a 404 page.

Fix broken link in Ecto guide

---

guides/docs/routing.md

`scope "admin" do` triggers the following warning:
```elixir
warning: router paths should begin with a forward slash, got: "admin"
(phoenix) lib/phoenix/router/scope.ex:77: Phoenix.Router.Scope.push/2
lib/hello_web/router.ex:27: (module)
(elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
(elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
(elixir) src/elixir_module.erl:80: :elixir_module.compile/5
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
(elixir) src/elixir.erl:239: :elixir.eval_forms/4
(elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
(elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
(elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
(elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in …
```

remove suggestion that triggers warning

---

guides/docs/routing.md

The relationship between posts and users should be many to one, not one to many.

correct table relationship

---

guides/docs/endpoint.md
lib/phoenix/endpoint.ex

Capitalise acronyms and add `host: nil` example for force SSL.

Improve endpoint SSL guide

---

lib/phoenix/endpoint.ex

The smallest PR the world has ever seen.

Endpoint: Fix a spelling error in the @moduledoc

---

guides/docs/plug.md

"the connection struct" is the kind of language you use for mutable structures. There is one "the" (which must be the one already in context), but "a" suggests returning that one or some other connection struct, which is of course what you normally do.

The connection -> a connection

---

lib/phoenix/router.ex

This fixes a small inconsistency within the Router docs between the example code and the subsequent references to it.

Router: Add missing Web to docs

---

mix.exs
mix.lock

Please don't merge until ExDoc 0.17 is released

Update docs to use groups_for_extras for guide grouping

---

lib/phoenix/digester.ex
mix.exs

Please see this issue:
https://github.com/elixir-lang/ex_doc/issues/779
and this PR:
https://github.com/elixir-lang/elixir/pull/6621
This groups the modules in the following way:
(not in a group)
Phoenix
Phoenix.Digester
Phoenix.Logger
Phoenix.Naming
Phoenix.Token
CHANNELS AND TRANSPORTS
Phoenix.Channel
Phoenix.Presence
Phoenix.Socket
Phoenix.Socket.Broadcast
Phoenix.Socket.Message
Phoenix.Socket.Reply
Phoenix.Socket.Transport
Phoenix.Transports.LongPoll
Phoenix.Transports.Serializer
Phoenix.Transports.WebSocket
DEVELOPMENT & TESTING
Phoenix.ChannelTest
Phoenix.CodeReloader
Phoenix.ConnTest
ENDPOINT & REQUESTS
Phoenix.Controller
Phoenix.Endpoint
Phoenix.Endpoint.CowboyHandler
Phoenix.Endpoint.Handler
Phoenix.Router
PROTOCOLS
Phoenix.Param
VIEWS AND TEMPLATING
Phoenix.Template …

Group modules using ExUnit 0.17 groupings

---

lib/mix/tasks/phx.gen.context.ex

Fixes a typo in the mix tasks docs

Fixes 'boostrap' to 'bootstrap' in phx.gen.context

---

lib/phoenix/endpoint.ex
test/phoenix/endpoint/endpoint_test.exs

Enforces local paths when using `static_path`.
Resolves #2516.

Enforce safe local urls with static_path

---

CHANGELOG.md
guides/docs/controllers.md
lib/phoenix/controller.ex
priv/templates/phx.gen.json/fallback_controller.ex

Encourage the use of `put_view/2` and `plug :put_view, View` instead.
See #2469.

Deprecate render/3 and render/4 in favor of put_view/2

---

lib/mix/tasks/phx.gen.presence.ex
priv/templates/phx.gen.presence/presence.ex

The main changes are in the template where the Presence module should have a `Web` suffix and there should be parentheses after `self`.

Fixed errors in the documentation in the presence.ex template and gen.presence file

---

lib/phoenix/controller.ex

Reverts phoenixframework/phoenix#2555
The syntax is exclusive to Elixir v1.5 so we are not quite ready for it yet.

Revert "use new elixir "not in" syntax in docs"

---

guides/docs/views.md

Change http://locahost:4000 to http://localhost:4000.

Fix tiny typo in guides/docs/views.md

---

guides/docs/routing.md

The output of `mix phx.routes` is vertically aligned, but one example in the routing guide lost its alignment. This updates it to match the command output.

Fix vertical alignment of `mix phx.routes` sample output in routing guide

---

guides/docs/routing.md

Quite a few of the sample outputs of `mix phx.routes` lost some whitespace, and thus their vertical alignment. All of the updated ones are taken directly from console output.
P.S. Apologies for not fixing all of these in my prior PR. I just happened to pause at that spot in the guide for the night and didn't check the rest of the page.

Fix all misaligned code blocks in routes guide

---

guides/docs/contexts.md

The `hello` path component is missing, yet the path was being referenced relative to `lib/`.
---
Files in other paragraphs are relative to `accounts/`; I'd be happy to change this that way instead, but it isn't consistent through the entire file, so I kept it as is.

guides/contexts: fix path to accounts/user.ex

---

guides/docs/contexts.md

The generated code includes an `id` pattern match, which is implicitly removed in the diff. Add the actual change for improved clarity.

guides/contexts: add missing edit/2 signature change

---

lib/phoenix/transports/websocket_serializer.ex
test/phoenix/transports/websocket_serializer_test.exs

`:join_ref` was not filtered out from all v1 websocket JSON responses (replies and broadcasts) which was crashing our Java library.

Do not encode  in v1 websocket messages (#2582)

---

assets/js/phoenix.js

* Fix missing/wrong parameters for `Channel#on`, `Channel#off`, `Channel#push` and `Channel#onMessage`
* Use `@params {type} [name]` notation for optional arguments (JSDoc)

Fix phoenix.js documentation

---

guides/docs/deployment/deployment.md

Several documents contained `mix.phoenix` this is find all and replace.
We'll need to devote more time into the testing guides as a whole, to include contexts.

Remove all references of mix.phoenix from guides

---

guides/docs/controllers.md

For functions in the code examples where params are not used, prepend `params` parameter with an underscore.
P.S. Thanks very much for putting together such excellent guides as part of the documentation; I've found them to be tremendously helpful!

Guides (Controllers): Prepend params with underscore in examples

---

lib/phoenix/transports/websocket.ex

Fixes #2601
By not returning the connection returned by send_resp, cowboy is unable to determine whether a response was allready sent, and send another 204 over the tcp connection.

Return mutated connection

---

guides/docs/phoenix_mix_tasks.md

Remove `mix phoenix.gen.html` and `mix phoenix.server`, and change `mix
phoenix.new` to say "Creates a new Phoenix v1.3.0 application".
Freshly installed Phoenix on two machines to confirm that `mix phoenix.gen.html` and `mix phoenix.server` no longer come up as mix tasks, and `mix phoenix.new` lists 1.3.0 as the version instead of 1.2.1. Confirmed that running `mix phoenix.new` creates a v1.3.0-rc project.

Update docs for mix tasks containing full phoenix name

---

guides/docs/contexts.md

I think that `Ecto.Changeset.cast_assoc/2` should read `Ecto.Changeset.cast_assoc/3`, referencing [this Ecto function](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3) shown as `cast_assoc/3` in the Ecto docs.
Note: the diff highlights the whole paragraph, but there are only two changes of one char each.

Guides (Contexts): Update docs to reflect correct cast_assoc function arity

---

lib/phoenix/presence.ex

The phoenix presence init/1 return type does not match the one declared in the callback declaration, causing an error when dialyzer is used.
This small PR should fix it.

fix init return type in Presence.init/1

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

In the current implementation:
`build_conn/0` defaults to generating a conn where the host is set to `"www.example.com"` because it passes `"/"` which `URI.parse` will return `nil`. You can trace that to here
https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/test/conn.ex#L21
You can override this by using `build_conn/3` and pass 
`build_conn(:get, "http://localhost/", nil)`
This causes the conn to set `host` to `"localhost"`. The problem is when using `build_conn/3` in conjunction with `recycle/1`. Currently, `recycle/1` starts off by calling `build_conn/0`. 
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/test/conn_test.ex#L467
This PR adds `build_conn/1` which takes a conn and derive the method and host to call `build_conn/3`
I am unsure if this is …

Phoenix.ConnTest.recycle/1 resets Plug.Conn.host

---

CONTRIBUTING.md

I found a passage in the routing documentation that I thought needs improvement and came here to check how to report and possibly contribute a patch, once the answer was researched.
Then the guidelines seems to rule out non-code issues being opened. I brought up the question where to raise doc issues on #elixir-lang. The view was offered that documentation was as important as code and needs to be handled similarly wrt issues. 
This is an attempt to reflect that in the contrib guide. Please consider this suggestion.

Include documentation bug reports

---

guides/docs/endpoint.md

Autolinking of the text inside ticks within link was causing markdown to be output to text of link (image). Also fixes the url fragment to the Endpoint API section.

Fix direct link to endpoint API docs

---

guides/docs/introduction/overview.md

The link to the learning guide from the overview page mentioned a "Learning Elixir and Erlang guide", but the `learning.html` page is neither of these things. I think the text should be updated to more accurately reflect the content of those pages.
I've also added a link to the [elixir-lang.org learning](https://elixir-lang.org/learning.html) page too, as I think that contains the information that the original learning link should've been pointing to.

Learning guide link now talks about Phoenix + other projects

---

mix.exs

This change makes `mix phx.digest` compress font files by default.
`.woff` files are still ignored since they're already compressed.

Add .eot and .ttf to gzippable_exts

---

package.json

The node_module/.bin directory will be on the PATH for executing npm scripts so there's no need to qualify this location in package.json. 
https://docs.npmjs.com/misc/scripts#path

Simplify npm test entry in package.json

---

lib/phoenix/controller.ex

Directly use query_string from Plug.Conn instead of encode query_params.

Optimize Phoenix.Controller.current_path/1

---

guides/docs/contexts.md

A change is not necessary since the bootstrapped code already has no id param

Remove diff of PageController create method in guide

---

guides/docs/views.md

`HelloWeb.PageView` defines `render/2` functions but the documentation says `render/3`.

Fix function arity in Views guide

---

guides/docs/phoenix_mix_tasks.md
installer/templates/phx_single/mix.exs
installer/templates/phx_umbrella/apps/app_name/mix.exs
installer/templates/phx_umbrella/apps/app_name_web/mix.exs

Semantic versioning starts at 0.1.0.
Also has been fixed in Elixir some time ago: https://github.com/elixir-lang/elixir/pull/4788.

Use 0.1.0 for the initial version in templates

---

installer/templates/phx_ecto/repo.ex

So that the `url:` param in the config file is being properly picked up if we want to hard code the config. in the dev. env.
With the previous code, even if we were populating the `url:` param in the dev.exs file we would have errors being thrown as the `DATABASE_URL` would be empty and would also empty the param for ecto thus creating an error.
This new code simply checks if the env. variable exists, if it does then it uses it to populate the config. otherwise it ignores it.

Fix the generated code of the ecto repo 

---

lib/phoenix/test/conn_test.ex

Currently the typespec for `build_conn` requires passing in the params as a binary/list/map, yet a nil is being passed in as the default and as it is not the list nil of `[]` but rather the atom `nil` it is making dialyzer very unhappy, fixed to the empty nil list of `[]` makes dialyzer happy again.

Fix for dializer with `build_conn`

---

guides/docs/testing/testing_controllers.md

Also reformatted some snippets to match a following example and the community style guide for [multiline pipelines](https://github.com/christopheradams/elixir_style_guide#pipe-operator).

Match error message key and value to what's expected in test

---

lib/mix/tasks/phx.gen.html.ex
test/mix/tasks/phx.gen.html_test.exs

This PR resolves #2381 
However, I'm not sure if just generate integer values for `array:integer`, and string values for other typs is sufficient, or I should generate different type for those possible arguments like `array:time` things. Please advise, thanks!

Generate multiple_select input in form for array fields.

---

guides/docs/testing/testing_controllers.md

That option gives an error message:
```
** (Mix) Invalid option: -y
```

Remove -y option from mix phx.new command

---

assets/js/phoenix.js
assets/test/channel_test.js

By default, Phoenix channels send up exactly the same join payload up to the server on a reconnect. This is fine for simple cases, but in more complex scenarios, you might have additional data to send to `join` in the case of reconnect.
This PR aims to provide an explicit API for updating the join params. The closest discussion that I could about this problem was [here](https://groups.google.com/forum/#!topic/phoenix-core/YrfjvctJW_0), but was referring to the socket payload.
Happy to add additional tests, or change function names if there are better alternatives. 🍍 🍍 🍍

Explicit js api for updating Channel reconnect join params

---

guides/docs/testing/testing_controllers.md

As per @josevalim comment in https://github.com/phoenixframework/phoenix/pull/2670.

Use text response for show test when user not found

---

guides/docs/contexts.md

The snippet included changes to `get_author!/1` but only mentioned after the snippet was presented.

Include get_author!/1 function on definitions

---

lib/phoenix/code_reloader/server.ex

Sometimes the built file will be empty after live reload. [#67](https://github.com/phoenixframework/phoenix_live_reload/issues/67)

Fix "phoenix_live_reload/issues/67"

---

lib/phoenix/controller.ex
test/phoenix/controller/controller_test.exs

This PR adds two additional security headers. [This was first discussed in the Phoenix-core mailing list](https://groups.google.com/forum/#!topic/phoenix-core/VtDUm21wSnc).
The `X-Download-Options` HTTP header has only one option: `X-Download-Options: noopen`. This is for Internet Explorer from version 8 on to instruct the browser not to open a download directly in the browser, but instead to provide only the ‘Save’ option. The user has to first save it and then open it in an application. The reason for this is that when HTML files download from the application, the browser will render it directly inline. That means that the file renders as part of the application and has direct access to the security context of it, meaning it may run phishing attacks or maybe access critical domain …

Add security headers

---

lib/mix/tasks/phx.server.ex

The `--no-deps-check` flag has no effect when used with the `phx.server` task, because Mix always runs the dependency check before loading tasks from dependencies. This replaces the `--no-deps-check` example to a working one using `--no-compile`, and suggests a workaround to run `phx.server` without checking dependencies.
Fixes #2690.

Fix non-working example usage in phx.server doc

---

lib/phoenix/channel.ex
test/phoenix/channel_test.exs

* Reply with an empty payload in case of the second arg is an atom
* Add test for reply/2 replying just status to transport

Support an atom as reply in `Phoenix.Channel.reply/2` (#2704)

---

lib/phoenix/test/channel_test.ex

When running in CI, sometimes the tests run slowly and cause these Channel tests to fail simply because it took more than 100 ms for the reply to come. This makes the tests almost always work fine locally but flakey in CI.
When using a standard ExUnit `assert_receive`, the default timeout can be adjusted to 1000ms like so:
```elixir
config :ex_unit, :assert_receive_timeout, 1000
```
Since these Channel test macros are always explicitly passing the timeout to the underlying `assert_receive` or `refute_receive`, we lose the option to configure the default globally and have to set a higher default on each test individually.
This PR honors the same `config :ex_unit, :assert_receive_timeout` configuration setting so that [the explicit value that's passed down is set to the default …

Honor ExUnit default receive timeouts in Channel tests

---

lib/phoenix/channel.ex

PR to resolve #2718 issue. Seems to be enough just to change specification, because documentation is up to date.

Resolve #2711 - Channel.terminate/2 callback specification

---

mix.exs
mix.lock

Cowboy 2.2.1 includes a fix that addresses an H2 issue for the Safari web browser.
Fixes #2686
(there is a discussion of the issue there along with sample code that demonstrates the problem)

Update the Cowboy 2 dep to be >= 2.2.1

---

lib/phoenix/endpoint.ex

Hi,
I recently had to start a new project in which I needed my watcher to run on a sub folder of my app. I dug a bit on the watchers code and found about the `:cd` option which wasn't documented and solved my problem.
This PR adds a bit of documentation about it.

Document `cd` option on watchers

---

README.md

Chris McCord has deprecated the phoenix-talk mailing list in July 2017
(see [1]) in favor of the Phoenix subforum on elixirforum.com, so
let's update the README accordingly.
[1]: https://groups.google.com/forum/#!topic/phoenix-talk/Z_Uk3foCyfY

Deprecate phoenix-talk link

---

lib/mix/phoenix/context.ex
test/mix/tasks/phx.gen.html_test.exs
test/mix/tasks/phx.gen.json_test.exs

When Phoenix is added to an umbrella app with a name that doesn't contain `web`, it maintains that name with the generators when using a separate context app.
Fixes #2656.

Fix issue when umbrella apps don’t use `web` in the name

---

guides/docs/testing/testing.md

Per exunit docs, `async` doesn't parallelize individual tests: it only parallelizes the case modules themselves.
from exunit [main namespace docs](https://hexdocs.pm/ex_unit/ExUnit.html)
```
use ExUnit.Case, async: true
```
and again, from the actual [Case docs](https://hexdocs.pm/ex_unit/ExUnit.Case.html#content)
>  :async - configure this specific test case to run in parallel with other test cases. May be used for performance when this test case does not change any global state. Defaults to false.

Guides: correct exunit async feature description

---

lib/phoenix.ex

Minor documentation tweaks I did in passing while reading this file.
* "Pubsub" → "PubSub": It is the normal spelling, and the one used by the package itself.
* "pubsub" → "pub/sub": Also the conventional spelling in lowercase.
* Fixed-width font for `gettext` (as it is customary, and consistent with [their official docs](https://www.gnu.org/software/gettext/manual/gettext.html)).
* Links `gettext`.
* A missing article.

Minor doc tweaks [ci skip]

---

lib/mix/phoenix.ex
lib/mix/tasks/phx.gen.schema.ex
test/mix/tasks/phx.gen.schema_test.exs

Adds context_app support for generating schema files based on `:context_app` in the config and `--context_app` in the CLI.
Fixes #2699

Add support for context_app with schema generator

---

mix.exs

`gettext` is used `only: :test` so I thought it should be moved under the "Test dependencies" section.

Move gettext under "Test dependencies" section in mix.exs

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

When `conn` gets recycled during tests, only the `accept` request header got persisted. This PR adds `authorization` to that list.
Fixes #2452.

Authorization request header is now persisted during conn recycling

---

guides/docs/controllers.md
guides/docs/testing/testing_controllers.md

In order to link to the specific section, some of the controller headings have
been changed to h2s so that they appears as links in ex_doc.

Link to action_fallback from controller testing guide

---

installer/templates/phx_assets/brunch/package.json

Update brunch to 2.10.12 in package.json. Previous version was 2.10.9. 
Fixes an issue with source mapping js from babel: https://github.com/brunch/brunch/issues/1635

Update brunch to 2.10.12 in project generator

---

assets/js/phoenix.js
assets/test/presence_test.js
priv/static/phoenix.js

Fixes #2255, for real this time :)
@josevalim and @alvinlindstam I would appreciate thoughts on this new API. It keeps the "lower level" existing API and simplifies the knowledge and code required to handle presence events. At the same time it also resolves the race condition in #2255 by tracking the joinRef or "session id" of the channel connection. The new API looks like this (taken from Alvin's example app):
```javascript
const renderPresences = (presence) => {
const listed_presences = presence.list((user, {metas: metas}) => {
return {user: user, ...}
})
...
}
let channel = socket.channel("user:all", {})
let presence = new Presence(channel)
presence.onSync(() => {
renderPresences(presence)
})
channel.join()...
```
Note: I still need to update the presence.js docs with the new API, but …

Resolve presence race and introduce new Presence API

---

README.md

Not 100% if this tiny edit makes sense but I noticed that the badge in the README was "failing" while the master branch on Travis was green. This change makes the travis badge in the README point directly to the master branch.

Update README's travis badge to point to master

---

guides/docs/channels.md

Having gotten lost in some of these abstractions myself, I tried to make
this introduction as concrete and clear as possible. The examples and
new diagram at the top should help readers quickly grasp what channels
can be used for and the flexibility and scalability they offer.
Beyond that, I added a few clarifications and examples, and reordered
the parts so that PubSub is last, since it's the least visible to an
application developer.

Rework the introduction and organization of the Channels guide

---

test/mix/tasks/phx_test.exs

leftover "ecto" - should be "phx"..

spelling phx_test.ex

---

lib/phoenix/router/helpers.ex
test/phoenix/router/helpers_test.exs

The `static_push/2` function is a drop in replacement for `static_path/2` with
the addition of performing a server push if the adapter allows. This function
only supports using a `Plug.Conn` struct - attempting to use it with an endpoint
will result in an error.

Generate a static_push function in the RouteHelpers

---

guides/docs/endpoint.md

This PR adds additional information on configuring HTTPS including a link to the Erlang options that can be set for TLS.
It also provides details around HSTS, the implications of turning it on, and how to turn it off for localhost.

Add additional information on TLS config and HSTS to the Endpoint guilde.

---

installer/templates/phx_assets/webpack/webpack.config.js

This change requires access to the `options` for webpack. To access
this, the webpack config has been changed to use a function instead of
an object.
Closes #2809

Update installer webpack config to minify CSS in production

---

installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex
installer/templates/phx_umbrella/apps/app_name_web/lib/app_name/application.ex

The [default documentation of the `*.Application` module for single apps](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/lib/app_name/application.ex#L2-L4) matches the template in the new [Library Guidelines](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Library%20Guidelines.md#avoid-spawning-unsupervised-processes), but not the ones for umbrella apps.

Update application.ex templates with default docs

---

guides/docs/testing/testing.md

The section warning about async tests for tests involving a database
was a little confusing to people since it's pretty out dated. This
language was introduce almost [3 years ago](https://github.com/phoenixframework/phoenix/commit/2b456abcea782684861f466d932b451b37279945),
back when async tests touching the database _were_ dangerous. Now that
this is no longer the case thanks to Ecto 2.0, this should be updated
in the guides.

Update docs about async tests

---

installer/templates/phx_assets/webpack/package.json
installer/templates/phx_assets/webpack/webpack.config.js

According to the TL;DR of the comment below, mini-css-extract-plugin is
replacing extract-text-webpack-plugin which will be deprecated. Since
this does not have a built in optimizer for CSS, a separate plugin is
used. However overriding the optimizer means that UglifyJS must be
included manually (previously this was a transitive dependency of
webpack which was used automatically in production mode)
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749#issuecomment-374549467
This closes #2818

Replace extract-text-webpack-plugin with mini-css-extract-plugin

---

guides/docs/routing.md

This makes the routing guide clearer for beginners.
Fixes issue #2833

Suggest file for BackgroundJob.Plugin in guide.

---

priv/templates/phx.gen.context/test_cases.exs

The `create` and `delete` tests were matching on the struct inside the {:ok, %Thing{} = thing} tuple, whereas the `update` test was matching in a separate assertion. They now all match inside the `{:ok, %Thing{} = thing}` assertion.
This screenshot shows the difference as it exists on `master` currently:
This was a simple/logical enough change that I figured I'd propose the solution instead of bringing it up on the mailing list, feel free to reject if not pertinent.

Unify assertion for context test case template.

---

installer/README.md

Following current instructions from README.md caused two builds: first command built the installer with prod env, and second command was building again with dev env, and only after that installing the installer. I believe the installer should be installed after compiling with prod env?

Fix installer archive installation instructions to use prod build

---

installer/templates/phx_gettext/errors.pot

This PR simply fixes typo in gettext remarks.

Fix typo and redundancy in remark in gettext template.

---

guides/deployment/heroku.md

update the heroku deployment guide for webpack
- by default the buildpack doesn't use node's latest LTS so it's running node 6.9, I thought it would be a nice improvement to use the LTS version (even if that version changes)
- It seems phoenix wants to use npm by default so I kept the compile file with npm.
refs #2827

update heroku deployment guide for webpack

---

guides/adding_pages.md
guides/channels.md
guides/controllers.md
guides/errors.md
guides/phoenix_mix_tasks.md
guides/plug.md
guides/presence.md
guides/templates.md
guides/testing/testing.md
guides/testing/testing_channels.md
guides/views.md
installer/templates/phx_gettext/gettext.ex
installer/templates/phx_web/views/error_helpers.ex
lib/phoenix/channel.ex
lib/phoenix/controller.ex
lib/phoenix/endpoint/instrument.ex
lib/phoenix/presence.ex
lib/phoenix/test/channel_test.ex
lib/phoenix/test/conn_test.ex
lib/phoenix/token.ex
lib/phoenix/view.ex
priv/templates/phx.gen.presence/presence.ex

This is mostly about adjusting guides and docs for https://github.com/phoenixframework/phoenix/issues/2605 since the formatter won't be able to fix these but I also added / removed parentheses in code in many places. I did not touch:
1. `Kernel.send` - it seems that `send` is not in the formatter's [interal locals_without_parens list](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code/formatter.ex) so it's written with parens in Elixir codebase since it's being formatted but it's without parens in docs and getting started guide so I was not sure what should be the way
2. `Logger.info`, `warn` and `error` - similarily
3. `Phoenix.HTML`'s functions in eex snippets - seems like these should stay without parens?

improve consistency regarding code formatting (function parentheses)

---

lib/phoenix/code_reloader.ex
lib/phoenix/code_reloader/server.ex
lib/phoenix/endpoint.ex
lib/phoenix/endpoint/supervisor.ex
test/phoenix/code_reloader_test.exs

Whenever I am working in a non-umbrella project that consists of Phoenix application, and a few dependencies, or I am working on a library and have it temporarily available on disk, I am missing the functionality of Phoenix code reloader picking up changes in those projects. I *think* it was possible to configure it before with specifying paths to additional to `web` folders (I have been adding `lib/` this way for example too), but that option is no longer around to specify which folders I want to reload and which not.
This pull request adds support for `:reloadable_apps` Endpoint configuration variable. Let's say I have a project (non-umbrella) consisting of `:ui` and `:core` applications. Currently, Phoenix code reloader will only pick up the changes in :ui.
With my pull request, the …

Add :reloadable_apps endpoint configuration

---

guides/contexts.md

The Contexts Guide was inconsistent in how it styled localhost URLs: sometimes they were plain text, sometimes code, and sometimes links. Since most of the prose is directing the reader to visit the URLs, it seems best to standardize on linking to localhost URLs in all locations in the guide.

Consistently link to localhost URLs in Contexts guide

---

installer/lib/phx_new/generator.ex
installer/templates/phx_web/templates/page/index.html.eex
installer/test/phx_new_test.exs

The phoenix version string that was previously used in the dependency
string has been moved to a module attribute so it can be easily reused.
The `Version` module is used so that both "1.4.0" and "1.4" formats can
easily be generated. The latter format is used when linking to the
changelog in the template.
A test has also been added to ensure the correct version is specified in
mix.exs based on the version of the installer.

Add changelog link to new template

---

lib/phoenix/controller.ex
test/phoenix/controller/controller_test.exs

Hello guys,
This PR adds a new security header that avoid window control attacks as described on issue #2906.
As mentioned in the issue/[presentation](https://developer.apple.com/videos/play/wwdc2018/207/) this new header is already [released on Safari 12](https://developer.apple.com/safari/whats-new/).
PS: This is my first contribution to an Elixir project so please let me know if I need to do something more. The `level:starter` tag was helpful. 👍

Add security header to avoid window control attacks - Closes #2906

---

lib/phoenix/router/helpers.ex
test/phoenix/router/helpers_test.exs

Currently calling a path such as:
page_page(conn, :show, :id, "extra-params")
Will raise a `Protocol.UndefinedError` as "extra-params" is not enumerable. A
custom error message is now raised in this scenario to prompt the user what to
do next.

Show a better router error message when a non-Enumerable is passed as params

---

lib/mix/tasks/phx.gen.context.ex
test/mix/tasks/phx.gen.context_test.exs

Mix.Shell.IO's `yes?` function already [adds a `[Yn]` hint](https://github.com/elixir-lang/elixir/blob/v1.6.6/lib/mix/lib/mix/shell/io.ex#L56) to the prompt. Without this change we currently have a `Would you like proceed? [Y/n] [Yn] ` prompt.

Remove redundant [Y/n] in shell prompt in context generator

---

lib/mix/tasks/phx.gen.context.ex
test/mix/tasks/phx.gen.context_test.exs

Add missing "to"s and refine usage of "prefer".

Correct grammar for prompt messages

---

lib/phoenix/endpoint/cowboy2_adapter.ex

Hello,
This PR adds support for running a phoenix endpoint with the Cowboy adapters on a local unix socket.
This configuration could be useful when reverse-proxying cowboy using NGINX or other web server.
The only change required to phoenix is to handle the `{:local, path}` tuple result from `:ranch:get_addr` when producing the startup message.
To enable a unix socket, the endpoint is configured with `port` 0 and a `{:local, path}` tuple for `ip` ([erlang docs reference](http://erlang.org/doc/man/inet.html#type-local_address)):
```elixir
config :my_app, MyAppWeb.Endpoint,
http: [port: 0, ip: {:local, "/path/to/my_app.sock"}],
```
Additionally, the application should remove any existing file at startup, otherwise it will fail to bind:
```elixir
def start(_type, _args) do …
```

Allow running phoenix endpoint on unix domain socket

---

guides/phoenix_mix_tasks.md

Add a reference to "Introduction to Mix" to make it easier for people new to Mix find it's documentation.

Add a reference to "Introduction to Mix"

---

mix.exs
mix.lock

```
warning: Enum.partition/2 is deprecated, use Enum.split_with/2
lib/gettext/extractor_agent.ex:64
warning: Enum.partition/2 is deprecated, use Enum.split_with/2
lib/gettext/po/parser.ex:44
warning: String.strip/1 is deprecated, use String.trim/1
lib/gettext/po/parser.ex:47
warning: String.strip/1 is deprecated, use String.trim/1
lib/gettext/po/parser.ex:55
warning: String.lstrip/1 is deprecated, use String.trim_leading/1
lib/gettext/po/parser.ex:65
warning: Enum.partition/2 is deprecated, use Enum.split_with/2
lib/gettext/po/parser.ex:71
warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
lib/gettext/po/tokenizer.ex:147
```

Remove warnings `mix test`

---

installer/templates/phx_assets/webpack/app.js

I think the path in the example probably points to an older generated directory structure.

Make path example consistent with generators

---

lib/phoenix/endpoint.ex
lib/phoenix/socket/transport.ex
test/phoenix/socket/transport_test.exs

As briefly discussed on IRC a few days ago (with @josevalim), this PR introduces the possibility for transports to receive an MFA tuple as configuration option for their origin check.
If there are things wrong, missing or to be improved, please let me know.

Add origin check for transports using an MFA tuple

---

guides/channels.md
guides/deployment/heroku.md
guides/views.md
installer/templates/phx_single/README.md
installer/templates/phx_umbrella/apps/app_name_web/README.md
installer/templates/phx_web/templates/layout/app.html.eex

As a new user, I started my first app and found that the docs links on the default landing page led to 404s. This PR updates all URLs which started with "phoenixframework.org/docs" to the URL which I felt best replaced it. There may be other URLs which should also be updated, but I am not familiar with the codebase yet, so I am not aware of any others. If there are, I would be happy to update them as well if I am pointed in the right direction.

Update docs urls

---

guides/channels.md
guides/contexts.md
guides/controllers.md
guides/phoenix_mix_tasks.md
guides/routing.md
guides/testing/testing_controllers.md
guides/views.md
lib/phoenix/view.ex

I think I changed it in all relevant points. I also changed the notes/explanations, let me know if the language is fine and if anything else is missing/needs change. I tried rgrep for _path outside the guides, but it's a never ending list of hits for unrelated stuff, I don't think I have missed something but it could happen

changed guides mentioning *_path and moduledoc in lib/phoenix/view.ex

---

installer/templates/phx_web/templates/page/index.html.eex
priv/templates/phx.gen.html/edit.html.eex
priv/templates/phx.gen.html/index.html.eex
priv/templates/phx.gen.html/new.html.eex
priv/templates/phx.gen.html/show.html.eex

I noticed that all the generated HTML contained nonconsecutive heading level which is a problem for accessibility (screen readers needs a proper document outline to understand the content of the page). As a bonus, it provides better SEO as well.
By changing the levels they are now living up to the WCAG standards.
This means that the headings now look a bit different since the styling used for the headings are a bit different. In my opinion, this makes it more readable.  I've added screen shots for you to see.

Adjust headings level to form proper document outline

---

installer/templates/phx_assets/webpack/webpack.config.js

This maintains feature parity with how brunch worked before.

Include vendor directory when bundling JS in webpack

---

lib/phoenix/router.ex

"put less pressure in the Elixir compiler" -> "put less pressure on the Elixir compiler"

Minor grammar fix for router.ex doc

---

guides/channels.md
installer/templates/phx_web/templates/layout/app.html.eex

I don’t think there is a valid reason to use `static_path` instead of `static_url` in default templates 😄 
`Phoenix.Endpoint` exposes (and documents) the `:static_url` runtime configuration but it’s not used by `static_path` when the user configures it.
If the `static_url` helper is used but `:static_url` is not configured, the fallback makes sure assets are still served from the application URL (eg. `localhost`).

Use “static_url” helper instead of “static_path” in templates

---

priv/templates/phx.gen.json/fallback_controller.ex

To fix #2968.
Since FallbackController is usually not edited for a while after being generated, we shouldn't write an automatic compiler error into it.

Don't rely on Ecto.Changeset when `--no-schema` is passed.

---

guides/controllers.md

While the function is named `Plug.Conn.halt/1`, the key that is updated is `:halted`. I believe this is a typo in the guides.

Fix incorrect `:halt` key name in the guides

---

lib/phoenix/channel.ex
lib/phoenix/template/eex_engine.ex

Looking at other errors in the codebase, it seems errors should not start with capital letters.
In addition, I think error messages should not contain backticks.
As a side note, I changed three error messages and all the tests are still green 😅 Probably there is nothing wrong with the test suite, but I found it "suspicious".

Downcase error starts

---

lib/phoenix/channel/server.ex

I also wanted to comment about the error messages in the private function `handle_result/2`, could be an option to use the new `FunctionClauseError`s? I'm not that familiar with the project to know if that could be a good idea, nor that breaking change is worth considering :)

Update  error messages of Phoenix.Channel.Server

---

assets/package.json

Rationale:
When importing anything from phoenix.js all the module ends up bundled. Marking the package as side effect free enables build optimizers to do tree shaking and scope hoisting and only the used code lands in bundle.
https://github.com/webpack/webpack/tree/master/examples/side-effects

Mark phoenix.js npm package as side effect free

---

lib/phoenix/controller.ex

Hey Chris,
I noticed a minor issue with the `@spec` in `Phoenix.Controller.layout/1`: It can return a binary *or an atom* as the 2nd element of the tuple. The issue is closely related to #1435.
~~I took the liberty to fix that but formatting the file resulted in a bunch of changes (running `mix format` on `Elixir 1.7.3 (compiled with Erlang/OTP 21)`). I decided to leave them in for now, happy to commit just the one line if that's preferred.~~
Thanks,
Michael
EDIT:
Sorry, just saw this: https://github.com/phoenixframework/phoenix/pull/3033#pullrequestreview-150184980
I have adjusted my PR accordingly.

Fix Dializer error when using Phoenix.Controller.layout/1

---

lib/phoenix/router.ex
lib/phoenix/router/scope.ex
test/phoenix/router/forward_test.exs

Previously, passing a non-atom argument to the forward macro:
forward "/admin", to: AdminController
Would result in the following error message;
== Compilation error in file web/router.ex ==
** (ArgumentError) cannot convert the given list to a string.
To be converted to a string, a list must contain only:
* strings
* integers representing Unicode codepoints
* or a list containing one of these three elements
Please check the given list or call inspect/1 to get the list
representation, got:
[to: SomePlug, init_opts: [foo: :bar]]
Now the following error message is displayed:
forward expects a module as the second argument, [to: AdminController]
given.
This closes #2995

Show a better error when trying use plug forward in router

---

guides/presence.md

This is an update to make the final urls listed in the tutorial be actual links the reader can click through on.
Assuming that the reader was actually following the tutorial, this adds a tiny bit of convenience.

Update urls to be links for reader convenience

---

assets/js/phoenix.js
assets/test/socket_test.js

We are experimenting with using Phoenix Channels for game networking. Our application is in WebVR so is sensitive to GC pauses, so this PR applies some changes to phoenix.js to reduce memory allocations and save some CPU time, particularly on the receive path.
Summary of changes:
- Avoid string template interpolation for log messages if logger has not been set on socket
- Skip unnecessary walking of the `CHANNEL_LIFECYCLE_EVENTS` array when checking channel membership on receive
- Unroll functional array operations into `for` loops to remove memory allocations for closures, copying, etc.
- Skip additional memory allocations + destructuring in `push` if logging is disabled, and eliminate the need to create an additional closure (with bindings) in `push` when connected.

phoenix.js memory + CPU improvements

---

lib/phoenix/endpoint.ex

Adds default value for check_origin option.

Minor ajustments in Phoenix.Endpoint options docs

---

installer/lib/phx_new/single.ex
installer/lib/phx_new/web.ex
installer/templates/phx_assets/app.css
installer/test/phx_new_test.exs
installer/test/phx_new_umbrella_test.exs

This fixes "no route found for GET /css/phoenix.css" from phoenix
installed with --no-webpack option. Use `:append` from the generator
instead of css-loader for static template generation.
This is the improvement of https://github.com/phoenixframework/phoenix/pull/2779 so it could go with version 1.4.

Only use css-loader syntax when generate with Webpack

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/supervisor.ex
test/phoenix/endpoint/endpoint_test.exs

If the pubsub server is configured at runtime (e.g. in the init callback) then
everything will appear to work as normal, but the pubsub server will have the
name of `Elixir.Supervisor` due to having nil as a name.
This closes #2992

Raise if the pubsub server name is not configured at compile time

---

priv/templates/phx.gen.schema/migration.exs

Running with the CLI:
```bash
$ mix phx.gen.html Sales Agent agents invited_by:references:agents
```
Will generate:
```elixir
add(:invited_by_id, references(:agents, on_delete: :nothing, type: :binary_id))
```
But the expected result should be the following as the discussion here: https://github.com/phoenixframework/phoenix/pull/3044#issuecomment-418120799
```elixir
add :invited_by, references(:agents, on_delete: :nothing, type: :binary_id)
```

Fixes the `references` switch should requires an explict fkey name.

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/supervisor.ex
test/phoenix/endpoint/endpoint_test.exs

Previously PubSub was required at compile time. This commit allows configuration
at runtime by looking up the PubSub module for the endpoint from the config
instead of compiling it into the module. The compile time errors have been move
to runtime and will trigger when attempting to start the pubsub children.

Allow runtime configuration of PubSub

---

test/phoenix/integration/websocket_channels_test.exs

Stumbled upon this when reading some code. This `assert` obviously doesn't assert much. 😄

Fix incorrect assert in websocket channel test

---

lib/phoenix/endpoint/cowboy2_handler.ex

When using Cowboy 1.x, the `cowboy_websocket` module is available, but
not a behaviour. This commit ensures that the module defines a
behaviour.
> warning: module :cowboy_websocket is not a behaviour
> (in module Phoenix.Endpoint.Cowboy2Handler)
>   lib/phoenix/endpoint/cowboy2_handler.ex:1

Fix warning about cowboy_websocket behaviour

---

test/test_helper.exs

Previously, if the version of a dependency which depends on cowboy (such
as plug) is updated beyond the version specified in the lock file, it
will also update cowboy. This will cause the tests to run against Cowboy
2 even when COWBOY_VERSION is set to 1.0.
This commit raises on the test helper when the version specified in
COWBOY_VERSION is "1.x" and the version of Cowboy in version 2.

Fix fetching the wrong version of cowboy when deps update

---

lib/phoenix/test/conn_test.ex

Fix typespec for `Phoenix.ConnTest.bypass_through/3`
The literal `:atom` should be `atom` :)

Fix typespec for ConnTest.bypass_through/3

---

lib/phoenix/view.ex

Not much, but here are some docs improvements in `lib/phoenix/view.ex`.

Typo and wording fixes in docs

---

lib/mix/tasks/phx.gen.cert.ex

Addressing #3085
One remaining issue: the printed instructions assume the Endpoint lives under the `#{base}Web` namespace, which may be typically correct for standalone apps, but not for child apps under an umbrella. I looked at some other Mix tasks, but I didn't see an easy way to determine the correct namespace.

 Block phx.gen.cert task at umbrella level 

---

assets/js/phoenix.js

Fix for Issue #3083 
Reset the reference to pending heartbeat to prevent unnecessary reconnect.
It's possible to reproduce the behaviour (see #3083 for details) with two separate machines or a docker container as the server.

Reset pendingHeartbeatRef on connection open

---

lib/phoenix/controller/pipeline.ex
lib/phoenix/exceptions.ex

Using `FunctionClauseError` results in showing the available clauses
when displaying the error message. This also renders nicely in the plug
exceptions page.
Instead of using `plug_status` in the exception, the `Plug.Exception`
protocol is explicitly defined for the `ActionClauseError` to allow easy
transitioning between `ActionClauseError` and `FunctionClauseError`.`
This closes #2657

Use FunctionClauseError for Phoenix.ActionClauseError

---

lib/phoenix/router/route.ex
test/phoenix/router/forward_test.exs
test/phoenix/router/route_test.exs

The Plug options passed when building the route are not escaped while building the `:dispatch` expression in `Phoenix.Router.Route.exprs/1`.
That produces `CompileError`s when building and unquoting the matches in `Phoenix.Router.__before_compile__/1`.
This is the [offending commit](https://github.com/phoenixframework/phoenix/commit/29a1f01e6b0134534cf617efbfc5d54b54c9cd55#diff-4b61711a8ead48b802b5b21df56705a4L99).
This bug affects v1.4.0-rc.1.

Escape Plug opts in routes

---

CHANGELOG.md

This has been merged in quite early in 1.4 development I think but never been released for 1.3, so I propose we add info to first released version of 1.4 changelog entry. The feature itself was discussed here: https://github.com/phoenixframework/phoenix/pull/2887

Add info on the :reloadable_apps option to CHANGELOG.md

---

guides/phoenix_mix_tasks.md

Phoenix Specific Mix Tasks guide has a reference to generating a 1.3.0 application with `phx.new` task.
This change removes the specific version so the docs stay accurate.
https://hexdocs.pm/phoenix/1.4.0-rc.1/phoenix_mix_tasks.html#phoenix-specific-mix-tasks

Remove hardcoded 1.3.0 reference in mix task docs

---

assets/package-lock.json
assets/package.json
package-lock.json

```
$ npm install
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
added 354 packages from 194 contributors, removed 41 packages, updated 20 packages and audited 18953 packages in 24.811s
found 3 vulnerabilities (1 low, 1 high, 1 critical)
run `npm audit fix` to fix them, or `npm audit` for details
```
The latest version of mocha addresses this problem. Also need to add `--exit` due to https://github.com/mochajs/mocha/issues/3044

upgrade mocha due to security audit

---

installer/templates/phx_single/formatter.exs
installer/templates/phx_umbrella/apps/app_name/formatter.exs
installer/test/phx_new_test.exs
installer/test/phx_new_umbrella_test.exs

[The documentation of `mix format`](https://hexdocs.pm/mix/Mix.Tasks.Format.html#content) states that the parent `.formatter.exs` must not specify files, in its `:inputs` configuration, that are inside the subdirectories listed in the `:subdirectories` option. If this happens, the behaviour of which formatter configuration will be picked is unspecified.
[Upcoming Elixir versions will print an error message if there are conflicting files.](https://github.com/elixir-lang/elixir/pull/8323)
I haven't included the `priv` dir for non-Ecto projects because the installer does not put any Elixir files there, but I'll include it if you think it makes sense.

Avoid .formatter.exs files with conflicting inputs

---

priv/templates/phx.gen.context/test_cases.exs

Currently, context tests generated by running the html generator (`mix phx.gen.context Accounts User users name:string`), produce a test with an extra line with some trailing whitespace (illustrated with dots here):
test "update_user/2 with valid data updates the user" do
user = user_fixture()
assert {:ok, %User{} = user} = Accounts.update_user(user, @update_attrs)
······
assert user.name == "some updated name"
end
This patch removes both newlines from the template, resulting in a generated test like this:
test "update_user/2 with valid data updates the user" do
user = user_fixture()
assert {:ok, %User{} = user} = Accounts.update_user(user, @update_attrs)
assert user.name == "some updated name"
end

Remove extra newline in generated context test cases

---

assets/js/phoenix.js
assets/test/socket_test.js

The timer state must be known in order to know if the channel was attempting to rejoin or not. It is
not correct to start a channel rejoin timer if it was not previously running. This involved changing the timer logic up a bit to clear out `this.timer` when it's done processing
Related to #3139

Allow channels to immediately reconnect when the socket does

---

guides/adding_pages.md
guides/templates.md
guides/views.md

Starting at phoenix 1.4, the class `jumbotron` does no longer exist, and `phx-hero` is used instead.

Use `phx-hero` class instead of `jumbotron`

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/cowboy_adapter.ex
lib/phoenix/transports/long_poll.ex
lib/phoenix/transports/websocket.ex
test/phoenix/integration/websocket_socket_test.exs

Previously, it was not possible to use a socket with a path that differed from
the key name. For example `:websocket` would always end with `/websocket` and
`:longpoll` would always end with `/longpoll`.
This commit allows a `:path` to be passed into the keyword options, the path
will be used instead of the default if available.

Allow custom paths to be provided to :websocket and :longpoll

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/cowboy2_handler.ex
test/phoenix/integration/long_poll_socket_test.exs
test/phoenix/integration/websocket_socket_test.exs
test/test_helper.exs

This commit allows sockets (websocket/longpoll) to use variables in the path.
For example, a socket can be defined with:
socket "/ws/:user_id", MyApp.UserSocket,
websocket: [path: "/project/:project_id"]
The params will be available in the connect map:
def connect(%{"user_id" => user_id, "project_id" => project_id}), do: ...
The `__handler__/2` function now hands off the a `do_handler` which is
responsible for modifying the passed `conn` to add the `path_params` and
`params`. `__handler__/2` is now called with the entire `conn` instead of just
the `path_info` and expects a `conn` to be available in the returned tuple.
As this is only supported in Cowboy 2, the `test_helper.exs` has been
updated to ignore `:cowboy2` tests when testing with `plug_cowboy` 1.x.

Allow variables to be used when defining socket paths

---

lib/phoenix/controller.ex

As there are multiple code with slightly different redirect behaviour nowadays (302, 303 and 307 at least), this is just making explicit the behaviour of redirect for status code.
I am not sure of the wording. Would be happy to change it if you think it need more work.

Make explicit the status code in case of redirect

---

guides/channels.md

* Added link to Phoenix.Channels.GenSocketClient, a stable Elixir client library for Channels
* This is especially useful for anyone that desires to use Channels from a Nerves project
* hat tip to @sasa1977

Added 3rd party elixir client library to guide

---

lib/phoenix/channel.ex
lib/phoenix/socket.ex

Avoid smart quotes by using backticks around string literals in the documentation. Also explain what a splat is use more consistent language between `Phoenix.Channel` and `Phoenix.Socket` (this is to help people that are relatively new to development).
Related ex_doc issue: https://github.com/elixir-lang/ex_doc/issues/928

Fix doc rendering bugs and improve channel documentation around topic patterns

---

priv/templates/phx.gen.schema/schema.ex
test/mix/tasks/phx.gen.schema_test.exs

Removes extra line break that makes the formatter update newly generated schema file

Removes extra line break on phx.gen.schema template

---

guides/presence.md
lib/phoenix/presence.ex

This PR adds some documentation to clear up some confusion I had. My use case was around using `Phoenix.Presence` but not broadcasting diff events (handle_diff -> no op). Phoenix.Tracker is a better fit than Presence in this situation, but I was not aware of it from the docs.

Document the use of `Phoenix.Tracker` instead of `Phoenix.Presence`

---

lib/phoenix/test/conn_test.ex

There's a formatting problem https://hexdocs.pm/phoenix/1.4.0/Phoenix.ConnTest.html#module-controller-testing

Fix code block format

---

guides/contexts.md

Hi there, I spotted a minor typo so figured I would submit a PR to fix it :) 
Thanks for all the great work

fix minor typo in contexts guide (ensure_author_exits -> ensure_author_exists)

---

assets/package.json

See https://github.com/mochajs/mocha/wiki/compilers-deprecation
Originally part of #3176

Fix Mocha warning about --compilers

---

lib/phoenix/controller.ex

Just something I noticed while reading the docs.
- typo: "of" -> "off"
- grammar: moved "repeatedly" up in the sentence
Thanks for building Phoenix :).

Minor typo/grammar change

---

guides/channels.md

The `phoenix.js` link [in the Channels Guide](https://hexdocs.pm/phoenix/channels.html#client-libraries) was still pointing to the `v1.3` branch.

Update Link to phoenix.js in Channels Guide

---

installer/templates/phx_assets/webpack/package.json
installer/templates/phx_assets/webpack/webpack.config.js

* uglifyjs-webpack-plugin  uses uglify-es, which is [no longer maintained](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058).
> uglify-es has been forked and the new project is called terser. For projects that need ES6 support, use it instead of uglify-es, since all new development will be happening over there (and things like webpack are switching over to it shortly too):
> https://github.com/fabiosantoscode/terser
* uglify-js does not have support for ES6, and the existing ES6 support (uglify-es) has been deprecated
* [Webpack 5 will use Terser as well as default minimizer](https://github.com/webpack/webpack/issues/7923).
* seems Webpack 4 switched to terser as well because they consider this a non-breaking change
[webpack/webpack#8350 …

Switch from uglifyjs-webpack-plugin to terser-webpack-plugin

---

installer/templates/phx_assets/webpack/package.json
installer/templates/phx_assets/webpack/webpack.config.js

I noticed there are a few npm warnings showing up when running `npm install` on a new phoenix project:
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN assets No description
```
This PR fixes them.

Update webpack-cli, fix npm install warnings, colorful webpack output in mix phx.server

---

lib/mix/tasks/phx.routes.ex

Hey 👋 & Happy New Year 🎆 
I Ran the `phx.routes` mix task the other day on an umbrella project and I was greeted by the following error message
```
** (Mix) umbrella applications require an explicit router to be given to phx.routes
```
It's not clear how one should specify the router, a file path or a module name so I added an example to make it clear. The new error message as follows:
```
** (Mix) umbrella applications require an explicit router to be given to phx.routes, for example:
$ mix phx.routes MyAppWeb.Router
```
This is well documented but thought this might save someone a bit of confusion.
We could also iterate through the apps and see if any of them have defined a router module with the default naming conventions and list them to make the error even more useful, something like …

Improved phx.routes umbrella error message

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

Adding a new argument to specify which headers will be persisted after recycling the connection. By default we keep the existing behavior, so only `accept` and `authorization` are persisted.

Enabling recycle of custom headers

---

installer/templates/phx_single/config/config.exs
installer/templates/phx_umbrella/apps/app_name_web/config/config.exs

This will hint to the users that a layout can be provided for error
pages.

Explicitly include the layout option when generating render_errors

---

guides/introduction/installation.md

Starting from version 1.4, Phoenix generates the Elixir child spec (making Elixir 1.5 the minimum working version for new Phoenix 1.4 apps, which is the case for the installation guide).
More info on: [v1.4.0 changelog](https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md#phxnew-installer).

Fix the Elixir minimum version on installation guide to 1.5

---

guides/endpoint.md
guides/phoenix_mix_tasks.md
lib/phoenix/endpoint.ex

Use Elixir v1.5's streamlined child specs in docs

---

.travis.yml

To avoid increasing much the build matrix, removed the combinations of new Elixir with older OTP versions.

Add Elixir 1.7 and 1.8 to Travis CI build matrix

---

lib/phoenix/controller.ex

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/controller.ex#L509 makes it clear that an atom is a valid layout value, the typespec should reflect that.

Fix typespec for put_layout

---

installer/templates/phx_web/templates/page/index.html.eex

Considering that the Elixir community on Slack has now more than 20k members, it's one of the best places to find help. Adding it to Phoenix initial default page should bring even more members to the community.

Add Elixir Slack link in the help column of the initial default page

---

lib/phoenix/test/conn_test.ex

the documentation on `phoenix/lib/phoenix/test/conn_test.ex` was using the deprecated method `conn/0` instead of `build_conn/0`, also in one example was giving the wrong arity

update documentation to reflect on function deprecations

---

guides/controllers.md

The semi-colon and "however" are unnecessary, since "If we don't find what we're looking for" and "we might find what we're looking for in Plug" don't disagree.

Reword sentence in Controllers guide

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

I would like to propose to print body in `ConnTest.response/2` in `inspect` format.
I think this would be useful and would avoid the test case from crashing when the response body is not printable.

Inspect body in ConnTest.response/2

---

guides/deployment/heroku.md

Added elixir_buildpack.config to the Heroku deployment documentation to prevent new users from getting tripped up by the Elixir 1.5.0 default on Heroku
This is the [forum post](https://elixirforum.com/t/ecto-migration-fails-on-heroku/18112/4) where I figured out the issue when I ran in to it while following the docs most recently.

Add elixir_buildpack.config to Heroku documentation

---

guides/phoenix_mix_tasks.md
guides/testing/testing.md
guides/testing/testing_controllers.md
guides/testing/testing_schemas.md
lib/mix/tasks/phx.gen.context.ex
lib/mix/tasks/phx.gen.html.ex
lib/mix/tasks/phx.gen.json.ex

1bf9ec3ee6c97bb3847669a74f2d8debd3648dc3 dropped special convention for context locations, but guides and documentation weren't properly updated.
This commit fixes some (hopefully all) of the outdated file names in the documentation.
cc @chrismccord

Update the documentation for 1.4.1 context location

---

guides/deployment/heroku.md

encourage setting both Elixir and Erlang version in elixir_buildpack.config
additionally I noticed information on using config_vars_to_export which is deprecated https://github.com/HashNuke/heroku-buildpack-elixir#migrating-from-previous-build-pack - and thus removed that from the guide.

Update heroku.md include erlang_version instructions

---

assets/js/phoenix.js

While running phoenix.js on react-native, we were getting a few of these in production:
```
#4 TypeError: null is not an object (evaluating 'this.conn.skipHeartbeat')
```
Adding a null reference check before evaluating that fixed the issue.

Added null reference check on resetHeartbeat() on phoenix.js

---

guides/deployment/heroku.md

in case 
`secret_key_base: System.get_env("SECRET_KEY_BASE") || raise "missing SECRET_KEY_BASE env var" `
is not the last argument eg.
```
config :app, AppWeb.Endpoint,
url: [host: "localhost"],
secret_key_base: System.get_env("SECRET_KEY_BASE") || raise "missing SECRET_KEY_BASE env var",
render_errors: [view: AppWeb.ErrorView, accepts: ~w(html json)],
pubsub: [name: App.PubSub, adapter: Phoenix.PubSub.PG2]
```
the raise lacking parentheses will cause a CompileError (elixir 1.7.1)
** (CompileError) config/config.exs:13: invalid call "missing SECRET_KEY_BASE env var"
adding parentheses avoids issue.

Update heroku.md add parentheses for raise

---

assets/js/phoenix.js

From the [documentation](https://hexdocs.pm/phoenix/js/index.html#socketconnect) it was not clear that passing params into `Socket.connect()` is deprecated, only in runtime this will show on the JS console.

phoenix.js: Document that passing params to connect() is deprecated

---

lib/mix/phoenix.ex
lib/mix/tasks/phx.gen.context.ex
test/mix/tasks/phx.gen.context_test.exs

 prohibit context creation with the same name as the application

---

installer/templates/phx_single/config/prod.exs
installer/templates/phx_umbrella/apps/app_name_web/config/prod.exs

When running `phx.new` with the `--umbrella` flag, the comments generated in the web app's `/config/prod.exs` have a small bug in that they refer to the `:app_name` instead of `:web_app_name`.
E.g. 
`awesome_umbrella/apps/awesome_web/config/prod.exs` has:
`config :awesome_web, AwesomeWeb.Endpoint,`
yet the comments in that file have 3 references to
`#     config :awesome, AwesomeWeb.Endpoint,`
For non-umbrella projects, the output is correct as `app_name` and `web_app_name` have the same value, however I still think it's more correct to use `web_app_name`.
Hope this is helpful! 😃

Fix documentation generated in prod.exs

---

lib/phoenix/token.ex
test/phoenix/token_test.exs

Because of the comparison being done in ms if assertions with 0
can sometimes lead to unexpected results
Example:
```
token = Phoenix.Token.sign(Endpoint, @salt, user_id)
assert {:error, :expired} = Phoenix.Token.verify(Endpoint, @salt, token, max_age: 0)
```
Even though this test should always pass, given that the expiration of the token is right now, it can sometimes fail giving it a transient behaviour.

Phoenix.Token.verify/4 will always return true when provided a max_age lower or equal to 0

---

README.md
guides/views.md
installer/templates/phx_web/templates/page/index.html.eex
lib/mix/tasks/phx.ex
mix.exs

This is a super nitpick, but [my friend](https://github.com/jalcine) dared me to open a PR, so here it is.
The project tagline currently reads:
> A productive web framework that does not compromise speed and maintainability.
While this may technically be true, it translates to the following logic:
```
(doesCompromiseSpeed && doesCompromiseMaintainability) === false
```
The issue with this is that since only one of the conditions needs to be `false`, it could be interpreted along the lines of:
> Other frameworks compromise both speed and maintainability, but Phoenix only compromises one of them.
Thus, I think it'd be better to change the "and" to an "or," so that it's clear that Phoenix does not compromise either speed _or_ maintainability. In other words:
```
(doesCompromiseSpeed || …
```

Update project tagline to be more clear

---

installer/templates/phx_assets/webpack/package.json

I was having a problem in my Phoenix project, that the `@import`'s of my CSS file was not following the given order, so updating `css-loader` to the latest version just fixed it.

Update css-loader to ^2.1.1

---

lib/phoenix/socket.ex

The typespec of Phoenix.Socket lists `id` as `nil`. It should be `String.t` if I see that correctly.

Fix typespec of socket.id

---

lib/mix/phoenix/schema.ex
priv/templates/phx.gen.schema/migration.exs
test/mix/tasks/phx.gen.schema_test.exs

If the current app configuration specifies a custom migration module the generated migration code will use that rather than the default
Ecto.Migration
config :ecto_sql, migration_module: MyApplication.CustomMigrationModule
cf.  https://github.com/elixir-ecto/ecto_sql/pull/76
I think I have all the bases covered, if not please advise and I will correct.
Thank you!

Allow the app configuration to specify a custom migration module for the generated migration code.

---

guides/channels.md

In the Channels guide, some of the ellipses in code examples breaks the syntax highlighting -- [Issue #3331](https://github.com/phoenixframework/phoenix/issues/3331). I've simply commented them out in both Elixir and JS.
Example Before:
After:
I wanted to try and generate the hex docs to make sure they are looking correct there as well but had some trouble. I followed these instructions from the README.md:
>To build the documentation from source:
>```bash
>$ cd assets
>$ npm install
>$ cd ..
>$ MIX_ENV=docs mix docs
>```
But was seeing this output:
```
$ MIX_ENV=docs mix docs
Compiling 76 files (.ex)
warning: redefining module Mix.Tasks.Phx.New.Ecto (current version loaded from /Users/llowder/.mix/archives/phx_new-1.4.2/phx_new-1.4.2/ebin/Elixir.Mix.Tasks.Phx.New.Ecto.beam) …
```

Comment out ellipses in code examples

---

guides/deployment/heroku.md

I felt like this doc could be simplified a bit for those who possibly have a more simplistic or conventional setup for their application and pushing to Heroku. So I've made some changes, open for discussion of course. Overall, I felt like having the buildpacks explain themselves might be better so we don't have to worry about decay in these docs as the buildpacks change.
Explained to the reader using the latest published version of the buildpack and if needed to use more nightly/edge, then consult the docs.
In some example output there was a line I removed .... "Run `git push heroku master` to create a new release using these buildpacks." When adding the heroku-buildpack-phoenix-static buildpack as I feel like it can cause confusion to beginners. Upon seeing this, someone might think this …

Updated with a more simple approach

---

installer/templates/phx_single/config/dev.exs
installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
installer/test/phx_new_test.exs
installer/test/phx_new_umbrella_test.exs
lib/phoenix/template.ex

Although this means Phoenix knows a bit about LiveView,
it is justified as LiveView is shaping to became an important
asset in the Elixir community and it will help with its getting
started experience.

Incorporate some of LiveView steps into Phoenix

---

lib/phoenix/controller.ex

Previously the list of headers in documentation was indented with 4 spaces which resulted in incorrect rendering.

Fix put_secure_browser_headers/2 docs

---

installer/lib/phx_new/generator.ex

This will help developers debug connection errors in development,
improving their getting started experience.

Enable show_sensitive_data_on_connection_error in config/dev.exs

---

lib/phoenix/controller.ex
test/phoenix/controller/controller_test.exs

- Motivation
I was creating a system the enable users to download files with a
variety of names the put spaces and other characters. When downloading
this kind of file names like `my custom report.xlsx` was returning
`my+custom+report.xlsx`. Esthetically it is ugly to users and they need to edit it to download with the correct nam
- Solution
I created the possibility to send option `encode`, the default value of
the option is nil, and it only avoid the encode_www_form if it was
passed as `false`
- Issue: #3343

Enable to use send_download without encode

---

lib/phoenix/controller.ex
lib/phoenix/router/helpers.ex
test/phoenix/router/helpers_test.exs

Similar to the `Phoenix.Controller.put_router_url/1` introduced in 1.4, this PR introduces a `Phoenix.Controller.put_static_url/1` function that allows to set the information used to generate the static url within the route helpers more dynamically.
My use-case for this is to enable one phoenix installation to serve multiple domains from one endpoint while having a way to set the correct url to use for static file serving seperately for all of them in cases when I have to use absolute urls. Basically what `put_router_url/1` does but then for static urls.

Introduce `put_static_url` for more dynamic static url generation

---

lib/phoenix/controller.ex
lib/phoenix/controller/flash.ex
test/phoenix/controller/flash_test.exs

Based on a conversation here:
https://groups.google.com/forum/#!searchin/phoenix-core/liveview%7Csort:date/phoenix-core/61kVmWkF6QI/70BFY0zFCAAJ
The proposed step forward for getting `--live` (and eventually `--no-live`) integrated into phoenix directly.
```
1. phx.new --live flag (it will be opt-in on v1.5 while we figure things out but probably enabled by default on v1.6)
2. phx.new.live generators
3. Bring the functionality in LiveView.Flash to Phoenix so we can get rid of one plug
```
It was suggested to start with #3
Once released, then I can help remove that code from phoenix_live_view and update the documentation to remove the need for the second flash plug.
@josevalim if I have mis-understood, let me know.

Refactor flash methods from Phoenix.Controller into Phoenix.Controller.Flash

---

lib/mix/tasks/phx.server.ex

Document that setting `server: true` in your endpoint configuration will allow you to start your Phoenix Endpoint server without using the `mix phx.server` task. Document this in a place that a user will likely find it, in the mix task that they need to use (by default) to start their server.

Document phx.server alternative

---

lib/phoenix/endpoint.ex

This adds documentation for the compress option. There is already an example for it which shows it can be used. I tested it all still works well.

Document compress option

---

guides/contexts.md
lib/mix/phoenix/context.ex
test/mix/tasks/phx.gen.context_test.exs
test/mix/tasks/phx.gen.html_test.exs
test/mix/tasks/phx.gen.json_test.exs

When `phx.gen` creates a new context, it creates the context and puts it as a sibling to a directory by the same name containing the generated schema: `mix phx.gen.html Accounts User ...` generates both `lib/my_app/accounts.ex` and `lib/my_app/accounts/user.ex`.
The generated tests do not follow the same structure—the tests are both generated under `test/my_app/accounts/`.
The inconsistency for the Context between `lib` and `test` make it difficult to configure tools such as [projectionist.vim](https://github.com/tpope/vim-projectionist) which may rely on a mirrored structure to intuit which test maps to which file.
This PR attempts to move the context's test up a directory so that both `lib` and `test` are in sync.

Move context test to mirror placement in lib

---

lib/phoenix/router/scope.ex
test/phoenix/router/scope_test.exs

Raise error when route name uses `static` in the prefix

---

guides/deployment/deployment.md
guides/deployment/heroku.md
installer/lib/phx_new/generator.ex
installer/templates/phx_single/config/prod.exs
installer/templates/phx_single/config/prod.secret.exs
installer/templates/phx_single/gitignore
installer/templates/phx_umbrella/apps/app_name/gitignore
installer/templates/phx_umbrella/apps/app_name_web/config/prod.exs
installer/templates/phx_umbrella/apps/app_name_web/config/prod.secret.exs
installer/templates/phx_umbrella/apps/app_name_web/gitignore
installer/templates/phx_umbrella/config/prod.secret.exs
installer/test/phx_new_test.exs
installer/test/phx_new_umbrella_test.exs

We have historically stayed away from environment variables
because it was incompatible with releases but now with
Distillery 2 and `mix release` in Elixir v1.9 this is a
solved problem, so we can push towards those best practices
for new apps.

Modernize config/prod.secret.exs

---

guides/deployment/heroku.md

Used the heroku guide recently and noticed references to files that were probably created in an earlier version of the guide, but that don't exist anymore, so removed them (Procfile and compile).
Also, if you're following the guide but skipping the static buildpack because you don't have HTML, you'll end up with a hard to understand error (Heroku stops your app because it doesn't attach to the assigned port). This is because the elixir buildpack uses `mix run --no-halt` and the configuration in the guide doesn't include `server: true`. This is fine if you're using the static buildpack, since it replaces the default Procfile with `mix phx.server` which adds it automatically.
Adding `server: true` just works for everyone. I'm not sure if I should add an explanation of why, or if that would …

Update Heroku guide to help non-HTML apps

---

lib/phoenix/digester.ex

Fixed logic issue in `Phoenix.Digester.uncompressed_digested_file?`.

---

installer/templates/phx_ecto/data_case.ex

`DataCase.errors_on/1` raises an error when it receives a changeset with an array field which was `cast`-ed with an invalid type.
When validating the type of an array field fails, `cast/4` it will put an error on the changeset, such as:
```elixir
[my_list_field: {"is invalid", [type: {:array, :string}, validation: :cast]}]
```
While processing this error, `errors_on/1` will try to `to_string/1` the `{:array, :string}` tuple, which produces the error:
```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:array, :string}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Time, URI, Version, Version.Requirement
```
`to_string/1` is called on error metadata as part of …

Fix DataCase.errors_on/1 when using changeset with array field

---

guides/phoenix_mix_tasks.md

Fixing mix ecto.drop documentation typo

Fixing mix ecto.drop documentation typo

---

lib/phoenix/digester.ex
test/phoenix/digester_test.exs

This PR fixes the issues I brought up in #3394. I've tested this fix in production on our project and it does work as originally intended. It is slightly inefficient since we are digesting the file twice, we could  improve that but I will leave for comment.

bugfix(SRI): Ensure that we are hashing digested file content

---

guides/deployment/deployment.md

I guess it is a typo, as it is generally bad idea to commit secrets to vcs and `config/prod.secret.exs` itself mentions it:
```
```

Fix secrets related info in Deployment docs

---

guides/ecto.md

Just a small addition where I got stuck for a second while following the guide.
The second sample also lists the `\q` command to exit the `psql` terminal, but if the reader follows along  from the beginning (and is unfamiliar with the Postgres Terminal at this point) he might get stuck before getting there.

Add \q command to exit psql after creating user

---

lib/mix/phoenix/context.ex
lib/mix/tasks/phx.gen.context.ex

This PR will allow `Context.function_count/1` to count both `def` and `defdelegate` functions.
Currently the `Context.function_count/1` function returns the number of `def` functions in the Context file.
I usually change the context file to contain only/mostly `defdelegate` functions which are delegated to modules under `context_folder/api/module_name.ex`. The prompt I get in the terminal about the number of functions I have in the Context file is always inaccurate due to this issue. It's a minor issue and might not be popular, but I'd thought I'd create this PR to scratch my own itch since it was just a one-liner.

Context.function_count/1 accounts for both def and defdelegate

---

guides/channels.md

Brand new Phoenix Channels client for the open-source Godot Game Engine https://godotengine.org, implemented in GDScript (Godot's Python like language).
This client implements almost every aspect of the official JS client (right now only push buffers are missing, other than that, everything else is there).
Although Godot is not a game engine as popular as Unity, it has been growing since its latest release, specially between open-source enthusiasts, and since it has built-in WebSocket support, I felt it had a natural fit for Phoenix Channels. Also last month the engine got [a grant](https://godotengine.org/article/godot-engine-awarded-50000-mozilla-open-source-support-program) from the Mozilla Foundation, which will help turn it into an even better "web-ready" platform, and again, I see a …

Added a link to another 3rd party Channel client: GodotPhoenixChannels

---

installer/templates/phx_ecto/data_case.ex

The generated `errors_on` function inside DataCase uses `Map.get`, but `opts` is a keyword list.
Right now, the `errors_on` function from `master` causes an error, like:
```
(BadMapError) expected a map, got: [count: 3, validation: :length, kind: :min, type: :string]
```
This is related to the recently merged #3204 PR.

Replace Map.get with Keyword.get inside generated DataCase errors_on function

---

guides/deployment/heroku.md

Heroku deployment guide had two minor errors:
- URL of the generated Heroku app was wrong. It just had the subdomain part, missing the hostname. This results in application redirecting to wrong URL if user follows the guide to the word, and nothing works as a result.
- Procfile said add like "mix phx.server" and again, if user does not know anything about Procfiles and follows the guide, this results in application failing to start. One needs to add line "web: mix phx.server"
- minor formatting change

Update Heroku buildpack docs

---

lib/phoenix/router.ex
lib/phoenix/test/conn_test.ex
test/phoenix/router/routing_test.exs
test/phoenix/test/conn_test.exs

@josevalim any input on how we should partially make `%Phoenix.Router.Route{}` public? Still needs docs about what is and isn't private, but not sure what's best at the moduledoc/or router_info function doc level. Would appreciate your thoughts

Add route_info lookup

---

assets/package.json
installer/templates/phx_assets/package.json

According to npm audit, the current versions of `webpack-cli ` and `optimize-css-assets-webpack-plugin` mentioned in the package.json have vulnerabilities:
```bash
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ optimize-css-assets-webpack-plugin [dev]                     │
├───────────────┼──────────────────────────────────────────────────────────────┤ …
```

Updating webpack-cli and optimize-css-assets-webpack-plugin node modules

---

installer/templates/phx_assets/webpack.config.js

The goal of this PR is to update the default Webpack config to load `./js/app.js` last so that it can be exported by the entry point as an output library.
**Issue**
Webpack output can not reliably be exposed as a library with the default config.
**Root Cause**
Webpack entry point returns last `./vendor/js` library when present instead of `./js/app.js`.
**The Fix**
Update default Webpack config to swap entry load order so `./js/app.js` loads last.
**Details**
Before getting started, I must disclose that I am not a Webpack expert! The extent of my knowledge is yesterday while upgrading a phoenix app from v1.3 -> v1.4 and replacing brunch with it, exposing this issue. 😄 
When using the default Webpack config, the entry section has `./js/app.js` first and then concats all contents of …

Patch webpack config to load app.js after vendor js

---

priv/templates/phx.gen.context/schema_access.ex

Minor problem I found while trying to doctest a context.
A little side-question: from what I see, doctesting a context is not supported out-of-the-box, so should I bother doing it or not?

Fixed template example field name

---

guides/channels.md

I noticed some minor flaws while learning about Channels. 
- The js examples use [keyCode, which is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). I've updated the examples to use [key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) instead. 
- `li` elements are not valid children outside of ol/ul/menu elements ([src](https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element)). I've replaced the `li` with a `p` tag, which matches the referenced [phoenix chat example implementation](https://github.com/chrismccord/phoenix_chat_example/blob/master/web/static/js/app.js#L51).
- Lastly, I added some [aria live region attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) for some …

Minor improvements to Channels docs page

---

lib/phoenix/endpoint.ex

Specifically it makes it more obvious that exactly `:supervisor` is passed instead of potentially some other atom. Use "the" instead of "a" because there can only be one instance of an atom in the system.

Changes to init callback description to make it easier to read

---

guides/channels.md

Fix malformed link to GodotPhoenixChannels in the Channels guide

fixed GodotPhoenixChannels url

---

installer/lib/mix/tasks/local.phx.ex

Following from [this Stack Overflow question](https://stackoverflow.com/questions/56743592/why-does-running-local-phx-downgrade-the-phoenix-archive) and a [closed issue](https://github.com/phoenixframework/archives/issues/2) on the archives repository, it is not clear from the `mix local.phx` docs that the command is no longer supported, and effectively downgrades to 1.3.2.
I deprecated the task, added a warning, and made the version that will be installed explicit, so that it's visible from the task output.
```
$ mix local.phx
WARNING: mix local.phx is no longer supported, use: mix archive.install hex phx_new
Are you sure you want to install "https://github.com/phoenixframework/archives/raw/master/phx_new-1.3.4.ez"? [Yn]
```

Use hex in mix local.phx

---

guides/deployment/releases.md

The current nodejs dependency does not include npm for some reason. Following the current instructions will cause a failure. There is no need to keep nodejs as it is a dependency of npm.

Fix Dockerfile build dependency

---

guides/deployment/releases.md

The assets compilation script now requires `npm` instead of `yarn` so we need to install it first.
Removed `python` and `git` because they are not needed in most deployments.
`build-base` is preserved because `gcc` is often needed.

Only install required dependencies in Dockerfile

---

guides/deployment/deployment.md

The deployment doc page is currently showing as follows:
```
$ MIX_ENV=prod mix compile
<<<<<<< HEAD
$ cd assets && webpack --mode production && cd ..
=======
$ npm run deploy --prefix ./assets
>>>>>>> 99a02839... Add a guide on v1.9 releases
$ mix phx.digest
```

Remove merge conflict from deployment docs.

---

guides/deployment/releases.md

In the [Releases Guide](https://hexdocs.pm/phoenix/releases.html#releases-assemble) the link for `deployment guide` is returning 404.
This PR aims to fix that with the [correct link](https://hexdocs.pm/phoenix/deployment.html).
Thank you very much for maintaining Phoenix! :tada: :heart:

Fix deployment link on Releases Guide

---

installer/templates/phx_assets/webpack.config.js

Thanks for all of the amazing work on Pheonix! Great framework.
I can't see any reason why we wouldn't want to enable source map generation by default. What do you think?

Build sourcemaps by default in dev

---

lib/phoenix/endpoint/cowboy_websocket.ex

`conn` is wrongly nested in pattern match, causing exceptions when passed to `Cowboy2Handler.copy_resp_headers/2`.
Fixes failing tests in  #3474, #3490, #3491 and #3495.

Fix Cowboy WebSocket error handling

---

lib/phoenix/endpoint.ex

`:check_origin` documentation is duplicated between endpoint configuration and `socket/3`. Moreover, these settings are not the same thing.
This pull request moves all options to `socket/3` and explains that the endpoint configuration sets the default option.

Improve :check_origin docs

---

guides/deployment/releases.md

Load the configured `@app` (by calling `repos/0`) before attempting the rollback, similar to `migrate/0`. 
Otherwise the following error gets raised:
```
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
(elixir) lib/keyword.ex:393: Keyword.fetch!/2
(postgrex) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
(db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
(connection) lib/connection.ex:622: Connection.enter_connect/5
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
```

 Fix rollback/2 in releases guide

---

lib/phoenix/controller.ex

This should fix #3459. I basically pulled the note from Plug's source code (elixir-plug/plug#853) and mofified it slightly.

Added header casing note

---

guides/deployment/releases.md

I loved to see this documentation, but I ran into a snag. My postgrex configuration has `ssl: true`, so the `:ssl` app is required for the connection. When I followed this guide, I got:
```
** (EXIT from #PID<0.165.0>) an exception was raised:
** (RuntimeError) SSL connection can not be established because `:ssl` application is not started,
you can add it to `extra_application` in your `mix.exs`:
def application do
[extra_applications: [:ssl]]
end
(postgrex) lib/postgrex.ex:538: Postgrex.ensure_deps_started!/1
(postgrex) lib/postgrex.ex:480: Postgrex.child_spec/1
(ecto_sql) lib/ecto/adapters/sql.ex:462: Ecto.Adapters.SQL.init/3
(ecto) lib/ecto/repo/supervisor.ex:162: Ecto.Repo.Supervisor.init/1
(stdlib) supervisor.erl:295: :supervisor.init/1
(stdlib) gen_server.erl:374: …
```

deployment guide: Application.load -> ensure_all_started

---

guides/deployment/releases.md

In all cases we assemble the release with `MIX_ENV=prod`!

Replace _build/dev with _build/prod in releases guide

---

lib/phoenix/socket.ex
test/phoenix/socket/socket_test.exs

This reflects the capabilities of Live View, allow multiple vallues to
be assigned at once.

Allow using a keyword list/map for socket assigns

---

guides/deployment/deployment.md

This is based on @josevalim 's comment in [https://stackoverflow.com/questions/30061044/how-to-start-phoenix-server-as-daemon](https://stackoverflow.com/questions/30061044/how-to-start-phoenix-server-as-daemon)

Added instruction to run Phoenix server in detached mode

---

guides/adding_pages.md

Just a little typo in the guide.

Minor typo fix in markdown

---

guides/deployment/heroku.md
guides/deployment/releases.md

Heroku's setup using buildpacks can get little tricky at times and is not very flexible. For example adding `ImageMagick` to our Heroku setup can get really complicated.
Heroku also [offers `container` stack](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml) which can be used to deploy apps using docker containers. In this way, we need to add a `Dockerfile` to define our image and whats needed to be built, then use `heroku.yml` to tell heroku how to run our image and what needs to be passed to it (think of it as `docker-compose`)
This PR updates the docs to also describe how we can build a container based app on heroku and set it up with phoenix.

Update Heroku deployment docs to include container based approach

---

lib/phoenix/endpoint.ex

This PR fixes wrong documentation for path of node watcher

Fixed wrong documentation on phoenix endpoint watcher

---

installer/templates/phx_single/config/dev.exs
installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
installer/test/phx_new_test.exs
installer/test/phx_new_umbrella_test.exs

A while ago the default `dev.exs` config was changed to begin incorporating Phoenix Live View, but a shell style glob `{live,views}` was added instead of a regex `(live|views)`, thus breaking the live reload of views in a new project.

Fixed default config for new projects so that live_reload works on views again

---

lib/phoenix/view.ex

When profiling a heavy loaded Phoenix application that in some cases calls Phoenix.View.assign_resource/3 many times this change makes the function be 25% faster.
The downside is that it changes `as: nil` behaviour. I suppose it is not a documented behaviour and we better get a speedup.

Optimize resource assigning in Phoenix.View

---

lib/phoenix/socket/serializer.ex

Fix of the mismatch between the types described in the `Phoenix.Socket.Serializer` behaviour and implemented in serializers [`Phoenix.Socket.V2.JSONSerializer`](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/serializers/v2_json_serializer.ex#L21) and [`Phoenix.Socket.V1.JSONSerializer`](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/serializers/v1_json_serializer.ex#L36).

Return iodata instead binary in Socket.Serializer behaviour

---

lib/phoenix/router/route.ex

Verb is a atom and is verified if is a atom in guard: `is_atom(verb)`

Fix `build/12` @spec

---

lib/phoenix/view.ex

This makes heavily nested rendering ~8% faster.

Inline assigns to map transformation in Phoenix.View

---

assets/js/phoenix.js

I recently had to supply socket.disconnect with a code for disconnecting and couldn't easily find any documentation. I added a link to the relevant part of the javascript socket documentation where you find codes with descriptions.

Updated phoenixjs disconnect documentation.

---

lib/mix/phoenix/schema.ex

It’s not clear if `--web` to generators takes a module or directory name. Both
```bash
$ mix phx.gen.html Sales User users --web Sales
```
```bash
$ mix phx.gen.html Sales User users --web sales
```
feel equally valid. However, passing `sales` generates module names like
```elixir
MyAppWeb.:"Elixir.sales.User"Controller
```
which won’t compile.
Instead of raising on bad input, accept both forms by normalising to camel case first.

Camelize --web option to generators

---

priv/templates/phx.gen.html/index.html.eex

The links "Show", "Edit" and "Delete" are sticked together. Wrap them with span to add a little space in between.
Note that the same is done in the "show" template:
https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.html/show.html.eex#L12

Fix trivial ui issue in generated index.html.eex template

---

lib/phoenix/endpoint.ex
lib/phoenix/socket/transport.ex
lib/phoenix/transports/websocket.ex
test/phoenix/integration/websocket_socket_test.exs
test/phoenix/socket/transport_test.exs

In the WebSockets standard, there is a feature to pass supported subprotocols.
To do this, the client passes the list of supported subprotocols in `Sec-WebSocket-Protocol` header of the upgrade request. eq: `Sec-Websocket-Protocol: v12.stomp, mqtt`.
The server selects a supported protocol and returns it in the same header `Sec-Websocket-Protocol: mqtt`, then the handshake is successful.
If the server does not return the header, then we get a handshake error, like that:
```javascript
WebSocket connection to 'ws://localhost:4000/socket/websocket' failed:
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' 
header but no response was received`
```
More details in rfc : https://tools.ietf.org/html/rfc6455#section-1.9
Many protocols require the explicit indication of the …

Support Websocket subprotocols

---

lib/phoenix.ex
lib/phoenix/logger.ex
mix.exs

Elixir's `Logger` is very constraining library and some people (like me)
prefer to use different approaches (like `logger` or `lager`) which
(among other things) allow for much more detailed log levels and
structured logging. If someone use such logging library then
`Phoenix.Logger` can generate needless noise in logs. This change allows
to disable this module by such users.

Allow disabling logger via application configuration

---

lib/phoenix/config.ex
lib/phoenix/endpoint.ex
lib/phoenix/endpoint/supervisor.ex
test/phoenix/endpoint/endpoint_test.exs

This allows passing additional configuration options in supervisor spec, ex.:
```elixir
children = [
{MyApp.Endpoint, url: [path: "/api"]}
]
```
Will be the same as setting:
```elixir
config :my_app, MyApp.Endpoint, url: [path: "/api"]
```
---
Configuration still overwrite values set in supervisor, so:
```elixir
children = [
{MyApp.Endpoint, url: [path: "/foo"]}
]
```
and
```elixir
config :my_app, MyApp.Endpoint, url: [path: "/bar"]
```
Will result in:
```elixir
assert "/bar" == MyApp.Endpoint.config(:url)[:path]
```

Merge arguments from supervisor into endpoint configuration

---

guides/deployment/releases.md

This has never worked for me, and I've always had to remove it
when setting up phoenix dockerfiles.  There is no "rel" directory
in the phoenix project root, so it has nothing to copy, so it crashes.
Here is someone else that had to remove it:
https://stackoverflow.com/questions/58163103/how-do-i-run-elixir-phoenix-docker-in-production-mode-using-example-from-phoenix
Did this refer to something used in older versions?

Remove COPY rel rel command from Dockerfile example

---

guides/introduction/installation.md

This basic detail was a hindrance to me when I followed the Up and Running Guide. Perhaps this clarification would help another novice in the future.

Add clarity to PostgreSQL instructions

---

guides/deployment/releases.md

- The steps `npm deploy` and `mix phx.digest` generate new Javascript
and a `cache_manifest.json` file inside the build docker container.
- The `COPY priv priv` copies the priv directory from the working
directory outside docker to the build docker container.  This also
contains the `cache_manifest.json`.
Therefore:
If you have ever played around with releases outside of docker, the
`COPY priv priv` command will overwrite the cache_manifest.json you just
built inside docker with whatever is in your working directory, which
is older.  It will give the appearance of any javascript changes you
make not being updated even if you build new docker containers.

Dockerfile: Ensure "COPY priv" is before "npm deploy" and "mix phx.digest"

---

installer/templates/phx_single/config/prod.exs
installer/templates/phx_single/config/prod.secret.exs
installer/templates/phx_umbrella/apps/app_name_web/config/prod.exs
installer/templates/phx_umbrella/apps/app_name_web/config/prod.secret.exs
test/phoenix/integration/endpoint_test.exs

Currently, default (generated by the installer) `prod.secret.exs` overwrites existing `:http` config (#3549).
Default `prod.secret.exs`:
```elixir
config :demo_app, DemoAppWeb.Endpoint,
http: [:inet6, port: String.to_integer(System.get_env("PORT") || "4000")],
secret_key_base: secret_key_base
```
The Config deep merges keyword lists only and `[:inet6, port: ...]` is a regular list so Config overwrites `:http` value. This behavior could be inconvenient (and maybe even confusing) if you have SSL or custom dispatch configuration in `config.exs` or `prod.exs`.
After some digging in Phoenix, Plug.Cowboy, Cowboy, and Ranch the only solution I've managed to find is to set `:inet6` inside `endpoint_config[:http][:transport_options][:socket_opts]` instead of `endpoint_config[:http]`.
Fixes #3549.

Do not overwrite `:http` configuration in `prod.secret.exs`

---

lib/phoenix/test/conn_test.ex
test/phoenix/test/conn_test.exs

closes https://github.com/phoenixframework/phoenix/issues/3531
ready for review

Add accept-language to the list of headers that are copied in Phoenix.ConnTest.recycle

---

guides/errors.md
installer/templates/phx_single/mix.exs
installer/templates/phx_web/endpoint.ex
installer/test/phx_new_test.exs

Adds the `CheckRepoReady` plug to default generated phoenix applications which checks whether the application's repos have the storage created or have pending migrations.
For that, we had to bump the minimum version of `phoenix_ecto` on the generated applications to `4.1` as to get the release with the changes in phoenixframework/phoenix_ecto#122 and then add the plug to the generated application's `endpoint.ex`.
- Once we have a release of the changes in elixir-ecto/ecto_sql#164, we should also bump the version of `ecto_sql` on the phoenix generated applications, so, for now, the check for whether the storage is created will not work (only the check for pending migrations)
- Once we have a release of the changes in elixir-plug/plug#876, we should bump the version of `plug` in …

Add CheckRepoReady plug to generated phoenix applications

---

guides/ecto.md

Using the `.html` file extension here led to a 404 when trying to access the "Using MySQL" section of the readme.

Fix 404 on "Using MySQL" link

---

lib/phoenix/template.ex

Patterns don't currently appear in `Phoenix.Template.UndefinedError` messages. Would this be appropriate?
```
** (Phoenix.Template.UndefinedError) Could not render "doesnotexist" for
MyAppWeb.PageView,  please define a matching clause for render/2 or define a template
at "lib/testing_web/templates/page/*". The following templates were compiled:
* index.html
```

Add template patterns to error messages?

---

lib/phoenix/exceptions.ex

The blame functionality previously used FunctionClauseError.blame/3,
however it is likely that blame/2 was intended to be used.
This could be triggered when requesting a route with invalid params
without the accept header in place.
This closes #3317

Fix blame in Phoenix.ActionClauseError

---

installer/templates/phx_static/app.js

When generating an app with the `--no-webpack` option, delete links don't work with _v2.10.0_ of the mentioned file.

Bump phoenix_html.js to v2.13.3

---

guides/routing.md

The example code for the `BackgroundJob.Plug`  module in `routing.md` is missing the `HelloWeb` prefix causing a compile error.  
This fixes that and improves some wording in the doc as well.

Fix typo and improve wording in routing.md guide

---

lib/phoenix/endpoint.ex
lib/phoenix/endpoint/supervisor.ex
test/phoenix/endpoint/endpoint_test.exs

Within my current Umbrella project, I have multiple applications sharing the same assets. That's why I've created an "empty" application only containing the assets and the cache manifest. Configuring the correct app was easy for `Plug.Static` through the `:from` option. But the `:cache_static_manifest` option could only use a directory within the app itself. 
This PR adds the option to define the application from where the path to the cache manifest must be resolved in a similar fashion as the `Plug.Static` option. Also a normal file path still works so no breaking backwards compatibility.

Load cache manifest from specified application

---

installer/templates/phx_static/app.js

Recently, notice a [PR](https://github.com/phoenixframework/phoenix/pull/3609) which bump the version of `phoenix_html.js`.
But, always giving the point which points to the newest version of phoenix_html.js maybe not a good idea. Assume such a situation:
+ a user `mix phx.new` a project with `phoenix 1.4.11` in 2021 (this is an extreme case, I know)
+ mainstream of phoenix has already ugraded to `phoenix 2.0.0`, and `phoenix_html` isn't compatible with `phoenix 1.4.11`
After reading the comments,  the user get the script at `https://raw.githubusercontent.com/phoenixframework/phoenix_html/master/priv/static/phoenix_html.js`, but that version of script is not working with his app.
Because of that, using a path relative to the the directory installed by Mix maybe a better solution - version …

Use phoenix_html.js installed by mix

---

lib/phoenix/endpoint.ex

Fix typo inside `lib/phoenix/endpoint.ex`

---

installer/templates/phx_ecto/data_case.ex
installer/templates/phx_test/support/channel_case.ex
installer/templates/phx_test/support/conn_case.ex

The intent of this PR is to improve the generated documentation in the installer with respect to async testing of PostgreSQL databases:
*  `channel_case.ex` template was missed as part of phoenixframework#3577 .
*  `data_case.ex` template incorrectly referenced `web_namespace` instead of `app_module`.
* fixed a typo in `conn_case.ex` template.

Updated `channel_case` sandbox documentation.

---

guides/ecto.md

Moving the paragraph in the ecto documentation to describe the code block immediately above it. The current placement is below a different code block, which initially confused me. I feel that the new placement reads better.

Moving paragraph in ecto documentation

---

lib/phoenix/transports/long_poll.ex
test/phoenix/integration/long_poll_channels_test.exs

This fixes #3590
With **WebSocket** (OK behaviour):
**Given**: I have a channel that returns `{:error, :channel_disabled}` on join
**When**: User joins the channel with WebSocket transport
**Then**: `channel.join(...).receive('error')` is triggered where we can handle the error and decide if we want to reconnect or not.
With **LongPoll** (NOT OK behaviour):
**Given**: I have a channel that returns `{:error, :channel_disabled}` on join
**When**: User joins the channel with LongPoll transport
**Then**: `channel.join(...).receive('error')` is never triggered (NOT OK). Instead the whole transport reconnects to the PubSub. In our case we return an error again and so it basically starts reconnection loop.
This happened because `LongPoll` returned 401 whenever channel returned
something that was …

Fix error handling when joining a channel using LongPoll

---

guides/deployment/heroku.md

Hi,
This patch changes `config.prod.exs` in the Heroku deployment guide, to make the endpoint bind to the
port requested by Heroku to prevent the R10 error from happening. As far as I can tell, the error should be happening to everyone currently following the guide strictly (?).
https://devcenter.heroku.com/articles/error-codes#r10-boot-timeout

Mention PORT env var in Heroku deployment docs

---

lib/phoenix/test/conn_test.ex

Just what it says in the title! 😄

Fix typo in `test/conn_test.ex`

---

installer/templates/phx_assets/package.json

This is a PR to update version constraints in `package.json`. Fixes #3654 
As mentioned in #3654 there are breaking changes in the dependencies. We should verify that they are not an issue.
I have tested that `mix phx.server` runs as normal, and that the webpack compilation runs without errors. I haven't done a detailed testing of the compilation of individual files, channels or liveview etc.

Update package.json to get latest js dependencies

---

lib/phoenix/router.ex
lib/phoenix/router/helpers.ex

You said a PR for this was welcome on the issue #3579, so here it is. 
I am still trying to figure out how to test it, since I can't use `Code.fetch_docs/1` on in memory modules. Tried to do the same it's done on [docs tests on elixir repo](https://github.com/kelvinst/elixir/blob/642a794ace79f8098187034f75455bf95de1e7fc/lib/elixir/test/elixir/kernel/docs_test.exs#L99-L121), but the `write_beam` function just writes the beam for the given module, and if I do that for the router, it will save the beam for it, but not for the helper that's defined altogheter.
Any idea? Maybe there is a way to get the helper from it to save its beam, IDK.

Adding option to disable `Router.Helpers` docs to `use Phoenix.Router`

---

guides/contexts.md

Adjustment for file path code highlighting in Contexts Guide.
We have:
... `lib/hello_web/views/session_view.ex:`
... `lib/hello_web/templates/session/new.html.eex:`
We wish
... `lib/hello_web/views/session_view.ex`:
... `lib/hello_web/templates/session/new.html.eex`:

Fix file path formatting

---

guides/testing/testing_channels.md

socket/2 is deprecated, see: https://github.com/phoenixframework/phoenix/blob/v1.4.12/lib/phoenix/test/channel_test.ex#L240

Use non-deprecated socket/3 in guide

---

guides/introduction/installation.md

... as it is redundant info found on the elixir install page.
Replaces https://github.com/phoenixframework/phoenix/pull/3653

Remove Debian distro specific help

---

lib/phoenix/controller.ex
test/phoenix/controller/pipeline_test.exs

This can be useful for applications that want to control the defaults on their own, for example I use different naming scheme where instead of `MyAppWeb.FooController` each controllers is named as `MyAppWeb.Controllers.Foo` and the views are named `MyApp.Views.Foo`, which is suits more into overall naming scheme after file path.

Add option to not define default layout and view

---

assets/js/phoenix.js

Sadly we have to support IE11 which does not support [Array.prototype.includes()
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes). The fix itself it quite simple: instead of includes we can use indexOf.

Replace includes with indexOf in phoenix.js
