phoenixframework/phoenix

lib/phoenix/channel.ex
=> Fix typo in channel documentation

priv/template/config/prod.exs
Sorry my editor changed some whitespace, shouldn't hurt though.
Changing `pring` to `print`...
=> Typo in prod.exs

lib/phoenix/endpoint/adapter.ex, lib/phoenix/endpoint/server.ex, test/phoenix/endpoint/adapter_test.exs
This set port to PORT env var if it isn't set in config
=> Set port to PORT env var if it isn't set in config

test/phoenix/pubsub/pubsub_test.exs, test/test_helper.exs
=> Do not run redis tests if redis is not running

lib/phoenix/endpoint.ex
Mainly markup, some very slight rephrasings here and there. Let me know if I have to change something or if I can do anything else!
=> Polish the docs in Phoenix.Endpoint

lib/mix/tasks/phoenix.new.ex, priv/template/mix.exs, test/mix/tasks/phoenix.new_test.exs
This should fix issue #583.
The test passes when I run it alone, but when ran toghether with the other tests sometimes fails. Is it some cache issue?
=> Generate proper files under umbrella

priv/template/config/dev.exs
Fixes a failure on master when generating a new application.
=> Fix syntax error in config/dev.exs

lib/mix/tasks/phoenix.gen.resource.ex, test/mix/tasks/phoenix.gen.resource_test.exs
=> Check for colons in plural when generating resources

lib/phoenix/channel.ex, lib/phoenix/code_reloader.ex, lib/phoenix/controller.ex, lib/phoenix/controller/pipeline.ex, lib/phoenix/endpoint.ex, lib/phoenix/endpoint/adapter.ex, lib/phoenix/exceptions.ex, lib/phoenix/html.ex, lib/phoenix/naming.ex, lib/phoenix/pubsub.ex, lib/phoenix/pubsub/local.ex, lib/phoenix/router.ex, lib/phoenix/router/scope.ex, lib/phoenix/socket/message.ex, lib/phoenix/template.ex, lib/phoenix/transports/json_serializer.ex, lib/phoenix/transports/long_poller.ex, lib/phoenix/transports/long_poller/server.ex, lib/phoenix/transports/serializer.ex, lib/phoenix/transports/websocket.ex, lib/phoenix/view.ex
While reading through the code, I fixed a few typo errors in the code comments.
=> Fix a few comment typos add some comment puncutation

lib/phoenix/channel/transport.ex, lib/phoenix/endpoint.ex, lib/phoenix/transports/long_poller.ex, lib/phoenix/transports/websocket.ex, mix.lock, test/phoenix/channel/transport_test.exs, test/phoenix/integration/channel_test.exs, test/phoenix/integration/websocket_client.exs
No docs yet, sending PR to discuss implementation.
=> Restrict requests based on origin

priv/static/brunch/brunch-config.js
Fixes https://github.com/phoenixframework/phoenix/issues/690
=> Add example of brunch file concatenation order

CHANGELOG.md, README.md, lib/phoenix/router/live_reloader.ex, priv/static/phoenix.js, web/static/js/phoenix.js
```javascript
let socket = new Socket("/ws")
socket.connect()
...
```
=> Do not connect automatically on `new Phoenix.Socket(..)`

priv/static/app.css, priv/templates/new/web/templates/layout/application.html.eex, priv/templates/resource/form.html.eex, priv/templates/resource/index.html.eex, test/mix/tasks/phoenix.gen.resource_test.exs
Since we ship with bootstrap by default, let's use the markup and classes
to make things look a little nicer by default.
=> Improve generated form styling.

lib/phoenix/html/form.ex, test/phoenix/html/form_test.exs
I'm refactoring a project to use v0.10 and I noticed that there wasn't a password input helper in the form builder.
=> Password input tag

lib/mix/tasks/phoenix.gen.html.ex, priv/templates/resource/form.html.eex, test/mix/tasks/phoenix.gen.html_test.exs
Addresses #759. Implemented as per the discussion there.
=> Add "step: any" to generated number inputs for decimal and float fields

lib/mix/tasks/phoenix.gen.html.ex, priv/templates/resource/controller_test.exs, test/mix/tasks/phoenix.gen.html_test.exs
@josevalim how does this look? I think there might be a couple more test cases around not redirecting when the params for new or update are invalid?
=> Generate test files for gen html

priv/templates/html/controller_test.exs, test/mix/tasks/phoenix.gen.html_test.exs
Update generated tests to use `html_response`
Add generation of new and update action failures
Add generation of edit action test
=> Add controller new and update failure tests

lib/phoenix/html/form.ex, test/phoenix/html/form_test.exs
Added a form helper for the url input type.
=> Added url_input/3

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs
Prompted by https://github.com/elixir-lang/elixir/pull/3281 :)
=> Check on mix new if the given application module exists and raise if so

installer/templates/new/config/prod.exs
This PR adds missing space in prod config template. :)
=> Add missing space in prod config

lib/phoenix/template.ex, test/phoenix/view_test.exs
refs: https://github.com/phoenixframework/phoenix/issues/782
=> Template render without assigns

installer/templates/static/brunch/package.json, package.json, priv/static/phoenix.js
This should solve https://github.com/phoenixframework/phoenix/issues/789. I generated a new phoenix project from the changes and made sure that brunch was working fine.
I was pretty conservative on the range of versions for brunch and brunch-sass; let me know if that needs to be changed :smile:.
Changes in `priv/static/phoenix.js` was due to an `npm install`.
First PR here, so be gentle :sweat_smile:.
=> Update brunch dependencies

installer/lib/phoenix_new.ex, installer/templates/new/lib/application_name/endpoint.ex
Requires a bump in Plug. Based on this PR: https://github.com/elixir-lang/plug/pull/230
=> Don't encrypt cookies by default

package.json
This patch fixes the issue previously reported here: https://github.com/phoenixframework/phoenix/issues/806
=> upgrade babel-brunch dependency on package.json

lib/phoenix/conn_test.ex
Wasn't rendering correctly in the API docs but I *knew* José had a lot of docs :P
=> Fixing moduledoc for ConnTest

installer/templates/ecto/model_case.ex
refs: https://github.com/phoenixframework/phoenix/issues/853
=> Add errors_on to ModelCase

installer/templates/static/brunch/app.js
```js
// let socket = new Socket("/ws")
// socket.connect()
// let chan = socket.chan("topic:subtopic", {})
// chan.join().receive("ok", chan => {
//   console.log("Success!")
// })
```
=> Updated example channel info in the app.js

test/mix/tasks/phoenix.gen.html_test.exs, test/mix/tasks/phoenix.gen.json_test.exs
This fixes #896 by updating the tests to reflect the new generator changes.
Let me know if there's anything I should change!
=> Fix failing tests

lib/phoenix/router.ex, lib/phoenix/router/resource.ex, lib/phoenix/router/route.ex, lib/phoenix/router/scope.ex, test/phoenix/router/helpers_test.exs, test/phoenix/router/route_test.exs, test/phoenix/router/scope_test.exs
Closes https://github.com/phoenixframework/phoenix/issues/887
=> Add assigns

lib/mix/tasks/phoenix.digest.ex
Just some doc updates :purple_heart:
=> Update example of generated files with the names we get in latest version.

lib/phoenix/view.ex
Just a minor doc improvement for `render_existing/3`.
=> Provide more detail on how to use a precompiled template

lib/mix/phoenix.ex, lib/mix/tasks/phoenix.gen.channel.ex, lib/mix/tasks/phoenix.gen.html.ex, lib/mix/tasks/phoenix.gen.json.ex, lib/mix/tasks/phoenix.gen.model.ex, test/mix/tasks/phoenix.gen.channel_test.exs, test/mix/tasks/phoenix.gen.html_test.exs, test/mix/tasks/phoenix.gen.json_test.exs, test/mix/tasks/phoenix.gen.model_test.exs
RFC @josevalim — Thanks for letting me take a stab at this, looking forward to your feedback.
This closes #921.
=> Generators should be aware of reserved names

lib/phoenix/endpoint.ex
As per discussion on IRC, this adds a bit of docs on how to setup custom dispatch for cowboy handlers.
=> Add docs for custom dispatch options

lib/phoenix/test/conn_test.ex
circunstances -> circumstances
accept -> accepts
=> Typo fixes

lib/phoenix/digester.ex, lib/phoenix/view.ex
Reading through some of the source files, a couple of typos were uncovered and corrected.
=> Various typos

installer/templates/new/config/prod.exs, installer/test/phoenix_new_test.exs
RFC @chrismccord — This closes #922.  I saw your comment and thought I'd pounce on the opportunity to contribute again.  Let me know if there's anything you'd like changed.
Thanks!
=> Include port: 80 in new projects

CHANGELOG.md, lib/phoenix/router.ex, lib/phoenix/router/console_formatter.ex, lib/phoenix/router/helpers.ex, lib/phoenix/router/route.ex, lib/phoenix/router/scope.ex, test/mix/tasks/phoenix.routes_test.exs, test/phoenix/router/console_formatter_test.exs, test/phoenix/router/forward_test.exs, test/phoenix/router/helpers_test.exs, test/phoenix/router/route_test.exs, test/router_helper.exs
@josevalim I could use a code review on this one
=> Add forward macro to router

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs
This PR adds sqlite database support to phoenix using sqlite_ecto
=> Add sqlite support

web/static/js/phoenix.js
@chrismccord as discucssed here: https://github.com/phoenixframework/phoenix/pull/1010
the change is only in the source file. Please compile the file and commit in as well :)
=> properly figure out protocol to use for websocked when relative endoint given

installer/lib/phoenix_new.ex, installer/templates/new/lib/application_name/endpoint.ex, installer/templates/new/web/channels/user_socket.ex, installer/test/phoenix_new_test.exs, lib/mix/tasks/phoenix.gen.channel.ex, mix.lock
@josevalim Can I get a signoff on the generate module and docs? Should we add comments with more info in UserSocket or is this good?
=> Generate UserSocket module in new projects

installer/templates/ecto/model_case.ex, installer/templates/new/test/support/channel_case.ex, installer/templates/new/test/support/conn_case.ex, installer/templates/new/test/test_helper.exs
cf. 8cdf7675533f602a4078d98eb729fff1fa18a388, https://github.com/phoenixframework/phoenix/commit/4c4c9fbc9d3923c9b10af6f265925e919dc7fdf8#diff-5fe767297b48fba5e13a940eb9681b9cR40
=> Remove redundant comments

lib/mix/tasks/phoenix.gen.model.ex, mix.exs, mix.lock, priv/templates/model/migration.exs, priv/templates/model/model.ex, test/mix/tasks/phoenix.gen.model_test.exs
Closes https://github.com/phoenixframework/phoenix/issues/1006
=> Use references/1 when generating migrations in ecto model task

priv/templates/html/show.html.eex
Simply adds the edit link to the show.html.eex template
=> Added the edit link generation to the show.html.eex template

lib/phoenix/channel.ex, lib/phoenix/channel/server.ex, lib/phoenix/channel/transport.ex, lib/phoenix/pubsub.ex, lib/phoenix/pubsub/local.ex, lib/phoenix/socket.ex, lib/phoenix/test/channel_test.ex, lib/phoenix/transports/fastlane.ex, lib/phoenix/transports/json_serializer.ex, lib/phoenix/transports/long_poll.ex, lib/phoenix/transports/long_poll/server.ex, lib/phoenix/transports/long_poll_serializer.ex, lib/phoenix/transports/serializer.ex, lib/phoenix/transports/websocket.ex, lib/phoenix/transports/websocket_serializer.ex, test/phoenix/channel/channel_test.exs, test/phoenix/integration/channel_test.exs, test/phoenix/integration/websocket_client.exs, test/phoenix/pubsub/local_test.exs, test/phoenix/pubsub/pubsub_test.exs, test/phoenix/socket_test.exs, test/phoenix/test/channel_test.exs, test/phoenix/transports/json_serializer_test.exs, test/phoenix/transports/websocket_serializer_test.exs, test/shared/pubsub_test.exs
@josevalim first pass and could use feedback. Do we want to merge this before starting the serialization fastlaning or do them both at once?
=> Do as much serialization as possible in the channels. Closes #1042

lib/phoenix/token.ex, test/phoenix/token_test.exs, test/phoenix/token_text.exs
I tried to follow the API from #699 I need some suggestions on testing this, since configuration all goes through the endpoint. I'm assuming the best way is to just "integration" test this. 
Also have some open questions:
1) Should we include expiration? 
2) Is this enough? 
cc @chrismccord @josevalim
=> Token Auth

installer/templates/new/web/templates/layout/app.html.eex, installer/templates/static/brunch/brunch-config.js, installer/templates/static/brunch/package.json, installer/test/phoenix_new_test.exs
Closes https://github.com/phoenixframework/phoenix/issues/1067
@josevalim hope you don't mind I went ahead and created a PR for above issue. :)
Heads up - this can only be merged once brunch 1.8.4 has been released https://github.com/brunch/brunch/pull/1001.
=> Use brunch auto-require

priv/templates/phoenix.gen.json/controller.ex, priv/templates/phoenix.gen.json/controller_test.exs
Changes status code from 200 to 201 when creating a JSON resource.
=> Return 201 status code when creating a JSON resource

lib/phoenix/router.ex, test/support/http_client.exs
same situation as described in this PR https://github.com/elixir-lang/elixir/pull/3576
=> Correct indentation in lists

lib/phoenix/socket.ex
I spent whole evening debugging ws connectivity due to this little typo.
=> Typo fix in Socket docs 

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs
=> Adds web/static/vendor back to generated projects

CONTRIBUTING.md, README.md, installer/lib/phoenix_new.ex
Going through the README's to learn how to use the latest code on the master branch I noticed a couple of minor things.
I didn't immediately understand the `--dev version must be inside Phoenix directory` error message. It doesn't seem to have anything to do with the version, it's about the location of the newly-created project.
Also when pulling changes from upstream, it's good to push them up to your fork on GitHub.
=> Improve docs for potential contributors

CHANGELOG.md, lib/phoenix/controller.ex, lib/phoenix/endpoint/render_errors.ex, test/phoenix/controller/controller_test.exs, test/phoenix/controller/render_test.exs, test/phoenix/endpoint/render_errors_test.exs
@josevalim I could use a review here when you have a moment
=> Rename format to _format and add get_format/1. Closes #1132

priv/templates/phoenix.gen.json/controller.ex
As discussed on the mailing list
=> Add location header to gen.json create action

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs
Fixes #1173 
@josevalim I assumed this was only needed in dev and test but not for prod. Let me know if that's not the case
=> Set hostname to localhost by default for dev and test

README.md
=> add slack channel to readme

lib/mix/tasks/phoenix.gen.html.ex, priv/templates/phoenix.gen.html/controller_test.exs, priv/templates/phoenix.gen.html/edit.html.eex, priv/templates/phoenix.gen.html/index.html.eex, priv/templates/phoenix.gen.html/new.html.eex, priv/templates/phoenix.gen.html/show.html.eex, test/mix/tasks/phoenix.gen.html_test.exs
=> Fix html gen underscores in tests

installer/templates/new/README.md
=> Remove database instructions from README.md when generated without ecto

installer/templates/new/mix.exs, installer/test/phoenix_new_test.exs
Fixes https://github.com/phoenixframework/phoenix/issues/1198
I took my comment in mix.exs from the Mix doc but I'm wondering if we should put something else. Did you have something in mind @josevalim?
Also, I'm not sure how useful is it to test it but I added some tests just in case.
=> Add ecto.reset and ecto.setup aliases

lib/phoenix/controller.ex
Currently it's not rendering correctly
=> Correct indentation for custom action example

lib/mix/tasks/phoenix.gen.html.ex, lib/mix/tasks/phoenix.gen.json.ex, lib/mix/tasks/phoenix.gen.model.ex, test/mix/tasks/phoenix.gen.html_test.exs, test/mix/tasks/phoenix.gen.json_test.exs, test/mix/tasks/phoenix.gen.model_test.exs
Closes https://github.com/phoenixframework/phoenix/issues/1191
=> Raise when table name not camel-cased in gen tasks

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
from http://contributor-covenant.org
to close #1209
=> add Code of Conduct

priv/templates/phoenix.gen.json/controller.ex
I noticed that all other method calls in this controller
use brackets. Adding brackets to match this style
in the render call of the show action.
=> Adding brackets to match rest of style

installer/test/phoenix_new_test.exs
So sorry, this should have been done as part of #1273 . Verified this fixes the build.
=> Fix assertion in phoenix_new_test

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs
Alright @josevalim, this should be more like what you expected.  Sorry for the confusion earlier.  :grinning: 
```shell
We are all set! Run your Phoenix application:
$ cd example_test
$ mix phoenix.server
You can also run your app inside IEx (Interactive Elixir) as:
$ iex -S mix phoenix.server
Before moving on, configure your database in config/dev.exs and run:
$ mix ecto.create
```
Closes #1280
=> Update database config messaging

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs
Thanks again for your help @josevalim, this closes #1279.
=> Show help when run without args

lib/phoenix/view.ex
Simple docs for render_existing to leverage the raw/1 function. Thanks to @chrismccord for the help.
=> Just updating the docs to render the raw function

lib/phoenix/router.ex
=> Update router.ex to fix docs

lib/phoenix/router.ex
=> fix typo in docs

lib/phoenix/router/helpers.ex, test/phoenix/router/helpers_test.exs
to be honest i do not fully understand that part of the code, so please take extra care reviewing ;-)
this is in reference to #1398
=> escape glob only route segments

brunch-config.js, package.json, priv/static/phoenix.js
I wanted to use the new babeljs pipeline with Phoenix. I got my [pull request for babel-brunch](https://github.com/babel/babel-brunch/pull/18) merged. Now, after updating the package.son, running `mix test` and integrating it into `https://github.com/chrismccord/phoenix_chat_example`, it all seems to work. Feedback and guidance appreciated, if needed.
=> Upgrade babel-brunch and commit its output.

CHANGELOG.md, lib/phoenix/socket/transport.ex, lib/phoenix/test/channel_test.ex
Hi
I've stumbled upon some minor/random typos, decided to do a pull request :v: 
Nick
=> random typos

priv/templates/phoenix.gen.model/migration.exs, test/mix/tasks/phoenix.gen.model_test.exs
Based IRC chat with @josevalim in reference to https://github.com/phoenixframework/phoenix/issues/1240. Let me know if I misunderstood the intent.
=> Add instructional on_delete: :nothing to gen.model

lib/phoenix/endpoint/cowboy_handler.ex
Wound up implementing a fix for #1314. Since @chrismccord wanted it exposed at the plug level, I'll be sending a pull request over that way momentarily. In order to keep the change low-impact, though, I also implemented the direct call to Ranch if the new functionality I'm sending to Plug is unavailable.
Overall, this is a deeper change than the cosmetic logging I originally was complaining about, so please let me know if/where further changes are needed and I'll be glad to make them. In particular, I'm unsure if modifying the integration tests like I have is the best policy-- finding where the tests should actually go was the most difficult part here-- and there may be some knock-on wartiness from coaxing the Endpoint.url call to return the active listening port.
Thanks a ton to @dm1try …
=> Properly handle ephemeral ports in endpoint config

lib/phoenix/test/channel_test.ex, test/phoenix/test/channel_test.exs
=> Adds refute_reply, refute_push, and refute_broadcast helpers

lib/phoenix/view.ex
"inflected" suggests grammatical change.
=> view.ex docs: inflected -> inferred

installer/templates/new/test/support/conn_case.ex, lib/phoenix/test/conn_test.ex, test/phoenix/test/conn_test.exs
=> Deprecate ConnTest.conn and add ConnTest.build_conn

installer/templates/new/test/support/channel_case.ex, installer/templates/new/test/support/conn_case.ex
Just a couple of typos I saw in passing.
=> Fixes a couple of typos

installer/lib/phoenix_new.ex, installer/test/mix_helper.exs, installer/test/phoenix_new_test.exs, lib/mix/tasks/phoenix.gen.html.ex, lib/mix/tasks/phoenix.gen.json.ex, priv/templates/phoenix.gen.html/controller_test.exs, priv/templates/phoenix.gen.json/controller_test.exs, test/mix/tasks/phoenix.gen.html_test.exs, test/mix/tasks/phoenix.gen.json_test.exs
=> Add :sample_binary_id option for generators

ISSUE_TEMPLATE.md
Since I watch this repo I've noticed that a large number of issues that are opened are support requests so I decided to submit this issue template for your consideration. You can see the rendered version here: https://github.com/jerel/phoenix/issues/new (click Preview)
=> Added an issue template to help users open helpful bug reports

installer/templates/new/mix.exs
Thanks for this amazing project! :metal:
=> Fix typo in mix.exs template

lib/mix/phoenix.ex, lib/mix/tasks/phoenix.gen.presence.ex, priv/templates/phoenix.gen.presence/presence.ex, test/mix/tasks/phoenix.gen.presence_test.exs
Ready for review. I wasn't sure how much docs to include on the generated Presence module. Too much?
=> Add Presence generator. Closes #1523

lib/phoenix/router/helpers.ex, test/phoenix/router/helpers_test.exs
=> Fix encoding of spaces in URL path components

lib/phoenix/test/conn_test.ex
Self-explainatory little doc fix
=> fix ensure_recycled specs in docs

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs
=> Improve options checking in the installer

web/static/js/phoenix.js
This will allow to transform payload before send it to channels
=> Add transform option

lib/phoenix/channel/server.ex, lib/phoenix/endpoint.ex
See https://groups.google.com/forum/#!topic/phoenix-core/SIHXEWEoFbA
Example output:
> [info] RECEIVED message on MyApp.ApiChannel
>   Parameters: %{"example" => "Hi"}
>   Ref: 20784513-6CF4-441D-9807-17E10B8D175E
=> Channel receive instrumentation

lib/phoenix/controller.ex, lib/phoenix/view.ex, test/support/http_client.exs
Since Dict is being deprecated, clean up the usage of it
=> Cleanup usage of Dict

installer/templates/new/config/prod.secret.exs
Insist on documenting or automating the creation of the file
=> Add additional information to prod.secret.exs

test/support/http_client.exs
rand_bytes deprecated use strong_rand_bytes instead
=> rand_bytes deprecated use strong_rand_bytes

test/phoenix/integration/endpoint_test.exs
@chrismccord I can fix #1782 only if I put `Supervisor.stop(DevEndpoint)` within the capture_log block. So ended up with nested capture_logs as the others are asserts. See if that works for you?
=> Ensure logs are silenced on endpoint test.

lib/phoenix.ex
- Fixed a minor grammar error in the documentation in `lib/phoenix.ex`
=> Grammar error fix

installer/templates/new/web/web.ex
I think this edit clarifies the purpose of `web/web.ex`.
=> Clarify inline docs, web/web.ex

installer/lib/phoenix_new.ex, installer/test/phoenix_new_test.exs, test/mix/tasks/phoenix.new_test.exs
=> Don't copy static files when both --no-brunch & --no-html are present.

lib/phoenix/code_reloader.ex, test/phoenix/code_reloader_test.exs
Yep! See: #1777.
I've added a bit of magic to parse `** (Xxxx) Yyyy` and display those up top—hope that's fine.
=> Update the code reloader design

lib/phoenix/logger.ex, test/phoenix/logger_test.exs
…because @scrogson asked us to at ElixirConf 2016.
=> Change "Processing by" to "Processing with" in the request log

lib/phoenix/digester.ex, lib/phoenix/endpoint/adapter.ex, test/fixtures/digest/priv/output/foo-288ea8c7954498e65663c817382eeac4.css, test/fixtures/digest/priv/output/foo-d978852bea6530fcd197b5445ed008fd.css, test/fixtures/digest/priv/static/foo.css, test/fixtures/manifest.json, test/fixtures/manifest_upgrade.json, test/fixtures/old_manifest.json, test/phoenix/digester_test.exs, test/phoenix/endpoint/endpoint_test.exs
This the first half a fix for https://github.com/phoenixframework/phoenix/issues/1876. Part 2 will be a new mix task which cleans old versions of assets.
=> Improve asset manifest

lib/mix/tasks/phoenix.digest.clean.ex, lib/phoenix/digest_cleaner.ex, lib/phoenix/digester.ex, lib/phoenix/endpoint/adapter.ex, test/fixtures/digest/cleaner/manifest.json, test/fixtures/digest/priv/output/foo-288ea8c7954498e65663c817382eeac4.css, test/fixtures/digest/priv/output/foo-d978852bea6530fcd197b5445ed008fd.css, test/fixtures/digest/priv/static/foo.css, test/fixtures/manifest.json, test/fixtures/manifest_upgrade.json, test/fixtures/old_manifest.json, test/mix/tasks/phoenix.digest.clean_test.exs, test/phoenix/digest_cleaner_test.exs, test/phoenix/digester_test.exs, test/phoenix/endpoint/endpoint_test.exs
This is a follow on to https://github.com/phoenixframework/phoenix/pull/1922, and should fix https://github.com/phoenixframework/phoenix/issues/1876. It depends on the previous PR, so the diff you see here is for both. The changes here are all in this commit: 4b4ed06.
=> Add mix digest clean

lib/phoenix/endpoint/render_errors.ex, test/phoenix/endpoint/render_errors_test.exs
=> emit warning when falling back to default format for ErrorView

lib/phoenix/socket/transport.ex, test/phoenix/transports/transport_test.exs
=> Look up system variable when checking origin

installer/lib/phoenix_new.ex, installer/lib/phx_new.ex
=> Make method check_directory_existence private

lib/phoenix/controller.ex, lib/phoenix/socket.ex, lib/phoenix/template.ex, lib/phoenix/test/conn_test.ex, lib/phoenix/transports/serializer.ex, lib/phoenix/view.ex, test/phoenix/endpoint/render_errors_test.exs, test/phoenix/integration/long_poll_test.exs, test/phoenix/integration/websocket_test.exs, test/phoenix/router/resources_test.exs
Found some small doc errors while taking a look a the Phoenix codebase.
=> Fix typos.

lib/phoenix/digester.ex, test/fixtures/digest/priv/static/app.js, test/fixtures/digest/priv/static/app.js.map, test/phoenix/digester_test.exs
#1936 solved, also I think we will need to digest the contents from *.map files too, I can do that too, but I need a feedback if it's okay
=> Source mapping url digest

installer/templates/assets/brunch/package.json, installer/templates/static/brunch/package.json
It should be pretty safe.
Changelog: https://github.com/brunch/brunch/blob/master/CHANGELOG.md
=> Update brunch to 2.9.1

lib/phoenix/channel.ex, lib/phoenix/logger.ex, lib/phoenix/socket.ex, lib/phoenix/socket/transport.ex, test/phoenix/logger_test.exs
@josevalim thoughts on __socket__/1? Prefer something else?
=> Refactor log options into private field

lib/mix/tasks/phoenix.gen.html.ex, test/mix/tasks/phoenix.gen.html_test.exs
=> Change generated checkbox class from "form-control" to "checkbox"

lib/phoenix/channel/server.ex
This reflects the changes introduced in https://github.com/elixir-lang/elixir/pull/5590
=> Issue warning instead of error for unhandled messages

priv/templates/phx.gen.html/context_test.exs, test/mix/tasks/phx.gen.html_test.exs
=> Fix phx.gen.html context_test.exs template

lib/phoenix/endpoint.ex
=> Fix docs for Endpoint configuration

lib/mix/tasks/phx.gen.json.ex, lib/phoenix/router.ex, priv/templates/phx.gen.json/controller.ex
Also:
- phx.gen.json: Don't generate :new, :edit routes
- Improve Phoenix.Router.resources docs
=> phx.gen.json: Remove new action from controller template

priv/templates/phx.gen.html/schema.ex
This PR removes space on the empty line in schema file
This is how the file is generated in current master(red blocks show spaces):
=> remove empty line with space in generated file

installer/templates/phx_ecto/data_case.ex
As discussed on https://github.com/phoenixframework/phoenix/commit/d77cddbb0dc00d6f1edcbcb21b7f266a3d0614a2#commitcomment-21075635
=> Replace errors_on/2 with errors_on/1

installer/templates/phx_umbrella/apps/app_name/mix.exs
Remove -rc from ecto 2.1 dependency in generator
=> Update generator ecto dependency to 2.1

test/mix/tasks/phx.gen.html_test.exs, test/mix/tasks/phx.gen.json_test.exs, test/mix/tasks/phx.gen.schema_test.exs
Ref: #2131 
I ported almost all tests from phoenix.gen.{html,json,model} to phx.gen.{html,json,schema}. There are only a few failing tests. Other ported tests are working just fine.
=> Port tests from phoenix.gen.{html,json,model} to phx.gen.{html,json,schema}

installer/templates/phx_umbrella/apps/app_name/config/prod.exs
Missing importing secrets from umbrella generator
=> Missing import_config "prod.secret.exs"

lib/mix/tasks/phx.gen.context.ex, lib/mix/tasks/phx.gen.html.ex, lib/mix/tasks/phx.gen.json.ex, lib/mix/tasks/phx.gen.schema.ex
=> Documentation for options on gen.{context, html, json}

lib/mix/phoenix.ex, lib/mix/tasks/phx.gen.context.ex, lib/mix/tasks/phx.gen.html.ex, lib/mix/tasks/phx.gen.json.ex, lib/mix/tasks/phx.gen.schema.ex
=> Check for file conflicts before copying. Closes #2193

README.md
Signed-off-by: David McKay <david@rawkode.com>
=> Specifying Elixir for code-block

README.md
=> Update info on removing previous Phoenix archives

installer/templates/phx_assets/brunch/brunch-config.js
Updated the files link and removed the link to concatenation to be consistent with the version in static
=> Update generated brunch-config.js brunch docs references #2253

installer/lib/phx_new/single.ex, installer/lib/phx_new/web.ex, installer/test/phx_new_test.exs, installer/test/phx_new_umbrella_test.exs, lib/mix/phoenix.ex, lib/mix/phoenix/context.ex, lib/mix/tasks/phx.gen.channel.ex, test/mix/tasks/phx.gen.channel_test.exs, test/mix/tasks/phx.gen.context_test.exs, test/mix/tasks/phx.gen.html_test.exs, test/mix/tasks/phx.gen.json_test.exs
As discussed on https://github.com/phoenixframework/phoenix/commit/c4c49ecc2d058e28e1ae6d5ca8fae72d03233cfd#commitcomment-21148819
Example dummy phoenix project: https://github.com/wojtekmach/phoenix_example/tree/master/dummy/test
Example dummy phoenix project (umbrella): https://github.com/wojtekmach/phoenix_example/tree/master/dummy_umbrella
Example tests on hex_web: https://github.com/hexpm/hex_web/tree/3f32fef19badef677b4a44a5e253b1ddef84f85e/test
=> Move generated tests to test/my_app

lib/phoenix/presence.ex
Unless I misunderstood, it was a bit confusing as the description does not follow the code example in order.
=> Update presence.ex description of an example

lib/phoenix/endpoint.ex
This makes it easy to search for those functions using the search box in
hexdocs.
A similar pattern is used for documenting Ecto.Repo.
=> Document functions generated in endpoint as callbacks

installer/templates/static/brunch/package.json
https://github.com/brunch/css-brunch
=> css-brunch: deprecation

installer/templates/static/brunch/package.json
Had some issues with old brunch, seems like stable releases should be stable.
=> brunch update for v1.2 branch

lib/mix/phoenix/schema.ex, test/mix/phoenix_test.exs
I am learning, so just picked this small thing (#2301).... and the question is.. is it all?
=> Change default float value, fixes #2301

lib/phoenix/channel.ex
plus moved the renders to a new line for clarity
=> corrected a small syntax error in the docs

lib/mix/tasks/phx.gen.context.ex
Continues work done in https://github.com/phoenixframework/phoenix/commit/c3351478748779fe0b777a4f41e7ace7ae5e2452
=> chore(phx.gen.context): Update moduledoc to reflect new default table naming

installer/mix.exs, installer/templates/new/mix.exs, installer/templates/phx_single/mix.exs, installer/templates/phx_umbrella/apps/app_name/mix.exs, installer/templates/phx_umbrella/apps/app_name_web/mix.exs, installer/templates/phx_umbrella/mix.exs, installer/test/mix_helper.exs, mix.exs
=> Use new mix.exs style

assets/js/phoenix.js, lib/phoenix/channel.ex, lib/phoenix/channel/server.ex, lib/phoenix/logger.ex, lib/phoenix/socket.ex, lib/phoenix/socket/message.ex, lib/phoenix/socket/transport.ex, lib/phoenix/transports/long_poll.ex, lib/phoenix/transports/long_poll_serializer.ex, lib/phoenix/transports/long_poll_server.ex, lib/phoenix/transports/v2/longpoll_serializer.ex, lib/phoenix/transports/v2/websocket_serializer.ex, lib/phoenix/transports/websocket.ex, lib/phoenix/transports/websocket_serializer.ex, package-lock.json, package.json, priv/static/phoenix.js, test/phoenix/integration/long_poll_test.exs, test/phoenix/integration/websocket_test.exs, test/phoenix/socket_test.exs, test/phoenix/transports/long_poll_serializer_test.exs, test/phoenix/transports/transport_test.exs, test/phoenix/transports/websocket_serializer_test.exs, test/support/websocket_client.exs
Adds version 2 of the channel wire protocol to resolve a race condition that was discovered when a client times out and rejoins. Backwards compatible with V1 clients.
=> Add channel protocol V2 

lib/mix/tasks/phx.gen.json.ex
Change "boostrap" to "bootstrap"
=> Correct typo in `mix help phx.gen.json`

assets/js/phoenix.js, package-lock.json
phoenix.js needs some love. Here's my first piece of ❤️
=> Document phoenix.js Socket.channel/2

mix.exs
This file was not added.
This file was recently added.
So need update phoenix_guides.
=> Update phoenix_guide and add pages from phoenix_guides

assets/js/phoenix.js, package-lock.json
The formatting of `phoenix.js` is inconsistent, and a lot of the code is missing JSDoc. This causes https://hexdocs.pm/phoenix/js/ to have a lot of missing, useful information.
This PR aims to take a stab at that problem :)
=> Cleanup and add more JSDoc to phoenix.js

installer/templates/phx_umbrella/apps/app_name/mix.exs
Release note for Ecto v2.2: https://github.com/elixir-ecto/ecto/blob/v2.2/CHANGELOG.md
=> Update phx_umbrella template's Ecto version: v2.1 -> v2.2

guides/docs/contexts.md
Correcting the reference to the plug that placed `current_author` in assigns.
=> Correct plug name

guides/docs/introduction/installation.md, guides/docs/up_and_running.md
Closes #2492 
@chrismccord @Gazler @josevalim 
I removed the mention of the skeleton app from the installation page, and added a note on creating an app without ecto and combining it with no-brunch to create a skeleton app. Feedback is welcome!
=> Guide Update: Move creating skeleton app

lib/mix/tasks/phx.gen.embedded.ex, lib/mix/tasks/phx.gen.html.ex, lib/mix/tasks/phx.gen.schema.ex, lib/phoenix/digester.ex, lib/phoenix/endpoint/cowboy_handler.ex, lib/phoenix/presence.ex, lib/phoenix/socket/message.ex, lib/phoenix/socket/transport.ex, lib/phoenix/transports/long_poll.ex
=>  Support linting code with Credo

lib/phoenix/socket/message.ex, lib/phoenix/transports/long_poll.ex
=> Fix reraising errors

installer/test/mix_helper.exs, test/mix/tasks/phx.new_test.exs
This was a shot in the dark, but it has resolved our build issues. Shrug 🍻
=> Rule out race by randomizing tmp test dirs

lib/phoenix/router.ex, test/phoenix/router/resources_test.exs
=> Raise error when declaring singleton with index

guides/docs/controllers.md
**File**: Controllers.md
**Line**: 336
**Change**: Add parentheses around function arguments in final pipeline function.
=> Guides: Fix code sample in controllers.md 

lib/phoenix/endpoint.ex
Fixes https://github.com/phoenixframework/phoenix/issues/2489
=> Document :scheme and :port options

guides/docs/channels.md
=> remove incorrect part of channel docs example

guides/docs/introduction/overview.md
I'm not sure if this is the best description ever, but it is a bit more informative.
=> An attemt at a description for templates

test/mix/tasks/phx.gen.channel_test.exs
- Upper cased the command argument to be consistent with the docs
- Fixed a test name
=> Minor channel test fixes

.travis.yml, lib/phoenix/endpoint/cowboy2_handler.ex, lib/phoenix/endpoint/cowboy2_websocket.ex, lib/phoenix/socket/transport.ex, lib/phoenix/transports/websocket.ex, mix-cowboy1.lock, mix.exs, test/phoenix/integration/endpoint_test.exs, test/phoenix/integration/long_poll_test.exs, test/phoenix/integration/websocket_test.exs
I need to tidy up the commits, but all the tests are passing.
It uses cowboy master because we need a fix that will be deployed with 2.1
Reviews appreciated @chrismccord @josevalim 
I'd recommend reviewing the commits individually so you can see the diff between cowboy and cowboy 2.
=> Cowboy 2 support

lib/phoenix/endpoint/cowboy_handler.ex
* Added `.Web` to all the `MyApp` module names since phoenix 1.3 or later generates with that name
* Added the needed route for the live_reload socket
=> Update documentation on the http dispatch option

lib/mix/tasks/phx.digest.ex
Grammar fix for `phx.digest` docs.
=> phx.digest task's documentation fix

.travis.yml
=> Add elixir 1.6 to CI build matrix

installer/lib/phx_new/generator.ex, installer/templates/phx_single/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name_web/lib/app_name/application.ex, installer/test/phx_new_test.exs, installer/test/phx_new_umbrella_test.exs
=> Conditionally generate child specs based on elixir version

guides/docs/channels.md
I had a hard time following the "Moving Parts" section initially, and thought a diagram could clarify how things work.
I made this diagram using [Monodraw](https://monodraw.helftone.com/). The Monodraw file is much easier to edit and update than the exported text, but weighs a few KB. If you like this diagram, you can decide whether you also want the Monodraw file checked in.
=> Add an overview and diagram to the 'Moving Parts' section

lib/phoenix/token.ex, test/phoenix/token_test.exs
Closes #2755 
If would be awesome if this could be backported to the 1.3 branch if there's a release planned.
=> Support :infinity for Phoenix.Token max age

lib/phoenix/controller.ex, lib/phoenix/router/helpers.ex, test/phoenix/controller/controller_test.exs, test/phoenix/router/helpers_test.exs
@josevalim we have some overlap here and need to reconcile the `current_url` docs and behavior with this new feature. Let's chat tomorrow about it.
=> Support subdomains in the Router Helpers. Closes #2462

guides/docs/templates.md, installer/templates/phx_single/lib/app_name_web.ex, installer/templates/phx_umbrella/apps/app_name_web/lib/app_name.ex
As discussed in https://github.com/phoenixframework/phoenix/issues/2767, @chrismccord requested that we add `get_flash/1` to the new project generator.
=> Add get_flash/1 to new project generator

CHANGELOG.md
=> Update date for 1.3.1 in CHANGELOG.md

guides/docs/channels.md
A tiny follow-on to https://github.com/phoenixframework/phoenix/pull/2765
I wanted to mention "messaging apps", thinking of something like WhatsApp. And I thought of the map example, too.
The goal of this section is to get people excited, so a variety of examples is helpful, I think.
=> Expand examples slightly

installer/lib/mix/tasks/phx.new.ecto.ex, installer/lib/mix/tasks/phx.new.web.ex
=> fix typo in generator help: inteded -> intended

package-lock.json, package.json
`expose-loader` 0.7.5 add `webpack >= v4.0.0` to peerDependencies https://github.com/webpack-contrib/expose-loader/commit/daf39ea
=> Upgrade expose-loader to 0.7.5

guides/docs/adding_pages.md
Now that the guide for Ecto isn't upcoming any longer - but actually here - I thought it would be helpful with a link for readers.
=> Add link to Ecto guide

guides/docs/channels.md
Fix link to webpack documentation on channels documentation
=> Fix typo on channel documentation

guides/docs/deployment/heroku.md
This PR aims at fixing the documentation regarding connecting to a heroku dyno with an interactive session. With heroku releasing a new feature it is now possible. This PR details how to do it.
refs #2558
=> amend heroku docs regarding remote interactive session in dyno

guides/introduction/learning.md
I am proposing this presentation talk to be in the learning section. I recommended phoenix to one of my friends and thought this video would be already here. I think its a great talk to complement resources at https://hexdocs.pm/phoenix/overview.html
=> add phoenix 1.3 keynote at lonestar elixirconf

installer/templates/phx_assets/webpack/package.json
style-loader unused since #2831
=> remove style-loader

lib/phoenix/router/route.ex
This halves the number of jump labels in generated assembly in large routers and speeds up compilation by 25% on OTP 21.
=> Optimise param merging in router

guides/up_and_running.md
Added a reference to learn more about mix tasks to make it easier for people reading the document.
=> Added a reference to learn more about mix tasks

guides/up_and_running.md
Fixed link error, now it works
=> Fixed link error

README.md
Adding instructions to build from source
=> Adding instructions to build from source

lib/phoenix/controller.ex
Quotation mark was off and invalid syntax (I think)
=> Fix syntax and typo in controller.ex

lib/phoenix/endpoint.ex
The tiniest fix possible, and nothing got broken in the process :>
=> Fixed a tiny typo in the endpoint.ex

guides/controllers.md
=> fixing wording in controller guide

lib/phoenix/router/helpers.ex, test/phoenix/router/helpers_test.exs
=> Fix multiple routes causing errors on unique helper clauses

lib/phoenix/controller.ex, lib/phoenix/endpoint/render_errors.ex, lib/phoenix/logger.ex, lib/phoenix/test/conn_test.ex, test/phoenix/endpoint/render_errors_test.exs, test/phoenix/integration/endpoint_test.exs
=> Instrument error rendering

guides/up_and_running.md
Fixes the link to the Adding Pages section on the Up and Running section.
=> Fix link to adding pages

guides/errors.md, installer/templates/phx_single/config/dev.exs, installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs
I just started a new 1.4-dev project, and missing colors was bothering me.
=> add colors option to webpack cmd.

lib/phoenix/socket/transport.ex, test/phoenix/socket/transport_test.exs
=> log origin when error on check_origin

guides/introduction/overview.md
MVC is an acronym and should be explained
=> explain MVC acronym

installer/templates/phx_web/templates/layout/app.html.eex
See https://github.com/phoenixframework/phoenix/issues/3000
=> Make viewport meta tag less restrictive in html layout

guides/channels.md, installer/templates/phx_assets/webpack/socket.js, installer/templates/phx_web/channels/user_socket.ex, lib/phoenix/endpoint.ex, lib/phoenix/socket.ex, lib/phoenix/socket/transport.ex, lib/phoenix/test/channel_test.ex, lib/phoenix/transports/long_poll.ex, lib/phoenix/transports/long_poll_server.ex, lib/phoenix/transports/websocket.ex, test/phoenix/integration/long_poll_channels_test.exs, test/phoenix/integration/websocket_channels_test.exs
This PR depends on https://github.com/elixir-plug/plug/pull/715 for providing client ssl certificate access with the cowboy2 adapter to work.
I am posting this PR as a WIP to track progress towards supporting these features. We should kick around what is needed or better ways we could pass these options forward.
=> Provide access to X-Headers and Client-SSL Certificate to Socket.connect/2

installer/lib/phx_new/ecto.ex, installer/lib/phx_new/umbrella.ex, installer/lib/phx_new/web.ex, installer/templates/phx_umbrella/apps/app_name/config/config.exs, installer/templates/phx_umbrella/apps/app_name/formatter.exs, installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name/mix.exs, installer/templates/phx_umbrella/apps/app_name/test/test_helper.exs, installer/templates/phx_umbrella/apps/app_name_web/config/config.exs, installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs, installer/templates/phx_umbrella/apps/app_name_web/formatter.exs, installer/templates/phx_umbrella/apps/app_name_web/lib/app_name.ex, installer/templates/phx_umbrella/apps/app_name_web/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name_web/mix.exs, installer/templates/phx_umbrella/apps/app_name_web/test/test_helper.exs, installer/templates/phx_umbrella/config/config.exs, installer/templates/phx_umbrella/formatter.exs, installer/templates/phx_umbrella/mix.exs, installer/test/phx_new_umbrella_test.exs
Added the formatter file, created an umbrella project using it, ran `mix format --check-formatted`, and formatted these 2 files to make it pass.
=> Add .formatter.exs for umbrella projects and update templates

installer/templates/phx_umbrella/apps/app_name/config/config.exs, installer/test/phx_new_umbrella_test.exs
To address https://github.com/phoenixframework/phoenix/issues/3019
=> Fix app config in namespaced umbrella apps

lib/phoenix/view.ex, test/phoenix/view_test.exs
=> Validate reserved :layout field in View.render/3

assets/package-lock.json, assets/package.json
None of those warnings affects Phoenix though.
=> Update JS deps to avoid security warnings

lib/phoenix/controller.ex
Seems like its a typo. Hopefully I got that right
=> fix minor typo on Phoenix.Controller.send_download/3 doc

installer/lib/phx_new/single.ex, installer/templates/phx_single/config/config.exs, installer/templates/phx_single/config/dev.exs, installer/templates/phx_single/formatter.exs, installer/templates/phx_single/lib/app_name/application.ex, installer/templates/phx_single/lib/app_name_web.ex, installer/templates/phx_single/mix.exs, installer/templates/phx_single/test/test_helper.exs, installer/templates/phx_test/controllers/page_controller_test.exs, installer/templates/phx_test/support/channel_case.ex, installer/templates/phx_test/support/conn_case.ex, installer/templates/phx_test/views/error_view_test.exs, installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs, installer/templates/phx_web/controllers/page_controller.ex, installer/templates/phx_web/endpoint.ex, installer/templates/phx_web/router.ex, installer/templates/phx_web/views/error_helpers.ex, installer/test/phx_new_test.exs, installer/test/phx_new_umbrella_test.exs, test/mix/tasks/phx.new_test.exs
and make sure the code generated by default is formatted
=> Add a .formatter.exs to generated phx.new projects

lib/phoenix/endpoint.ex, lib/phoenix/logger.ex, lib/phoenix/socket.ex, test/phoenix/integration/websocket_channels_test.exs, test/phoenix/logger_test.exs
=> Log and instrument UserSocket connect

priv/templates/phx.gen.json/controller_test.exs, test/mix/tasks/phx.gen.json_test.exs
Addresses https://github.com/phoenixframework/phoenix/issues/2911 if that is, in fact, how you want this test format structured @chrismccord
=> Update format of default json controller tests

assets/.babelrc, assets/package-lock.json, assets/package.json, installer/templates/phx_assets/webpack/babelrc, installer/templates/phx_assets/webpack/package.json
https://babeljs.io/blog/2018/08/27/7.0.0
=> assets - upgrade to babel 7

installer/templates/phx_single/config/test.exs, installer/templates/phx_umbrella/apps/app_name_web/config/test.exs
=> Move test port to 4002 to not overlap with the proposed ssl port

lib/phoenix/endpoint/cowboy2_adapter.ex
=> Log the configured URL instead of the raw ip

installer/lib/mix/tasks/phx.new.ex
Fixes #3103
Correctly prints `cd path/to/project` when project is created in a nested directory.
Includes cleanup to remove as best as I can tell unneeded code.
Example
```console
% mix phx.new test/sample
* creating test/sample/config/config.exs
* creating test/sample/config/dev.exs
...
* creating test/sample/assets/static/images/phoenix.png
* creating test/sample/assets/static/favicon.ico
Fetch and install dependencies? [Yn] n
We are almost there! The following steps are missing:
$ cd test/sample
$ mix deps.get
$ cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development
Then configure your database in config/dev.exs and run:
$ mix ecto.create
Start your Phoenix app with:
$ mix phx.server
You can also run your app inside IEx (Interactive Elixir) as:
$ iex -S …
```
=> Do not assume project in current directory

lib/phoenix/channel.ex
Add documentation and typespec parameter names to `Phoenix.Channel` callbacks, as well as missing
```elixir
{:noreply, Socket.t, timeout | :hibernate}
```
return type to `intercept/1` example.
=> Document Phoenix.Channel callbacks

lib/phoenix/presence.ex
Add documentation for `Phoenix.Presence` callbacks and hide private callbacks.
=> Document Phoenix.Presence callbacks

guides/testing/testing.md
This pr fixes inconsistent test statements in test.md.
=> Make test.md more consistent

guides/controllers.md
Use the correct link to mime types
=> update link to mime  types

guides/views.md
Just a minor difference that I've noticed while reading the docs, but I think it's worth updating it nonetheless
=> update guide view snippet to agree with latest phx.new

guides/testing/testing_channels.md, lib/phoenix/test/channel_test.ex
=> Add note to assert_broadcast documentation to prevent confusion

priv/templates/phx.gen.json/controller_test.exs, test/mix/tasks/phx.gen.json_test.exs
=> Don't use json encoder for map fields

lib/phoenix/endpoint/cowboy2_adapter.ex, lib/phoenix/endpoint/supervisor.ex
=> Print access info separately from bound address

lib/mix/tasks/phx.routes.ex, lib/phoenix/router/console_formatter.ex, test/phoenix/router/console_formatter_test.exs
@Gazler let me know your thoughts on the formatting in relation to the router output. Thanks!
=> Show socket paths on mix phx.routes. Closes #3237

lib/phoenix/test/conn_test.ex
Let the reader know where the list of allowed status atoms are. Thanks ✨
=> Update doc for ConnTest.assert_error_sent

lib/phoenix/controller.ex, test/phoenix/controller/controller_test.exs
Based on issue discussion:
https://github.com/phoenixframework/phoenix/issues/1786#issuecomment-481631844
=> Support `:disposition_type` option in send_download/3

priv/templates/phx.gen.json/controller_test.exs
=> Fix value encoding in json generator controller test update method

guides/views.md
The guide does not match with the default `ErrorView` of a new Project anymore.
I tried to update the guide to match the current generated ErrorView. Since I'm just learning Elixir and Phoenix, I hope I understood everything correctly.
I'm not sure if its necessary to mention implementing the `def render("404.html", _assigns)` function because
a) It is deleted in the next step right away and does not provide much value over the the default implementation
b) `ErrorView` already contains an example of this possibility which, in my opinion, is very self explanatory
```
```
=> Update ErrorView Guide

installer/templates/phx_single/config/prod.exs, installer/templates/phx_umbrella/apps/app_name_web/config/prod.exs
I just fixed two small typos in the installer template docs.
=> Fixed typos in installer template docs.

assets/js/phoenix.js
globalwindow exists in react native but it doesn't have the addEventListener method
i didn't research why the object exists nor what it is exactly
=> fix react native crash

lib/phoenix/router.ex
=> Don't ignore plug params and pass them to init

lib/phoenix/presence.ex
This PR updates the line to add the supervisor into the supervision tree of the application.
=> Docs Update: Presence - Adding supervisor into application.ex

guides/contexts.md
=> Fix Multi.run usage in contexts guide

guides/up_and_running.md
I hadn't noticed it in first instance, so better explicitly mention it.
=> mentioning the .gitignore

guides/deployment/releases.md
The first line should be executed by Docker as it sets elixir 1.9.0 as the base image
=> Remove comment in Dockerfile

guides/deployment/releases.md
This PR aims to use the `AS` keyword pattern as describe in the [docker documentation](https://docs.docker.com/develop/develop-images/multistage-build/#name-your-build-stages) not only in the app stage but also in the build stage.
Thank you for the time and for maintaining this awesome library. :confetti_ball: :tada:
=> Improve docker keyword in Dockerfile

guides/routing.md
this seems like a leftover from 4d61eacd83d61899a895167715d8754c5c8187be ?
=> replace Plug.Logger with Plug.Telemetry in routing guide

guides/adding_pages.md
This makes the note stand out a bit, which I feel is justified for this piece of information.
=> Format note on hot code reloading like other notes

lib/phoenix/test/channel_test.ex, test/phoenix/test/channel_test.exs
=> Convert subscribe_and_join payload to string keys

lib/phoenix/router.ex
This pull request adds a “Routing” section to `Phoenix.Router` docs.
While Rails is a popular framework, the routing convention mimicked by Phoenix should be documented for first-time developers and those from other stacks (where regex is far more common). Features like globbing also don’t behave like Rails or Unix counterparts.
=> Explain routing in router docs

assets/js/phoenix.js, assets/test/channel_test.js, assets/test/socket_test.js
=> stateChangeCallbacks filter on channel remove

guides/endpoint.md
=> Reference Plug HTTPS Guide from Endpoint Guide

lib/phoenix/endpoint.ex, lib/phoenix/endpoint/supervisor.ex, test/phoenix/endpoint/endpoint_test.exs, test/phoenix/endpoint/supervisor_test.exs
=> Checks force_ssl has not changed from compile time to runtime

lib/phoenix/router/helpers.ex, test/phoenix/router/helpers_test.exs
Fixes #3554
I wasn't sure where to put tests for something like this. If someone can point me in the right direction, I'll be glad to go back and add some.
=> Escape plug options in helpers

CONTRIBUTING.md, lib/phoenix/test/conn_test.ex
=> Fix `ConnTest` and `Contributing` typos

priv/templates/phx.gen.context/schema_access.ex
=> fix inconsistency

installer/templates/phx_single/README.md, installer/templates/phx_umbrella/apps/app_name_web/README.md
I almost joined phoenix-talk googlegroups-group, so I thought...
=> replacing phoenix-talk with phoenix-forum in app-templates

assets/js/phoenix.js
Just added a description of what it does, as I had to go into the source code to figure out how it worked.
=> Add documentation for channel.off function

installer/templates/phx_test/views/layout_view_test.exs
This provides some guidance for users planning to write their first helpers.
=> Add some pointers to Phoenix.HTML in the generated LayoutViewTest

CHANGELOG.md
Noticed this typo while keeping an eye on 1.5 changes :)
=> Fix Phoenix.Ecto.CheckRepoStatus name in changelog

installer/templates/phx_assets/app.js
=> remove css named import in favour of direct import

installer/lib/phx_new/single.ex, installer/lib/phx_new/web.ex, installer/templates/phx_single/lib/app_name/application.ex, installer/templates/phx_single/mix.exs, installer/templates/phx_umbrella/apps/app_name_web/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name_web/mix.exs, installer/templates/phx_web/telemetry.ex, installer/test/phx_new_test.exs, installer/test/phx_new_umbrella_test.exs, mix.exs
This is still a work-in-progress.  Opening a draft PR to get early feedback.
=> Add Telemetry generator to installer

guides/views.md
modified the closing tag in guides/views.md from div tag to section tag.
=> fixed the closing tag from div to section

guides/channels.md
update guides/channels.md at v1.4 branch.
- removed dead link
- fixed link format
ref: https://github.com/phoenixframework/phoenix/pull/3709
=> fix guides/channels.md

lib/phoenix/socket.ex
=> MyApp -> MyAppWeb in Phoenix.Socket documentation

lib/phoenix/token.ex
Improves the documentation about token generation.
First time I read the documentation about `Phoenix.Token` and saw the
`salt`, I become clear to me stat salt should be some kind of
randomly generated string.
After exploring the codebase and [researching the
internet](https://elixirforum.com/t/how-is-phoenix-token-different-from-jwt/2349/5)
I found out my code readability can be improved by replacing randomly generated string with a description of the token namespace.
I think this change will help improve the usability of the `Phoenix.Token` module by hinting that salt can be namespace as well.
I found `user_salt` variable a little bit confusing because a user doesn't have salt and if it has, it'll be some randomly generated string for password hashing which is not the case for …
=> token salt can be treated as namespace

installer/templates/phx_umbrella/apps/app_name_web/mix.exs, installer/test/phx_new_umbrella_test.exs
This PR fixes #3777 .
I also added a couple of tests equivalent to those added on #3755 for the single.
=> Fix umbrella no html

guides/introduction/community.md
The new website looks so good. I love the color palette (not sure if that's new or not, but something definitely pops out more now).
This comes from https://github.com/phoenixframework/phoenix_site/pull/51 and I'd be super happy to have it added to the community page!
=> Add real-time phoenix to community.md

guides/telemetry.md, mix.exs
A guide to telemetry events and the Telemetry supervisor.
=> Telemetry guide

lib/mix/tasks/phx.gen.secret.ex, test/mix/tasks/phx.gen.secret_test.exs
I think we can omit padding since eventually they would be stripped out :).
=> Minor improvement in secret generating

guides/realtime/channels.md
Channels are introduced in a way that could make people think broadcasts are automatic.
This patch proposes an intro that makes the programming model a bit more clear in my mind.
=> Elaborate a bit more the intro to channels

installer/templates/phx_umbrella/apps/app_name_web/mix.exs
Otherwise I ended up with a `CheckRepoStatus.init/1 is undefined` after a fresh install.
=> Update phoenix_ecto version for umbrella app generator

lib/phoenix/endpoint.ex, lib/phoenix/socket/transport.ex, test/phoenix/integration/websocket_channels_test.exs
=> Extract user agent from socket connect_info

guides/introduction/community.md
Simple PR adding my free LiveView course to the Community guide.
Thanks!
=> Add LiveView course link to community.md

guides/routing.md
=> Tiny grammar fix

lib/phoenix/endpoint/cowboy2_adapter.ex
=> Fix the other Cowboy.Drainer link

CHANGELOG.md
Minor code formatting, capitalisation and punctuation fixes.
Take note, this is for the 1.4 branch.
=> Improve CHANGELOG.md (v1.4)

CHANGELOG.md
Minor code formatting, capitalisation and punctuation fixes.
Take note, this is for the 1.5 branch.
=> Improve CHANGELOG.md (v1.5)

guides/request_lifecycle.md
=> added missing word in sentence

guides/deployment/heroku.md
"setup" is the noun and "set up" is the (phrasal) verb.
E.g. "I will set up the setup."
=> heroku.md: Setup -> set up

guides/ecto.md, guides/testing/testing.md, guides/testing/testing_channels.md, guides/testing/testing_contexts.md, installer/lib/phx_new/generator.ex, installer/templates/phx_ecto/data_case.ex, installer/templates/phx_single/mix.exs, installer/templates/phx_test/support/channel_case.ex, installer/templates/phx_test/support/conn_case.ex, installer/templates/phx_umbrella/apps/app_name/mix.exs, installer/test/phx_new_test.exs, installer/test/phx_new_umbrella_test.exs
Ref https://github.com/phoenixframework/phoenix_live_view/issues/887
=> Use Ecto.Adapters.SQL.Sandbox.start_owner!/2 in generators

guides/request_lifecycle.md
Fixed a minor typo (line 175)
the router is responsible for dispatching __verb/patch__ -> 
the router is responsible for dispatching __verb/path__
=> fix: minor typo

guides/contexts.md
If https://github.com/elixir-ecto/ecto_sql/pull/240 is merged, this one updates docs to match.
=> contexts.md: Update migration example output

guides/mix_tasks.md
- Remove not existed -v option
- Correct description of --to option
=> Fix migrate task description

guides/plug.md
- Eliminate plug methods dependency from the first example
- Reuse data already found, like message
It makes more clear and fair comparison.
But it still shows nesting complexity in the first example and
much more composable, clear, and reusable way in the second example.
=> Fix plugs as composition example

guides/views.md
Me again.  I just noticed a typo as I was reviewing my PR.
=> Fix typo in guides

guides/telemetry.md
I'm finding `:tag_values` is really powerful when controlling how metrics show up in LiveDashboard, so I thought it might be worth adding another example. This also serves to promote the new `Phoenix.LiveView` telemetry events.
=> Add additional example of using tag_values in Telemetry guide

guides/deployment/deployment.md
Adding a Community Guides footer that can be used for other platforms. Added Render to it; Nanobox isn't accepting new signups so I didn't include it.
=> Add Community Guides footer with Render

guides/introduction/community.md
We released two Phoenix LiveView products that we've been working on for 3 months on Wednesday.
=> Update community.md to include two Groxio courses

guides/request_lifecycle.md
This fixes my incorrect typo fix. It also updates the sentence to make the intent slightly clearer (imo).
See #4066 for details.
=> Re-do typo fix

installer/templates/phx_single/README.md
This mimicks the info here: https://hexdocs.pm/phoenix/up_and_running.html
=> How to start fresh apps in IEx

guides/realtime/channels.md
=> Fix typo in Phoenix.Channels docs (#4084)

installer/templates/phx_single/config/dev.exs, installer/templates/phx_single/config/test.exs, installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs, installer/templates/phx_umbrella/apps/app_name_web/config/test.exs
Reviving #3991 as the old PR haven't got any attention probably it's always closed.. 😢 
- It does not overlap with other PRs
- I confirmed the change works in Microsoft Windows as well
=> Use 127.0.0.1 in dev and test

priv/templates/phx.gen.auth/schema.ex
Use redact: true for password & hash in `mix phx.gen.auth`
=> Use redact: true for password & hash in mix phx.gen.auth

priv/templates/phx.gen.auth/confirmation_controller.ex, priv/templates/phx.gen.auth/confirmation_controller_test.exs
See: https://github.com/aaronrenner/phx_gen_auth/pull/102
=> Update phx.gen.auth confirmation controller template

installer/templates/phx_single/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name_web/lib/app_name/application.ex
Updates the application module installer templates  to include the impl attributes for Application behaviour callbacks.
=> Adding @impl attributes to application modules

lib/phoenix.ex
=> Update dependency list on the Phoenix main docs

installer/templates/phx_single/config/runtime.exs
This refers to details which just landed in the `Plug.Cowboy` docs - https://github.com/elixir-plug/plug_cowboy/pull/61
=> Link to details on IP address selection

Earthfile
This updates the Earthfile to run installer tests.
=> Run installer tests in CI

guides/views.md
=> 3 small grammar fixes

guides/controllers.md
in the "Flash Messages" section.
=> Smooth out some wording

guides/views.md
At the beginning of the Phoenix View guide, smoothing out some grammatical issues.
=> Clarifying wording

priv/templates/phx.gen.auth/test_cases.exs
Fix for phx.gen.auth generated test confirm_account arity description.
=> Fix phx.gen.auth confirm_account test arity description

lib/mix/tasks/phx.gen.live.ex
=> Update docs for phx.gen.live to match task output

guides/deployment/releases.md
Many new features have been added to Docker, including the integration of a caching feature that makes it much faster with dependency caching.
Furthermore, I believe it's best to also use multistage when building with multiple language, which can then also be versioned.
=> Update Docker file sample

guides/plug.md, lib/phoenix/controller.ex, lib/phoenix/endpoint.ex
Make references to Plug callbacks valid links for easier navigation.
=> Add links for Plug callbacks

guides/ecto.md
Added more info on the output and formatting
=> added some formating

installer/templates/phx_single/gitignore, installer/templates/phx_umbrella/gitignore
https://github.com/elixir-lang/elixir/commit/e935cf078444ccc4291e02c6eb64563884ec4c9a#diff-9e3f7e25c9b25140c73745f6b8b0e7f5aa8c143a5289e33f08a95dcb9b65a6b4R296-R297
=> Add tmp folder to gitignore template

lib/phoenix/config.ex, test/phoenix/config_test.exs
=> Helpful error message when accessing endpoint config at compile time

lib/phoenix/router.ex, lib/phoenix/router/helpers.ex, test/mix/tasks/phx.gen.cert_test.exs
Since minimum supported version is Elixir v1.9 / OTP 20
=> Remove conditionals based on opt_release

guides/views.md
Thery were introduced in 89a444e5c93b1c0c882a52b3fd650c74084051f6 #4224
=> Fix links in Views guide

guides/howto/custom_error_pages.md
It tackles de problem described in https://github.com/phoenixframework/phoenix/pull/4230
Closes #4230
=> Fix code instructions in How-to: Custom Error Pages

guides/authentication/mix_phx_gen_auth.md, priv/templates/phx.gen.auth/confirmation_controller.ex, priv/templates/phx.gen.auth/reset_password_controller.ex, priv/templates/phx.gen.auth/session_controller.ex
Port of https://github.com/aaronrenner/phx_gen_auth/pull/116
=> Make user enumeration prevention clearer

CHANGELOG.md
=> Update changelog with `--database sqlite3` changes

assets/js/phoenix.js
Should fix https://github.com/phoenixframework/phoenix/issues/4323.
I originally intended to create a promise and resolving it immediately in order to run in a microtask instead of a macrotask, but that causes the same ordering issue, just one more level down (promises fired from promises).
A slightly more optimal approach here would be to fire the first event within the current task, and any subsequent ones from a `setInterval`. This might be advantageous if the lower bound timeout of `setTimeout` in some modern browsers end up creating problems, but that might cause even more ordering issues.
Added a commend, but I can remove that if the source code is an inappropriate location.
=> Fire each event in a separate task for the LongPoll transport

guides/introduction/community.md
The IRC link for #elixir-lang has been updated, this updates the phoenix docs to match.
=> Change IRC link in community.md

lib/mix/tasks/phx.gen.live.ex
Clean up a few typos and lingering mentions of views/controllers.  Re-organize argument discussion and clarify namespacing.
=> Live generator docs

installer/templates/phx_web/views/layout_view.ex
=> Add compiler flag to nowarn on live_dashboard_path to generator

installer/templates/phx_single/config/config.exs, installer/templates/phx_umbrella/apps/app_name_web/config/config.exs
Bump `eslint` to v0.12.18. 
Changelog: https://github.com/evanw/esbuild/releases/tag/v0.12.18
=> Bump eslint

installer/templates/phx_single/config/runtime.exs, installer/templates/phx_umbrella/config/runtime.exs
Just fixes for two small typos I noticed as I was starting a new Phoenix app. Thanks for all your great work, maintainers!
=> Fix minor typos in umbrella and single configs

guides/deployment/releases.md
This is the error I got on fly.io
```
Error error building: error rendering build status stream: When using COPY with more than one source file, the destination must be a directory and end with a /
```
=> Fix dockerfile

mix.exs
Currently, the documentation does not show the changelog.
=> Added CHANGELOG.md into the documentation

guides/asset_management.md
- recognize `--watch` and `--deploy` mode via `process.argv`
(called via `mix cmd ...` so env vars are out)
- minify assets in deploy mode
(just like default phx_new app does)
- enable inline sourcemaps in watch mode
(just like default phx_new app does)
- just use `logLevel: 'info'`
(equivalent to how CLI usage in default phx_new app behaves)
- add placeholder for loaders aside to the one for plugins
(since it's a very common need with npm based fonts etc)
- update rest of the guide accordingly
(list all script modes, watcher hook, assets.deploy alias)
=> Improve esbuild plugins guide

guides/deployment/gigalixir.md
Fixes https://github.com/phoenixframework/phoenix/issues/4474
=> Update Gigalixir deployment guide

guides/asset_management.md
No longer turtles all the way down...
=> Remove redundant phrase

guides/authentication/mix_phx_gen_auth.md
This just syncs the documentation with the PR from @goncalotomas in #4471
=> Unix default hashing algorithm changed in #4471

lib/mix/phoenix.ex, lib/mix/tasks/phx.gen.auth.ex, lib/mix/tasks/phx.gen.auth/injector.ex, test/mix/tasks/phx.gen.context_test.exs, test/mix/tasks/phx.gen.html_test.exs, test/mix/tasks/phx.gen.json_test.exs, test/mix/tasks/phx.gen.live_test.exs
Relaced `Enum.map` + `Enum.join` combinations with `Enum.map_join`.
=> Replace `Enum.map` + `Enum.join` with `Enum.map_join`

guides/directory_structure.md
This PR updates the "Directory structure" page based on the output from `mix phx.new hello` (1.6.0). It also adds a summary of the new `Hello.Mailer` module.
=> guides: 'Directory structure' page review

guides/introduction/up_and_running.md
This PR includes the following changes:
- Update the documented server log to remove mention of Webpack and replace it with one which is more accurate
=> guides: Update documented server console log

package.json
=> add require to exports for cjs

guides/routing.md
This PR includes the following changes:
* Update the `:browser` pipeline to v1.6.0 (replace `fetch_flash` with `fetch_live_flash`, and the addition of `put_root_layout`)
* Describe the new plugs in the `browser` pipeline section
* Add a few changes for conciseness
=> guides: update the Routing docs

guides/contexts.md
This PR updates the samples to match the Phoenix v1.6.0 generators
output. It also updates some links to HexDocs and includes some minor updates
regarding the test helper functions to create fixtures.
=> guides: update `Context` page

guides/mix_tasks.md
This PR adds the new Mix Tasks based on the Phoenix v1.6.0 output,
it also updates a few examples from the "Mix Tasks" guide.
=> guides: update 'Mix tasks' page

guides/deployment/releases.md
Reverts phoenixframework/phoenix#4531
=> Revert "Fix Dockerfile in guides/deployment/releases.md"

CHANGELOG.md
Be more specific about `@view_module` and `@view_template`
=> Change wording on Changelog

guides/deployment/deployment.md
Its is already mentioned some lines before within the same section of the guide.
=> Remove already mentioned comment about runtime.exs

lib/mix/tasks/phx.gen.live.ex
Add docs on required updates to the router file.
=> Doc update for phx.gen.live

lib/mix/phoenix/schema.ex, priv/templates/phx.gen.embedded/embedded_schema.ex, priv/templates/phx.gen.schema/schema.ex, test/mix/tasks/phx.gen.embedded_test.exs
=> fix: `Ecto.Enum` field creation with `mix phx.gen.embedded`

guides/contexts.md
create `cart_item_controller.ex` in right dir for consistency
from: `lib/hello_web/cart_item_controller.ex`
to: `lib/hello_web/controllers/cart_item_controller.ex`
=> Update contexts.md: create cart_item_controller.ex in right dir

guides/routing.md
Splitting away the utility and the usage for Path Helpers for easier understanding.
It was indeed quite a mouthful earlier and hopefully its simper to read and digest with the following changes
=> simplify path helpers desc

lib/phoenix/socket.ex, test/phoenix/socket/socket_test.exs
=> Reverse order of definition of channel handler functions

lib/phoenix/router.ex
I had to find this out manually since none of the documentation describes this ability.
Open to rewording!
=> Detail the ability to use dynamic scope parts

lib/mix/tasks/phx.gen.live.ex, test/mix/tasks/phx.gen.live_test.exs
=> Add upgrade instructions to phx.gen.live task

guides/deployment/fly.md
- uses the new fly launch feature that detects the Phoenix app
=> updated Fly.io deployment guide

installer/templates/phx_assets/app.css
Looks nicer this way, I think :)
=> Improve app.css formatting

priv/templates/phx.gen.live/live_helpers.ex
Just a space missing in live_helpers.ex
=> Indentation fix

lib/phoenix/endpoint/supervisor.ex, lib/phoenix/logger.ex, test/phoenix/endpoint/endpoint_test.exs
This adds the Endpoint init telemetry event and implements #4712
=> Added Endpoint init telemetry event

lib/mix/tasks/phx.gen.live.ex, priv/templates/phx.gen.live/live_helpers.ex
It's all document changes. :sweat_smile: 
- Convert live_helpers.ex template modal/1 doc's EEX Syntax to HEEX
- Update phx.gen.live module doc to prune removed "ModalComponent"
=> Update "phx.gen.live"-related docs

guides/testing/testing_channels.md
If I'm not mistaken, this code won't work otherwise.
=> Fix reference to UserSocket module in setup block

lib/phoenix/controller.ex, lib/phoenix/param.ex, lib/phoenix/router.ex, lib/phoenix/router/helpers.ex, lib/phoenix/router/route.ex, lib/phoenix/router/scope.ex, lib/phoenix/verified_routes.ex, test/phoenix/router/forward_test.exs, test/phoenix/router/helpers_test.exs, test/phoenix/router/route_test.exs, test/phoenix/verified_routes_test.exs
Still needs to support interpolated query string form, as well as moduledocs
=> Add verified routes

lib/mix/tasks/phx.gen.channel.ex, test/mix/tasks/phx.gen.channel_test.exs
Hi @chrismccord, I did a quick fix for #4899 :)
=> Fix gen channel task.

installer/templates/phx_single/lib/app_name/application.ex
The bug was injected by this PR https://github.com/phoenixframework/phoenix/pull/4888
=> Fix a bug that remove the Telemetry when ecto is disabled

guides/telemetry.md
Related to https://github.com/phoenixframework/phoenix/pull/4888
=> Update Telemetry guide change the children order

installer/templates/phx_live/assets/topbar.js
Also removed an extra whitespace entry.
=> Fixes #4965

CONTRIBUTING.md, README.md, guides/asset_management.md, guides/contexts.md, guides/controllers.md, guides/deployment/fly.md, guides/deployment/heroku.md, guides/directory_structure.md, guides/ecto.md, guides/howto/custom_error_pages.md, guides/introduction/community.md, guides/mix_tasks.md, guides/plug.md, guides/real_time/channels.md, guides/request_lifecycle.md, guides/routing.md, guides/telemetry.md, guides/testing/testing.md, guides/views.md
Found via `markdownlint --ignore installer --ignore integration_test --disable MD004 MD007 MD013 M  D014 MD024 MD026 MD028 -- **/*.md`
See a detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
Not sure about the `instaler` folder and its usage, hence I ignored it from checking.
=> Fix markdown issues

priv/templates/phx.gen.auth/confirmation_edit.html.heex
For reference
https://github.com/phoenixframework/phoenix/blob/64ab5740a4c69337590a3c859ed52ac0744741a4/priv/templates/phx.gen.auth/routes.ex#L52-L53
=> Fix: Verified route in mix phx.gen.auth confirmation_edit.html.heex

installer/templates/phx_single/config/config.exs
per https://tailwindcss.com/docs/guides/phoenix
=> bump tailwind config to version 3.1.8

test/phoenix/verified_routes_test.exs
This is a just an extra passing test - I thought I found a bug here but I was confused -- having an explicit test here might be useful for the future.
=> Add test for static paths

priv/templates/phx.gen.auth/settings_live.ex
Fix for:  https://github.com/phoenixframework/phoenix/issues/4994
=> Fix current password label for settings page template

installer/templates/phx_web/components/layouts/root.html.heex
The app and the root both have the same flash component. 
https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/components/layouts/root.html.heex#L15-L27 
And
https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/components/layouts/app.html.heex#L40-L52
I am removing from the root.
=> Remove extra flash

lib/phoenix/token.ex
https://github.com/elixir-plug/plug_crypto/blob/4ef6db0ee6bb7649bebb17ffc44b7d410453016c/lib/plug/crypto.ex#L360
=> Add :infinity to Token.max_age_opt

lib/mix/tasks/phx.digest.ex
Noticed a minor typo in one of the new commits!
=> Fix minor typo in `phx.digest` comment

lib/phoenix/controller.ex
=> Fix typespec for put_new_layout/2 and put_new_view/2

installer/templates/phx_single/config/prod.exs, installer/templates/phx_single/lib/app_name/application.ex, installer/templates/phx_single/mix.exs, installer/templates/phx_umbrella/apps/app_name/lib/app_name/application.ex, installer/templates/phx_umbrella/apps/app_name/mix.exs, installer/templates/phx_umbrella/config/prod.exs, installer/test/phx_new_test.exs, installer/test/phx_new_umbrella_test.exs
Adds the usage of the `Swoosh.Finch` adapter for newly generated projects. Related to #4876
=> Add Swoosh.Finch

installer/templates/phx_web/components/core_components.ex, priv/templates/phx.gen.live/core_components.ex
=> Remove underscore in opts variables

guides/directory_structure.md
Remove reference to Milligram and replace with Tailwind
=> Remove reference to Milligram and replace with Tailwind

installer/templates/phx_web/components/core_components.ex, priv/templates/phx.gen.live/core_components.ex
See https://github.com/phoenixframework/phoenix/commit/1d5829347a55fe7dd0376e3162a5e7ca7688669c#r88959157
=> Use default false value for :multiple form attr

guides/request_lifecycle.md
Missed in #5087 && #5068! :shrug:
=> Fix hello_html directory name

guides/testing/testing.md, installer/templates/phx_test/controllers/error_html_test.exs
In the process of upgrading a Phoenix 1.6.15 application to 1.7.0-rc.0 I found this typo.
=> Update import documentation in generated ErrorHTMLTest

guides/components.md
First time contributor here. 😅  
Working through the guide and ran into errors as it was written. I believe I've updated the guide properly but happy to make changes if not.
=> Fix layouts module in component guide

lib/mix/tasks/phx.gen.release.ex
Is this the least significant change ever committed to this wonderful project? It might just be! 😆
=> Fix a typo in the phx.gen.release docs

installer/templates/phx_single/config/config.exs, installer/templates/phx_umbrella/apps/app_name_web/config/config.exs, integration_test/config/config.exs
See the [tailwind CHANGELOG](https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md)
I also created https://github.com/phoenixframework/tailwind/pull/63
=> use the latest tailwind

guides/howto/create-json-rest-api.md
This pull request originates [from this discussion](https://elixirforum.com/t/does-elixir-phoenix-team-spends-too-much-time-on-frontend/46822/22?u=exadra37) on the Elixir forum where I volunteered to add a guide to show how to use Phoenix for a JSON REST API.
Signed-off-by: Exadra37 <exadra37@gmail.com>
=> Added a step by step guide on how to create a JSON REST API.

CHANGELOG.md
These entries appear only in the specific tags but not in master
=> Add entries to changelog for v1.6.14 v1.6.15

priv/templates/phx.gen.json/changeset_json.ex
=> Typo in comment of ChangesetJSON

guides/howto/custom_error_pages.md, installer/templates/phx_web/controllers/error_html.ex, priv/templates/phx.gen.presence/presence.ex
> The commits are self-explanatory.
=> Fix inconsistent generated code

priv/templates/phx.gen.auth/reset_password_edit.html.heex
Format reset_password_edit.html.heex
=> Fix integration tests

guides/routing.md
=> Fix sentence

priv/templates/phx.gen.auth/confirmation_edit.html.heex, priv/templates/phx.gen.auth/confirmation_live.ex, priv/templates/phx.gen.auth/forgot_password_live.ex, priv/templates/phx.gen.auth/reset_password_edit.html.heex, priv/templates/phx.gen.auth/reset_password_live.ex, priv/templates/phx.gen.auth/reset_password_new.html.heex
- Added some CSS classes that were missing in some places. 
- The navigation links were not unified between the --live option and the --no--live option, so I added them to both.
=> touchup styles, add navigation links

installer/templates/phx_single/gitignore, installer/templates/phx_umbrella/apps/app_name/gitignore, installer/templates/phx_umbrella/apps/app_name_web/gitignore, installer/templates/phx_umbrella/gitignore
Seems like my last changes were lost in the esbuild refactoring.
=> Add back tmp folder ignore in all gitignores

priv/templates/phx.gen.auth/auth.ex
=> Simplify auth hook

guides/plug.md
Updated app.html.heex path with the new layouts folder.
=> Docs: Updated folder structure for layouts

guides/request_lifecycle.md
=> Changes to request_lifecycle.md

installer/templates/phx_assets/tailwind.config.js
Use the spelling that is used by the Tailwind/Heroicons team: https://tailwindcss.com/docs/stroke-width#setting-the-stroke-width
=> Change Hero Icons to Heroicons

.gitignore
=> Ignore ./cover/ folder

guides/plug.md
=> update plug guide - fix file location, closes #5395

guides/json_and_apis.md
small change to update referenced code block.
=> update changeset code block to match 1.7

guides/real_time/channels.md
update channels guide - fix file location to match phoenix 1.7.x standards
=> update channels guide - fix file location to match phoenix 1.7.x standards

guides/testing/testing_controllers.md
to match a phoenix 1.7.2 project
=> Update listings in testing controllers guide

guides/contexts.md
* update code listings
* favor usage of components over functions from Phoenix.HTML.Form
* use phx.gen.context instead of phx.gen.html for Orders context creation
closes #5238
=> Update Contexts guide: Adjust code listings + favor components in views

lib/phoenix/controller.ex
=> Fix put_root_layout typespec

guides/testing/testing_contexts.md
=> Update testing contexts guide - to match a phoenix 1.7.2 project

guides/real_time/channels.md
- typo fix
- example paths consistency
=> channels guide language/wording tweaks

guides/deployment/releases.md
Small changes as I read the docs.
=> Fix typo on releases.md

guides/authentication/mix_phx_gen_auth.md, lib/mix/tasks/phx.gen.auth.ex
This PR updates the moduledoc for `phx.gen.auth` to mention the `--live` option. 
It also updates the _guide_ for `phx.gen.auth`, and links to @bemesa21 's blog post.
=> Update gen auth docs

guides/introduction/community.md
The [Build It With Phoenix](https://builditwithphoenix.com) video course has been completed and can now be added to this guide.
=> feat: add Build It With Phoenix video course to community guide

SECURITY.md
=> Add a security policy using GitHub advisories

guides/contexts.md
Adding "Education" to seeds.exs, in order for the example later in the document to work as intended:
`
Title: Elixir Flashcards
Description: Flash card set for the Elixir programming language
Price: 5.000000
Views: 0
Categories:
Education
Books
`
=> doc update: Added Education to seeds so that later example will work

guides/howto/using_ssl.md
Started with fixing a typo, but grew to revising the section as a whole.
=> Revise HSTS docs in using_ssl.md

installer/test/mix_helper.exs
While working on my own generators and utilizing the mix_helper module, I noticed that tmp files were not being removed; only the contents within them were. This makes things difficult to track, especially when trying to see what files are being generated, due to the numerous random directories being created and not being cleaned between runs. Here you can see the output of one run:
```bash
❯ cd tmp
❯ ls
+y5E0V98wE/                FWssDkXKgo/                TK5FAP/                    dwvhd9RNA3/                olnF+LTFg4/
0r5AJLwI1d/                G2qEVW9bWD/                TOvg5FCelf/                fb/                        pRHHd1rZnn/
1BLZ5enP/                  GB4Xr5gQ/                  TXkqg956we/                fjYfzH3Axb/                pTW/
1CBqNafDs6/                GSADpO41Ar/ …
```
=> Removing tmp files

mix.exs
=> Changed phx_new dependency to be inlcuded in :docs

assets/js/phoenix/longpoll.js, assets/js/phoenix/socket.js, assets/test/socket_test.js, installer/templates/phx_assets/app.js, installer/templates/phx_web/endpoint.ex
=> Add longpoll fallback and make LP enabled by default

installer/templates/phx_single/config/dev.exs, installer/templates/phx_umbrella/apps/app_name_web/config/dev.exs, lib/phoenix/endpoint.ex
Closes https://github.com/phoenixframework/phoenix_live_view/issues/2253
=> Exclude uploads folder from live reload patterns

guides/json_and_apis.md
This is a very small nitpick, but the sentence in the docs reads clearer with this change.
=> Change example filename to fit the scenario ✅

installer/templates/phx_single/config/dev.exs, installer/templates/phx_umbrella/config/dev.exs
Waiting for https://github.com/phoenixframework/phoenix_live_view/pull/3161
=> enable runtime checks for new lv projects in dev env

lib/phoenix/token.ex
=> Clarify Token secrecy in docs

installer/templates/phx_single/config/config.exs, installer/templates/phx_umbrella/apps/app_name_web/config/config.exs, integration_test/config/config.exs
To pick up bug fixes https://github.com/tailwindlabs/tailwindcss/compare/v3.4.0...v3.4.3
=> Upgrade Tailwind to 3.4.3

priv/templates/phx.gen.auth/schema.ex
fixes https://github.com/phoenixframework/phoenix_live_view/issues/3235
=> cast current_password and add as virtual field

priv/templates/phx.gen.auth/context_functions.ex
Noticed it while running this [formatter](https://hexdocs.pm/doctest_formatter/readme.html) on a personal project 😄
=> Fix doctest in phx.gen.auth

assets/js/phoenix/socket.js
=> socket.js check if global is available

.github/workflows/ci.yml, assets/.eslintrc.js, assets/.gitignore, assets/jest.config.js, assets/js/phoenix/socket.js, assets/package-lock.json, assets/package.json, assets/test/channel_test.js, assets/test/presence_test.js, assets/test/serializer_test.js, assets/test/socket_test.js
So... I was trying to update the JS dependencies and somehow ended up replacing mocha with jest. Wooops. Let me know what you think 😃
This is consistent with the setup we use in LiveView.
=> update js dependencies, move to jest for testing

guides/introduction/community.md
=> Update community.md, Add Phoenix Tutorial (Phoenix 1.6)

assets/js/phoenix/socket.js
👋 This is a small docs update to correct a handful of incorrect types in the parameters to the `Socket` constructor.
=> Fix JavaScript type documentation on Socket

lib/mix/tasks/phx.gen.context.ex, lib/mix/tasks/phx.gen.presence.ex, lib/mix/tasks/phx.gen.release.ex, lib/mix/tasks/phx.gen.socket.ex, lib/phoenix/code_reloader/server.ex, lib/phoenix/endpoint/render_errors.ex, lib/phoenix/endpoint/sync_code_reload_plug.ex, lib/phoenix/socket/pool_supervisor.ex, lib/phoenix/socket/transport.ex
=> Fix typos and improve language

lib/phoenix/verified_routes.ex
=> Additional documentation fixes for VerifiedRoutes

guides/asset_management.md, guides/authentication/mix_phx_gen_auth.md
Fix small typo in mix phx.gen.auth guide and uniformly use Node.js (instead of Node.JS).
=> Minor improvements to guides

guides/real_time/channels.md, priv/templates/phx.gen.socket/socket.js
Updating filename of heex template to hold token script tags
`.../templates/layout/app.html.heex` > `.../templates/layout/root.html.heex`
=> Improve channel docs and example code

guides/deployment/gigalixir.md
This updates the documentation related to deploying Phoenix to Gigalixir.
=> docs: update gigalixir getting started docs

guides/cheatsheets/router.cheatmd
Fixed another broken link I found in [cheatsheet](https://hexdocs.pm/phoenix/router.html#resources).
=> fix broken link

installer/templates/phx_web/components/layouts/app.html.heex
Closes https://github.com/phoenixframework/phoenix_live_view/issues/3415.
=> Move flash_group to the end of the app template

lib/phoenix/socket.ex
Make wording similar to:
* https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#assign/2
* https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#assign/3
=> Update Phoenix.Socket.assign/2,3 docs

guides/contexts.md
Added some “consistency” to the docs 😄
=> Fixed a typo in contexts.md

installer/templates/phx_web/components/layouts/root.html.heex
This pull request closes #5656
made scrollbar gutter to auto for default root layout
=> make scrollbar-gutter auto

guides/introduction/up_and_running.md, guides/request_lifecycle.md
=> minor grammar and typo fix in documentation

guides/deployment/gigalixir.md, guides/request_lifecycle.md
intepolation -> interpolation
commited -> committed
=> A couple typos

lib/mix/tasks/phx.digest.clean.ex
See https://github.com/phoenixframework/phoenix/issues/5752#issuecomment-2612036847
=> Allow running phx.digest.clean task multiple times

installer/templates/phx_assets/topbar.js
Changes:
- Removes polyfill for requestAnimationFrame as it's no longer needed for modern browsers
- Improves DOM manipulation by only appending canvas when showing
- Updates copyright year and version numbers
=> Update topbar.js to v3.0.0

CHANGELOG.md
Typo discovered. Seems we're all not quite used to writing 2025 now :)
=> Fixed date for v1.7.19

installer/templates/phx_web/telemetry.ex, lib/phoenix/endpoint.ex, lib/phoenix/logger.ex, lib/phoenix/socket.ex, lib/phoenix/socket/pool_supervisor.ex, test/phoenix/socket/socket_test.exs
and also use it for logging drain events
=> add [:phoenix, :socket_drain] telemetry event

installer/lib/phx_new/generator.ex
```
warning: this clause of defp phoenix_dep/2 is never used
│
471 │   defp phoenix_dep("deps/phoenix", %{pre: ["dev"]}),
│        ~
│
└─ lib/phx_new/generator.ex:471:8: Phx.New.Generator.phoenix_dep/2
```
=> fix unused clause warning in installer on Elixir 1.18

guides/controllers.md, installer/templates/phx_single/lib/app_name_web.ex, installer/templates/phx_umbrella/apps/app_name_web/lib/app_name.ex, lib/phoenix/controller.ex
=> clarify app layout docs, default to explicit :app layout

installer/templates/phx_umbrella/apps/app_name_web/config/runtime.exs
=> prevent double config import in umbrella generator

guides/asset_management.md, lib/mix/tasks/phx.gen.release.ex
Fixes https://github.com/phoenixframework/phoenix/issues/5976.
=> add a section about npm when using phx.gen.release --docker

.github/workflows/assets.yml, .github/workflows/ci.yml
Similar to: https://github.com/phoenixframework/phoenix_live_view/pull/3552
=> auto update assets

priv/templates/phx.gen.release/Dockerfile.eex
- Fix links to Docker Hub
- Name the final stage to make it easy to target it
- Use consistent line changes and 2 spaces indent
=> Minor Dockerfile updates

lib/phoenix/controller.ex, lib/phoenix/endpoint/render_errors.ex, test/phoenix/controller/render_test.exs, test/phoenix/endpoint/render_errors_test.exs
=> Set __changed__: nil on controller render for LiveView compatibility

guides/introduction/community.md, lib/mix/tasks/phx.gen.release.ex
Follow up of erlef/security-wg#48
=> Update EEF Security WG Links

lib/mix/tasks/phx.gen.html.ex, lib/mix/tasks/phx.gen.live.ex
Closes https://github.com/phoenixframework/phoenix/issues/5714.
=> require at least one attribute in phx.gen.live/html

guides/data_modelling/faq.md
=> Update faq.md: Word missing

installer/templates/phx_web/components/core_components.ex
PR created from #6177 discussion.
=> Remove range from .input

priv/templates/phx.gen.context/access_no_schema.ex, priv/templates/phx.gen.context/access_no_schema_scope.ex, priv/templates/phx.gen.context/schema_access.ex, priv/templates/phx.gen.context/schema_access_scope.ex, test/mix/tasks/phx.gen.context_test.exs
Relates to: https://github.com/elixir-lang/elixir/issues/14424
=> remove unused default argument in generated contexts

lib/mix/phoenix/schema.ex, test/mix/tasks/phx.gen.schema_test.exs
=> use context_app for scopes

priv/templates/phx.gen.auth/schema.ex
Originally reported: https://elixirforum.com/t/phoenix-1-8-0-rc-0-released/70256/104
=> remove unused current_password field

guides/authn_authz/scopes.md
Here are some edits to the scopes guide, with the intent to make the introductory paragraphs a bit more concise.
=> Update scopes guide

installer/templates/phx_web/components/core_components.ex
references https://github.com/phoenixframework/phoenix/issues/6204
See https://github.com/saadeghi/daisyui/blob/master/packages/daisyui/src/components/fieldset.css#L11.
The label itself looks exactly the same.
=> use label instead of fieldset-label

lib/mix/tasks/phx.gen.release.ex
The Dockerfile generator now accepts explicit `otp` and `elixir` parameters for its base image. This change is necessary because the versions auto‑detected on the development host aren’t guaranteed to exist on Docker Hub, which could otherwise lead to missing‑image build failures. By providing a way to pin the desired OTP and Elixir versions, users can enforce referencing published images.
=>  allow overriding auto-detected OTP and Elixir versions

lib/phoenix/channel/server.ex, lib/phoenix/debug.ex, lib/phoenix/socket.ex, test/phoenix/debug_test.exs
Relates to: https://github.com/phoenixframework/phoenix_live_view/pull/3776
=> Phoenix.Debug

installer/templates/phx_web/components/layouts.ex
=> fix typo in Layouts closing tag

guides/real_time/channels.md
The existing docs point to an older repo that isn't using the params function so it's a bit confusing. I believe Phoenix changed this behavior at some point.
I thought it'd also be nice to have a simple example right in the docs. I took most of this from an example that Chris McCord shared in the elixir forums.
=> Update channels.md to include correct way to update the channel params for reconnections

.github/workflows/ci.yml, lib/mix/tasks/phx.gen.cert.ex
Closes https://github.com/phoenixframework/phoenix/issues/6319.
=> fix phx.gen.cert on OTP 28

.formatter.exs
Relates to: https://github.com/phoenixframework/phoenix_live_view/pull/3903
=> add refute_patched to locals_without_parens

installer/templates/phx_assets/app.js, installer/templates/phx_static/app.js, installer/templates/phx_web/components/core_components.ex, installer/templates/phx_web/components/layouts.ex, installer/templates/phx_web/components/layouts/root.html.heex, lib/mix/tasks/phx.gen.live.ex
Closes https://github.com/phoenixframework/phoenix/issues/6366.
Closes https://github.com/phoenixframework/phoenix/pull/6368.
=> Do not rely on Phoenix.LiveView.JS when using --no-live

priv/templates/phx.gen.auth/AGENTS.md
Changes fix documentation related to this issue https://github.com/phoenixframework/phoenix/issues/6406
=> Update Agents.md documentation to match current method
